### ISSUE TITLE
Support Microsoft.Owin.Security.Forms

### ISSUE THREAD

**Issue by damianh** [NancyFx/Nancy#1080]
..or whatever it'll be renamed to.

It would looks something like this https://github.com/owin/owin-hosting/blob/master/src/main/Owin.Types/Extensions/OwinResponseExtensions.Security.cs where a user can add a IPrincipal to the environment dictionary via a NancyContext extension.

**Comment by thecodejunkie** [comment]
@damianh what about this? Resolved? Close?

**Comment by damianh** [comment]
Fixed via [`Nancy.MSOwinSecurity`](https://github.com/NancyFx/Nancy.MSOwinSecurity)
