### ISSUE TITLE
Adding Nancy.Viewengines.Razor NuGet package breaks xbuild on mono on Ubuntu

### ISSUE THREAD

**Issue by colinangusmackay** [NancyFx/Nancy#1082]
If a project has the "Nancy.Viewengines.Razor" NuGet package added then the build of the project  fails when using xbuild on mono on Ubuntu.

This is because the package adds the following to the csproj file:
```xml
<PostBuildEvent>
if $(ConfigurationName) == Debug (
xcopy /s /y /R "$(SolutionDir)packages\Nancy.Viewengines.Razor.0.17.1\BuildProviders\Nancy.ViewEngines.Razor.BuildProviders.dll" "$(ProjectDir)bin\"
xcopy /s /y /R "$(SolutionDir)packages\Nancy.Viewengines.Razor.0.17.1\lib\Net40\Nancy.ViewEngines.Razor.dll" "$(ProjectDir)bin\"
)</PostBuildEvent>
```

My current workaround is to remove the content of the `<PostBuildEvent>` and reference any type in the `Nancy.ViewEngines.Razor.dll` explicitly somewhere in the project. e.g. Overriding the default bootstrapper and then adding this:

    protected override System.Collections.Generic.IEnumerable<System.Type> ViewEngines
    {
      get 
      { 
        yield return typeof (RazorViewEngine);
      }
    }

So far, this seems to work without issue - although the `Nancy.ViewEngine.Razor.BuildProviders.dll` is not copied in this instance.

**Comment by zippy1981** [comment]
Let me ask the bigger question. Lots of OSS C# has xcopy commands in the msbuild. It would be relatively trivial to write an xcopy program in C or python, or shell that would sit in the path and make this magicallywork. The hard part is getting mono to ship this binary alongsize xbuild

**Comment by stkrzysiak** [comment]
@zippy1981 I just learned about xcopy, but for those familiar with both xcopy and rsync, couldn't we just write a wrapper around rsync that converts xcopy->rsync flags? At the very least we could make an alias for xcopy?

**Comment by LinuxDoku** [comment]
Why don't simply use the copy task of msbuild which is supported by xbuild on mono out of the box? https://msdn.microsoft.com/library/3e54c37h.aspx (also featured in the msbuild task porting guide: http://www.mono-project.com/archived/porting_msbuild_projects_to_xbuild/)

There was a little bug in monodevelop but with the latest release it does not break the .csproj anymore and can be widely adopted with full tooling support.

**Comment by phillip-haydon** [comment]
*shrug* 

If anyone wants to create a PR which fixes this, runs on both Windows and Linux, doesn't involve any installing of things to work, and achieves the same end goal. We will be happy.
