### ISSUE TITLE
Outputing Hebrew Chars

### ISSUE THREAD

**Issue by ygaradon** [NancyFx/Nancy#1109]
hello i try to use your amazing platform:

i write the simple module:
 
       Get["/hebrew"] = x =>
       {
               return "עברית";
       };

but unfortunately i was getting as output: ×¢×‘×¨×™×ª
i was sure it's an encoding issue so i download the source and debug and found this:
in the Nancy.Response line 103 at the GetStringContents if i make the following modification it's solve the issuse:

before:

           protected static Action<Stream> GetStringContents(string contents)
        {
            return stream =>
            {
                var writer = new StreamWriter(stream) { AutoFlush = true };
                
                writer.Write(contents);
            };
        }

after:

        protected static Action<Stream> GetStringContents(string contents)
        {
            return stream =>
            {
                var writer = new StreamWriter(stream, System.Text.Encoding.UTF8) { AutoFlush = true };
                
                writer.Write(contents);
            };
        }

just adding the System.Text.Encoding.UTF8 to the StreamWriter constructor solve it.

i also want to notice that routes with Hebrew chars are don't work:
example:

         Get["/עברית"] = x =>
         {
                 return "hebrew route";
         };

don't get fire thanks!

**Comment by thecodejunkie** [comment]
I think the proper solution to this is #2020
