### ISSUE TITLE
Allow Nancy.*.Tests projects target .net 4.5, where appropriate

### ISSUE THREAD

**Issue by damianh** [NancyFx/Nancy#1143]
Discussed briefly in Jabbr so decided to create an issue.

The async work is currently out in a different repo and has some work to to bring it up to scratch, mostly in the area of failing tests. Time is marching on, so I'd like to help get it closer to being pulled into master. To greatly simplify tests that are async based/affected I'd like to use async/await, that is, target .net 4.5 in tests.

To be clear, the shipped assemblies should remain targeting 4.0.

The cost is that Nancy development will no longer support VS2010. Developing _with_ nancy remains unchanged. Perhaps ask the community of contributors if this is a problem?

The unknown is whether Mono 3 / Travis has a fit. For some reason I expect it will.

Using async/await in .net 4 via MS.Bcl, MS.Bcl.Async and MS.Bcl.Targets is undesirable and probably won't work under mono.

**Comment by thecodejunkie** [comment]
v2.x will be 4.5+
