### ISSUE TITLE
Hashtags in URLs are broken

### ISSUE THREAD

**Issue by DrRataplan** [NancyFx/Nancy#1154]
Good day,

When I try to request an URL containing an (encoded) hashtag character, Nancy routes my request incorrectly.

The route I use is a GET to /Users/{userGuid}/{ItemId}/Something

The Url I use is 

```
/Users/id-C2FA7B9C3D591B35D0282E60EF00F652/id-B71E36CFFAD17AC819AF7B5CB9551825#2003-08-01#null#inod_e02577fdba737f7c71523e3550a73cc0/Something
```

Obviously, I URLEncode them to %23, this makes the URL

```
/Users/id-C2FA7B9C3D591B35D0282E60EF00F652/id-
B71E36CFFAD17AC819AF7B5CB9551825%232003-08-01%23null%23inod_e02577fdba737f7c71523e3550a73cc0/Something
```

While debugging, I used the IPipelines.onBeforeRequest pipeline to check out the Url received by Nancy. The new pipeline is placed at the start. The context received in this pipe contains an Url looking like this:

```
http://localhost:80/Kluwer/Api/Endpoint/Users/id-C2FA7B9C3D591B35D0282E60EF00F652/id-B71E36CFFAD17AC819AF7B5CB9551825##2003-08-01%23null%23inod_e02577fdba737f7c71523e3550a73cc0/Something
```

The path where Nancy tries to route my request to is 

```
/Api/Endpoint/Users/id-C2FA7B9C3D591B35D0282E60EF00F652/id-B71E36CFFAD17AC819AF7B5CB9551825
```

This path doesn't exist, there is only a /users/{}/{}/something path so Nancy returns a 404.

This is obviously not the right behaviour, just look at the two hashtags. Somehow, somewhere, the single %23 is changed to ##. These characters break the Url resolving.

I worked around this problem by replacing the # character at the client with a placeholder (pile of poo) and replacing all placeholders with # characters at the server.

I do hope I've made my problem clear.

**Comment by adamralph** [comment]
I'm observing the same problem with self hosting.

**Comment by adamralph** [comment]
...and I am encoding the #'s as %23

**Comment by adamralph** [comment]
Right now I'm working around it by using the Korean for "hash" as a replacement "해시". :stuck_out_tongue_winking_eye:
