### ISSUE TITLE
Context.CancellationToken

### ISSUE THREAD

**Issue by prabirshrestha** [NancyFx/Nancy#1202]
This issue starts with the question on how can I implement something like Timeout in Nancy.

Here is the twitter discussion. https://twitter.com/PrabirShrestha/status/371729596695457792

I personally think the NancyContext should contain CancellationToken property with getter and setters.

```
Before += Timeout(60 * 1000);

public void Timeout(int ms) {
    var oldCancellationToken = context.CancellationToken;
    var cts = new CancellationTokenSource();
    oldCancellationToken.Register(cts.Cancel);
    var ct = cts.Token;
    Task.Delay(ms, ct).ContinueWith(t => cts.Cancel());
    context.CancellationToken = ct;
}
```

**Comment by thecodejunkie** [comment]
@damianh @grumpydev something for 2.x and the TPL & await/async change?

**Comment by damianh** [comment]
Yes 2.x

**Comment by damianh** [comment]
I think this can be in 2.1 or after.
