### ISSUE TITLE
WCF hosting Interface

### ISSUE THREAD

**Issue by parhs** [NancyFx/Nancy#1204]
Hello.
I have a rest json service and I want to have it together with a simple web server to avoid JSONP / CORS hell. So i used Nancy.However ,since nancy wcf self host isnt an interface cant handle that.
So I made an interface and implemented it like the source.

So if you think that this is correct include something like this

 [ServiceContract]
 public interface INancyWcfGenericService
    {
        
            [WebInvoke(UriTemplate = "*", Method = "*")]
             Message HandleRequests(Stream requestBody);
        
    }

**Comment by phillip-haydon** [comment]
Closing this since it's old and WCF and I hate WCF and this will prob never happen.
