### ISSUE TITLE
Content negotiation in OnError pipeline

### ISSUE THREAD

**Issue by khellang** [NancyFx/Nancy#1212]
I'd like to return different responses within the OnError pipeline depending on the Accept headers. Is there any way I could do this today (through Nancy conneg)?

I was experimenting a bit and couldn't find a way so I ended up with an implementation myself. See the implementation [here](https://github.com/khellang/Nancy/compare/onerror-conneg) and the resulting application code in [this gist](https://gist.github.com/khellang/6418180).

This seems to work, but I haven't tested it extensively. Is there a reason why it isn't already there?

**Comment by thecodejunkie** [comment]
@khellang you closed #1213 without a merge.. mistake? I guess the validity of this issue relies on that :) Thanks

**Comment by khellang** [comment]
Part of this was solved with #1348. I'll take a look at the rest ASAP.
