### ISSUE TITLE
Allow owin passthrough to work pre-request

### ISSUE THREAD

**Issue by damianh** [NancyFx/Nancy#1221]
Passthrough delegate is only checked OnRequestComplete. There are some situation where one would like the passthrough delegate to be checked before handling the request, i.e. always pass through "/api" requests.

**Comment by thecodejunkie** [comment]
@damianh Did anything ever happen to this? Still something we want/should do? Close? Thanks

**Comment by damianh** [comment]
Yes I believe so. I'll examine it again.

**Comment by damianh** [comment]
Closing. If I come across the need for this again, I'll just PR.
