### ISSUE TITLE
Flatten namespaces for extension methods

### ISSUE THREAD

**Issue by grumpydev** [NancyFx/Nancy#1223]
Currently when you want to use model binding for instance,  you have to bring in the namespace, which has caused issues with a few people in the past. We could switch on the R# setting for the various folders to not enforce namespace/folder mappings and flatten them all into the Nancy namespace.

Something that will actually help with user friction @damianh ;-)

Thoughts?

**Comment by thecodejunkie** [comment]
Let's target this for the v2.x timeframe. Milestone assigned accordingly

**Comment by damianh** [comment]
Breaking change would mean v3?

**Comment by thecodejunkie** [comment]
No, v2 because we'll bump the major
