### ISSUE TITLE
Using QueryString in URL in test fails

### ISSUE THREAD

**Issue by jchannon** [NancyFx/Nancy#1326]
If I have

`var result = browser.Get("/search?test=hi")` 

Result = 404

If I use

`var result = browser.Get("/search", with => with.Query("test","hi"))`

Result = 200

I assume this is because of encoding

**Comment by cloudhunter89** [comment]
Is this issue actually resolved?  It still doesn't seem to work, but maybe there is some configuration or context that is missing.  I have the following two simple test cases and with a query in the get string it fails.
using Nancy;
using Nancy.Testing;
using NUnit.Framework;

`namespace NancyTest`
`{`
`  public class BrowserTest`
`  {`

    [Test]
    public void BrowserWithoutQuery()
    {
      DummyModule dummyModule = new DummyModule();
      ConfigurableBootstrapper bootstrapper = new ConfigurableBootstrapper(with =>
      {
        with.Module(dummyModule);
      });
      Browser browser = new Browser(bootstrapper);
      BrowserResponse result = browser.Get(
        "/query",
        with =>
        {
          with.HttpRequest();
        });
      Assert.AreEqual(Nancy.HttpStatusCode.OK, result.StatusCode);
      string queryResult = result.Body.AsString();
      Assert.AreEqual("Your query was: ", queryResult);
    }

    [Test]
    public void BrowserWithQuery()
    {
      DummyModule dummyModule = new DummyModule();
      ConfigurableBootstrapper bootstrapper = new ConfigurableBootstrapper(with =>
      {
        with.Module(dummyModule);
      });
      Browser browser = new Browser(bootstrapper);
      BrowserResponse result = browser.Get(
        "/query?value1=something&value2=200",
        with =>
        {
          with.HttpRequest();
        });
      Assert.AreEqual(Nancy.HttpStatusCode.OK, result.StatusCode);
      string queryResult = result.Body.AsString();
    }
  }

  public class DummyModule : NancyModule
  {

    public DummyModule() : base()
    {
      Get["/query"] = _ =>
      {
        Response resp = Response.AsText("Your query was: " + Request.Url.Query);
        return resp;
      };
    }
  }
}
