### ISSUE TITLE
JSON syntax error when POST body is over 81920 bytes

### ISSUE THREAD

**Issue by aaronlerch** [NancyFx/Nancy#1333]
(Apparently I submitted this issue by accident before I finished it, sorry!)

Howdy-

We ran into an interesting issue that I don't actually think is a _Nancy_ issue, but I'm not sure where else to report it. I wrote up a gist to provide a full reproduction -- I just followed all the directions in the gist and reproduced it locally on my mac easily. It's also reproducible for me on Ubuntu 13.x, I haven't tried reproducing it anywhere else. The gist is here: https://gist.github.com/aaronlerch/7594503

In a nutshell, when running Nancy on Mono (OWIN) behind nginx, request bodies over 81920 bytes are becoming corrupted. It is directly related to the MemoryStream/FileStream optimization going on in [RequestStream](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/IO/RequestStream.cs). I do not believe this class holds the _root cause_ but like I said, I'm not sure where else to report this.

When running on Mono and POSTing a large body directly to the app, things work correctly. The temp-file-based FileStream is created and switched to without a problem. But when you access the exact same process behind an nginx proxy front-end, 8000 NUL values are inserted into the request body stream, starting at offset 81920.

What an odd coincidence. ;)

And the error message you get, in my case, is "JSON syntax error" as the JSON parser encounters a NULL character when it doesn't expect one and fails. Very confusing to uncover the root cause.

I don't have a windows machine readily available, so I didn't go so far as to compile Nancy locally and debug the state of the streams as the memory stream is copied to the file stream, and thus I'm not exactly sure _where_ the problem is. But when I increased the threshold to a value higher than my content length, all was well. I would have just specified the `disableStreamSwitching` constructor argument to `RequestStream`, but as I'll mention in another bug report, that's broken and not an option.

Let me know if you have any more questions, and especially if you have an idea of where I should be submitting this bug report. I suspect it's a bug in Mono itself but I haven't debugged it any further to find out.

Thanks-
Aaron

**Comment by MarkoBL** [comment]
Is there any update for this problem? I just came across this issue and disabling the async FileStream worked. I think it would be a good idea to disable it by default for mono, as long as there's no fix for it, maybe by using the ```__MonoCS__``` define.
