### ISSUE TITLE
Performance overhaul

### ISSUE THREAD

**Issue by thecodejunkie** [NancyFx/Nancy#1384]
Even though we have great performance, there is always more that can be done. This issue will only track what is needed and what has been done. Each change should be logged as a different issue and tracked in here. If you have suggestions on things that should be included in this list, please post a comment so it can be added to the list.

**Comment by webcoyote** [comment]
@Jevonius mentioned "A task of 'improve performance' is significantly easier if there is an appropriate set of benchmarks available that enable identification of problem code and can be used to validate improvements."

How about the [Tech Empower benchmarks](http://www.techempower.com/benchmarks/), which show that NancyFX performing at [only ~6% of the top-rated framework](http://www.techempower.com/benchmarks/#section=data-r9&hw=peak&test=json)!

**Comment by donnyv** [comment]
Any movement on performance benchmarks?

**Comment by khellang** [comment]
There's https://github.com/TechEmpower/FrameworkBenchmarks/pull/1565. I've still not gotten the benchmarks to run properly on my machine. You could help out, @donnyv...

**Comment by thecodejunkie** [comment]
We continuously audit our code, no need for us to have a long running open issue for it

**Comment by jocull** [comment]
I know I’m necro’ing an old issue here. Is there any explaination about the module lifecycle mentioned above regarding performance? I’m digging into Nancy this week (hoping to pick it up at my shop!) and also noticed how the constructors redeclare the routes each time. This feels... heavy. Of course I haven’t measured it. There’s a lot of dynamics to wrap my head around.
