### ISSUE TITLE
Nancy.Url.Fragment should be populated by implicit cast from System.Uri

### ISSUE THREAD

**Issue by zippy1981** [NancyFx/Nancy#1399]
I was working on #1398 and during unit testing I discovered that casting fromUri to Url doesn't set the fragement. According to @grumpydev that is by design because on the server urls don't have fragment. However, redirect urls can have a fragment section (at least Nancy and chrome seemed to allow it, not sure what the standards say) so I'd argue against that. 

I'm willing to send a pull request. I'd just like the powers that be to agree upon one of two courses of action (or provide a third one)

1. Urls should have fragments
 * The implicit constructors should preserve anchors
 * ToString() should preserve anchors
2. Urls should not have fragments
 * Url.Fragment should be marked as obsolete
 * The implicit constructors should explicitly strip anchors
 * ToString() should explicitly strip anchors

So powers that be, I, your faithful library consumer, await your decree.

**Comment by khellang** [comment]
`Url.Fragment` is already dead at this point :smile:
