### ISSUE TITLE
CRSF Validation Issue on Load Balanced Servers

### ISSUE THREAD

**Issue by jchannon** [NancyFx/Nancy#1405]
When using `@Html.AntiForgeryToken()` on a load balanced server, if the page posts to the other server it causes an `Nancy.Security.CsrfValidationException:`

Setting the `CryptographyConfiguration` property in the Bootstrapper didn't solve this, nor registering the `CryptographyConfiguration` instance in `ApplicationStartup` with the container.

I also tried using reflection to set the internal static property on `CrsfApplicationStartup` to set the `CryptographyConfiguration`

All failed and resorted to sticky sessions on the load balancer.

**Comment by thecodejunkie** [comment]
@grumpydev @jchannon Would this be solved if the `CryptographyConfiguration` was set to use `MachineKeyEncryptionProvider` and `MachineKeyHmacProvider` ? If not, then how would be reproduce this locally so we could trace down the cause?

**Comment by thecodejunkie** [comment]
This should either be resolved or closed in the 1.x milestone

**Comment by CrescentFresh** [comment]
What's the status of this with respect to 1.4? I see it was set for milestone 1.4 on Oct 23 '15. Was it then moved forward to 2.0 milestone instead?

**Comment by mylifeandcode** [comment]
Having the same issue. Doing this in my bootstrapper didn't have any affect:

`            var cryptographyConfiguration = new CryptographyConfiguration(
                new RijndaelEncryptionProvider(new PassphraseKeyGenerator("blahblahblah", new byte[] { 8, 2, 10, 4, 68, 120, 7, 14 })),
                new DefaultHmacProvider(new PassphraseKeyGenerator("blahblahblah", new byte[] { 1, 20, 73, 49, 25, 106, 78, 86 })));

            Csrf.Enable(pipelines, cryptographyConfiguration);
`
Help!

**Comment by thecodejunkie** [comment]
How are you guys setting up the `CryptographyConfiguration` the proper solution should be to override the `CryptographyConfiguration` **property** and return a new `CryptographyConfiguration` **instance**. For CSRF we have an `IApplicationStartup` implementation called `CsrfApplicationStartup` that takes a `CryptographyConfiguration` instance in the ctor.. so unless you've overriden that property it is likley that `CsrfApplicationStartup` runs with the default (which just used random values)

**Comment by bnek** [comment]
Did anyone solve this problem successfully?
