### ISSUE TITLE
HttpStatusCode.NotFound does not work on /

### ISSUE THREAD

**Issue by jgillich** [NancyFx/Nancy#1424]
This works as expected (shows empty page with a 200 status code):

```
Get[@"/"] = parameters =>
{
    return HttpStatusCode.OK;
};

```

But this doesn't (shows a directory listing by the ASP.NET development server):

```
Get[@"/"] = parameters =>
{
    return HttpStatusCode.NotFound;
};
```

Note that I don't have a base path in my module, it works as expected for any route except `/`.

**Comment by bbenetskyy** [comment]
For me it's looks like **IIS 7** problem from #2541 . As I was write there, probably should help next **Web.config** additional configuration:
```
<system.webServer>
    <modules runAllManagedModulesForAllRequests="true" />
    <validation validateIntegratedModeConfiguration="false" />
    <handlers>
      <add path="*" name="Nancy" type="Nancy.Hosting.Aspnet.NancyHttpRequestHandler" verb="*" preCondition="integratedMode" resourceType="Unspecified" allowPathInfo="true" />
    </handlers>
  </system.webServer>
```

Only this solution help me resolve that Issue
