### ISSUE TITLE
Nancy.Request.Query should contain the valueless names

### ISSUE THREAD

**Issue by zippy1981** [NancyFx/Nancy#1435]
Currently Nancy.request will handler http://foo/com/?name=value, or duplicates i.e. http://foo/com/?name=value&name=value2 becomes 

Request.Query.name == "value,value2"

However, what if I want to do http://foo/com/?name? That's being swallowed by the quer string parser. I think the key should be added to the dictionary with  a value modeled after DbNull called QueryNull.Value. I'd be ok with another representation.

Thoughts? I'll write the patch.

**Comment by MrTomWhite** [comment]
@grumpydev It looks like this issue has been resolved w/ #1537; can we go ahead and close this issue ?

**Comment by grumpydev** [comment]
Done :)
