### ISSUE TITLE
WebSocket server on the same port

### ISSUE THREAD

**Issue by jgillich** [NancyFx/Nancy#1437]
I use [Fleck](https://github.com/statianzo/Fleck) as a WebSocket server together with Nancy, each on it's own port. Is it possible to run both on the same port?

It should be possible to proxy all non-HTTP requests to another tool and other frameworks are able to do that just fine (like express & SocketIO), but I have no idea where to start with Nancy.

**Comment by TiagoOliveiraMarques** [comment]
Some time has passed since the last post but I had the same problem as described here and I made a simple library for that purpose.
For those interested, here is the [repo](https://github.com/lifeemotions/websocketproxy)

**Comment by rkgarcia** [comment]
@TiagoOliveiraMarques do you test the performance with your library?

**Comment by TiagoOliveiraMarques** [comment]
@rkgarcia Sorry for the late reply. I tested it with apache benchmark and made some "hot path" benchmarks. If I remember correctly it has something like 75% the throughput of a nancy self hosted server on a i7 machine serving a "Hello World" string. IIRC ab uses HTTP/1.0 requests (so one connection per HTTP request). The bottleneck is indeed in the connection creation.
