### ISSUE TITLE
The type IEnumerable'1 does not have an accessible constructor - FluentValidation

### ISSUE THREAD

**Issue by ghost** [NancyFx/Nancy#1465]
*Described in: https://groups.google.com/forum/#!topic/nancy-web-framework/HO4oVxUFgkM*

**Issue**
Exception is being called when Nancy tries to validate a model. The exception only occurs when Unity is used as a dependency injection framework. I assume it's because Nancy.Validation.FluentValidation.DefaultFluentAdapterFactory expects a IEnumerable which Unity tries to resolve.

**Comment by ayoung** [comment]
Just curious, what is the proposed fix for this? in other words, what is the advice from the Unity guys?

**Comment by khellang** [comment]
Switch to another container? :smile:

**Comment by ayoung** [comment]
This is how solved it. Until a more permanent solution is in place. Like this one https://github.com/NancyFx/Nancy.Bootstrappers.Unity/issues/7

```c#
protected override void ConfigureApplicationContainer(IUnityContainer existingContainer)
{
    existingContainer.RegisterType<IFluentAdapterFactory, DefaultFluentAdapterFactory>(
        new ContainerControlledLifetimeManager());
    existingContainer.RegisterType<IModelValidatorFactory, FluentValidationValidatorFactory>(
        new ContainerControlledLifetimeManager());

    existingContainer.RegisterType(typeof(IEnumerable<IFluentAdapter>), typeof(UnityEnumerableShim<IFluentAdapter>));
    existingContainer.RegisterType(typeof(IEnumerable<IValidator>), typeof(UnityEnumerableShim<IValidator>));
}
```

**Comment by thecodejunkie** [comment]
@khellang This should be closed right? Because of this https://github.com/NancyFx/Nancy.Bootstrappers.Unity/pull/9

**Comment by khellang** [comment]
I think so.
