### ISSUE TITLE
Serialization of F# Discriminated Unions works but is a bit verbose. 

### ISSUE THREAD

**Issue by albertjan** [NancyFx/Nancy#1502]
DU's get serialized like this now:

```js
"type": {
    "tag": 2,
    "isHome": false,
    "isNee": false,
    "isMailing": true,
    "isCurrentTemporary": false, 
    "isLegal": false,
    "isOffice": false,
    "isPermanent": false
}
```

and it should probably look like:

```js
"type": "Mailing"
```

**Comment by albertjan** [comment]
I don't mind if this is closed. Newtonsoft.Json does this fine. Nobody probably wants to repeat that work in the internal json deserializer. (maybe we can nick a new one from mono that does this better.)

**Comment by khellang** [comment]
:smile:
