### ISSUE TITLE
Scripts.Render throws ArgumentNullException

### ISSUE THREAD

**Issue by synhershko** [NancyFx/Nancy#1515]
After following this: https://github.com/NancyFx/Nancy/wiki/How-to-use-System.Web.Optimization-Bundling-with-Nancy

And having this in my layout:

```C#
@Scripts.Render("~/content")
```

I'm getting the following exception as YSOD:

```
Value cannot be null.
Parameter name: httpContext

[ArgumentNullException: Value cannot be null.
Parameter name: httpContext]
   System.Web.HttpContextWrapper..ctor(HttpContext httpContext) +9720154
   System.Web.Optimization.Scripts.get_Context() +59
   System.Web.Optimization.Scripts.RenderFormat(String tagFormat, String[] paths) +86
   RazorOutput.RazorView.Execute() +2268
   Nancy.ViewEngines.Razor.NancyRazorViewBase`1.ExecuteView(String body, IDictionary`2 sectionContents) +111
   CallSite.Target(Closure , CallSite , Object , Object , Object ) +236
   System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3(CallSite site, T0 arg0, T1 arg1, T2 arg2) +468
   Nancy.ViewEngines.Razor.<>c__DisplayClass24.<RenderView>b__23(Stream stream) +2459
   Nancy.Hosting.Aspnet.NancyHandler.SetNancyResponseToHttpResponse(HttpContextBase context, Response response) +132
   Nancy.Hosting.Aspnet.NancyHandler.EndProcessRequest(Task`1 task) +125
   Nancy.Hosting.Aspnet.NancyHttpRequestHandler.EndProcessRequest(IAsyncResult result) +33
   System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +129
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +22
   System.Web.AsyncStepCompletionInfo.ReportError() +16
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9690182
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155
```

**Comment by vmrocha** [comment]
Does anyone managed to get system.web.optimization to work on nancy unit testing with xunit?

**Comment by staff0rd** [comment]
I had this problem too.  I compared my web.config to the one provided by @synhershko.  I was missing the following under `System.Web`, and upon adding it I no longer got the YSOD;

    <httpRuntime targetFramework="4.5" />

**Comment by rogersillito** [comment]
I already set targetFramework in my web.config but when running my tests I'm getting the same stack trace as above unless I remove the line that references the bundle from my template.  This issue still seems to be live?

**Comment by thecodejunkie** [comment]
This is not our package not our content (community contributed wiki page) so I am afraid we are unable to provide any good help on this

**Comment by rogersillito** [comment]
@thecodejunkie thanks for the clarification.  For others who might find their way here, my conclusion was that although it works fine with Nancy in a 'production' context ([once you have following this wiki page](https://github.com/NancyFx/Nancy/wiki/How-to-use-System.Web.Optimization-Bundling-with-Nancy)), ASP.NET Optimization/Bundling needs to be disabled/removed in order to make use of Nancy.Testing
