### ISSUE TITLE
Nancy.ViewEngines.ViewNotFoundException: Unable to locate view 'index'

### ISSUE THREAD

**Issue by mrThirsty** [NancyFx/Nancy#1528]
I created a self hosted project by using the Nancy Self host with razor project template. When I hit run all i get is this error message:

Nancy.RequestExecutionException: Oh noes! ---> Nancy.ViewEngines.ViewNotFoundException: Unable to locate view 'index'
Currently available view engine extensions: sshtml,html,htm
Locations inspected: views/Index/index-en-ZA,views/Index/index,Index/index-en-ZA,Index/index,views/index-en-ZA,views/index,index-en-ZA,index
Root path: C:\Sandbox\TFS\MusicBox\MusicBox.Debug\bin\Debug

I haven't made any changes to what was created when I created the project, and I have compared to another project I Created last year with nancy and there are no differences..

So what gives, why does this project template not work?

**Comment by pashute** [comment]
similar issue when I set two projects, and hand in a HostConfiguration with UrlReservations.CreateAutomatically = true in both, and two different uris, localhost:3579 and localhost:3580.  The first project succeeds the second one - identical except uri, fails.

            var uri =
                new Uri("http://localhost:3579");
            var uris = new[] {uri};
            var hostConfig = new HostConfiguration();
            hostConfig.UrlReservations.CreateAutomatically = true;

            using (var host = new NancyHost(hostConfig, uris))

**Comment by hikeeba** [comment]
I am also having this problem. Has a really simple cshtml file in my app, added the NuGet Razor view engine and it says 

```
Nancy.RequestExecutionException: Oh noes! ---> Nancy.ViewEngines.ViewNotFoundException: Unable to locate view 'razor.cshtml'
Currently available view engine extensions: sshtml,html,htm
Locations inspected: views/v1/v1/razor.cshtml-en-US,views/v1/v1/razor.cshtml,v1/v1/razor.cshtml-en-US,v1/v1/razor.cshtml,views/v1/razor.cshtml-en-US,views/v1/razor.cshtml,v1/razor.cshtml-en-US,v1/razor.cshtml,views/v1/razor.cshtml-en-US,views/v1/razor.cshtml,v1/razor.cshtml-en-US,v1/razor.cshtml,views/razor.cshtml-en-US,views/razor.cshtml,razor.cshtml-en-US,razor.cshtml
Root path: G:\Development\Axiom Pro Future Architecture Test 1\Source\Host\bin\Debug
If you were expecting raw data back, make sure you set the 'Accept'-header of the request to correct format, for example 'application/json'
   at Nancy.ViewEngines.DefaultViewFactory.GetRenderedView(String viewName, Object model, ViewLocationContext viewLocationContext)
   at Nancy.ViewEngines.DefaultViewFactory.RenderView(String viewName, Object model, ViewLocationContext viewLocationContext)
   at Nancy.Responses.Negotiation.ViewProcessor.Process(MediaRange requestedMediaRange, Object model, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(IEnumerable`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.CreateResponse(IList`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(Object routeResult, NancyContext context)
   at Nancy.Routing.DefaultRouteInvoker.<>c__DisplayClassa.b__6(Task`1 completedTask)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)
```

**Comment by pashute** [comment]
I found that inside the web.config it was referring to a different version (2.0) while in the references it said version 3.0.  See here for the official answer which got me in the correct direction....

http://stackoverflow.com/questions/34493086/which-dll-version-should-i-use-razor-dll-manifest-does-not-match-0x80131040

**Comment by bheydarshahi1beyond** [comment]
When I copied my solution over the Internet, Windows 10 blocked some files without telling me, including the file Nancy.ViewEngines.Razor.dll. Unblocking the file through its properties context menu fixed the issue for me.
