### ISSUE TITLE
WCF hosting - Multiple IIS hostnames

### ISSUE THREAD

**Issue by rintje** [NancyFx/Nancy#1575]
Hi there,

I'm trying to deploy a Nancy webservice via WCF hosting in an IIS website/application. When i add two hostname bindings to the application, the second one returns a 404.

The service is configured via a RouteTable in combination with a custom WebServiceHostFactory derived class:

RouteTable.Routes.Add(
    new ServiceRoute("MyServiceName", new MyNancyServiceHostFactory(), 
    typeof(NancyWcfGenericService)))

Are multiple IIS hostnames a supported scenario? If so, how to make it work?

**Comment by phillip-haydon** [comment]
I don't see any reason why this wouldn't work, however this issue seems dead in the water. I did test the diagnostics myself in a sub directory and it works, but I don't have IIS to test with sub applications.
