### ISSUE TITLE
Guidance for unofficial Nancy NuGet Packages

### ISSUE THREAD

**Issue by liddellj** [NancyFx/Nancy#1576]
I think it would be beneficial for the community if it was clear whether a given NuGet was an _official_ Nancy package (i.e. one which comes from the NancyFx org and is maintained by the core Nancy team), or whether it is written and maintained by a third party.

There are a few packages which do not appear within a repo under the NancyFx org, but which are named Nancy.{blah}, and use the same logo, e.g. [Nancy.MSOwinSecurity](http://www.nuget.org/packages/Nancy.MSOwinSecurity/), [Nancy.RouteHelpers](http://www.nuget.org/packages/Nancy.RouteHelpers/), [Nancy.Bootstrappers.Mef](http://www.nuget.org/packages/Nancy.Bootstrappers.Mef/). There are a bunch of other ones which are named Nancy.{blah}, but do not use the Nancy logo.

Perhaps provide some official guidance within the wiki which requests that people do not use the official Nancy logo, but instead provides an alternate 'Nancy Community', or 'Nancy Contrib' logo?

This would have a two-fold benefit in that it would make it clear which packages are official, and also give people a nice icon to use for their own packages.

**Comment by thecodejunkie** [comment]
Decided that we cannot really police this in a good way. Thanks

**Comment by phillip-haydon** [comment]
Personally I think this is more of an issue with NuGet itself rather than us. NuGet website makes it too easy to not be obvious about where the package comes from.
