### ISSUE TITLE
Token auth logout

### ISSUE THREAD

**Issue by Rafailong** [NancyFx/Nancy#1581]
Hi there,

I am using Token auth to secure my API. By now I have implemented the login of the API and it is working great.

But I don't have any idea how to implement the logout. Should I store the token in somewhere else so when the user wants to logout the token will be just lapsed?

Thanks in advance for your help!

**Comment by jeffdoolittle** [comment]
@khellang I propose this issue be marked as closed.

**Comment by jeffdoolittle** [comment]
thanks
