### ISSUE TITLE
Internal Server Error while logging out from iPad

### ISSUE THREAD

**Issue by DigitalFlow** [NancyFx/Nancy#1582]
Hello everyone,
I am experiencing problems with the internal LogoutAndRedirect function.
When a user is logged in and logs out from a desktop computer using FireFox, everything works as expected.
But when a user is logged in via iPad (Safari Browser) and logs out, I get an error page with error 500 - InternalServerError.
The Problem occurs in `Nancy.Authentication.Forms.FormsAuthentication.DecryptAndValidateAuthenticationCookie`, here is the relevant part of the stack:

```
Nancy.RequestExecutionException: Oh noes! ---> System.ArgumentOutOfRangeException: startIndex darf nicht länger als die Länge der Zeichenfolge sein. (EN: startIndex may not be higher than the length of the string)
Parametername: startIndex
bei System.String.InternalSubStringWithChecks(Int32 startIndex, Int32 length, Boolean fAlwaysCopy)
bei System.String.Substring(Int32 startIndex)
bei Nancy.Authentication.Forms.FormsAuthentication.DecryptAndValidateAuthenticationCookie(String cookieValue, FormsAuthenticationConfiguration configuration)
```

I'm currently drilling down the problem, but I would appreciate it, if someone had an idea what the problem could be.

Edit: So I installed Safari on the desktop computer and there are no problems, the log out works flawlessly. I then installed Chrome on the iPad and the log out works also.
The problem has to be the mobile safari browser.

**Comment by jongleur1983** [comment]
If I understand the stacktrace right, it would be great to get the cookieValue, ideally as used in ValidateAuthenticationCookie() and as sent by the browser(s) (not sure how to check that for a mobile safari browser).
Looking into the nancy source I guess it's a malformed cookie value used here. As your stack trace does not contain line numbers, there are two candidates for the Exception:

    var decodedCookie = Helpers.HttpUtility.UrlDecode(cookieValue);
    var hmacStringLength = Base64Helpers.GetBase64Length(configuration.CryptographyConfiguration.HmacProvider.HmacLength);
    var encryptedCookie = decodedCookie.Substring(hmacStringLength);
    var hmacString = decodedCookie.Substring(0, hmacStringLength);

**Comment by thecodejunkie** [comment]
This might have been fixed with the `v1.4.x` releases as we've changed encoding/decoding stuff + fixed a bug around cookie values such as `httpOnly` and `secure`

Any chance you could verify @DigitalFlow ?

**Comment by DigitalFlow** [comment]
Sure, I can test whether the issue still occurs with the newest version of Nancy.
Unfortunately I can't access the iPad before tomorrow, but I'll report when I had a chance to test this.

**Comment by thecodejunkie** [comment]
@DigitalFlow did you ever get around to testing this? Thanks
