### ISSUE TITLE
owin.ResponseStatusCode not set on uncaught exceptions

### ISSUE THREAD

**Issue by jchannon** [NancyFx/Nancy#1594]
By default if an exception is thrown Nancy captures it and sets `owin.ResponseStatusCode` to 500.  If for example, you throw an exception in a `IStatusCodeHandler` `owin.ResponseStatusCode` is set to 200.  If the exception is not caught in the owin middleware the owin host will convert it to a 500.  This is fine because the final response is 500 but if you have middleware inspecting the owin environment dictionary its misleading.

I've looked at the `NancyMiddleware.cs` https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Owin/NancyMiddleware.cs#L98 but I can't see where to set the status code as the `NancyEngine` catches the exception.  I guess we could check if `context.Items` has the owin dictionary in it and set the response status code where the exception gets caught but the whole Task voodoo going on in there seems delicate so I didn't want to change anything without checking where the best place to do it is first.

Thoughts?

**Comment by thecodejunkie** [comment]
So you guys agreed on a solution, but never implemented it? :smiley_cat:

**Comment by jchannon** [comment]
I don't know, is that the solution?

**Comment by jchannon** [comment]
I've just hit this again debugging an production issue!!

**Comment by jchannon** [comment]
Checked with @psibernetic and its still in master

**Comment by psibernetic** [comment]
IMO Nancy should catch exceptions and set the response status code to 500 if nothing else intervened so that other middleware have a chance to take part in the response party rather than needing to catch exceptions.

**Comment by thecodejunkie** [comment]
@jchannon @psibernetic perfect opportunity to become bff's and work on a pull-request together :smile:

**Comment by jchannon** [comment]
I'll let you do it tomorrow. It's in the scary bit of the code base :p

**Comment by khellang** [comment]
Closed with #2457
