### ISSUE TITLE
DefaultRouteDescriptionProvider fails with dynamic assemblies

### ISSUE THREAD

**Issue by sloncho** [NancyFx/Nancy#1622]
We use Reflection.Emit to create modules at runtime. When the `DefaultRouteDescriptionProvider` is hit, it fails with `NotSupportedException` on `assembly.GetManifestResourceNames`, as expected: http://msdn.microsoft.com/en-us/library/system.reflection.emit.assemblybuilder.getmanifestresourcenames%28v=vs.110%29.aspx

**Comment by khellang** [comment]
Closed with #1623 :+1:
