### ISSUE TITLE
Seperate libraries not loading defined nancy dependencies

### ISSUE THREAD

**Issue by jchannon** [NancyFx/Nancy#1629]
We all know of the issue where you have a `MyApp.Tests` lib that uses `Nancy.Testing` to test your app and the requirement to install `Nancy.Validation.FluentValidation` in your test lib for the test to pass validation. I think this is so that the dll is in the appdomain.

I've just lost 3 hours on the same issue but this time with `Nancy.Serialization.ServiceStack`

In my test lib I'm using HttpClient and the OWIN pipeline to post the below model as JSON. In my module it calls BindAndValidate on this model:

```
    public class ApiLoggingModel
    {
        public LoggingEnum Level { get; set; }
        public string Message { get; set; }
    }
```

All is well however its using ` Nancy.ModelBinding.DefaultBodyDeserializers.JsonBodyDeserializer` not the `Nancy.Serialization.ServiceStack` one I have registered in my app.  The only reason I noticed was because ServiceStack was throwing an exception I assume on enums when the app was running. My tests were saying all was fine but in reality it wasn't the case.  If I added `Nancy.Serialization.ServiceStack` to my tests lib it would show the same behaviour.

This leads me onto the same scenario with OWIN hosting. I have a IIS Host project and a Self host project. Both reference a class lib with all my modules, validation etc in it.  I have to install the `Nancy.Validation.FluentValidation` package in my host project for the validation stuff to work, the same goes for the serialization stuff.

I'm not sure how we get around this issue but its a huge PITA and I'm not sure if its a nancy issue we need to solve or a .net thing

**Comment by thecodejunkie** [comment]
@jchannon isn't this just the classic ".net trying to be smart with assembly references problem?
