### ISSUE TITLE
Inconsistent behavior of OnError pipeline

### ISSUE THREAD

**Issue by sloncho** [NancyFx/Nancy#1638]
According to the wiki: "If only one exception is wrapped, then Nancy will unwrap that exception and hand it to the OnError pipeline."

The above statement is right, if a hook is attached to the application piepelines.

But if an error handler is attached to the pipelines in the module, it gets the wrapped AggregationException instead.

See [test, demonstrating the issue](https://gist.github.com/sloncho/f43e16f597548678b787).

**Comment by alanedwardes** [comment]
I am also seeing this. As there aren't any responses to this I'm guessing it is the desired behavior, and module code should be written expecting to unwrap the exceptions?

Thanks.

**Comment by horsdal** [comment]
That does seem inconsistent. Do you want to send PR for unwrapping in the module error pipeline?

**Comment by sloncho** [comment]
I'm working on it, and just posted on Jabbr:
just wondering which route to take
looking at the code, the change need to happen in DefaultRequestDispatcher, and flattent the exception there
to avoid duplicated code, is it ok to use NancyEngine.FlattenException (which sounds like a bad idea to me for coupling these 2 classes). Or should I proceed with actually extract the exception handling in its own class/interface?

**Comment by sloncho** [comment]
Before I proceed, based on my jabbr conversation w/ @khellang , I need some clarification if the current implementation of flattening is the desired one. Probably @rasmus-beck can add some insight.

For what I see, if from some route a custom exception is thrown, with nested inner exceptions, the current implementation of [FlattenException](https://github.com/NancyFx/Nancy/blob/89f50d8637a51966762fd7fbf09a833f484287cb/src/Nancy/NancyEngine.cs#L307) will return only the inner-most one, thus loosing information.

I'm talking about `MyCustomException(SomeOtherCustomException(SomeSystemException)))` scenario. Is it the desired behavior `FlattenException` to return `SomeSystemException`?

As @khellang pointed out, it is unlikely that some of the inner exceptions will be an aggregate exception, if the outermost one is not. While moveing this code to it's own extension method, which can be reused in the `DefaultRequestDispatcher`, should I change the behavior as well? If yes, what would be the new one?

Thanks

**Comment by khellang** [comment]
Was this fixed with #2066?

**Comment by khellang** [comment]
Could any of you try to pull the latest build for the CI feed at [MyGet](http://myget.org/gallery/nancyfx) and test this out?

**Comment by sloncho** [comment]
Yes, my test passes with the latest code, as well as it does not unwrap inner exceptions.

**Comment by khellang** [comment]
Alright, I'm marking this as closed by #2066. The fix'll be out as part of 1.4 :smile:

**Comment by sloncho** [comment]
Although I do not see any code which addresses the issue in #2066. I.e. the code there deals only with the inner exceptions. I do not see the change which fixes the unwrapping on the module pipeline.

Unless it was fixed as a side effect somewhere else.

**Comment by rasmus-beck** [comment]
@sloncho I'm a little late to the party I see. But you seem to have it under control. Let me know if there is anything else you need my help with on this.
