### ISSUE TITLE
First chance exceptions of type RuntimeBinderException

### ISSUE THREAD

**Issue by webdev7** [NancyFx/Nancy#1642]
I am getting a lot of this log outputs :

> A first chance exception of type 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' occurred in Microsoft.CSharp.dll

So I have tried the examples and the same happens to me for example in the ModelBinder example of Nancy:

```
   private static Response CastResultToResponse(dynamic result)
    {
        try
        {
            return (Response)result;
        }
        catch
        {
            return null;
        }
    }
```

Does anybody has the same behavior?

Kind regards,
Tom

**Comment by hiscodeness** [comment]
@thecodejunkie Just to make sure, has something change since you wrote the previous comment, because I'm definitely seeing this exception while doing model binding? Here's the exception message: 
```
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll ("Cannot implicitly convert type 'Nancy.ModelBinding.DynamicModelBinderAdapter' to 'MyApp.Api.UserDataQuery'")
```

The exception is handled by Nancy and model binding works fine, so this doesn't affect the application.

**Comment by tynor88** [comment]
Something has definitely changed. I wrote some Unit Tests last year, which have been running fine. Now after the upgrade i get the above RuntimeBinderException both locally and on the BuildServer when trying to Bind<>.

Any fix for this issue?

**Comment by thecodejunkie** [comment]
Hi

Could you share the failing tests? Without a reliable way of reproducing
the problem we have no way to analyze and possibly fix it

Thanks
