### ISSUE TITLE
Exception when use GenericFileResponse

### ISSUE THREAD

**Issue by azhidkov** [NancyFx/Nancy#1658]
In my program I need **Content-Length** header be set. I use self-host for hosting nancy but it doesn't return me header, and when I try to set Content-Length manuall I've got *System.Net.WebExceptionThe remote server returned an error: (500) Internal Server Error.*

I saw that in unit-tests [here (GenericFileResponseFixture.cs)](https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Tests/Unit/Responses/GenericFileResponseFixture.cs) this work fine, but when I try to use it in self-host application it doesn't work. 

I wrote simple test for illustrating this (placed in NancySelfHostFixture.cs):
```csharp
[Fact]
public void Should_return_audio_stream_with_content_length()
    {
        using (CreateAndOpenSelfHost())
        {
            // when
            var request = WebRequest.Create(new Uri(BaseUri, "record/1234"));
            request.Method = "GET";

            WebResponse response = request.GetResponse();
            Stream s = response.GetResponseStream();

            byte[] bytes = new byte[4 * 1024 * 1024];
            s.Read(bytes, 0, bytes.Length);

            // assert
            bytes.Length.ShouldBeGreaterThan(1);
        }
    }
``` 

And I added new route in TestModule:
```csharp
Get["/record/{id}"] = parameters =>
{
    var resources = new DirectoryInfo("../../Resources/"); // file from resources
    GenericFileResponse.SafePaths.Add(resources.FullName);

    var file = new FileInfo("../../Resources/record.wav");
    var response = new GenericFileResponse(file.FullName, "application/octet-stream");
    return response;
};
```

When I try to get stream back from the server I've got exception 'The parameter is incorrect'. 
I found out that error occur in GenericFileResponse in **GetFileContent** method.

**Comment by lund** [comment]
It seems like this error has been reintroduced in another form in v1.0.
The same exception is thrown when writing the result to the HttpResponseStream.

**Comment by thecodejunkie** [comment]
@azhidkov @xt0rted @lund Sorry for the massive delay =( I just tired this on master, using the test and route that @azhidkov shared in the initial post and it worked flawless. So perhaps this was something we sorted after it was reported. If either of you are still having issues with this, please let us know. That said, I am closing this issue now. 

Thank you
