### ISSUE TITLE
SSL Offloading not supported

### ISSUE THREAD

**Issue by mvandiest** [NancyFx/Nancy#1679]
Nancy.Security.ModuleSecurity:

Currently this check for a secure request is limited to inspecting the requesting url:

`if (!request.Url.IsSecure)`

Using SSL Offloading this check will usually be false as the communiction between the Offloader and the server is done over http internally. 

Typically in offloading scenarios the offloader will add a custom header, e.g. AWS uses X-Forwarded-Proto: http://amzn.to/1ipyAil

I'm under the gun on a project so I don't have time to make the mod and pull request, but it would be nice if this could be modified to look for a configurable custom header to inspect in addition to the Url check.

**Comment by khellang** [comment]
Closed with #1815

**Comment by khellang** [comment]
In your bootstrapper, you can now do `SSLProxy.RewriteSchemeUsingForwardedHeaders(pipelines)` to rewrite the scheme to `https` if there's a `X-Forwarded-Proto` or a `Forwarded` header present.

**Comment by mvandiest** [comment]
Awesome. Thanks!

**Comment by khellang** [comment]
@mvandiest Hopefully we'll be able to push v1.1 sometime tomorrow. If you need the bits before then, pull them [from MyGet](https://www.myget.org/gallery/nancyfx) :smile:
