### ISSUE TITLE
Root Path when Self-Hosting

### ISSUE THREAD

**Issue by CallumVass** [NancyFx/Nancy#1688]
Hi,

When working with static content / views on a self-hosted application, the root path is set to the output directory: ie bin\Debug . This means that when modifying the static content, the program has to be restarted to see the changes. It would make sense if the default behavior would be for it to look in the project root for static content, as its very rarely when you modify the output files directly, right?

To get it to work for me, with the help of @khellang, I've had to do the following:

```
public class SelfHostRootPathProvider : IRootPathProvider
{
    public string GetRootPath()
    {
        return StaticConfiguration.IsRunningDebug 
            ? Path.GetFullPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", "..")) 
            : AppDomain.CurrentDomain.BaseDirectory;
    }
}

public class Bootstrapper : DefaultNancyBootstrapper
{
    protected override IRootPathProvider RootPathProvider
    {
        get { return new SelfHostRootPathProvider(); }
    }
}
```

Then in my Main method:

```
        using (var host = new NancyHost(new Uri("http://localhost:1234"), new Bootstrapper()))
        {
            host.Start();
            Console.ReadLine();
        }
```

Would this be something that could be incorporated into the code-base? Thoughts?

**Comment by cpisto** [comment]
I'm a fan of this solution (or something similar), without it its pretty tedious editing view templates and static content while debugging in visual studio.

**Comment by michaelrkn** [comment]
Even simpler:

```csharp
namespace MyAppName
{
    using Nancy;
    using System.IO;

    public class CustomRootPathProvider : IRootPathProvider
    {
        public string GetRootPath()
        {
            return Directory.GetCurrentDirectory();
        }
    }
}
```
