### ISSUE TITLE
Allocate maintainers to the bootstrapper repositories

### ISSUE THREAD

**Issue by thecodejunkie** [NancyFx/Nancy#1712]
Nancy has the ability to use any IoC container with the application you write. The container you choose is not only used to resolve dependencies in your modules etc. but is also an intricate part Nancy.

We use a concept we called the [bootstrapper](https://github.com/NancyFx/Nancy/wiki/Bootstrapper) that wraps the container and uses it to compose the actual framework itself. No container, no framework at runtime :)

Right now we ship bootstrapper implementations for TinyIoC (shipped in Nancy.dll), Autofac, Ninject, StructureMap, Unity and Windsor. We would love to continue to do so, but in order to do this we are going to need a bit of help from the community.

We are looking for Nancy users, that use the various bootstrappers that we ship and that **has a good understanding of the underlying container that it uses**. Essentially we are looking for people to work with us to make sure that the various bootstrapper implementations are as good as they possibly can be, both now and moving forward.

This would be done by having you work with us and get commit access to the bootstrapper repository that you want to help maintain. We are not necessarily looking for just a single contributor per bootstrapper, so if there are multiple people interested, then we are happy to let you work as a team.

You would, of course, work close with the core Nancy team because we need to be able to discuss changes to the bootstrapper architecture and the impact it would have on the bootstrapper implementations.

We have a [test suite](https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Tests/Unit/Bootstrapper/NancyBootstrapperBaseFixture.cs) for the expected behaviour of a bootstrapper implementation (help verify lifetime scopes etc.) and we are looking into writing some documentation that explains the expectations and lifetime of a bootstrapper to help you understand the mechanics when helping us maintain the various implementations.

If you are interested in helping out, leave a comment along with the name(s) of the bootstrapper(s) that you would be interested in getting involved in and we'll take it from there.

Thanks!

**PS. If you choose to participate then you are not signing up for a life-sentence (in case you want to)! We understand that peoples availability will change after time, just as it do for us in the Nancy team. We will also see about getting 2-3 contributors on each boostrapper and have you work as a team. That should help reduce the amount of effort required**
## Potential maintainers
- Autofac:
- Ninject:
- StructureMap:
- Unity:
- Windsor:
## TODO

Let's build up a check-list of things needed to be done to make this happen. Share your thoughts, suggestions and ideas!

**Comment by asbjornu** [comment]
@thecodejunkie We're still waiting for a resolution on this. The most important thing for me isn't necessarily having official maintainer status, but rather a set of tests that the implementation needs to comply with. How far have you, @grumpydev et al gotten on this? Any progress since November 5th 2014? :smiley:

**Comment by grumpydev** [comment]
There are a set of tests around lifetimes etc, but unfortunately they aren't great and are a pain to implement - something could be done with a set of scenarios and the testing framework though I guess, although when scanning is involved it's hard to isolate unless we end up with a multitude of projects.

**Comment by asbjornu** [comment]
@grumpydev Great! What I'd love to see is a NuGet package called `Nancy.Bootstrappers.Testing` or something similar, where all the different assertions are placed and where each bootstrapper implementation can take care of fulfilling the requirements. This way, it's easy to continually update Nancy along with its bootstrapping requirements, which in the core of Nancy will be fulfilled by TinyIoC.

If you could start implementing such a package for the tests revolving around TinyIoC within the Nancy solution, we can work together on improving it and ensuring that Nancy's requirements are taken care of. Each container will of course have edge cases that the core test suite can't cater to, so each bootstrapper implementation will need its own set of tests on top of the common ones, but having a common test suite would take us a long way and give us a lot more robust and complete implementations than what we have today, I'm sure.

**Comment by jvandertil** [comment]
I can give a hand with the StructureMap bootstrapper :)

**Comment by asbjornu** [comment]
@thecodejunkie: Can you please elaborate on why this was closed?
