### ISSUE TITLE
Unhandled exception when use Hosting.Self with port forwarding

### ISSUE THREAD

**Issue by ErwinCat** [NancyFx/Nancy#1724]
Nancy.Hosting.Self version 0.23.2.0. Run it on local network PC. 
I use router with port forwarding from provider to local network(see image).
Request from local PC work fine, but when request comes from an external network, unhandled exception occurred: "System.InvalidOperationException: Unable to locate base URI for request: 95.78.85.102". I think Exception thrown at "NancyHost" class "ConvertRequestToNancyRequest" method:
```C#
private Request ConvertRequestToNancyRequest(HttpListenerRequest request)
        {
            var baseUri = this.baseUriList.FirstOrDefault(uri => uri.IsCaseInsensitiveBaseOf(request.Url));
```
Property "request.Url" contain external ip address from provider, and property "this.baseUriList" contain local ip address.
Is it bug or feature?
P.S. Sorry for my english
![1](https://cloud.githubusercontent.com/assets/1770739/4692210/ce2c0b74-5752-11e4-97dc-c51140afa71c.png)

**Comment by abdullin** [comment]
This issue prevents use of NancyFx self-hosting on Windows Azure

**Comment by grumpydev** [comment]
Odd, I have self hosted Nancy services in Azure, although they are running in VMs, how are you running yours?

**Comment by grumpydev** [comment]
Does it dump the error to the error hook or just eat it completely?

**Comment by jchannon** [comment]
You could also make use of Nancy Self Host exception handler `UnhandledExceptionCallback` https://github.com/NancyFx/Nancy/wiki/Self-Hosting-Nancy#host-configuration

**Comment by abdullin** [comment]
1. Using the latest NancyFx
2. Elevated privileges
3. HTTPS endpoint

Launching things this way:

```
public override void Run()
		{
			var processes = ApiEnvironment.WireHandlers( _inputsRegistrar, _client );
			var nancyBootstrapper = ApiEnvironment.WireApi( _inputsRegistrar );


			var internalUri = new Uri(GetEndpointAsUri("Http"));
			using (var nancyHost = new NancyHost(nancyBootstrapper, internalUri))
			{
				nancyHost.Start();
				_log.Information( "Worker role us running" );
				var token = cancellationTokenSource.Token;
				var task = host.Start( token );

				token.WaitHandle.WaitOne();
				if( !task.Wait( 5000 ) )
					_log.Warning( "Host didn't stop in time." );
			}
		}

		private static string GetEndpointAsUri( string name )
		{
			var http = RoleEnvironment.CurrentRoleInstance.InstanceEndpoints[ name ];
			var baseUri = String.Format( "{0}://{1}", http.Protocol, http.IPEndpoint );
			return baseUri;
		}

```


If I RDP to the Cloud worker, then I can access site from the internal IP address, however trying to access it from the public IP address (public side of the load balancer) ends up in timeout in the browser

**Comment by abdullin** [comment]
PS: thanks for the heads-up regarding the error hook. I'll give it a try

**Comment by abdullin** [comment]
NB: I didn't test with exception hook, however my guess is that NancyHost could blow up here:

```
            var baseUri = this.baseUriList.FirstOrDefault(uri => uri.IsCaseInsensitiveBaseOf(request.Url));

            if (baseUri == null)
            {
                throw new InvalidOperationException(String.Format("Unable to locate base URI for request: {0}",request.Url));
            }
```

Reason: request will have public url, which is different from the internal endpoint url.

**Comment by grumpydev** [comment]
Is there a reason why you are binding just to a specific IP btw rather than using localhost with rewriting switched on (so it rewrites to bind to http://+:port/ ?

**Comment by abdullin** [comment]
I tried doing that as well. It exhibited the same behavior.

**Comment by abdullin** [comment]
Exception detail:
```
2015-04-14 14:41:16.342 +00:00 [Fatal] Unhandled failure
System.InvalidOperationException: Unable to locate base URI for request: https://xxxx.skuvault.com/
   at Nancy.Hosting.Self.NancyHost.ConvertRequestToNancyRequest(HttpListenerRequest request)
   at Nancy.Hosting.Self.NancyHost.Process(HttpListenerContext ctx)
```

**Comment by grumpydev** [comment]
I wonder if we can do some jiggery pokery with request.LocalEndPoint if it can't find it using request.Url - I assume that will give us the actual local binding port/ip, rather than the requested one.

**Comment by abdullin** [comment]
I recall reading on forwarding in .NET world. It gets messy. I don't think you can get the local binding IP in all cases. 

What about allowing to provide public url in the config (adding it to the baseUri list)?

**Comment by grumpydev** [comment]
If you're just listening on one hostname it's quite an easy "fix", the difficulty comes when we bind to multiple uris and we want to be able to still separate base path from the actual path.

**Comment by abdullin** [comment]
Another alternative - provide delegate to let user provide a custom resolution, if needed. Default resolution would be something like `request => this.baseUriList.FirstOrDefault(uri => uri.IsCaseInsensitiveBaseOf(request.Url))`

In my case the override would be `request => "known public url";`

**Comment by grumpydev** [comment]
I wonder if this would work (totally untested)

https://github.com/grumpydev/Nancy/blob/SelfHostPortForward/src/Nancy.Hosting.Self/NancyHost.cs#L289

**Comment by grumpydev** [comment]
Saw this today and thought it was worth mentioning @abdullin https://technet.microsoft.com/library/security/ms15-034?f=255&MSPPError=-2147217396

**Comment by abdullin** [comment]
@grumpydev Thank you for the heads up. 

BTW, fix that you mentioned earlier - didn't work. I'll try to dig further on that tomorrow and will post back.

**Comment by abdullin** [comment]
I ended up with adding this as a fall-back to `GetBaseUri`:

    return new Uri(request.Url.GetLeftPart(UriPartial.Authority));

**Comment by grumpydev** [comment]
We're about to do a new release and I'd like to get a fix or workaround in for this, I'm not 100% sure what that line does though :D

**Comment by abdullin** [comment]
Basically I ended up doing that:
```
		private Uri GetBaseUri(HttpListenerRequest request)
		{
			var url = this.baseUriList.FirstOrDefault(uri => uri.IsCaseInsensitiveBaseOf(request.Url));

			if (url != null)
			{
				return url;
			}

			// we get here, if request is forwarded (e.g. by azure load balancer)
			return new Uri(request.Url.GetLeftPart(UriPartial.Authority));
		}
```

More robust scenario would be to provide a boolean option, which allows to use `Authority` (Schema + Host + Port) as base uri, if base Uri doesn't match normally. It will default to false (current behavior).

**Comment by khellang** [comment]
@grumpydev Does #1900 mean we can close this?

**Comment by grumpydev** [comment]
Yes, assumed github would have done it automatically, but I guess not :)
