### ISSUE TITLE
Replace convention based approach in metadata modules

### ISSUE THREAD

**Issue by liddellj** [NancyFx/Nancy#1729]
Currently metadata modules (implementations of `IMetadataModule`) are resolved through a convention based approach, but I've seen feedback from a few parties that this is a bit crap. It's not kind to refactoring, and it's not entirely obvious what's going on.

I think a better approach would be to allow `IMetadataModule` implementations to decide whether they can provide metadata for a given `INancyModule` by adding the following method to the `IMetadataModule` interface:

```csharp
/// <summary>
/// Returns a value indicating whether the <see cref="IMetadataModule"/> provides metadata for the given <see cref="INancyModule"/>.
/// </summary>
/// <param name="module">The Nancy module.</param>
/// <returns>True if the <see cref="IMetadataModule"/> provides metadata for the given <see cref="INancyModule"/>, otherwise false.</returns>
bool CanDescribe(INancyModule module);
```

This change would go hand-in-hand with removing the convention based approach, which would make this a breaking change.

I'm opening this issue to discuss the idea before I open a PR.

**Comment by thecodejunkie** [comment]
Closing this with @liddellj blessing :grin:
