### ISSUE TITLE
Rake fails on pi using latest albacore

### ISSUE THREAD

**Issue by jarred-s** [NancyFx/Nancy#1742]
Running rake mono fails to install on the raspberry pi after following the instructions at https://github.com/NancyFx/Nancy/wiki/Running-Nancy-on-your-Raspberry-Pi due to the albacore dependency.

Fails using the latest albacore 2.2.0
    
    pi@raspy ~/Nancy $ sudo gem install albacore
    Fetching: albacore-2.2.0.gem (100%)
    Successfully installed albacore-2.2.0
    1 gem installed
    Installing ri documentation for albacore-2.2.0...
    Installing RDoc documentation for albacore-2.2.0...
    pi@raspy ~/Nancy $ rake mono
    rake aborted!
    NameError: uninitialized constant Albacore::Task
    /home/pi/code/Nancy/customassemblyinfo.rb:5:in `<class:CustomAssemblyInfo>'
    /home/pi/code/Nancy/customassemblyinfo.rb:4:in `<top (required)>'
    /home/pi/code/Nancy/rakefile.rb:6:in `<top (required)>'
    (See full trace by running task with --trace)

Fails forcing albacore 1.0.0

    pi@raspy ~/Nancy $ sudo gem install albacore --version "~> 1.0"
    Fetching: albacore-1.0.0.gem (100%)
    Successfully installed albacore-1.0.0
    1 gem installed
    Installing ri documentation for albacore-1.0.0...
    Installing RDoc documentation for albacore-1.0.0...
    pi@raspy ~/Nancy $ rake mono
    Version: 0.23.2
    Main project does not update assembly info
    D, [2014-11-10T22:48:31.066781 #2588] DEBUG -- : Executing xbuild: "" "src/Nancy.sln" /p:configuration="MonoRelease" /p:TagetFrameworkProfile="" /p:TargetFrameworkVersion="v4.0"
    sh: 1: : Permission denied
    F, [2014-11-10T22:48:31.109831 #2588] FATAL -- : XBuild failed, see the build log for more details.
    rake aborted!
    XBuild failed, see the build log for more details.
    /var/lib/gems/1.9.1/gems/albacore-1.0.0/lib/albacore/support/failure.rb:12:in `fail_with_message'
    /var/lib/gems/1.9.1/gems/albacore-1.0.0/lib/albacore/xbuild.rb:30:in `execute'
    /var/lib/gems/1.9.1/gems/albacore-1.0.0/lib/albacore/support/createtask.rb:24:in `block in xbuild'
    Tasks: TOP => mono => compilemono
    (See full trace by running task with --trace)

After finding the version available when the wiki article was written found it works forcing albacore 1.0.0.rc2 (rc3 showed the same error as above).

    sudo gem install albacore --version "1.0.0.rc2"

I'll update the wiki to reflect this, could it be fixed by forcing rc2 in the Gemfile?

**Comment by Vadi** [comment]
Is there any solution to this issue? I am trying to compile Nancy in Mac OSX.

**Comment by khellang** [comment]
I think #1956 will address this?

**Comment by khellang** [comment]
BTW, Travis builds Nancy on UNIX on every commit on master, so it can't be that bad :wink:

**Comment by jarred-s** [comment]
The fix for me on the pi was to force albacore version 1.0.0.rc2.

Anything newer or older would fail.

**Comment by khellang** [comment]
Yeah, it's very picky; https://github.com/NancyFx/Nancy/blob/5dc9e2a179c5f3a50f6caf238d0341cdd2dd1474/.travis.yml#L12
