### ISSUE TITLE
Update Documentation to include more information on model binding

### ISSUE THREAD

**Issue by metatron-the-chronicler** [NancyFx/Nancy#1746]
Things like creating custom model binds need to be explained in detail on the wiki.  It is not good that information like this is on stackoverflow rather than the documentation section(s) for this project.  As an example I found this answer on stackoverflow in regards to creating a custom model binder: http://stackoverflow.com/questions/13730352/multiple-custom-model-binders-in-nancy
however it ends up not being clear (to someone not familiar with how Nancy works.) about where registration would take place in the bootstrapper if auto discovery failed.  The wiki docs on model binding only cover the simplest case where everything works.

**Comment by jchannon** [comment]
Our Wiki can be edited by anyone, please feel free to add anything from the SO post to the model binding page in the wiki
