### ISSUE TITLE
In Razor use .targets file instead of changing Build Events

### ISSUE THREAD

**Issue by Crisfole** [NancyFx/Nancy#1747]
NuGet allows installing `.targets` files that can change the build in a more easily reversible and extensible manner than adding text manually.

Plant something like the following into the `build` nuget directory to copy files after a successful build:

    <Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
      <PropertyGroup>
        <BuildDependsOn>
          $(BuildDependsOn);
          CopyRazorStuff
        </BuildDependsOn>
      </PropertyGroup>

      <Target Name="CopyRazorStuff" Condition="$(Configuration)'=='retail'">
        <Copy SourceFiles="$(SolutionDir)packages\Nancy.Viewengines.Razor.0.23.2\BuildProviders\Nancy.ViewEngines.Razor.BuildProviders.dll" DestinationFiles="$(ProjectDir)bin\" />
        <Copy SourceFiles="$(SolutionDir)packages\Nancy.Viewengines.Razor.0.23.2\lib\Net40\Nancy.ViewEngines.Razor.dll" DestinationFiles="$(ProjectDir)bin\" />
      </Target>
    </Project>

**Comment by khellang** [comment]
Should be fixed with #2101
