### ISSUE TITLE
TinyIoC + embedded dependencies

### ISSUE THREAD

**Issue by ppekrol** [NancyFx/Nancy#1767]
Hi,

it looks like TinyIoC is not handling embedded dependencies well. 
Our Raven.*.dll contain such dependencies (using https://github.com/Fody/Costura) and when AutoRegistration is taking place it throws. I substituted TinyIoC with structuremap and everything is working fine.

Simplest way to reproduce it:
- Create new empty web project
- install Nancy, Nancy.Hosting.AspNet
- install https://www.nuget.org/packages/RavenDB.Client (used 3.0.3528)
- run the application

[FileNotFoundException: Could not load file or assembly 'ICSharpCode.NRefactory.CSharp, Version=5.0.0.0, Culture=neutral, PublicKeyToken=d4bfe873e7598c49' or one of its dependencies. The system cannot find the file specified.]
   System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type) +0
   System.RuntimeTypeCache.GetEnclosingType() +24
   System.RuntimeType.get_DeclaringType() +16
   Nancy.TinyIoc.TinyIoCContainer.<AutoRegisterInternal>b__13(Type type) +126
   System.Linq.WhereListIterator`1.MoveNext() +56
   Nancy.TinyIoc.TinyIoCContainer.AutoRegisterInternal(IEnumerable`1 assemblies, DuplicateImplementationActions duplicateAction, Func`2 registrationPredicate) +744
   Nancy.TinyIoc.TinyIoCContainer.AutoRegister(IEnumerable`1 assemblies, DuplicateImplementationActions duplicateAction, Func`2 registrationPredicate) +43
   Nancy.DefaultNancyBootstrapper.AutoRegister(TinyIoCContainer container, IEnumerable`1 ignoredAssemblies) +276
   Nancy.DefaultNancyBootstrapper.ConfigureApplicationContainer(TinyIoCContainer container) +65
   Nancy.Bootstrapper.NancyBootstrapperBase`1.Initialise() +388
   Nancy.Hosting.Aspnet.NancyHttpRequestHandler..cctor() +56

To eliminate this problem I've created a custom bootstrapper, but I think that TinyIoC should handle this case better.

```
public class TinyIoCBootstrapper : DefaultNancyBootstrapper
{
    protected override void ConfigureApplicationContainer(TinyIoCContainer container)
    {
        base.ConfigureApplicationContainer(container);

        var store = new DocumentStore { Url = "http://localhost:8080/", DefaultDatabase = "Northwind" }.Initialize();

        container.Register(store);
    }

    protected override IEnumerable<Func<Assembly, bool>> AutoRegisterIgnoredAssemblies
    {
        get
        {
            return base.AutoRegisterIgnoredAssemblies
                .Concat(new Func<Assembly, bool>[]
                    {
                        assembly => assembly == typeof(IDocumentStore).Assembly
                    });
        }
    }
}
```

**Comment by PureKrome** [comment]
Any further update on this? This issue is _really_ hurting us at the moment :cry: (Note: I hate asking for help without trying to help, first :cry: )

**Comment by grumpydev** [comment]
I'm hoping it's just another exception catch, but haven't had chance to look at it yet .. if you add a nasty "catchall exception" around the assembly loading/autoregister does it go away?

**Comment by PureKrome** [comment]
@grumpydev Adding a _catchall exception_ ... isn't that just avoiding the real issue (whatever that is) and not really fixing the root problem?

**Comment by khellang** [comment]
![Pokemon Exception Handling](http://g-images.amazon.com/images/G/01/toys/brands/pokemon/main.gif)

**Comment by grumpydev** [comment]
@PureKrome a catchall is the wrong solution yes, but the correct solution is probably to catch a type of exception I'm not already catching.. stuff can go wrong when loading/enumerating assemblies,so specific exceptions are caught - I assume this is one i'm not catching, but if you can wrap it in a catch all I will know if it's as simple as finding the right exception or not :)

**Comment by PureKrome** [comment]
@grumpydev ah kewl. cheers :)

@khellang 
![oh you!](http://i.giphy.com/n988gduPMFC8w.gif)

**Comment by PureKrome** [comment]
@grumpydev I haven't tried adding a catchall thingy yet in _our_ codebase .. because i'm not sure where, etc?

I'm looking a the wiki (specifically, [the bootstrapper page](https://github.com/NancyFx/Nancy/wiki/Bootstrapper)) but i can't see anywhere, where it mentions specific TinyIOC stuff.

Also, I thought [auto-registration was disabled in v 0,12](http://elegantcode.com/2012/09/12/nancy-0-12-released/) ? This is an issue with auto-reg?

**Comment by PureKrome** [comment]
@ppekrol I just got mine working finely.

Like you suggested above, your first fix then opened up the next problem .. with some scanning thingy against `Raven.Database`. R.D is referencing `System.Web.Http 5.2.2.0` which I guess I'm not using .. and :boom: .. 

So following you're lead, I asked Nancy to ignore `Raven.Database` also :)

    protected override IEnumerable<Func<Assembly, bool>> AutoRegisterIgnoredAssemblies
    {
        get
        {
            return base.AutoRegisterIgnoredAssemblies
                .Concat(new Func<Assembly, bool>[]
                {
                    assembly => assembly == typeof(IDocumentStore).Assembly,
                    assembly => assembly.FullName.StartsWith("Raven.Database", StringComparison.OrdinalIgnoreCase)
                });
        }
    }

and .. we're back.

Still, this is a cheap band-aid fix until the proper resolution is found.

Note: i'm not sure if this would work also? `assembly => assembly.FullName.StartsWith("Raven.", StringComparison.OrdinalIgnoreCase)` .. ie ... don't do anything for any Raven dll's.

**Comment by ppekrol** [comment]
@PureKrome yes, all Raven assemblies should be ignored (for now).

I assumed that you were not referencing Raven.Database, because you said earlier that you are not using Embedded, apologies for bad assumption.

Yes, your solution (with StartsWith) should work.

**Comment by PureKrome** [comment]
My bad - i'm not using Embedded at all for -LIVE- .. but for our unit tests, then yes we are.

My poor communication there. Sincere apologies.

**Comment by kspeakman** [comment]
I'm having this exact error. In my case, I'm using embedded RavenDB in integration tests and then quite separately have some unit tests against Nancy services, all using MSTest. There are no test projects which use both Nancy and RavenDB. The error only occurs during the TFS build process when the tests are run, which results in all Nancy tests failing with the exact error given in the OP. The same tests pass when run in Visual Studio, even on the build machine.

**Comment by mthird** [comment]
For anyone still having this problem, I had to add the Raven.Abstractions assembly to the list.  Just replace the AutoRegisteredIgnoredAssemblies method with the following:

```c#
        protected override IEnumerable<Func<Assembly, bool>> AutoRegisterIgnoredAssemblies
        {
            get
            {
                return base.AutoRegisterIgnoredAssemblies
                    .Concat(new Func<Assembly, bool>[]
                        {
                            assembly => assembly == typeof(IDocumentStore).Assembly || assembly == typeof(DocumentHelpers).Assembly
                        });
            }
        }
```

**Comment by kspeakman** [comment]
I upgraded to TFS 2015, and using the newer build process, I no longer have this issue.

**Comment by luisrudge** [comment]
Thanks @mthird. Your solution works for me!
