### ISSUE TITLE
Nancy.Hosting.ASP - MaximumRequestLength exceeded

### ISSUE THREAD

**Issue by gbrown31** [NancyFx/Nancy#1768]
Hi,

I am attempting to upload files using Nancy hosted in ASP.NET running in IIS 8, I'm running into an issue where the request is throwing an exception in the NancyHandler.cs in the Nancy.Hosting.Aspnet project.

Attached is a screenshot of the error using the file upload demo. Included in the screen shot is my web.config, with request limits commented out so as to use the default IIS settings. I know that I could set these to a very high value so that this exception is avoided but that is undesirable for my project.

![nancy - maxlengthexception](https://cloud.githubusercontent.com/assets/1902412/5413202/3e06e318-820c-11e4-9bb0-87b41518a46b.jpg)

Ideally, what I would like to happen is to set my web.config values to a reasonable limit and handle the exception with something along the lines of the IStatusCodeHandler interface that Nancy provides. However, the request is never reaching my application because of the request limit exception. Hopefully you can help me as this is the first issue I've found whilst using Nancy that there isn't an elegant solution for.

Regards,
Gary

**Comment by gbrown31** [comment]
@khellang thanks for response and info. Adding a global.asx file to handle all errors seems a bit ugly in comparion to other status codes that can be handled through the IStatusCodeHandler interface which Nancy provides.

The project I am using Nancy for is in its final stages so changing the middleware layer seems like a bigger task that there is time for but I'll definitely check out the OWIN based implementation before starting a new project.

**Comment by khellang** [comment]
@gbrown31 My point was that this seems to happen outside the Nancy pipeline. E.g. the Nancy pipeline hasn't even been initialized yet. It's might seem a bit ugly, but handling exceptions (for the host layer) is sometimes necessary. You'd have to do the same with any other host as well.

**Comment by khellang** [comment]
@gbrown31 Would #1695 help you?

**Comment by khellang** [comment]
Ah. Maybe not. This is for requests, not response :smile:
