### ISSUE TITLE
impossible to deploy on azure

### ISSUE THREAD

**Issue by floliver** [NancyFx/Nancy#1770]
Hello,

As the title say I tried a lot of way to deploy on azure and ... impossible.
On the local emulator of azure (sdk azure) it works but not on the real server.
Also, the azure is not talkative a lot ...
Did someone got some problems to deploy on azure too ?

Thanks in advance,
Flo

**Comment by floliver** [comment]
Hi ! Happy new year ! :) 
I did use custom errors off and still get a 500 : floliver.cloudapp.net.
I'm kinda lost because all the documenation seems so simple ... just click and run x)

**Comment by jonorossi** [comment]
@floliver I can see the Nancy favicon on that page so Nancy is configured correctly under IIS, unless you've manually put that favicon in the root directory. Your application is bombing out for some reason (e.g. cannot connect to database) so you'll need that error message.

If you were on Azure Web Sites I would have suggested to turn on Failed Request Tracing. I haven't turned on detailed errors remotely for years so cannot remember all the flags, you might also need `<httpErrors errorMode="Detailed" />` according to [this StackOverflow answer](http://stackoverflow.com/questions/5385714/deploying-website-500-internal-server-error/5385884#5385884).

**Comment by floliver** [comment]
Thanks i got an error !!!! Youhou ! :+1: 
Nancy.RequestExecutionException: Oh noes! ---> Nancy.ViewEngines.ViewNotFoundException: Unable to locate view 'index'
Currently available view engine extensions: sshtml,html,htm,cshtml,vbhtml
Locations inspected: views/Index/index-fr-FR,views/Index/index,Index/index-fr-FR,Index/index,views/index-fr-FR,views/index,index-fr-FR,index
Root path: F:\sitesroot\0\

**Comment by floliver** [comment]
Hi,
Youhou I got an error ! :D 
Nancy.RequestExecutionException: Oh noes! ---> Nancy.ViewEngines.ViewNotFoundException: Unable to locate view 'index'
Currently available view engine extensions: sshtml,html,htm,cshtml,vbhtml
Locations inspected: views/Index/index-fr-FR,views/Index/index,Index/index-fr-FR,Index/index,views/index-fr-FR,views/index,index-fr-FR,index
Root path: F:\sitesroot\0\

**Comment by xt0rted** [comment]
Try running the site locally in release mode. If you get the same error then the issue is probably in one of your view paths. Most likely one of them is prefixed with `../` or `/` which isn't supported but works in debug mode.

**Comment by khellang** [comment]
Any news on this? I'll close the issue, since we haven't heard anything in a while. Feel free to reopen :smile:

**Comment by floliver** [comment]
Did my best did not get the solution x). And i stopped trying ^^.

**Comment by horsdal** [comment]
Nancy lists the places it tried to look for the index view in the exception message. Did you check if the index view file is in one of those locations on the server?
