### ISSUE TITLE
Explicit support for HEAD requests

### ISSUE THREAD

**Issue by jbattermann** [NancyFx/Nancy#1771]
Even though #2 'reads' like it was added to Nancy a while back, there's, at least to my understanding, no explicit support for HEAD requests and what I am doing right now is checking/comparing the NancyContext for the request-type inside my Get["/"] etc handlers... which seems cumbersome.

While GET and HEAD are very closely related, I do have different implementations for the two: e.g. I only want to return the cache / ETAG value in a HEAD request and nothing else.. if I kept my GET implementation dumb it would always hit the underlying data "loading" mechanisms, be it cache or db.

So if I could define explicit Head ["/"] handlers it would remove a hell lot of if-conditions inside my Get handlers.

Is there a particular reason why this isn't available or is it.. and I am just not seeing it?

Cheers and thanks,
-J

**Comment by adamhathcock** [comment]
I would like this feature as well.  A pull request might be from me soon.
