### ISSUE TITLE
MaxJsonLength exceeded doesn't return http 500

### ISSUE THREAD

**Issue by andrew-m** [NancyFx/Nancy#1777]
When the MaxJsonLength limit is exceeded, instead of returning an http 500, the connection is reset. A minimal case using Owin hosting is at this gist. 

https://gist.github.com/andrew-m/1342e30851f302f97b5b

(you may need to nuget Microsoft.Owin.Host.HttpListener in addition to the packaged in the using statements).

We have seen similar behaviour using Nancy.Hosting.Self, except that instead of an http 500, we get an http 200 with an empty response.

In both cases you can't catch the exception in the module. However running in a debugged and turning on break-on-exceptions shows that it throws from Nancy.Owin.NancyMiddleware.cs at line 163 or in a class from System.Threading called Overlapped.cs.

We're using Nancy (and Nancy.Owin) version 0.23.2.

**Comment by andrew-m** [comment]
This doesn't really feel like the MaxJsonLength is the important detail, but that some types of exceptions don't get handled, which depending on the hosting model, either manifest as dropped connections (Microsoft.Owin) or empty responses with http 200 (Nancy.Hosting.Self).

**Comment by hulvei3** [comment]
I can confirm a similar behaviour using Nancy.Hosting.Self returning HTTP 200 even though a unhandled-exception was thrown. When catching in the selfhost set in `HostConfiguration` the stack-trace leads down to this:
```C#
...
   at Nancy.Responses.DefaultJsonSerializer.Serialize[TModel](String contentType, TModel model, Stream outputStream)
   at Nancy.Responses.JsonResponse`1.<>c__DisplayClass1.<GetJsonContents>b__0(Stream stream)
   at Nancy.Hosting.Self.NancyHost.OutputWithContentLength(Response nancyResponse, HttpListenerResponse response)
   at Nancy.Hosting.Self.NancyHost.ConvertNancyResponseToResponse(Response nancyResponse, HttpListenerResponse response)
   at Nancy.Hosting.Self.NancyHost.Process(HttpListenerContext ctx)
END OF STACKTRACE
```

**Comment by grumpydev** [comment]
This is because the exception doesn't throw until the body is materialised, which is after the main pipeline processing is finished - you can alter your JSON processor to wrap the response in a MaterialisingResponse, that should throw the error within the normal execution. This is potentially not very efficient though, so might be worth doing it just in debug mode.

**Comment by hulvei3** [comment]
I'm not very familiar with the internals of Nancy, but as @andrew-m states this issue isn't really about the JSON serialization but more about some exceptions not being handled, right?
But maybe this is a special case?

**Comment by hulvei3** [comment]
IMO I shouldn't have to override any default JSON processing to get any error that might occur.

**Comment by grumpydev** [comment]
Its due to the deferred execution of the body and how self host (or the OWIN host) works.. you can get the exception (see above), but the response has already gone to the client at this point so you can't *change* the response code.
