### ISSUE TITLE
Not possible to update default accept header in CoerceBlankAcceptHeader

### ISSUE THREAD

**Issue by dariusdamalakas** [NancyFx/Nancy#1779]
By default application/html is taken as default if accept headers are missing in requests. It would be good to be able to override this, and default to application/json or application/xml if needed.

https://github.com/NancyFx/Nancy/blob/82b5a38a7c06cbc764a1899427fd8019603324ac/src/Nancy/Conventions/BuiltInAcceptHeaderCoercions.cs#L15 is private member, if that could be public it would be easy to override this.

**Comment by grumpydev** [comment]
You can already customise the conventions, remove all the defaults, add your own, add some defaults and some of your own etc., you don't change the convention, just choose which ones you want - it's covered in the docs:

https://github.com/NancyFx/Nancy/wiki/Content-Negotiation
