### ISSUE TITLE
Unhandled exception in NancyHost.ConvertNancyResponseToResponse leaves hanging browser.

### ISSUE THREAD

**Issue by mistakenot** [NancyFx/Nancy#1780]
The context's Response isn't closed after an exception is thrown in ConvertNancyResponseToResponse(Response, HttpListenerResponse) in Nancy.Hosting.Self.NancyHost.cs. 

Error originally created by a handler that returned an invalid HTTP response code, which threw an exception here in said method just before the response is written:

``` c#
if (nancyResponse.ContentType != null)
{
     response.ContentType = nancyResponse.ContentType;
}
response.StatusCode = (int)nancyResponse.StatusCode;
```

I suspect the fix would be to add a finally block in NancyHost.Process(HttpListenerContext) to ensure context is closed to stop the browser hanging. Happy to have a go at a fix myself, but am completely new to this framework so thought it best to check here first that this is a problem and not something I'm doing wrong.

**Comment by hulvei3** [comment]
this might be a variant of the origin-error of #1777

**Comment by hulvei3** [comment]
I think the browser hanging only exist if `AllowChunkedEncoding = false` is set in the selfhost config
