### ISSUE TITLE
Is it possible to use Nancy with the ASP.NET 5.0 Core framework?

### ISSUE THREAD

**Issue by mmisztal1980** [NancyFx/Nancy#1781]
As title says - I've downloaded the MS VS 2015 Preview and decided to see if I can use Nancy with a ASP.NET vNext project. All is fine when I get rid of the "aspnet50core" framework, however it appears that I'm missing some dependencies when trying to use that framework.
 
Here's my project.json : 

```json
{
    "webroot": "wwwroot",
    "version": "1.0.0-*",
    "exclude": [
        "wwwroot"
    ],
    "configurations": {
        "Debug": {
            "compilationOptions": {
                "define": [ "DEBUG", "TRACE" ]
            }
        },
        "Release": {
            "compilationOptions": {
                "define": [ "RELEASE", "TRACE" ],
                "optimize": true
            }
        }
    },
    "packExclude": [
        "**.kproj",
        "**.user",
        "**.vspscc"
    ],
    "dependencies": {
        "Microsoft.AspNet.Server.IIS": "1.0.0-beta1",
        "Microsoft.AspNet.Owin": "1.0.0-beta1",
        "Nancy.Bootstrappers.Ninject": "0.23.2",
        "Ninject": "3.0.1.10",
        "Nancy.Hosting.Owin": "0.17.1",
        "Nancy.Owin": "0.23.2"
    },
    "frameworks": {
        "aspnet50": {

        },
        "aspnetcore50": {
            "dependencies": {
                "Microsoft.AspNet.Server.IIS": "1.0.0-beta1",
                "Microsoft.AspNet.Owin": "1.0.0-beta1",
                "Nancy.Bootstrappers.Ninject": "0.23.2",
                "Ninject": "3.0.1.10",
                "Nancy.Hosting.Owin": "0.17.1",
                "Nancy.Owin": "0.23.2"
            }
        }
    }
}
```

This gives me ~23 compilation errors regarding missing "using" directives or assembly references.
Is it possible to use Nancy with this framework at all? 

Best regards

**Comment by xt0rted** [comment]
The `Nancy.Hosting.Owin` package is obsolete now, what happens when you remove that?

**Comment by mmisztal1980** [comment]
Removing that package from aspnetcore50 framework has no effect. I'm still having the same errors.

**Comment by grumpydev** [comment]
I doubt you can use it targetting Core as that's very cut down (pretty much if it's not a PCL it aint going to work) - you can target the full version though.

**Comment by mmisztal1980** [comment]
Correct me if I'm wrong, but MS is intending to use that framework to target OSX/Linux environments - correct? Is Nancy intended to work in those environments, using this framework, in the future?

**Comment by grumpydev** [comment]
Nancy already works on OSX/Linux environments with Mono - we will, at some point, look at a .net core version, but it doesn't actually give us anything we haven't already got.

**Comment by mmisztal1980** [comment]
So - currently, if I want to deploy something on Mono, should I stick with the ASP.NET 5.0 or an earlier version?

**Comment by grumpydev** [comment]
Stick with .net 4.5 - there's no compelling reason to use the new ASP.Net bits yet imo (outside of mucking around with it), and plenty of reasons not to :)
