### ISSUE TITLE
Nuget packages get out of date

### ISSUE THREAD

**Issue by beachwalker** [NancyFx/Nancy#1786]
Hi,

it seems the Nuget packages get out of date and some features (e.g. access
to public static IList<JavaScriptPrimitiveConverter> PrimitiveConverters { get; set; }) is not in the official package.

Would be nice if the release cycle is closer to the latest developent (beta packages?) or at least a more  up to date release will be pushed to nuget.org.

**Comment by khellang** [comment]
What does "the Nuget packages get out of date" mean? Out of date compared to what? The master branch?

**Comment by beachwalker** [comment]
You said it is from Nov 5, 2013. Indeed. But was removed and added again!

For example:
Look at this versions of JsonSettings

![image](https://cloud.githubusercontent.com/assets/2715897/5872504/95581758-a2ec-11e4-9e73-847bb0eca059.png)

https://github.com/NancyFx/Nancy/blob/824d37b8d41993b12183793127f6c0a836ea698e/src/Nancy/Json/JsonSettings.cs

The change on 7 Feb 2014 "Fix XML docs typo" does not contain the public static IList<JavaScriptPrimitiveConverter> PrimitiveConverters { get; set; } Property.

It was added again on 8 Jul 2014 "Merge remote-tracking branch 'upstream/master'"

https://github.com/NancyFx/Nancy/blob/0cfef8afc1b80804f8b527f34c6d9556c65d2276/src/Nancy/Json/JsonSettings.cs

It is declared on the nuget website, that the package is created on Friday, July 18 2014 but it really seems that the package is made upon a version prior to 7 Feb 2014 or from another repository (branch/clone). Maybe there is omething wrong with the build automation/ci?


I tried to do the following which is possible with the current master (cloned from github to local dir and build myself), but is not possible with the current package because the class because the "JavaScriptPrimitiveConverter" is missing in the package as I already said:

    public class IdConverter : JavaScriptPrimitiveConverter
    {
        public override IEnumerable<Type> SupportedTypes
        {
            get
            {
                yield return typeof(Id);
            }
        }

        public override object Serialize(object obj, JavaScriptSerializer serializer)
        {
            var id = obj as Id;
            if (id != null)
            {
                return id.ToString();
            }

            return null;
        }
        
        public override object Deserialize(object primitiveValue, Type type, JavaScriptSerializer serializer)
        {
            if (type == typeof(Id) && primitiveValue is string)
            {
                return new Id(primitiveValue as string);
            }

            return null;
        }
    }

![image](https://cloud.githubusercontent.com/assets/2715897/5872320/6cbd6642-a2ea-11e4-8de4-fa3208721a1f.png)

Also the PrimitveConverters List is not available when using the last package from nuget:

![image](https://cloud.githubusercontent.com/assets/2715897/5872390/4ae9a71e-a2eb-11e4-9d6f-848e259d31ec.png)

The used Nancy package version is 0.23.2.0 which is also the latest at nuget.org:

![image](https://cloud.githubusercontent.com/assets/2715897/5872421/ac312dda-a2eb-11e4-9462-4c2687137810.png)

**Comment by beachwalker** [comment]
... "out of date" compared to the master branch

**Comment by khellang** [comment]
Riiight. I see what's going on here. The PR (#1310) wasn't merged until Aug 9, 2014, and the last NuGet release was Jul 18, 2014 (how embarrassing :confounded:). Luckily for you, we're looking at doing a release Very Soon™ :smile:
