### ISSUE TITLE
Nancy 1.0.0 & Windsor Bootstrap Error

### ISSUE THREAD

**Issue by acgentry** [NancyFx/Nancy#1792]
After upgrading to 1.0.0, Nancy is failing to bootstrap when using Windsor, getting the following errors:

Can't create component 'Nancy.ViewEngines.ViewEngineApplicationStartup' as it has dependencies to be satisfied.

'Nancy.ViewEngines.ViewEngineApplicationStartup' is waiting for the following dependencies:
- Service 'System.Collections.Generic.IEnumerable`1[[Nancy.ViewEngines.IViewEngine, Nancy, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' which was not registered.
- Service 'Nancy.ViewEngines.DefaultViewLocator' which was registered but is also waiting for dependencies.
'Nancy.ViewEngines.DefaultViewLocator' is waiting for the following dependencies:
- Service 'System.Collections.Generic.IEnumerable`1[[Nancy.ViewEngines.IViewEngine, Nancy, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' which was not registered.

**Comment by maciasello** [comment]
With Nancy.Bootstrappers.Windsor v. 1.0.0 the container configuration code (which includes registering `CollectionResolver` as container's sub-resolver) has been moved from `GetApplicationContainer` to `ConfigureApplicationContainer` on `WindsorNancyBootstrapper`.

Please make sure that your override of `ConfigureApplicationContainer` invokes base implementation (in my case it didn't). Earlier it was not overridden in `WindsorNancyBootstrapper` and thus not invoking it did not make harm. Now it is necesary.

**Comment by khellang** [comment]
Yes, @acgentry, as you can see, the `ConfigureApplicationContainer` method on the bootstrapper does [quite a bit of work](https://github.com/NancyFx/Nancy.Bootstrappers.Windsor/blob/c484d12ea728a269a122c373d19cf763cbaa2b11/src/Nancy.BootStrappers.Windsor/WindsorNancyBootstrapper.cs#L78-L97). Please try to call the `base` method and see if that solves your problem :smile:

**Comment by acgentry** [comment]
Thanks @maciasello & @khellang

**Comment by abelevtsov** [comment]
Thanks you a lot @maciasello and @acgentry
