### ISSUE TITLE
Does Nancy support custom request headers?

### ISSUE THREAD

**Issue by donnyv** [NancyFx/Nancy#1794]
I need to add a custom header but it looks like its read only. Is there somewhere else in the framework to do this?

    ctx.Request.Headers = new RequestHeaders(new_headers);

**Comment by albertjan** [comment]
Why do you want to change the headers sent by the client?

**Comment by donnyv** [comment]
I want to inject a custom header that tells the backend servers what app instance to use.

**Comment by albertjan** [comment]
And they accept NancyRequestHeaders? I'd say the `ctx.Items` hash is more suited for that purpose

**Comment by donnyv** [comment]
I'm using HAProxy acl rules to filter the header out.

**Comment by donnyv** [comment]
That doesn't seem to do anything.

**Comment by thecodejunkie** [comment]
Why, exactly, do you want this to be an actual header when it does not originate from the actual client itself? What are you trying to accomplish?

**Comment by donnyv** [comment]
I ended solving my problem with a cookie instead. Thanks
