### ISSUE TITLE
NancyFX on Mono/Linux and possible compatibility issues

### ISSUE THREAD

**Issue by Kibele** [NancyFx/Nancy#1799]
Hi,

I'm a newbie in C# first of all. I work for a company with two colleagues, C# coders. We are on a project of writing our own web-based Customer Relationship Management system. We have decided to use NancyFX framework.

My development environment is MonoDevelop on Ubuntu 14.04. I am learning C# coding with NancyFX as a starter point.

So,

after cloning the Nancy repository and opening the project in MonoDevelop on Ubuntu, "git status" reports that:

"modified:   src/packages/repositories.config"

It simply adds lines such that:

<repository path="../Nancy.Authentication.Basic.Tests/packages.config" />

which means slash marks are used appropriate for linux environment. MonoDevelop/Linux does not recognize defined repository paths, I think.

If you are interested in OS compatibilities, I want to report compatibility issues here and work in sync with Nancy repository.

Sincerely...

**Comment by albertjan** [comment]
You shouldn't clone this repository, if you want to use Nancy. You should read up about [nuget](http://nuget.org). It lets you install nancy without building it yourself.

**Comment by Kibele** [comment]
Thanks. Nuget is great for production. On the other hand, building from source code is very educational and guiding for me thanks to open source and community.

**Comment by thecodejunkie** [comment]
Building Nancy on Mono 2.x and 3.x works fine. We do that on every single commit to the master branch, through Travis https://travis-ci.org/NancyFx/Nancy/
