### ISSUE TITLE
Claims support

### ISSUE THREAD

**Issue by grumpydev** [NancyFx/Nancy#1800]
# Replacing current "user" objects with ClaimsPrincipal/ClaimsIdentity

## Mandatory:

- [x] Remove IUserIdentity
- [x] Replace UserIdentityExtensions with a version that has the same (as much as possible - will need to be updated for the new, correct, structure of a claim) API but uses ClaimsPrincipal
- [x] Update SecurityHooks to use the new extensions and claim structure
- [x] Update ModuleSecurity to use the new extensions and claim structure
- [x] Update NancyContext to use ClaimsIdentiy/Principal
- [x] Allow the principal to "flow" from hosting
- [x] Update OWIN to automatically flow the identity
- [x] Update tests

## Preferred:

- [x] Update Forms Auth to use the new extensions and claim structure
- [x] Update Stateless Auth to use the new extensions and claim structure
- [x] Remove Token Auth :fire:
- [x] Update Basic Auth to use the new extensions and claim structure

## 4.0 Support (up for debate):

- [ ] Create a new project Nancy.Security containing a "copy" of ClaimsPrincipal/ClaimsIdentity (nabbed from Mono?), possibly renamed to NancyClaimsPrincipal/NancyClaimsIdentity
- [ ] Reference that new project in Nancy, and the auth projects, and use that new type everywhere, rather than the .net 4.5 one (see Mandatory above)
- [ ] For .net 4.5 add a conditional compilation that adds implicit casting between NancyClaimsPrincipal/NancyClaimsIdentity and the .net 4.5 versions
- [ ] Update core build script to build both versions 
- [ ] Include the new assemblies in the core Nancy nuget for the relevant platforms

The working branch for this issue can be found at https://github.com/nancyfx/nancy/tree/v2

**Comment by damianh** [comment]
Mandatory + Preferred :+1:

4.0 Support  :-1:

**Comment by damianh** [comment]
What about our hosts? should we just suggest owin hosts? delete the WCF one?

**Comment by grumpydev** [comment]
I guess OWIN and probably asp.net we should update, self host would make no sense to update I don't think, and WCF can just stay as is - flowing the principal would obviously be optional.

**Comment by felipeleusin** [comment]
Do you guys need help with this? Would love to contribute to nancy and I'm kinda tired of using Nancy.MSOwinSecurity. Also -1 on 4.0 support

**Comment by damianh** [comment]
@felipeleusin You'll still need Nancy.MSOwinSecurity to interact with IAuthenticationManager. But yes, hopfully with this, I can get rid of some extension methods.

**Comment by felipeleusin** [comment]
Yeah, you are correct. I was thinking of interfacing between ClaimsPrincipal and IUserIdentity.

**Comment by damianh** [comment]
Fixed via #1820
