### ISSUE TITLE
NancyWcfGenericService - no extension method `CreateStreamResponse' of type `System.ServiceModel.Web.WebOperationContext' 

### ISSUE THREAD

**Issue by Kibele** [NancyFx/Nancy#1801]
Hi,

I'm on Ubuntu 14.04. Mono 3.12.0 (64-bit) is installed and I'm building on MonoDevelop 5.7. I get this error:

nancy.git/src/Nancy.Hosting.Wcf/NancyWcfGenericService.cs(31,31): Error CS1061: Type `System.ServiceModel.Web.WebOperationContext' does not contain a definition for `CreateStreamResponse' and no extension method `CreateStreamResponse' of type `System.ServiceModel.Web.WebOperationContext' could be found. Are you missing an assembly reference? (CS1061) (Nancy.Hosting.Wcf)

**Comment by thecodejunkie** [comment]
WCF is not implemented on Mono, If you have set MonoDevelop to use the correct build targets for mono (MonoDebug/MonoRelease) then it will not compile the Nancy WCF projects
