### ISSUE TITLE
Nancy.Testing With.Dependency<T>(T instance) is disposing of the instance provided

### ISSUE THREAD

**Issue by PureKrome** [NancyFx/Nancy#1802]
Unit testing code with `Nancy.Testing`.
When I provide an instance of an object using `With.Testing<T>(T instance)` I believe the object is disposed of.

I [made this full repo](https://gist.github.com/PureKrome/ba3a519d807e5103243c) to proove this.

Sample code which hightlights the problem :+1: 

```C#
var browser = new Nancy.Testing.Browser(with =>
            {
                with.Module<SampleModule>();
                with.Dependency<IDocumentStore>(documentStore); // THROWS EXCEPTION
                //with.Dependency(documentStore); // WORKS
            });
```

**Comment by felipeleusin** [comment]
:+1: also have been experiencing this... if I register an instance with TinyIoC the instance gets disposed (also IDocumentStore)

**Comment by horsdal** [comment]
I reproduced this and it seems to be an issue in `ConfigurableBootstrapper`. I'll do the PR in the next couple of days.

**Comment by PureKrome** [comment]
![woot](https://31.media.tumblr.com/43e63461d1e3f22a49b18dbf15227a1d/tumblr_inline_n3t10oQfIh1solpjm.gif)

ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou-ThankYou

**Comment by horsdal** [comment]
:laughing: :heart:

**Comment by thecodejunkie** [comment]
Dafaq is this? @horsdal did you use waffle.io to move this issue along?

![image](https://cloud.githubusercontent.com/assets/50543/6606958/ab876b7c-c83b-11e4-9413-9995b77e74cf.png)

It's saying that I assigned you and that I added the "in progress" label with is bollocks :) I did sign up to waffle.io, with my personal Github account, earlier today. If you did it, then it seems it's have major problems with multiple people pointing towards the same shared repo. Either way, waffle.io adds these shitty labels and I'd like to avoid those (=== leaky app)

**Comment by horsdal** [comment]
Don't know where those came. But they showed up immediately after I opened the PR. 
Never touched waffle.io.

**Comment by khellang** [comment]
Removed the `in progress` label altogether. @thecodejunkie maybe you should unlink Nancy from waffle.io?

**Comment by PureKrome** [comment]
@khellang closed == fixed? If yes, can a milestone tag be added please (so i know what version to check this against).

**Comment by khellang** [comment]
@PureKrome Yes, as GitHub says, it was closed from #1862 (which has milestone info).

**Comment by khellang** [comment]
@PureKrome You can test it out right away by pulling from the CI feed :smile:

**Comment by PureKrome** [comment]
AH! i missed the commit info .. and clicking on that gives all the info. ta!

(and dude. dude.   DUDE... thanks -heaps- for looking into the issue. I _really_ mean it).

/me hugs.
