### ISSUE TITLE
StaticContentConventionBuilder.AddDirectory broken in 1.0.0?

### ISSUE THREAD

**Issue by ThomasWeiss** [NancyFx/Nancy#1811]
Steps to reproduce:
* Added a file `image.jpg` to an `assets` folder in my project, set to `CopyAlways` -> copied to `Debug/assets/image.jpg` on build
* Added the following in my bootstrapper:
```
protected override void ConfigureConventions(Nancy.Conventions.NancyConventions nancyConventions)
{
	base.ConfigureConventions(nancyConventions);
	nancyConventions.StaticContentsConventions.Add(Nancy.Conventions.StaticContentConventionBuilder.AddDirectory("test", "assets"));
}
```
* Ran the project in self-hosting on port 8080
* Browsed to `http://localhost:8080/test/image.jpg`
* Neither Chrome or IE can display the result (connection reset IIRC)
* Switched back to 0.23.2
* Works like a charm! :)

**Comment by khellang** [comment]
I looked at the history of the `StaticContentConventionBuilder`, and it seems unchanged recently. Could the bug be somewhere else?

**Comment by horsdal** [comment]
Sounds like #1789 which seems to have to do with the self host.

**Comment by ThomasWeiss** [comment]
Nice catch, that's it!
