### ISSUE TITLE
Problem using CORS?

### ISSUE THREAD

**Issue by fagnercarvalho** [NancyFx/Nancy#1816]
Its seems that I having a inconsistency when using CORS during a post request.

Wherever I try to activate CORS using this code inside a extension method it simply won't work:

``` csharp
module.After.AddItemToEndOfPipeline((x => x.Response
                .WithHeaders("Access-Control-Allow-Origin", "*")
                .WithHeaders("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept")));
```
However, if I use this in ApplicationStartup method from the Bootstraper class it works:
``` csharp
pipelines.AfterRequest += (ctx) =>
{
    ctx.Response.Headers.Add("Access-Control-Allow-Origin", "*");
    ctx.Response.Headers.Add("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
};
```

Why this is happening? Is there something I'm doing wrong?

**Comment by horsdal** [comment]
Strange. Do you have a full repro?

**Comment by fagnercarvalho** [comment]
Hello @horsdal! I'm sorry for the delay.
It seems that I cant reproduce this issue anymore. If, for some reason, I come across this problem again I open a new issue here, but for now CORS is working.

Thank you!

**Comment by horsdal** [comment]
:+1:
