### ISSUE TITLE
Route with a greedy segment in OWIN host not matching with dots in last part of segment

### ISSUE THREAD

**Issue by bendetat** [NancyFx/Nancy#1829]
I'm using 1.1.0 of both Nancy and Nancy.Owin.

If I have a route with a greedy segment:

    Get["/echo/{slug*}"] = _ => _.slug;

Then:

- `/echo/foo` returns `foo` :+1: 
- `/echo/foo/bar` returns `foo/bar` :+1: 
- `echo/foo.bar/gaz` returns `foo.bar/gaz :+1:
- `echo/foo.bar` doesn't match the route (404) :-1:

Obviously this is something around Nancy assuming something with a dot at the end of the route is a file. This is inconsistent though because using `Nancy.Testing` to try to replicate this passes on the `/echo/foo.bar` case:

    var module = new ConfigurableNancyModule(with => with.Get("/echo/{slug*}", (o, nancyModule) => o.slug));
    var browser = new Browser(with => with.Module(module));

    Assert.Equal(browser.Get("/echo/foo").Body.AsString(), "foo");
    Assert.Equal(browser.Get("/echo/foo/bar").Body.AsString(), "foo/bar");
    Assert.Equal(browser.Get("/echo/foo.bar/gaz").Body.AsString(), "foo.bar/gaz");
    Assert.Equal(browser.Get("/echo/foo.bar").Body.AsString(), "foo.bar");

(i.e. all of the assertions pass)

**Comment by olegKoshmeliuk** [comment]
After Adding in Startup.cs
```
app.UseStageMarker(PipelineStage.MapHandler);
```
and in web.config
```
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true" />
</system.webServer>
```
Without this additional configuration, the StaticFileModule from OWIN would intercept the request and return a 404.
(from https://github.com/NancyFx/Nancy/wiki/Managing-static-content#extra-steps-required-when-using-microsoftowinhostsystemweb)

**Comment by damianh** [comment]
Tested this with the `Microsoft.Owin.Host.HttpListener` with actual HTTP requests.

```
namespace ConsoleApplication2
{
    using System;
    using System.Net.Http;
    using System.Threading.Tasks;
    using Microsoft.Owin.Hosting;
    using Nancy;
    using Owin;
    using Xunit;

    public class Foo
    {
        [Theory]
        [InlineData("/echo/foo")]
        [InlineData("/echo/foo/bar")]
        [InlineData("/echo/foo.bar/gaz")]
        [InlineData("/echo/foo.bar")]
        public async Task Bar(string requestUri)
        {
            Action<IAppBuilder> builder = app =>
            {
                app.UseNancy();
            };
            using (WebApp.Start("http://localhost:1080", builder))
            {
                using (var client = new HttpClient { BaseAddress =  new Uri("http://localhost:1080") })
                {
                    var response = await client.GetAsync(requestUri);
                    Assert.Equal(System.Net.HttpStatusCode.OK, response.StatusCode);
                }
            }
        }
    }

    public class SampleModule : NancyModule
    {
        public SampleModule()
        {
            Get["/echo/{slug*}"] = _ => _.slug;
        }
    }
}
```

All test passed

![image](https://cloud.githubusercontent.com/assets/57436/10084772/8406f620-6305-11e5-9492-47cd8c9668d7.png)

I strongly suspect the problem is with IIS and/or the SystemWeb dealing with the request because it thinks its a file. If you must use IIS, try this host: https://www.nuget.org/packages/Microsoft.Owin.Host.IIS
