### ISSUE TITLE
Automatic conditional request / ETag support

### ISSUE THREAD

**Issue by grumpydev** [NancyFx/Nancy#183]

**Comment by thecodejunkie** [comment]
Handled in #547

**Comment by albertjan** [comment]
But #547 was never merged. :smile:

**Comment by thecodejunkie** [comment]
Oh you are right.. a quick glance made me think it was :P

**Comment by thecodejunkie** [comment]
Closed due to death by old age. If anyone cares to take a stab at this, please feel free :heart:
