### ISSUE TITLE
Nancy.Testing.BrowserResponseBodyWrapper does not support gzipped responses

### ISSUE THREAD

**Issue by rasmus-beck** [NancyFx/Nancy#1837]
I was trying to write a test for my REST API tonight, that tested a gzipped response. But using the Nancy test framework isn't possible, as the `BrowserResponseBodyWrapper` sees the response stream as being closed.

This is not a very detailed issue description, but I will write a failing test for this sometime in the next couple of days.

**Comment by horsdal** [comment]
@rasmus-beck did you get around to that failing test?

**Comment by rasmus-beck** [comment]
Sorry got sidetracked. We decided to let the load balancer do the GZipping, and I lost all focus on this. Will see if I can get around to this soon.

**Comment by horsdal** [comment]
:cool:

**Comment by yannisgu** [comment]
Heres a test for reproduction: https://github.com/NancyFx/Nancy/compare/master...yannisgu:issue1837
Didn't find a solution yet...

**Comment by rasmus-beck** [comment]
@yannisgu Thanks!

**Comment by xt0rted** [comment]
When creating the `GZipStream` ([DeflateStream](https://msdn.microsoft.com/en-us/library/system.io.compression.deflatestream(v=vs.110).aspx) as well) you need to pass`true` as the [third parameter](https://msdn.microsoft.com/en-us/library/27ck2z1y(v=vs.110).aspx#parameters). The remarks section has more information as to why.

Here's a passing version of the above test.
```c#
[Fact]
public void Should_support_gzipped_response()
{
    // Given
    bootstrapper.AfterRequest.AddItemToEndOfPipeline(ctx =>
    {
        ctx.Response.Headers["Content-Encoding"] = "gzip";
        var contents = ctx.Response.Contents;
        ctx.Response.Contents = responseStream =>
        {
            using (var gzip = new GZipStream(responseStream, CompressionMode.Compress, leaveOpen: true))
            {
                contents.Invoke(gzip);
            }
        };
    });

    // When
    var result = browser.Get("/");

    // Then
    using (var responseStream = new MemoryStream(result.Body.ToArray()))
    using (var zipStream = new GZipStream(responseStream, CompressionMode.Decompress))
    using (var zipStreamReader = new StreamReader(zipStream))
    {
        zipStreamReader.ReadToEnd().ShouldEqual("Hello World");
    }
}
```

**Comment by thecodejunkie** [comment]
Related to #2011 

https://github.com/NancyFx/Nancy/pull/2011#issuecomment-132979264
