### ISSUE TITLE
Why is the single quote escaping wrapped in NET_4_0 ?

### ISSUE THREAD

**Issue by eoftedal** [NancyFx/Nancy#1838]
Why is escaping of single quotes wrapped in #if NET_4_0 ?

https://github.com/NancyFx/Nancy/blob/82b5a38a7c06cbc764a1899427fd8019603324ac/src/Nancy/Helpers/HttpEncoder.cs#L375-L379

HTML-encoders really should escape single quotes as well, as single quote is often used to mark beginning and end of attributes in HTML

**Comment by grumpydev** [comment]
It's taken from Mono, so I imagine it's a "bug for bug compatibility" thing.

**Comment by khellang** [comment]
Is this an *HTML*-encoder? Anyway, this is probably an issue for the Mono project. BTW, maybe it's time for us to do a "re-import" of this class? The `NET_4_0` ifdefs was [recently removed](https://github.com/mono/mono/commit/032f313d5f3b99954cabb3e152b3c8d4424d5a2b)

**Comment by grumpydev** [comment]
@khellang : it should be going when we do 2.0 anyway
