### ISSUE TITLE
Using an assembly reference to improve accuracy of assembly loading

### ISSUE THREAD

**Issue by thecodejunkie** [NancyFx/Nancy#1842]
During assembly scanning, we try to work a bit of magic by scanning for unloaded assemblies that reference as Nancy assembly. However, as we know, .NET is sometimes trying to be smart and clear referenced assemblies, where a type is not directly referenced in code. This results in Nancy not loading the assembly thus some types will not be loaded and be discovered by Nancy at runtime. There is little we can do about this behavior (unless, explicitly force people to add a type reference somewhere in their code).

One possible workaround could be to look for an attribute (guessing that they'll not be cleaned up)

```c#
[AttributeUsage(AttributeTargets.Assembly)]
public class NancyReferenceAttribute : Attribute
{
}
```

It could then be slapped on an assembly

`[assembly: NancyReference]`

We could then update ADATS to look for the attribute first and if it's not present, then we will try and look for a Nancy reference. Come to think of it, the attribute usage should be considered a directer type usage so it's mimicking referencing a Nancy type, in a less convoluted approach. We shouldn't need to update ADATS, the attribute would just provide (in my opinion) a cleaner approach to the solution we tell people to use.

Thoughts?

**Comment by khellang** [comment]
So we'll use this to force a reference to Nancy.dll (including compile-time type usage)?

**Comment by grumpydev** [comment]
There's no need to update ADATS I don't think.. as soon as you add that assembly attribute it will create a hard reference and load it using the normal Nancy reference logic.

Feels a bit icky, but every solution feels icky, and at least this feels more logical - although I'd probably call it EnableNancyAssemblyScanning or something.

**Comment by thecodejunkie** [comment]
I think this falls under the "less icky, more logical" when it comes to solutions to this. It always rubbed me the wrong way to have to suggest to people to put

```c#
var foo = typeof(SomeNancyType);
```

In their code :)

Not too sure about the name. `NancyReference` was never intended to be the final name, and even though `EnableNancyAssemblyScanning` feels more right, it still feels a bit off. Unless we can think of a better name, then I am happy to go with `EnableNancyAssemblyScanning`.

This will also require us to document it a bit more on the wiki

**Comment by horsdal** [comment]
How about a name that's "the way around" like `IncludeInNancyAssemblyScanning`?

**Comment by khellang** [comment]
:+1: I vote for `IncludeInNancyAssemblyScanning`

**Comment by grumpydev** [comment]
IncludeInNancyAssemblyScanningPlease

**Comment by khellang** [comment]
LOL :grin: Reminded me of MvvmCross' [LinkerPleaseInclude class](https://github.com/MvvmCross/NPlus1DaysOfMvvmCross/blob/master/N-25-Tabbed/Tabbed.Droid/LinkerPleaseInclude.cs) :stuck_out_tongue_closed_eyes:
