### ISSUE TITLE
File upload Headers read bug

### ISSUE THREAD

**Issue by SonicChen** [NancyFx/Nancy#1850]
When I upload file with Chinese name. I found it's not possible to get the correct uploaded file name in Nancy.
After browsing the reflected codes. I found HttpMultipartBoundary.ExtractHeaders() read Headers from Stream with each byte directly instead with charset.

**Comment by khellang** [comment]
There might be some funky stuff going on when reading bytes from the stream and converting it to a string without encoding, but without some real test data/cases it's hard to reproduce. @SonicChen Would it be possible for you or @WesolyPierozek to write a test case or come up with some test data for this, so we could make sure we get a correct fix in?

**Comment by WesolyPierozek** [comment]
My request is:
```
------FormBoundary_8D2248CC12FAE48
Content-Disposition: form-data;name="file_content"; filename="Данные.txt"
Content-Type: application/octet-stream

some data values
------FormBoundary_8D2248CC12FAE48--
```

Filename is injected to request by:
```
byte[] fileHeaderBytes = Encoding.UTF8.GetBytes(string.Format(FileDataTemplate, fileFieldName, HttpUtility.UrlEncode(fileName), fileContentType, fileName));
requestStream.Write(fileHeaderBytes, 0, fileHeaderBytes.Length);
```
So I assume that binary content of request is in utf-8.

Received file name is ```ÐÐ°Ð½Ð½ÑÐµ.txt```

**Comment by khellang** [comment]
Alright. I have a failing test for this:

> Test Name:	Nancy.Tests.Unit.HttpMultipartBoundaryFixture.Should_handle_non_ASCII_filenames
> Test FullName:	Nancy.Tests.Unit.HttpMultipartBoundaryFixture.Should_handle_non_ASCII_filenames
> Test Source:	c:\Users\Kristian\Code\Nancy\src\Nancy.Tests\Unit\HttpMultipartBoundaryFixture.cs : line 30
> Test Outcome:	Failed
> Test Duration:	0:00:00,086
> 
> Result Message:
> Assert.Equal() Failure
> Position: First difference is at position 0
> Expected: Данные.txt
> Actual:   ÐÐ°Ð½Ð½ÑÐµ.txt
> Result StackTrace:
at Nancy.Tests.ShouldAssertExtensions.ShouldEqual(Object actual, Object expected) in c:\Users\Kristian\Code\Nancy\src\Nancy.Tests\ShouldExtensions.cs:line 108
   at Nancy.Tests.Unit.HttpMultipartBoundaryFixture.Should_handle_non_ASCII_filenames() in c:\Users\Kristian\Code\Nancy\src\Nancy.Tests\Unit\HttpMultipartBoundaryFixture.cs:line 43

Let me see if I can fix the reading :smile:

**Comment by khellang** [comment]
@WesolyPierozek @SonicChen Could you try to install the v1.2-Pre1491 from https://www.myget.org/gallery/nancyfx and check if it fixes the issue?

**Comment by WesolyPierozek** [comment]
I tested it and it seems to give correct results.
Thanks for fast feedback ;-) .

By the way last time i checked specification for supporting utf-8 names, and i noticed there is standard which supports Content-Disposition parameter called filename*=UTF-8''[filename] but lot of libraries and web browser don't support it.
Here you can found more details http://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http but it is another story. My problem was solved. Thanks a lot and I'm waiting for official release.

**Comment by khellang** [comment]
@WesolyPierozek Thanks for following up! :+1: Glad it fixed it for you :grin:
