### ISSUE TITLE
UTF-8 encoded filename

### ISSUE THREAD

**Issue by WesolyPierozek** [NancyFx/Nancy#1851]
I have issue with encoding of filename during sending data via form. I have built request by manual inserting data to the stream. Problem is when cyrylic named file is attached. 

Part is:
```
FileDataTemplate 
= "Content-Disposition: form-data;name=\"{0}\"; filename=\"{3}\"\r\nContent-Type: {2}\r\n\r\n";
```

Issue may be related to #1850.
Problem is that returned HttpFile.Name has strange letters.
I'm using selfhosting with NancyModule.

**Comment by khellang** [comment]
If it's related to #1850, why not close this and take the discussion over there? :smile:
