### ISSUE TITLE
Async Request returns 500 internal server error...

### ISSUE THREAD

**Issue by Healian** [NancyFx/Nancy#1858]
i am trying to use nancy to handle ajax calls from javascript where i created an asynchronous request handler like so

            Post["/game_login.html", true] = async (o, x) => {
                var username = Request.Form.Username;
                var password = Request.Form.Password;
                var world = Request.Form.World;
                var domain = Request.Form.Domain;
                var proxyUsername = Request.Form.ProxyUsername;
                var proxyPassword = Request.Form.ProxyPassword;
                var proxyServer = Request.Form.ProxyServer;
                var token = (username + password + domain + world).GetMd5Hash();

                var robot = new Robot {
                    Owner = new RobotOwner {
                        Token = token
                    }
                };
                
                if (await robot.Initialize(username, password, new Realm(world, domain), new Proxy {
                    Username = proxyUsername,
                    Password = proxyPassword,
                    Server = proxyServer
                })) {
                    Robots.Add(robot);
                    return (Response)token;
                }

                return (Response)"";
            };

however when the user calls it it returns 500 internal server error immediately any help?

**Comment by Healian** [comment]
well it turned out to be a problem of my code... but how could i intercept such internal server errors ?

**Comment by hlesesne** [comment]
I believe this would be a good candidate for the OnError pipeline:

https://github.com/NancyFx/Nancy/wiki/The-Application-Before,-After-and-OnError-pipelines
