### ISSUE TITLE
Nancy.Templates.vsix is outdated (only install the old version Nancy 0.21.1)

### ISSUE THREAD

**Issue by dns** [NancyFx/Nancy#1859]
The Intro page https://github.com/NancyFx/Nancy/wiki/Introduction is outdated.

Step 1. Install the Nancy project templates. http://visualstudiogallery.msdn.microsoft.com/f1e29f61-4dff-4b1e-a14b-6bd0d307611a  link to old version of Nancy.Templates.vsix 

By default all templates will not work on VS2012, unless the user upgrade the nancy by issuing this command:

PM> Install-Package Nancy
Successfully installed 'Nancy 1.1'.
Successfully removed 'Nancy 0.21.1' from Nancy.DemoApplication1.
Successfully added 'Nancy 1.1' to Nancy.DemoApplication1.
Successfully uninstalled 'Nancy 0.21.1'.

PM> Install-Package Nancy.Hosting.Aspnet
Attempting to resolve dependency 'Nancy (≥ 1.1)'.
Successfully installed 'Nancy.Hosting.Aspnet 1.1'.
Successfully removed 'Nancy.Hosting.Aspnet 0.21.1' from Nancy.DemoApplication1.
Successfully added 'Nancy.Hosting.Aspnet 1.1' to Nancy.DemoApplication1.
Successfully uninstalled 'Nancy.Hosting.Aspnet 0.21.1'.

**Comment by 06b** [comment]
I wonder if it's worth including alternative instructions of using SideWaffle for Visual Studio users, however it looks like SideWaffle is still on 0.22. But it should work for VS2012 users.
