### ISSUE TITLE
Having multiple route parameters with constraints is not supported

### ISSUE THREAD

**Issue by danielmarbach** [NancyFx/Nancy#1863]
Currently when you have modules which multiple parameters with constraints the constraints get never invoked. The following test including the module reproduces it.

	public class RouteConstraintsTests
    {
        private readonly INancyBootstrapper bootstrapper;

        private readonly Browser browser;

		public static bool Invoked { get; set; }

        public RouteConstraintsTests()
        {
			Invoked = false;

            this.bootstrapper = new ConfigurableBootstrapper(
                configuration =>
                {
                    configuration.ApplicationStartup((c,p) => { });
                    configuration.Modules(new Type[] { typeof(RouteConstraintsModule)});
                    configuration.RouteSegmentConstraints(new[] {typeof (VersionRouteConstraint)});
                });

            this.browser = new Browser(this.bootstrapper);
        }

        [Fact]
        public void Should_be_supported()
        {
            var response = browser.Get(
                @"/4.2...5.3",
                with =>
                {
                    with.HttpRequest();
                });

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
			Assert.True(Invoked);
        }

        public class VersionRouteConstraint : RouteSegmentConstraintBase<Version> {
            public override string Name
            {
                get { return "version"; }
            }

            protected override bool TryMatch(string constraint, string segment, out Version matchedValue)
            {
				Invoked = true;
                return Version.TryParse(segment, out matchedValue);
            }
        }
    }

 	public class RouteConstraintsModule : NancyModule
    {
        public RouteConstraintsModule()
        {
            this.Get["/{left:version}...{right:version}"] = _ =>
            {
                return 200;
            };
        }
    }

The problem is that the [TrieNodeFactory](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Routing/Trie/TrieNodeFactory.cs#L55) matches with `CaptureNodeWithMultipleParameters` which then itself does not serve as a parent node for possible multiple `CaptureNodeWithConstraint`. So essentially the `CaptureNodeWithMultipleParameters` should create `TrieNode` with the `TrieNodeFactory` for the matched parameter segments.

Sorry was too tired today to wrap my head around it more in the short time window I had. Hopefully this is enough for you guys to fix it.

**Comment by hlesesne** [comment]
I'm working through this and almost have it working, but am a little confused as to how I should be boosting the routing weights for a match with validation.

For example, according to https://github.com/NancyFx/Nancy/wiki/Defining-routes#pattern

> Multiple Captures Segment - (100) - /{file}.{extension} or /{file}.ext a segment containing a mix of captures and literals.

The route should only be weighted 100, whether or not their are multiple parameter matches (2 parameters still appear to be worth 100).

My thought was that, by default, it would be worth 100, but for each matched parameter *that matches a constraint - eg: {param:constraint}*, I would boost the score by an additional 100. For example, this route "/{left:version}...{right}" it seems to me should score lower than "/{left:version}...{right:version}".

Am I heading in the right direction?

**Comment by hlesesne** [comment]
It appears that my previous comment may have been a bit premature. It appears that score is determined before evaluation, so I don't believe I can adjust the numbers for multiple matches. I'll let it be as it is and conflicting routes will probably just need to be worked out by the dev. Any other suggestions would be greatly appreciated.
