### ISSUE TITLE
INancyEngine should be disposable and be disposed when the boostrapper and container is disposed.

### ISSUE THREAD

**Issue by damianh** [NancyFx/Nancy#1864]
Main problem [is here](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Owin/NancyMiddleware.cs#L98). When the middleware ( -> boostrapper -> container) is disposed, Nancy is still handling requests. Sometimes successfully. 

`INancyEngine` should be `IDisposable` and [here](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Owin/NancyMiddleware.cs#L98) should be seeing an ObjectDisposedException.

**Comment by grumpydev** [comment]
Not sure I agree with this, using Dispose as a flag to "not accept requests" sounds smelly to me when we have no resources that need cleaning up. What issue does it actually cause?

**Comment by damianh** [comment]
NancyEngine holds a reference to a bunch of resourses https://github.com/NancyFx/Nancy/blob/master/src/Nancy/NancyEngine.cs#L26 (not sure if they're disposable or not).

Nonetheless, philosophically, if a middleware has been disposed, it shouldn't be able to handle requests. Pit of success, fail fast etc.

**Comment by thecodejunkie** [comment]
Did you guys ever reach a consensus on this? @grumpydev @damianh

**Comment by damianh** [comment]
No consensus. I still think it needs to be fixed.
