### ISSUE TITLE
Support for other IoC containers

### ISSUE THREAD

**Issue by ravensorb** [NancyFx/Nancy#1869]
It appears there is a hard dependency on TinyIoC -- it would be great if there was an easier way to support other containers.  Possible create a DefaulftNancyBootstrapper class that takes a generic type that has to be derived from a specific interface (IDependencyResolver or something like that).

Thoughts?

**Comment by grumpydev** [comment]
Errrrrrr... http://www.nuget.org/packages?q=nancy.bootstrappers

**Comment by ravensorb** [comment]
Seems like a lot of work to add support for a new one :)  If you look at what we did in SQLite, in XLabs, or what was done in Json.NET - there was a simply interface that has 2 methods (CanResolve, and Resolve) that needed to be implemented.

**Comment by grumpydev** [comment]
Container abstractions nerf the power of containers to point of any differentiation being pointless. Our system is easy to implement and yet allows users the full power of their chosen container. CanResolve and Resolve is a slippery slope towards the CSL.
