### ISSUE TITLE
Binding fails on abstract classes within a list

### ISSUE THREAD

**Issue by bramdebouvere** [NancyFx/Nancy#1871]
When trying to bind a model that contains a list with an abstract type, we get the following exception:

"Cannot create an abstract class."
```
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
  at Nancy.Json.JavaScriptSerializer.ConvertToObject(IDictionary`2 dict, Type type)
   at Nancy.Json.JavaScriptSerializer.ConvertToType(Type type, Object obj)
   at Nancy.Json.JavaScriptSerializer.ConvertToList(ArrayList col, Type type)
   at Nancy.Json.JavaScriptSerializer.ConvertToType(Type type, Object obj)
   at Nancy.Json.JavaScriptSerializer.ConvertToObject(IDictionary`2 dict, Type type)
   at Nancy.Json.JavaScriptSerializer.ConvertToType(Type type, Object obj)
   at Nancy.Json.JavaScriptSerializer.ConvertToObject(IDictionary`2 dict, Type type)
```

Is there any way we can work around this?

**Comment by albertjan** [comment]
The serializer doesn't know what types of classes you want in your list. I don't think this ever works with json. It doesn't contain any type information. There could be several different classes with this abstract class as it's base. And if there's only one you can just specify that.

**Comment by bramdebouvere** [comment]
There are indeed multiple classes with this abstract class as its base class.
There should at least be a way to map them based on the given members in the json string?

How could we manually specify that?

**Comment by khellang** [comment]
@bramdebouvere You can try to implement a `JavaScriptConverter` and add an instance of it to `JsonSettings.Converters` :smile:

**Comment by bramdebouvere** [comment]
We considered doing that, but our objects are very complex and we're looking for a reusable method to fix this issue. It seems like you have to map every field and subfield yourself with a custom JavaScriptConverter, and that would just not be maintainable in our case.

**Comment by khellang** [comment]
@bramdebouvere Well, the built-in serializer (nicked from Mono) is pretty primitive, I'm not sure there are better alternatives. I think you'd be better of adopting JSON.NET and see if they have something for you :smile:

**Comment by bramdebouvere** [comment]
That's exactly what we ended up doing :)

We added https://github.com/NancyFx/Nancy.Serialization.JsonNet to our project,
then we added the following class:
```
    public class CustomJsonSerializer : JsonSerializer
    {
        public CustomJsonSerializer()
        {
            // This makes sure we can use members like
            //      "$type": "***, ***" 
            // to define the used class when deserializing abstract classes
            this.TypeNameHandling = TypeNameHandling.Auto;
            this.TypeNameAssemblyFormat = FormatterAssemblyStyle.Simple;
        }
    }
```

And we added the following code to our bootstrapper:
```
        protected override void ConfigureApplicationContainer(TinyIoCContainer container)
        {
            container.Register(typeof(JsonService));
            container.Register<JsonSerializer, CustomJsonSerializer>(); //we added this line
        }
```

Now the enduser can send the following:
```
"Items": [
      {
        "$type": "OurNamespace.WebServices.Contracts.OrganisedVisitRebooking, OurAssembly.WebShop.WebServices.Contracts",
        "Id": "00000000-0000-0000-0000-000000000000",
        "Quantity": 0,
        "UnitPrice": 0.0,
        "AdvancementPrice": 0.0
      }
]
```
Json.NET then parses the item correctly!

Thanks to everyone who commented! :+1:

**Comment by khellang** [comment]
@bramdebouvere Thanks for following up with your solution! :+1: An excellent reference for similar problems in the future :smile:

**Comment by cloudhunter89** [comment]
I think my question is related to this, and I don't think it merits having a separate issue (but I am happy to open a separate issue if preferred).  Are there any suggestions for handling things like ISet<> as a class member?  I was hoping that a custom JavaScriptConverter would be able to intercept the deserialization, but Converter is only invoked if it handles the... top level the class.  I'll admit at this point I am grasping at straws to avoid requiring type information...
