### ISSUE TITLE
implicit case of Url to string does not include port

### ISSUE THREAD

**Issue by jchannon** [NancyFx/Nancy#1887]
I have some code like this:

`return new Response{ StatusCode = HttpStatusCode.Created, Headers = { { "Location", this.Request.Url + id } } };`

The incoming url is:

`http://localhost:1924/api/mcus`

The header looks like this:

`http://127.0.0.1/api/mcus/134`

Changing the code to

`return new Response{ StatusCode = HttpStatusCode.Created, Headers = { { "Location", this.Request.Url.ToString() +"/" + id } } };`

results in:

`http://localhost:1924/api/mcus/134`

**Comment by albertjan** [comment]
Weird because the implicit operator calls `ToString` see: https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Url.cs#L166

I just wrote this testcase: 

```c#
[Fact]
public void Should_add_port_when_implicitly_converting_toString()
{
    // Given
    this.url.Scheme = "https";
    this.url.HostName = "www.nancyfx.org";
    this.url.Port = 1234;
    this.url.BasePath = "/base";
    this.url.Path = "/";

    // When
    string result = this.url;

    // Then
    result.ShouldEndWith("https://www.nancyfx.org:1234/base");
}
```

and thats green too.

**Comment by jchannon** [comment]
That is weird, its when I was doing #1888 I spotted it

**Comment by jchannon** [comment]
Although if I take the ToString out on that test it still passes. Will go back to where I spotted it

**Comment by jchannon** [comment]
Think it might have been a dodgy build :worried:
