### ISSUE TITLE
Combining TryParse and route constraints fails

### ISSUE THREAD

**Issue by philjones88** [NancyFx/Nancy#1889]
Seems if you do:

`Get["/foos/{id:int}"] = parameters => {
int id = (int)parameters.id.TryParse<int>(-1);
return new {Key = id};
};`

You'll end up with -1 as the `Key` value from the `id` parameter.

This does seem strange but I upgraded routes to be {id:int} without removing the TryParse's and hit this issue.

**Comment by khellang** [comment]
What does this even mean?

**Comment by khellang** [comment]
If you have `{id:int}`, the `id` parameter should already be an `int` and shouldn't need any parsing.

**Comment by philjones88** [comment]
@khellang Yes it shouldn't need parsing. I would expect this to work though. I know it's silly code but it happened so might help someone else who accidentally hits this :)

**Comment by hlesesne** [comment]
@philjones88 I'm not seeing the behavior you describe.

Given this route:

```c#
            Get["/testint/{id:int}"] = _ =>
            {
                var key = (int) _.id.TryParse(-1);
                var otherKey = (int) _.id.TryParse<int>(-1);
                return new {key, otherKey};
            };
```

and this Url:

```
/testint/123456.json
```

I get the result:

```javascript
{"key":123456,"otherKey":123456}
```

I may be misunderstanding, but I believe you are seeing at least the otherKey value as -1?

**Comment by khellang** [comment]
We need to stop using the `_` convention for arguments that *clearly* aren't ignored, folks :smilE:

**Comment by hlesesne** [comment]
@khellang I updated the example.

**Comment by philjones88** [comment]
This is with 0.23.2 (Blame @jchannon for not getting us on 1.0! ;) )

**Comment by hlesesne** [comment]
@khellang This is off topic and better suited for jabbr probably, but I'd never realized the intent of the "_" convention (ignored params collection) and just used it as shorthand. I'll modify my practice.

BTW - It looks like that convention is used in the sample here https://github.com/NancyFx/Nancy/wiki/Defining-routes#pattern-scoring and other samples on that page - should I update that or am I missing the point?

**Comment by khellang** [comment]
@hlesesne Yeah, I know, I just keep seeing people using the underscore convention (which is a convention for ignored/throwaway variables in many (most?) programming languages) for the arguments object, when it's clearly in use. I guess it's our own fault if the samples use it as well.
