### ISSUE TITLE
Nancy.Validation.DataAnnotations - required NancyContext to validate a model, even though it's not used

### ISSUE THREAD

**Issue by Stephen2** [NancyFx/Nancy#1890]
Hi everyone,

I am running a background task (no NancyContext) and for whatever reason wanted to call ModelValidation, which was failing due to no NancyContext.

Inspecting the source, the context wasn't used, so I created a non-context requiring version all the way through the interfaces/implementations.

Sorry I'm not confident enough to post the pull request, but here is the example:
public interface IValidatableObjectAdapter
    {
        /// <summary>
        /// Validates the given instance.
        /// </summary>
        /// <param name="instance">The instance.</param>
        /// <param name="context">The <see cref="NancyContext"/> of the current request.</param>
        /// <returns>An <see cref="IEnumerable{T}"/> of <see cref="ModelValidationRule"/> instances.</returns>
        IEnumerable<ModelValidationError> Validate(object instance, NancyContext context);

		//SPHACK
		IEnumerable<ModelValidationError> Validate(object instance);
	}

I hope this is considered for real code update, it seems to work fine.

**Comment by xt0rted** [comment]
This was changed in PR #1739 to give custom validators access to the context. None of the built-in data annotations validators use the `NancyContext` so chances are you could just pass `null` for it or `new NancyContext()`.

**Comment by khellang** [comment]
Yeah. This is part of our "context everywhere" mantra and I don't think we'll change this back. If you're sure you're only ever going to use the built-in validators or custom ones not needing the context, you can just pass `null` or a dummy context, as @xt0rted says.
