### ISSUE TITLE
Add support for resolving ~/-style paths to SSVE

### ISSUE THREAD

**Issue by anton-gogolev** [NancyFx/Nancy#1893]
SSVE is a perfectly viable option for a lot of scenarios. One thing that's missing, I think, is the root path resolution.

Adding support for resolving `~/`-relative paths will transform this:

    <link href="~/content/styles.css" type="text/css" rel="stylesheet">

    <form action="~/foo" method="get">

Into this:

    <link href="/application/path/content/styles.css" type="text/css" rel="stylesheet">

    <form action="/application/path/foo" method="get">

An approach with `@Path('~/foo')` is ok-ish, but why not add a bit of extra smarts?

Thoughts?

**Comment by Crisfole** [comment]
Pretty sure this already exists...

**Comment by khellang** [comment]
Makes sense. Are you up for it? :smile:

**Comment by anton-gogolev** [comment]
I can surely give it a shot. 

Onto "design", if I may. I was thinking of two approaches:

* Establish a whitelist of attributes (action, src, href) where path resolution should take place
* Or blindly replace anything starting with "~/ or '~/ with a resolved URL. 

Which sounds more reasonable?

And this should get its own "feature flag" to explicitly enable this behavior, shouldn't it?

**Comment by grumpydev** [comment]
Not sure if you've seen the source to SSVE but it's essentially just a regex, I think the best way to do this without it being annoying would be to look for action="~/ src="~/ but that's going to be slow (the more regexes you run the slower it will be) - I'm not personally convinced there's enough value here to warrant the change.

**Comment by khellang** [comment]
I'd suggest you use a RegEx like `(?<attr>[a-zA-Z]*)=\"~(?<path>.*)\"`, then loop over the matches and either replace blindly or filter on the `attr` group. It doesn't really matter to me. :smile:

**Comment by anton-gogolev** [comment]
See #1894

**Comment by grumpydev** [comment]
Nice :)

**Comment by khellang** [comment]
Closed with #1894 :smile:
