### ISSUE TITLE
not all route can be found

### ISSUE THREAD

**Issue by jiujiu1123** [NancyFx/Nancy#1896]
Hi, guys I am using version 1.1 of Nancy self hosting, I have created a some module like this
```
public UserModule():base("/User")
```
However some route/module does not appear to be functional( return a 404), so I went to the diagnostics page and found out only some route can be found and access, Nancy seems to ignore the other routes. I have confirmed the issue on both windows and mac(mono)
![screen shot 2015-04-16 at 6 13 15 pm](https://cloud.githubusercontent.com/assets/8244605/7176769/83799fac-e464-11e4-93ba-6e600739afc2.png)
 examples of some modules/route being ignored:
![screen shot 2015-04-16 at 6 16 10 pm](https://cloud.githubusercontent.com/assets/8244605/7176800/d12b68d4-e464-11e4-9ceb-65b39dfe5fd5.png)
:

I was wondering if there is a workaround for this issue. 
Thanks in advance.
Peter

**Comment by khellang** [comment]
Are they public classes?

**Comment by jiujiu1123** [comment]
@khellang Thank you so much!!!!  You just save the day, It's all working now can't believe I missed that.

**Comment by khellang** [comment]
It's usually just a simple thing. Been there myself :wink:
