### ISSUE TITLE
this.RequireHttps() broken for Linux hosts?

### ISSUE THREAD

**Issue by Huk256** [NancyFx/Nancy#1899]
Hello.

I don't know if this is a bug or just missing documentation... following this tutorial:

https://github.com/NancyFx/Nancy/wiki/Accessing-the-client-certificate-when-using-SSL

I was able to create simple SSL enabled, self-hosted application, and force SSL on certain modules by adding "this.RequireHttps()", however this only works on Windos - since on Linux there is no "netsh" command to enable SSL on certain port, I used nginx following this tutorial:

https://github.com/NancyFx/Nancy/wiki/Hosting-Nancy-with-Nginx-on-Ubuntu

with the following nginx configuration:

    server {
    listen       80;
    listen       443 ssl;
    ssl_certificate    /home/james/sslCert2/server.crt;
    ssl_certificate_key /home/james/sslCert2/server.key;

    server_name  localhost;
    root /home/james/nancywebpageroot/NancyWebPage.DPL.Services/bin/Debug/;

    location /Content/ {
        alias /home/james/nancywebpageroot/NancyWebPage.DPL.Services/bin/Debug/Content/;
        location ~*  \.(jpg|jpeg|png|gif|ico|css|js|ttf)$ {
            expires 365d;
        }
    }

    location / {
            proxy_pass http://127.0.0.1:8080;
    }       
}

while the above enables SSL on port 443, it makes "this.RequireHttps()" worthless (if I use it - Chrome reports ERR_TOO_MANY_REDIRECTS), so in order to secure certain modules with SSL I would have to use paths inside nginx config file - which is not acceptable :(

Question is - is "this.RequireHttps()" Windos only option or am I missing somethig in my configuration? Also could someone explain a bit more what does "EnableClientCertificates" host configuration option does? Is it require to enable SSL? Documentation is rather scarce...

Thanks in advance.

Best regards.

P.S.

I already asked a question about this on stackoverflow:

http://stackoverflow.com/questions/29634033/nancyfx-ssl-how-to-make-this-requirehttps-work-on-linux

But since there is no answer I'm trying here :)

**Comment by Huk256** [comment]
OK, today I tested some more and now I know that "this.RequiresHttps()" works (that is it does what it's supposed to - checks if URL is secured and if not - redirects), problem is with the nginx configuration I posted - when we point to some SSL only module, and are redirected to https://127.0.0.1:443 - nginx actually makes request to Nancy on proxy_pass url - that is: http://127.0.0.1:8080 - so we have the following "Catch 22" situation:

1. We request - for example: http://127.0.0.1:8080/auth
2. Nancy checks the url and since it is not HTTPS enabled, it redirects
3. nginx catches the request correctly end enables SSL, then request the page again on proxy_pass url 
4. Nancy gets request with URL pointing to: http://127.0.0.1:8080/auth again - since it is not secured it redirects...

The loop is completed.

Question remains - how can we "fool" Nancy to think it got request from https enabled URL? I think this can be done by properly configuring nginx - but my experience there is very limited, I can say I tried:

1. Setting: 

proxy_redirect  http:// https://; 

or something similar - while in curl I can see that the "Location" header is being pointed to https - Nancy doesn't seem to use "Location" header during requests

2. I also tried some rewrites inside location block - but couldn't get them to work.

If this can't be done by server configuration alone, what else is required?

Best regards.

**Comment by khellang** [comment]
Check out #1679 for a solution to SSL offloading. Basically you can use that hook to "trick" Nancy to think it's HTTPS, even though it's over HTTP. It uses either the  `X-Forwarded-Proto` or the `Forwarded` header, make sure you configure Nginx to include one of them.

**Comment by khellang** [comment]
You can check out https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-load-balancing-with-ssl-termination for config samples on how to include a `X-Forwarded-Proto` header (I think :stuck_out_tongue:)

**Comment by khellang** [comment]
Let me know if you get it working so we can close this and write up an answer on SO that we can point to (or people will find) in the future :smile:

**Comment by Huk256** [comment]
Thanks for the answer, combination of "SSLProxy.RewriteSchemeUsingForwardedHeaders (pipelines);" and the following nginx config:

    server {
    listen       80;

    server_name  localhost;
    root /home/james/nancywebpageroot/NancyWebPage.DPL.Services/bin/Debug/;

    location /Content/ {
        alias /home/james/nancywebpageroot/NancyWebPage.DPL.Services/bin/Debug/Content/;
        location ~*  \.(jpg|jpeg|png|gif|ico|css|js|ttf)$ {
            expires 365d;
        }
    }

    location / {
    proxy_pass http://127.0.0.1:8080;
    }    
    }

    server {
    listen       443 ssl;
    ssl_certificate    /home/james/sslCert2/server.crt;
    ssl_certificate_key /home/james/sslCert2/server.key;


    server_name  localhost;
    root /home/james/nancywebpageroot/NancyWebPage.DPL.Services/bin/Debug/;

    location /Content/ {
        alias /home/james/nancywebpageroot/NancyWebPage.DPL.Services/bin/Debug/Content/;
        location ~*  \.(jpg|jpeg|png|gif|ico|css|js|ttf)$ {
            expires 365d;
        }
    }

    location / {
    proxy_pass http://127.0.0.1:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    }    
    }

Did the trick, now "this.RequireHttps()" works as it should, thanks for the help - I would like to ask one more, related question - in ASP.NET, the RequireHttpsAttribute can be use to force SSL on whole class or on selected methods - I wonder if the latter is possible with Nancy's "this.RequireHttps()" somehow?

Best regards.

**Comment by khellang** [comment]
Just call the method in the constructor of a module (outside route definitions)?

**Comment by albertjan** [comment]
You can even add it to the whole application by calling it in the bootstrappers `ApplicationStartup` function like:

```c#
protected override void ApplicationStartup(TinyIoCContainer container, IPipelines pipelines)
{
    pipelines.BeforeRequest.AddItemToStartOfPipeline(SecurityHooks.RequiresHttps(true, 443));
}
```

**Comment by Huk256** [comment]
Thanks for the answers but you misunderstood me :)

I know I can secure whole module (or even entire application) by using either way you posted - however I would like to know if securing only selected path (not the whole module) is possible, I tried something like this:

	public class TestModule : NancyModule
	{
		Get["/secured"] = x =>
		{
			this.RequiresHttps(true, 443);
			return "TEST";
		}

		Get["/unsecured"] = x =>
		{
			return "TEST";
		}
	}

But this doesn't seem to do anything for the "/secured" path, there is no redirect when user tries to access it without SSL - so I wonder if something like the above is currently  possible with Nancy... I'm sorry if my earlier question wasn't clear enough on that :)

Best regards.

**Comment by Huk256** [comment]
OK, guys since there is no answer let's conclude that there is no equivalent to: "this.RequireHttps()" on path level :) This isn't a big deal let's just ignore it for now.

I will close this issue since the original problem was resolved :) - more specific instructions, as well as some more explanations are available at stackoverflow:

http://stackoverflow.com/questions/29634033/nancyfx-ssl-how-to-make-this-requirehttps-work-on-linux/29832733#29832733

Thanks for all your help.

Best regards.

**Comment by grumpydev** [comment]
It would be simple enough to add following the same model as the security hooks now use whereby they either add a hook, or execute the code that would go into the hook immediately, depending on whether it's in the ctor or in the route itself - it was done for all the security bits, but we didn't do it for anything else.
