### ISSUE TITLE
DefaultStatusCodeHandler should negotiate content and provide a JSON response

### ISSUE THREAD

**Issue by jonathanfoster** [NancyFx/Nancy#1905]
It would be nice if the `DefaultStatusCodeHandler` negotiated content and provided a JSON response instead of just the custom 400 and 500 error pages.

**Comment by khellang** [comment]
Agreed :+1: Are you up for the task?

**Comment by jonathanfoster** [comment]
I'll pull this issue.

**Comment by jonathanfoster** [comment]
Pull request 1911 (https://github.com/NancyFx/Nancy/pull/1911) adds this feature. Take a look at the PR and let me know if there's any feedback.

**Comment by khellang** [comment]
Fixed by #2081

**Comment by khellang** [comment]
Thanks, @jonathanfoster! :grin:

**Comment by jonathanfoster** [comment]
Thank you guys for making an awesome framework. I'm just happy I could contribute.
