### ISSUE TITLE
Miss css files when routed like Get["/somename/{someId}"]

### ISSUE THREAD

**Issue by LoserKiss** [NancyFx/Nancy#1906]
No matters if i use master page or write all html code in one file. Maybe i do it wrong? (I use super simple view engine). nancy 1.2.0; authentication forms 1.2.0; bootstrapper autofac 1.2.0; hosting self 1.2.0.
(with routes without getparams it's all OK, and even with route "/{id}" it's ok)

**Comment by LoserKiss** [comment]
Even more! I figured out that Get["/home"] will return normal html, but Get["/home/"] will return html without css!!

**Comment by LoserKiss** [comment]
Even more, all request with more than one slash would have this bug.

**Comment by khellang** [comment]
I have no idea what you're saying. Are you getting 404's on your CSS files when you're accessing your site using a specific URL? I think maybe this is a question for StackOverflow?

**Comment by LoserKiss** [comment]
Oh, sorry. I found what was wrong. My css link were like <link href="Content/Css/bootstrap.min.css" rel="stylesheet">. And when i request /post/, my browser tries to retrieve css file from mysite/post/Content/Css/bootstrap.min.css. Sorry for disturb)

**Comment by khellang** [comment]
Alright then :+1:
