### ISSUE TITLE
Browser with.Dependencies(..) broken?

### ISSUE THREAD

**Issue by PureKrome** [NancyFx/Nancy#1909]
_Notice: I'm not sure if this issue is related to #1862 or this is a TinyIOC issue and should be raised there._

When testing a route using `Nancy.Testing` and using `with.Dependencies(someCollectionOfDependencies);` it fails to correctly set them up.

As a work around, I need to iterate through each one and `with.Dependency(someDependency);` and _that_ works.

for example ..

*Fails*
```
var browser = new Browser(with =>
{
    with.Module<MyModule>();
    with.Dependencies(dependencies); // a collection of `x` dep's.
});
```
*Succeeds*
```
var browser = new Browser(with =>
{
    with.Module<MyModule>();
    foreach(var dependency in dependencies)
    {
        with.Dependency(dependency);
    }
});
```

btw, the collection `dependencies` are identical.

Lastly, this is with version `1.2` of Nancy, etc.

**Comment by horsdal** [comment]
On a quick first glance it doesn't seem related to #1862. It _could_ be another issue in `ConfigurableBootsttrapper` though.

**Comment by PureKrome** [comment]
:+1:  Ok, is this enough info for you @horsdal (or anyone else on the team), right now?

**Comment by khellang** [comment]
@PureKrome I don't know how that method has ever worked. The method takes a `params object[] dependencies`, loops over them and calls `this.Dependency<T>(dependency)` where `T` is inferred to `object` :confused: I'll send a PR to fix it. In the meantime you can should explicitly invoke the `Dependencies<T>` overload.

**Comment by PureKrome** [comment]
>where T is inferred to object
AH! I was _hoping_ that was happening ... based on the error message :) Awesome!

Sweet as candy! 

![](http://i.giphy.com/8EcQCM4mZo5na.gif)
