### ISSUE TITLE
Nancy.Authentication.Token - How do we handle sliding/persistent access?

### ISSUE THREAD

**Issue by RPM1984** [NancyFx/Nancy#1915]
So i'm looking at using [Nancy.Authentication.Token] (https://github.com/NancyFx/Nancy/wiki/Token%20Authentication) to authenticate users of my Nancy REST API.

I have a SPA web app built in React, and an iOS app. Each app can have many users, and these are essentially the "clients" that I need to give access to, e.g

App | Client
------|--------
SPA | Bob
SPA | Alice
iOS | Bob

So Bob can only update Bob's info, and not Alice's etc.

My question is, if Bob is on the SPA website, logs in via a web form, gets a token, etc - then Bob closes his browser - wouldn't he have to log the user in again (via the web form?) when he opens his browser again? (or when the token expires). Do i somehow have to persist the token into a cookie/local storage (and is that secure?). Do i have to do silent refresh operations behind the scenes?

Forms Auth handles this via a sliding/persistent cookie - so i'm wondering how i can achieve this using Nancy Token auth?

**Comment by thecodejunkie** [comment]
@jeffdoolittle care to chim in? @RPM1984 did you ever get anywhere with this?

**Comment by RPM1984** [comment]
@thecodejunkie nope, never got any further than the convo above. Will probably end up using [IdentityServer3](https://github.com/IdentityServer/IdentityServer3)

**Comment by jeffdoolittle** [comment]
@thecodejunkie Isn't token auth slated to be deprecated in favor of using a JSON Web Token implementation over OWIN? I'd concur with @RPM1984 and recommend going with IdentityServer.

**Comment by PureKrome** [comment]
I'm pretty sure JWT is the way forward.

**Comment by phillip-haydon** [comment]
Sounds like JWT is the way to go, so closing this for now.
