### ISSUE TITLE
DynamicDictionaryValue does not have implicit operator for nullable types

### ISSUE THREAD

**Issue by ahkjeldsen** [NancyFx/Nancy#1918]
When handling multiple routes the same way, it could be preferable to cast capture groups to nullable types.

``` csharp
Get["/sizes/{accountId:int}"] =
Get["/sizes/{accountId:int}/{siteId:int}"] =
Get["/sizes/{accountId:int}/{siteId:int}/{year:int}"] =
Get["/sizes/{accountId:int}/{siteId:int}/{year:int}/{month:int}"] =
Get["/sizes/{accountId:int}/{siteId:int}/{year:int}/{month:int}/{day:int}"] = x => { ... }
```

Here I cant simply put
``` csharp
long? siteId = x.siteId;
```
Because if the first route is matched, then siteId isn't set and DynamicDictionaryValue will try to cast the value as a long and throw a NullReferenceException.

Instead I have to do something like
``` csharp
long? siteId = x.siteId.HasValue ? x.siteId : null;
```
Which just seem a bit excessive when an implicit operator could have been implemented instead.

So would it be possible to add implicit operators to DynamicDictionaryValue that supports nullable types?

**Comment by thecodejunkie** [comment]
@ahkjeldsen Yep, this should be possible. I just added a quick `implicit operator overload` for `int?` and tried it. Seem to work. Will see about getting a pull-request in that supports null operator on the primitives
