### ISSUE TITLE
Routing dropping .json extension

### ISSUE THREAD

**Issue by meetshawn** [NancyFx/Nancy#1919]
When using `Get["/{path*}"]` if the URL is a filename.json "path" never contains the .json extension just filename, yet for every other file extension I tried it keeps the respective extension.

**Comment by xt0rted** [comment]
This is a feature of [content negotiation](https://github.com/NancyFx/Nancy/wiki/Content-Negotiation#file-extension-support).

**Comment by albertjan** [comment]
Files should be served using static content conventions. I think .json files will work then.
