### ISSUE TITLE
Intermittent Cyclical Dependency failure with Ninject IoC

### ISSUE THREAD

**Issue by wilhen01** [NancyFx/Nancy#1922]
We're suffering an intermittent issue with one of our Nancy apps with an IoC failure complaining of cyclical dependencies when attempting to load response processors. It seems to happen on app startup, but only lasts a few seconds - it generally causes the first call or two against the app to fail, but then resolves itself somehow. 

Stacktrace looks like this (though interesting the specific response processor it fails on varies - sometimes it's the built in JsonProcessr as below, sometimes a custom response processor)

	Error activating IResponseProcessor using binding from IResponseProcessor to JsonProcessor
	A cyclical dependency was detected between the constructors of two services.

	Activation path:
	  5) Injection of dependency IResponseProcessor into parameter processors of constructor of type DefaultResponseNegotiator
	  4) Injection of dependency IResponseNegotiator into parameter negotiator of constructor of type DefaultRouteInvoker
	  3) Injection of dependency IRouteInvoker into parameter routeInvoker of constructor of type DefaultRequestDispatcher
	  2) Injection of dependency IRequestDispatcher into parameter dispatcher of constructor of type NancyEngine
	  1) Request for INancyEngine

	Suggestions:
	  1) Ensure that you have not declared a dependency for IResponseProcessor on any implementations of the service.
	  2) Consider combining the services into a single one to remove the cycle.
	  3) Use property injection instead of constructor injection, and implement IInitializable
		 if you need initialization logic to be run after property values have been injected.
		at Ninject.Activation.Context.Resolve()
	   at Ninject.KernelBase.<>c__DisplayClass15.<Resolve>b__f(IBinding binding)
	   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
	   at System.Linq.Enumerable.<CastIterator>d__b1`1.MoveNext()
	   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.<GetCompatibleProcessorsByHeader>d__3c.MoveNext()
	   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
	   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.<GetCompatibleHeaders>d__23.MoveNext()
	   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
	   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
	   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(Object routeResult, NancyContext context)
	   at Nancy.Routing.DefaultRouteInvoker.<>c__DisplayClassa.<Invoke>b__6(Task`1 completedTask)

**Comment by wilhen01** [comment]
I should probably have said, we're using Nancy 1.2.0 with Nancy.Hosting.Aspnet and Nancy.Bootstrappers.Ninject (also 1.2.0) and Ninject 3.2.0.0 with Ninject.Extensions.ChildKernel and Ninject.Web.Common (also 3.2.0.0)

**Comment by wilhen01** [comment]
Anyone got any insight on this? Still experiencing it on the project in question, and unfortunately I've had no luck tracking it down.

**Comment by phillip-haydon** [comment]
Unfortunitely none of us use any IoC container besides TinyIoC so with little to no knowledge of ninject its hard for us to help. 

Do you happen to have a particular module that is dependent on something from Nancy?

**Comment by wilhen01** [comment]
Not directly @phillip-haydon - we specify Ninject Modules containing bindings for our custom classes where we need to bind an implementation class to an interface but when it comes to all the Nancy stuff we're taking advantage of Nancy and Ninject's automatic assembly scanning etc. to discover all the Nancy modules, Response Processors etc. and any dependencies where explicit binding isn't required. 

This auto-binding includes a whole bunch of classes which implement IResponseProcessor to handle our Content Negotiation, but I've checked all the classes in question and can't see any reason why any of it would trigger a cyclic failure, and the fact that upon a second call the error disappears suggests that maybe it's a timing issue?

**Comment by khellang** [comment]
I'm pretty sure there's no cyclic dependencies in Nancy. If that were the case, there would've been tests failing and lots of people complaining. Unless we have a small repro of this, I'm not sure how you want us to debug it for you? :smile:

**Comment by wilhen01** [comment]
@khellang No, definitely no cyclic dependenices in Nancy...we use the Nancy/Ninject combination in about 20 other projects and I've never seen this issue elsewhere (which makes it all the more annoying!)

I haven't had time to try and reproduce this on a smaller scale but I suspect if I made a toy solution and tried I wouldn't see it. Was kinda hoping someone might have experienced something similar and be able to point me in the right direction...

**Comment by phillip-haydon** [comment]
Between here, Twitter, and JabbR, I haven't heard of anyone else getting similar issues. 

If you're able to reproduce the issue, you will either realize something is wrong on your end, or you will give us something to fix :D either way I'm not entirely sure we can be much help :(

**Comment by wilhen01** [comment]
Fair play. Thanks for the input anyway guys

**Comment by thecodejunkie** [comment]
@wilhen01 do you feel that this issue can be closed? Thanks

**Comment by wilhen01** [comment]
Sure. I'll re-open it if I find something further you guys can investigate.

**Comment by jherman** [comment]
I can say I get this also intermittently, and it does seem to recover itself afterwards (I use ninject as well).  Here is the exception I'm thrown:

```
Nancy.RequestExecutionException: Oh noes! ---> Ninject.ActivationException: Error activating IResponseProcessor using binding from IResponseProcessor to ViewProcessor
A cyclical dependency was detected between the constructors of two services.

Activation path:
  5) Injection of dependency IResponseProcessor into parameter processors of constructor of type DefaultResponseNegotiator
  4) Injection of dependency IResponseNegotiator into parameter negotiator of constructor of type DefaultRouteInvoker
  3) Injection of dependency IRouteInvoker into parameter routeInvoker of constructor of type DefaultRequestDispatcher
  2) Injection of dependency IRequestDispatcher into parameter dispatcher of constructor of type NancyEngine
  1) Request for INancyEngine

Suggestions:
  1) Ensure that you have not declared a dependency for IResponseProcessor on any implementations of the service.
  2) Consider combining the services into a single one to remove the cycle.
  3) Use property injection instead of constructor injection, and implement IInitializable
     if you need initialization logic to be run after property values have been injected.

   at Ninject.Activation.Context.Resolve()
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.<GetCompatibleProcessorsByHeader>d__3c.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.<GetCompatibleHeaders>d__23.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(Object routeResult, NancyContext context)
   at Nancy.Routing.DefaultRouteInvoker.<>c__DisplayClassa.<Invoke>b__6(Task`1 completedTask)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)
```

**Comment by wilhen01** [comment]
Any luck getting to the bottom of it @jherman ? I haven't had any time to investigate further unfortunately.

**Comment by jherman** [comment]
I have not. Just haven't had the time myself.  I see this error about once or twice a month when I'm debugging, and just ignored it because it seems benign. For some reason today, I decided to just google it, and this thread came up first. Thought I would just leave this stack trace so you didn't feel alone :) Definitely seems to be a timing issue.

**Comment by chrismasters** [comment]
Can also say I've seen this, as well as another intermittent issue with binding a constructor value when the parameter has bound in the kernel as a constant.

Definitely seems like timing, but can't reproduce reliably

**Comment by tofutim** [comment]
I ran into this today.

**Comment by wilhen01** [comment]
FYI guys I eventually got sick of Ninject and switched to Autofac - it got rid of this issue and gave us a fairly significant performance boost too. I know that's not a fix as such but it's one option!

**Comment by frankradocaj** [comment]
I'm getting the same intermittent problem. I agree with @chrismasters that it seems to be a timing issue. FWIW, here is my stack trace:

```
Error activating IRouteSegmentConstraint using binding from IRouteSegmentConstraint to BoolRouteSegmentConstraint
A cyclical dependency was detected between the constructors of two services.

Activation path:
  6) Injection of dependency IRouteSegmentConstraint into parameter routeSegmentConstraints of constructor of type TrieNodeFactory
  5) Injection of dependency ITrieNodeFactory into parameter nodeFactory of constructor of type RouteResolverTrie
  4) Injection of dependency IRouteResolverTrie into parameter trie of constructor of type DefaultRouteResolver
  3) Injection of dependency IRouteResolver into parameter routeResolver of constructor of type DefaultRequestDispatcher
  2) Injection of dependency IRequestDispatcher into parameter dispatcher of constructor of type NancyEngine
  1) Request for INancyEngine

Suggestions:
  1) Ensure that you have not declared a dependency for IRouteSegmentConstraint on any implementations of the service.
  2) Consider combining the services into a single one to remove the cycle.
  3) Use property injection instead of constructor injection, and implement IInitializable
     if you need initialization logic to be run after property values have been injected.
]
   Ninject.Activation.Context.Resolve() +229
   System.Linq.WhereSelectListIterator`2.MoveNext() +111
   System.Linq.&lt;CastIterator&gt;d__94`1.MoveNext() +75
   System.Linq.Enumerable.FirstOrDefault(IEnumerable`1 source, Func`2 predicate) +200
   Nancy.Routing.Trie.Nodes.CaptureNodeWithConstraint.Match(String segment) +83
   Nancy.Routing.Trie.Nodes.TrieNode.GetMatches(String[] segments, Int32 currentIndex, IDictionary`2 capturedParameters, NancyContext context) +58
   Nancy.Routing.Trie.Nodes.&lt;GetMatchingChildren&gt;d__7.MoveNext() +701
   Nancy.Routing.Trie.Nodes.&lt;GetMatchingChildren&gt;d__7.MoveNext() +772
   System.Linq.Buffer`1..ctor(IEnumerable`1 source) +153
   System.Linq.Enumerable.ToArray(IEnumerable`1 source) +106
   Nancy.Routing.DefaultRouteResolver.Resolve(NancyContext context) +90
   Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken) +147
   Nancy.&lt;&gt;c__DisplayClasse.&lt;InvokeRequestLifeCycle&gt;b__c(Task`1 t) +59
   Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines) +314
   Nancy.NancyEngine.HandleRequest(Request request, Func`2 preRequest, CancellationToken cancellationToken) +413
   Nancy.NancyEngineExtensions.HandleRequest(INancyEngine nancyEngine, Request request, Func`2 preRequest, Action`1 onComplete, Action`1 onError, CancellationToken cancellationToken) +128
   Nancy.Owin.&lt;&gt;c__DisplayClass6.&lt;UseNancy&gt;b__1(IDictionary`2 environment) +1256
```

**Comment by DanCaveman** [comment]
I had this problem when IEnumerable<MyItem> as a constructor argument for MyItemFactory.  When I changed it to a list, it worked perfectly.  I noticed that ninject did not complain until I attempted to traverse the IEnumerable and return a MyItem (during the create).  That got me thinking that Ninject was not creating the constructor items until it tried to enumerate them, well after the class was created.
```
public class MyItemFactory{
   private readonly IEnumerable<MyItem> _myPossibleItems;
   public MyItemFactory(IEnumerable<MyItem> myPossibleItems){
       _myPossibleItems = myPossibleItems; // <-- NO ERROR HERE
   }
  public void MyItem Create(string differentiator){
       if(differentiator == "specific"){
           return _myPossibleItems.OfType<MySpecificItem>().First();  // <-- ERROR HERE
       }
  }
}
```

Hope this helps.  I know this is an old post.
