### ISSUE TITLE
[Closed] Access "/" result to a 404 (Windows/Ubuntu)

### ISSUE THREAD

**Issue by mickaelandrieu** [NancyFx/Nancy#1923]
Hi everyone,

I have created an ASP.net project with Xamarin Studio, and then I have added "Nancy.Hosting.AspNet" package from NuGet.

I'm on Windows 8.1 and if I execute this code:

```csharp
namespace NancyBlog
{
	using Nancy;

	public class HelloModule : NancyModule
	{
		public HelloModule ()
		{
			Get["/"] = _ => "Hello Nancy World";
		}
	}
}
```

The web brower returns me a 404, I tried to change the port in case or another webserver listen to 8080 and I have the same result, 404 error is returned by Mono.WebServer.XSP/2.8.0.0 Win32NT server according to the HTTP response headers.

The "funny thing" is if I change the url, for example ```Get["/hello"]``` things works as expected.

Do you have any idea on fix this and why do I encounter this issue ?

**Comment by mickaelandrieu** [comment]
Hi,

same issue on ubuntu/mint OS.

``bash
sudo apt-get install monodevelop
sudo apt-get install mono-xsp4
``

Then in MonoDevelop, I did the same step explained in the previous post => 404 catched by Nancy.

This is very annoying.

**Comment by grumpydev** [comment]
So is it a nancy 404 or a web server / host 404?

**Comment by mickaelandrieu** [comment]
@grumpydev thank you to help me, I'm pretty sure it's from nancy.

**Comment by grumpydev** [comment]
It does seem to be, but I'm at a loss as to why, I'd put my money on it being a weird mono/XSP bug/issue, but I haven't seen anyone else with the same or similar problems, and we have plenty of mono users.

**Comment by grumpydev** [comment]
No idea why that would help, but if it's fixed it's fixed :)

**Comment by mickaelandrieu** [comment]
yes, pragmatism before all :D

**Comment by mickaelandrieu** [comment]
@grumpydev sadly, this bug remains in Windows environnement :/ (Xamarin studio, any web browser, any port used).

To resume: "/" => 404
"/anything-i-want-as-url" => 200

**Comment by grumpydev** [comment]
Still a bug in XSP though by the looks of it.

**Comment by mickaelandrieu** [comment]
how to fix it ? 

I tried to use different versions of .NET availables on my PC, but the issue remains :(
