### ISSUE TITLE
Bootstrapper not located

### ISSUE THREAD

**Issue by cvetomirtodorov** [NancyFx/Nancy#1926]
I have a class library with an abstract `BootstrapperBase : DefaultNancyBootstrapper` and an ASP.NET Nancy host with a `AspNetBootstrapper : BootstrapperBase`. The problem is that my bootstrapper is not instantiated. If I add the interface like this `AspNetBootstrapper : BootstrapperBase, INancyBootstrapper` it gets located and instatiated.

**Comment by grumpydev** [comment]
This is a .net trying to be clever and not loading your assembly issue - you don't have a hard reference between your class library and your host project so it thinks it doesn't need to load it, adding that interface adds that hard reference and forces it to load.

**Comment by khellang** [comment]
@cvetomirtodorov You could add the `IncludeInNancyAssemblyScanningAttribute` in the `Properties.cs` file of your class library to make sure Nancy includes the assembly in the scanning for bootstrappers:

    [assembly: IncludeInNancyAssemblyScanningAttribute]

**Comment by cvetomirtodorov** [comment]
@khellang The `IncludeInNancyAssemblyScanningAttribute` attribute on itself does not solve the problem. Only adding the `INancyBootstrapper` to the `AspNetBootstrapper` does.

@grumpydev  I don't think that adding `INancyBootstrapper` should add a **hard** reference to my class library since that is a Nancy interface. My ASP.NET project already should have a hard reference since my `AspNetBootstrapper` inherits from the `BootstrapperBase` in my class library.

**Comment by horsdal** [comment]
The attribute should be added somewhere in the ASPNET project, not the class library, me thinks.

**Comment by cvetomirtodorov** [comment]
@horsdal Adding the `IncludeInNancyAssemblyScanningAttribute` in the ASP.NET host project worked. But I am sure why the host assembly is not included in the scanning.

**Comment by khellang** [comment]
@cvetomirtodorev Yeah, it makes little sense. What probably happens is what I tried to explain above. The host assembly references Nancy, but doesn't explicitly use any of its types at compile-time, thus the compiler removes the reference. If you pull up the host assembly in DotPeek or similar you'll see the reference is gone.

This is a scenario that we definitely should support though. It's not as SDHP as it could be, as is. Maybe we should add `Assembly.GetCallingAssembly`'s result to ADATS in the bootstrapper locator, before we do any scanning. This way we'll make sure the host assembly is always included, no matter which references it has. @NancyFx/owners @NancyFx/most-valued-minions Makes sense?
