### ISSUE TITLE
StatelessAuthentication on module/application

### ISSUE THREAD

**Issue by angelotinti** [NancyFx/Nancy#1933]
Hi,

I'm using the StatelessAuthentication per application combined with a aspect-like implementation on modules to authenticate users.

The Func on StatelessAuthenticationConfiguration connects to a database to validate and return a IUserIdentity based on a token retrieved from the request.

On the modules, we have a base implementation that identifies an attribute on the module class and then adds a before to the beforePipeline. Something like, DoNotRequiresAuthenticationAttribute.

So, for all the modules without the attribute we execute a validation based on the context.CurrentUser witch was defined by the StatelessAuthenticationConfiguration func.

The StatelessAuthenticationConfiguration func always executes, cuz it is on application level, but sometimes we dont want it to execute, based on the attribute setted (or not) in the modules.

We chose the StatelessAuthentication per application cuz being on the Bootstrapper allows us to use the Container to resolve classes used to validate the token, witch is not possible with the StatelessAuthentication per module.

Theres a way to retrieve the module type, inside the func from the StatelessAuthenticationConfiguration, from the NancyContext or something like that?

**Comment by thecodejunkie** [comment]
Unfortunately there is no way to get a hold of the module name / type from the request pipeline. The closest you could do is

```c#
var resolver =
     requestContainer.Resolve<IRouteResolver>();

var result =
     resolver.Resolve(context);
```

and then you can access `.Route` on the result to get some basic information like the method, path and so on.

I will look into adding it to the information, shouldn't be too hard

**Comment by thecodejunkie** [comment]
Had a look at this is a bit tricky to bake in at the moment. The best advice I can give right now is to use the code above and check the route and apply a base-path route naming convention.
