### ISSUE TITLE
Routes not updating when I restart

### ISSUE THREAD

**Issue by matthewcanty** [NancyFx/Nancy#1934]
Think I might be going mad but I cannot figure this out. I have tried this with `Nancy.Hosting.Self` and `Nancy.Hosting.Aspnet`.

Given I create a route: `Get["/something"] = x => "Hello";`

I get `Hello` in the browser. But if I change the route to return something else, let's say an `int`:
`Get["/something"] = x => 1;`

Then all I get back is "This web page is not available".

I've looked around at the possibility of routes being cached but whatever I've found has not helped.

Thanks for your help.

**Comment by khellang** [comment]
@matthewcanty That's because Nancy interprets `int` as a HTTP status code. See [the wiki](https://github.com/NancyFx/Nancy/wiki/Defining%20routes#action):

> The Response object declares several implicit cast operators which enables an action to also return, instead of a Response object, any of the following
> 
> `int` which will be interpreted as a HTTP status code of the response
> `HttpStatusCode` enumerable value
> `string` which will be interpreted as the body of the response
> `Action<Stream>` which is a function that writes to the response stream

**Comment by matthewcanty** [comment]
Thanks. I was just freaking out. Just a bad choice of type to test being returned I guess...

I wonder what 1 is telling the browser to do? My guess is it interprets it as 100 and just _continues_ to do nothing at all...

**Comment by khellang** [comment]
Just pull up Fiddler, Postman or even Chrome dev tools and check. There's nothing wrong with returning an empty HTTP response with status code 1 :smile:
