### ISSUE TITLE
Failing on mono 4.0 on Windows 8.1

### ISSUE THREAD

**Issue by daxfohl** [NancyFx/Nancy#1935]
In mono 4.0 for windows, it seems that the headers are included in the response body.  

This is what I see when running the "Nancy Application with self-hosting" template.

When run in mono 3.1:

    C:\>curl localhost:20003
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>NancyApplication8</title>

            <style type="text/css">

                    body {
                            text-align: center;
                    }

            </style>

    </head>
    <body>
            <img src="/Content/nancy-logo.png" alt="Nancy logo" /><br />
            This view was rendered using the SuperSimpleViewEngine
    </body>
    </html>

When run in mono 4.0:

    C:\>curl localhost:20003
    P/1.1 200 OK
    Vary: Accept
    Content-Type: text/html
    Server: Mono-HTTPAPI/1.0
    Date: Wed, 13 May 2015 15:12:24 GMT
    Transfer-Encoding: chunked
    Keep-Alive: timeout=15,max=100

    15e
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>NancyApplication8</title>

            <style type="text/css">

                    body {
                            text-align: center;
                    }

            </style>

    </head>
    <body>
            <img src="/Content/nancy-logo.png" alt="Nancy logo" /><br />
            This view was rendered using the SuperSimpleViewEngine
    </body>
    </html>

    0

**Comment by grumpydev** [comment]
Can't see how this can be anything other than a Mono bug?

**Comment by Advoskr** [comment]
I also face the same problem and on ubuntu 15.04 with Mono 4 everything works great

**Comment by thecodejunkie** [comment]
I'm with @grumpydev here, this is a Mono bug. We don't explicitly do anything different on the various Mono versions so if it breaks on a newer version, then that's not us.

**Comment by tritao** [comment]
Can you guys file a bug in our bugtracker (Xamarin) and attach some repro so we can take a look at it?

**Comment by Advoskr** [comment]
I posted this bug to Mono team, hope they can investigate this problem https://bugzilla.xamarin.com/show_bug.cgi?id=32128

**Comment by thecodejunkie** [comment]
This is confirmed as a bug in Mono 4. Closing this issue
