### ISSUE TITLE
DefaultModelBinder requires public default constructor

### ISSUE THREAD

**Issue by jvandertil** [NancyFx/Nancy#1938]
The default model binder requires the existence of a public default constructor. 
Is it possible to allow non public default constructors as well?

Root cause seems to be:
https://github.com/NancyFx/Nancy/blob/master/src/Nancy/ModelBinding/DefaultBinder.cs#L432
and
https://github.com/NancyFx/Nancy/blob/master/src/Nancy/ModelBinding/DefaultBinder.cs#L436

I can work on a pull request to fix this, but I'm wondering if there is a good reason to not allow this.

**Comment by khellang** [comment]
Landed with #1946
