### ISSUE TITLE
BrowserContextExtensions should return BrowserContext for chaining

### ISSUE THREAD

**Issue by lijunle** [NancyFx/Nancy#1939]
Current:

```cs
BrowserResponse response = Browser.Post(
    "form",
    with =>
    {
        with.Accept("text/plain");
        with.JsonBody<Form>(form);
    });
```

Could be better:

```cs
BrowserResponse response = Browser.Post(
    "form",
    with => with.Accept("text/plain").JsonBody<Form>(form));
```

**Comment by grumpydev** [comment]
The first one reads properly, the second one doesn't - first one reads "with this accept value and this json body",  second one reads "accept text plain and a json body" - that doesn't make sense.

**Comment by lijunle** [comment]
I think that is only naming issue. That could be like this:

```cs
BrowserResponse response = Browser.Post(
    "form",
    ctx => ctx.WithAccept("text/plain").WithJsonBody<Form>(form));
```

or

```cs
BrowserResponse response = Browser.Post(
    "form",
    ctx => ctx.WithAccept("text/plain").And.WithJsonBody<Form>(form));
```

**Comment by grumpydev** [comment]
The first one is a syntax change for the sake of it, and also falls down when one of the extensions wants to return it's own builder type - the second one is just replacing "with" with "and", and is still less expressive imo.

Sorry, just don't see any value in this.

**Comment by lijunle** [comment]
The value here is keep the syntax same as (or at least similar with) [ResponseExtensions](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/ResponseExtensions.cs).
