### ISSUE TITLE
Are these (minor) typos?

### ISSUE THREAD

**Issue by lijunle** [NancyFx/Nancy#1940]
In [RoutingDescription](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Routing/RouteDescription.cs#L20-L28) class, there is some check in constructor:

```cs
public RouteDescription(string name, string method, string path, Func<NancyContext, bool> condition)
{
	if (String.IsNullOrEmpty(method))
	{
		throw new ArgumentException("Method must be specified", method); // <-- pass null or empty method variable?
	}

	if (String.IsNullOrEmpty(path))
	{
		throw new ArgumentException("Path must be specified", method); // <-- pass method variable?
	}

	// ...
}
```

Are those method variable typo? Should it be a string `"method"` and `"path"` accordingly?

**Comment by khellang** [comment]
Yes. Those are typos. Want to fix 'em? :smile:

**Comment by lijunle** [comment]
@khellang could you please take a look on my PR #1941 ?
