### ISSUE TITLE
FluentValidation doesn't work on vnext

### ISSUE THREAD

**Issue by awec** [NancyFx/Nancy#1942]
Not sure what the policy is for reporting vnext bugs as it's currently not supported, but going to open this anyway. Maybe you want to create a label for vnext specific issues? 

When trying to use FluentValidation with Nancy on vnext an error is thrown when calling BindAndValidate<T>: 

'Nancy.Validation.ModelValidationException' occurred in Nancy.dll but was not handled in user code Additional information: No model validator factory could be located. Please ensure that you have an appropriate validation package installed, such as one of the Nancy.Validation packages.

I have Nancy.Validation.FluentValidation installed. I also have the appropriate registrations done in the Bootstrapper. You can see an example set of code in my Gist here: https://gist.github.com/awec/af94a240956b68e81e2b
 
Tried to debug this myself and couldn't figure it out cause I don't really know how Nancy works at that level. The modules window in Visual Studio suggests that Nancy.Validation.FluentValidation.dll is indeed loaded, but for some reason is not detected when the BindAndValidate method is called.

**Comment by awec** [comment]
Ok, I've spent ages looking at this.

The problem is that when Nancy takes a cache of the loaded assemblies from AppDomain.Current during bootstrapping it doesn't contain Nancy.Validation.FluentValidation.dll (because it has had no reason to be loaded yet). 

The DLL is eventually loaded after the TinyIOC Registrations occur.

However, AppDomainAssemblyTypeScanner will never load the correct types, because it works off the cached version of the assemblies that were loaded at bootstrap time. All the TypesOf<T> methods in this class work off that cache. 

We cannot rely on these dlls being loaded in time for them to be picked up by the AppDomainAssemblyTypeScanner on bootstrap.

**Comment by phillip-haydon** [comment]
Ran into this issue last night with SimpleValidator :( but at 2am I didn't start looking for a solution.

**Comment by awec** [comment]
I have a PR that fixes it. Basically we need to call UpdateTypes() on the Assembly scanner after all the IOC registrations have happened.

Not sure it's the most efficient or best long term fix, but it works (as far as I can see).

**Comment by grumpydev** [comment]
It should load it as part of the scan that picks up assemblies that reference nancy - is that not working or are you saying it runs too late?

**Comment by awec** [comment]
That method works off file paths and the .Location property of the assembly. Assemblies in vnext are loaded into memory, so the .Location property is always an empty string. 

So it doesn't find the dll we need.
