### ISSUE TITLE
Accept dash sign in routing segment default value.

### ISSUE THREAD

**Issue by lijunle** [NancyFx/Nancy#1951]
From `IsParameterized` extension method [source code](https://github.com/NancyFx/Nancy/blob/v1.2.0/src/Nancy/Extensions/StringExtensions.cs#L22), it accept `[A-Za-z0-9_]` as default value. But I think it should accept dash (`-`) too.

Basically, change the regex to the following should resolve this

```
{(?<name>[A-Za-z0-9_]*)(?:\?(?<default>[A-Za-z0-9_-]*))?}
```

**Comment by thecodejunkie** [comment]
@lijunle Would you care to send us a pull-request for this? Thanks

**Comment by lijunle** [comment]
Do I need to add one test case for this?

**Comment by thecodejunkie** [comment]
@lijunle From what I can tell, we do not have any test for `IsParameterized`, so we would not enforce it. Bonus points if you added test coverage for the extension method :smile_cat:

**Comment by lijunle** [comment]
However, I just resolve it without test. :dog:
