### ISSUE TITLE
Builds do not run bundle

### ISSUE THREAD

**Issue by tparnell8** [NancyFx/Nancy#1953]
I noticed that the builds on travis run `gem install albacore`, `gem install otherGems` instead you should run `bundle` this ensures that the gemfile is always correct, and if someone alters the bundle file as part of their PR, the requested gem(s) are pulled down as part of the build.

**Comment by tparnell8** [comment]
you will of course still have to `gem install bundle`

**Comment by thecodejunkie** [comment]
My brain might be a bit tired tonight, but could you elaborate a bit more on this? Thanks
