### ISSUE TITLE
Feature Request: Enchance IUserIdentity

### ISSUE THREAD

**Issue by ravensorb** [NancyFx/Nancy#1954]
Any thought to including a basic Dictionary to the IUserIdentity to allow providers to include a little extra detail if they want.  For example, it would be nice to be able to have a place to store an internal userID, lastLogon, or the users email address.  

I know that I can do this when I implement my own IUserIdentity -- the issue is I need to cast from IUserIdentity to my custom implementation if I do that which is not ideal.

**Comment by horsdal** [comment]
The user and identity stuff has gotten an overhaul for upcoming 2.0, where it uses `ClaimsPrincipal` and friends. You can see the 2.0 code in the v2 branch (https://github.com/NancyFx/Nancy/tree/v2) and the claims code in particular in PR #1820
Maybe that will help you (once 2.0 is out, that is)?

**Comment by dealproc** [comment]
In the meantime, @damianh offered an MSOwin set of extensions that could potentially be utilized, if you're willing to abandon using the default nancy bits for authentication/authorization.  It's been working pretty well thus far.

**Comment by ravensorb** [comment]
I like where 2.0 is going -- assuming that ClaimsIdentity will also be full supported in the pipeline.  That said, I still think it would be nice to allow for either defining a generic that could be used to store a user context (that was serializable) or provide a simple string based dictionary/hashtable concept.  Consider how the ASP.NET Authentication/Authorization pipeline has evolved to be more extensible in this area (note I am not prompted the ASP.NET auth pipeline as a whole due - just how it evolved to allow for a generic T to be used to store pertinent user properties)

**Comment by ravensorb** [comment]
Out of curiosity, how is v2 going?  I was looking at the branch and it seems like there have been no commits since march.

**Comment by damianh** [comment]
Replaces with `ClaimsPrincipal` via #1820
