### ISSUE TITLE
Compile Error When Converting Sample Code to VB

### ISSUE THREAD

**Issue by jbackroads** [NancyFx/Nancy#1958]
Hello,

My VB.NET web application uses Plivo to send out SMS messages. I am following their example in order to send an auto-reply to any inbound SMS message received by my Plivo numbers. 

Their sample code was in C#, which I converted to VB. All is well except for the DirectCast shown here:

    Dim output = resp.ToString()
    Dim res = DirectCast(output, Nancy.Response)

(complete code is included at the end of this post)

The error points to the "output" variable in the 2nd line: "Value of type 'String' cannot be converted to 'Nancy.Response'".

These lines in the original C# are:

    var output = resp.ToString();
    var res = (Nancy.Response)output;

I raised this issue with Plivo, since I was trying to implement their sample code, but they couldn't help and suggested I contact the Nancy team on GitHub. Please advise how to best resolve this. 

Thank you!
Julie

Here is the entire code:

	Imports Microsoft.VisualBasic
	Imports System
	Imports System.Collections.Generic
	Imports System.Reflection
	Imports RestSharp
	Imports Plivo.API
	Imports Nancy

	Public Class SMSautoreply
		Inherits NancyModule
		Public Sub New()
			Post("/reply_to_sms") = Function(x)
										Dim from_number As [String] = Request.Form("From")
										' Sender's phone number
										Dim to_number As [String] = Request.Form("To")
										' Receiver's phone number
										Dim text As [String] = Request.Form("Text")
										' The text which was received
										' Print the message
										Console.WriteLine("From : {0}, To : {1}, Text : {2}", from_number, to_number, text)

										Dim resp As New Plivo.XML.Response()

										' Generate Message XML
										' Sender's phone number
										' receiver's phone number
										resp.AddMessage("Thank you for your message", New Dictionary(Of String, String)() From { _
										 {"src", to_number}, _
										 {"dst", from_number} _
										})

										' Print the XML
										Console.WriteLine(resp.ToString())

										' Return the XML
										Dim output = resp.ToString()
										Dim res = DirectCast(output, Nancy.Response)
										res.ContentType = "text/xml"
										Return res

									End Function
		End Sub
	End Class

**Comment by xt0rted** [comment]
[Nancy.FormatterExtensions](https://github.com/NancyFx/Nancy/blob/188bc90450b10d263495d0a33c4cec98a1903937/src/Nancy/FormatterExtensions.cs#L26) has an extension method that will create a response object with your string value so you don't need the cast. There's also one that will return an object as xml using the built-in serializer.
```vb
Return Response.AsText(resp.ToString(), "text/xml")
```

**Comment by jbackroads** [comment]
Thank you!
 
I'll be able to try that tomorrow and will update the issue on GitHub at that time.
 
Julie


-----Original Message-----
