### ISSUE TITLE
Question: Difference between application and module pipelines?

### ISSUE THREAD

**Issue by devkhan** [NancyFx/Nancy#1965]
I have seen in the documentation, sometimes these two are referred distinctively. And also is there a difference in the Before/After hooks of these two pipelines?

**Comment by khellang** [comment]
Hey @devkhan! The [module-](https://github.com/NancyFx/Nancy/wiki/The-before-and-after-module-hooks) and [application pipelines](https://github.com/NancyFx/Nancy/wiki/The-Application-Before%2C-After-and-OnError-pipelines) are explained in detail in the wiki.

It's basically hooks which are executed before and after route execution on a global (application pipelines) and per-module basis. Here's an example:

If a route is resolved to a module called `FooModule`, the pipelines will be invoked as follows:

 - Application Before Pipeline
 - FooModule Before Pipeline
 - FooModule Route Handler
 - FooModule After Pipeline
 - Application After Pipeline

The difference between the before- and after pipelines is that in the before pipeline, you have the possibility to "short circuit" the request handling. I.e. you can return a response, which will the be returned directly to the user agent, without even invoking a potential route handler.

If you have questions like this another time, we'd :heart: it if you asked on StackOverflow. It makes it easier for others with the same questions to find them later :smile:

**Comment by devkhan** [comment]
Thanks. I will also post this as an answer wiki on StackOverflow. :bow:

**Comment by khellang** [comment]
If you don't mind, I'd like to answer it myself :wink:

**Comment by devkhan** [comment]
Okay, you can answer and I will remove mine and mark yours as accepted.
