### ISSUE TITLE
How to get array in query string.

### ISSUE THREAD

**Issue by ilmattodel93** [NancyFx/Nancy#1971]
Hi all, I have an array sent as query string to a get route, how can I have back that list/dictionary in nancy?
I tried using context.request.query["_wheres"] but it is always null and I figured out that context.request.query seems to do not parse correctly the query array.

This is my request params:
_columns:id,name,founder_id
_wheres[0][type]:basic
_wheres[0][column][0]:auth/profiles
_wheres[0][column][1]:id
_wheres[0][operator]:=
_wheres[0][value]:1
_wheres[0][boolean]:and
_limit:1
_with:founder
_randomCacheBuster:0.43095245701260865

URL: http://localhost:100/api/v1/auth/profiles?_with=founder&_wheres%5B0%5D%5Btype%5D=basic&_wheres%5B0%5D%5Bcolumn%5D=active&_wheres%5B0%5D%5Boperator%5D=%3D&_wheres%5B0%5D%5Bvalue%5D=true&_wheres%5B0%5D%5Bboolean%5D=and&_orders=id%2CDESC&_randomCacheBuster=0.05710214423015714

**Comment by khellang** [comment]
Would you mind asking this over at StackOverflow? :smile:

**Comment by ilmattodel93** [comment]
I wrote it here because using ToDictionary() on the query dynamic dyctionary it seems more a "missing feature" than a question.

**Comment by khellang** [comment]
Oh, sorry. Didn't see any information about anything API related, just a typical SO question... If you have questions about "missing features", I suggest you include them :smile:

**Comment by grumpydev** [comment]
There's no ToDictionary because it *is* a dictionary :) it implemements IDictionary<string, object>

**Comment by khellang** [comment]
I just tested the following and it works:

```csharp
public class TestModule : NancyModule
{
    public TestModule()
    {
        Get["/"] = args => Request.Query.@where;
    }
}
```

    curl "http://localhost:63677/?where=testing&where=testing2&where=testing3&where=testing4"

Output:

    testing,testing2,testing3,testing4

**Comment by ilmattodel93** [comment]
@grumpydev There is a ToDictionary defined here :) https://github.com/NancyFx/Nancy/blob/master/src/Nancy/DynamicDictionary.cs#L332
@khellang The problem is not with multiple values with the same key, but with different keys with the same name such as 

curl "http://localhost:63677/?where[0]=testing&where[1]=testing2&where[2]=testing3&where[3]=testing4"

should work.
In fact what I receive from the client is something like
curl "http://localhost:63677/?where[0][column]=column&where[0][operator]=in&where[0][value][0]=1&where[0][value][0]=2&where[0][value][0]=3" and seems not to work :/

**Comment by khellang** [comment]
I'm not sure why you expect that to work? I've never seen anything like that done before, so I'm pretty sure Nancy doesn't support it...

**Comment by ilmattodel93** [comment]
I expect it because it's supported and works in most frameworks or languages like PHP, express for nodeJS, etc...
That's also the standard way of how lists of inputs with the same name works.
I attach here some links to explain it

https://secure.php.net/http_build_query
http://stackoverflow.com/questions/6243051/how-to-pass-an-array-within-a-query-string?answertab=votes#tab-top

**Comment by khellang** [comment]
Those examples are for *generating* query strings, not servers parsing them. I don't think there's any *standard* around this. Do you have a RFC for it?

**Comment by ilmattodel93** [comment]
https://www.npmjs.com/package/qs
https://secure.php.net/parse_str
any other languages parses the query string provided before correctly, so I think that's something not supported by the language. I havent seen an rfc for it, but it's something popular, maybe an optional flag to activate that parser could be useful.

**Comment by khellang** [comment]
Uh... From that PHP page:

> It bears mentioning that the parse_str builtin does NOT process a query string in the CGI standard way, when it comes to duplicate fields.  If multiple fields of the same name exist in a query string, every other web processing language would read them into an array, but PHP silently overwrites them:
>
>    <?php
>      # silently fails to handle multiple values
>      parse_str('foo=1&foo=2&foo=3');
>
>    # the above produces:
>    $foo = array('foo' => '3');
>    ?>
>
> Instead, PHP uses a non-standards compliant practice of including brackets in fieldnames to achieve the same effect.
> 
>    <?php
>    # bizarre php-specific behavior
>    parse_str('foo[]=1&foo[]=2&foo[]=3');
>
>    # the above produces:
>    $foo = array('foo' => array('1', '2', '3') );
>    ?>

Those are separate functions/libraries specifically for doing this. The usage is way too narrow for Nancy to include it out of the box.
You're welcome to creating a library for doing this yourself and linking to it here, though :smile:

**Comment by ilmattodel93** [comment]
I see your point! Thanks for explanation! :D
