### ISSUE TITLE
Limited implementation of IUserIdentityResolver in Nancy.Authentication.Token 

### ISSUE THREAD

**Issue by mkamayd** [NancyFx/Nancy#1975]
It will be nice to have an easy way to add whatever I want to the IUserIdentity.
I will like to add a UserId for example. So that I can do at any module something like this:

```
this.RequiresAuthentication()
UserIdentity identity = (UserIdentity)this.Context.CurrentUser;
var userId = identiy.UserId;
```

using my 

```
 public class UserIdentity : IUserIdentity
    {
        public string UserName { get; set; }
        public IEnumerable<string> Claims { get; set; }
        public int UserId { get; set; }
    }
```

but with current implementation of  

```
public interface IUserIdentityResolver
    {
        IUserIdentity GetUser(string userName, IEnumerable<string> claims, NancyContext context);
    }
```

I don't see a way to provide the userId to GetUser. I will prefer something like a dictionary in order to provide the user Id. I tried to use the NancyContext.Items dictionary but does not work as get cleared after each request.

If there is in fact a way without having to rewrite the whole thing please point me in the right direction.

**Comment by fagnercarvalho** [comment]
+1
I got the same problem.
It would be nice if we could do that.

**Comment by mkamayd** [comment]
I have fork and done some changes; It's not finish yet. I will commit and push, next week, to my forked version.

**Comment by fagnercarvalho** [comment]
Nice! I can't wait for that! :+1:
