### ISSUE TITLE
Nancy not responding when run from a service

### ISSUE THREAD

**Issue by bluebaroncanada** [NancyFx/Nancy#1976]
Running Nancy in a Windows service.  All the Nancy modules and stuff are in a project I changed from a console to a library.
For now I'm running the service project as LocalSystem.  Adapting from the default code for the server, I have:

    protected override void OnStart(string[] args)
    {
        SetStatus(ServiceState.SERVICE_START_PENDING, 5000);

        eventLog.WriteEntry("Dust service starting");

        var uri =
            new Uri("http://localhost:8080");

        var config = new HostConfiguration() { UrlReservations = new UrlReservations() { CreateAutomatically = true, User = "LocalSystem" } };

        #if DEBUG
        StaticConfiguration.Caching.EnableRuntimeViewDiscovery = true;
        StaticConfiguration.Caching.EnableRuntimeViewUpdates = true;
        #endif

        using (var host = new NancyHost(uri, new Bootstrapper(), config))
        {
            host.Start();
        }
    }

Now I just converted over, so this has never actually worked.  I've also abutted the start() with extraneous logs.  They were getting printed, so I know host.Start(); is being executed.
however, port 8080 isn't open.  Could this have something to do with the urlreservations?  I would assume that an error would be thrown if that were the case.

This DID work when it was part of a standalone program.

P.S. I know it's dangerous to run as localsystem but for now we have to until we can figure a way to get regular Windows 7 users to be allowed to start a process.  This is just a temporary solution.

**Comment by bluebaroncanada** [comment]
P.S. A freenode channel would be super awesome

**Comment by arandjel-sarenac-devtech** [comment]
try with a https://jabbr.net/#/rooms/nancyfx

**Comment by bluebaroncanada** [comment]
Thanks!

**Comment by bluebaroncanada** [comment]
I hope this helps someone else.  https://github.com/dealproc had the answer.  Said he's had this issue before, too.  It's obviously not specific to running a service so it must be an answer to problems others are having and is probably already answered somewhere.

The problem is

    using (var host = new NancyHost(uri, new Bootstrapper(), config))

This is going to go out of the code block and call dispose on the NancyHost object.

**Comment by phillip-haydon** [comment]
That is correct, if you're using in a windows service you want to manage the creation / disposing of the host in the service start/stop, and not use a using block.

In a console app you want to add a read-key or similar after host.start() before the using block closes so it holds the host open and disposes after losing scope. OR you need to manage it yourself. :)

**Comment by bluebaroncanada** [comment]
Suggest that you might want to put an actual comment explaining that in the base code.

**Comment by arandjel-sarenac-devtech** [comment]
Try with this. 
`using (var host = new NancyHost(uri))
            {
                host.Start();
                Console.ReadKey();
            }`

ReadKey will block then your host remains active until focus console and type something.

**Comment by bluebaroncanada** [comment]
My project doesn't have a console.

**Comment by arandjel-sarenac-devtech** [comment]
Then this should give you idea.
`public partial class MyWinService : ServiceBase
    {
        private IDisposable host;

        public MyWinService()
        {
            InitializeComponent();
        }

        protected override void OnStart(string[] args)
        {
            var uri = new Uri("http://localhost:3579");
            this.host = new NancyHost(uri).Start();
        }

        protected override void OnStop()
        {
            this.host.Dispose();
        }
    }`

**Comment by bluebaroncanada** [comment]
Yup.  That's almost exactly how I did it.

**Comment by bluebaroncanada** [comment]
Using Topshelf.

**Comment by grumpydev** [comment]
Glad you got it sorted, but this is a standard .net "thing" rather than a Nancy issue - it's clear from your original code that the host will be disposed, and the behaviour around the host being disposed is also covered in detail in the documentation:

>NancyHost implements the IDisposable interface and will automatically call the Stop method on the host when the application is closing. If you need more control over when the host is started and stopped, simply create an instance, without the using-statement, and explicitly call Start() and Stop() as needed.

https://github.com/NancyFx/Nancy/wiki/Self-Hosting-Nancy

In an ideal world we would throw an object disposed exception if you tried to use the host after it was dipsosed, but as disposing it closes the actual listener there's no way for us to do that as the request will never get through.

**Comment by bluebaroncanada** [comment]
Oh I totally agree this is a standard .Net thing but I've found that others have had the same issue so a quick comment in the code might not hurt.

**Comment by grumpydev** [comment]
You could make it a pull request @bluebaroncanada ? :)

**Comment by oscarsan** [comment]
I think i'm having the same problem, but frankly i don't see what im doing wrong

I have a Service inherited by service base

    partial class LinkService : ServiceBase
    {
        public LinkService()
        {
            InitializeComponent();
        }
        public LinkService(RouterSystem router)
            : this()
        {
            MyRouter = router;
        }

        RouterSystem MyRouter;

        protected override void OnStart(string[] args)
        {
            MyRouter.Start();
        }
   }

On That Routersystem i have on Start.
        public void Start()
        {
            HostConfiguration config = new HostConfiguration();
            config.UrlReservations.CreateAutomatically = true;

            MyNancyHost = new NancyHost(new Uri("http://localhost:80/"), new JotlinkBootstrapper(marshaler, routerListener), config);
            MyNancyHost.Start();
    }

     public void Stop()
     {
         MyNancyHost.Stop();
     }


When i run this as a normal application it works perfect, but if i run this as service it will crash automatically without even get to this line, if I comment the lines before everything works ok.

**Comment by oscarsan** [comment]
Hi

After trying debugging this issue i notice that actually the exception was through inside the TinyIoC, the reason was I was using 

    public class SelfHostRootPathProvider : IRootPathProvider
    {
        public string GetRootPath()
        {
            return Directory.GetCurrentDirectory() + @"\www";
        }
    }

To determine the root path, and when running as a service the current directory is windows/system32 in windows. This happens even before start nancy. Totally my mistake.
