### ISSUE TITLE
No pdb in Nuget package

### ISSUE THREAD

**Issue by samizzo** [NancyFx/Nancy#1977]
I installed Nancy and the self-hosting module in Visual Studio 2013 using nuget, and I'm not seeing any PDB files. Has a borked package been uploaded? The Nancy version appears to be 1.2.0.

**Comment by phillip-haydon** [comment]
PDB files are never shipped with nuget packages... They exist only when you create a debug build because they contain debug information. Having these in a nuget package would cause performance issues with Nancy.

**Comment by thecodejunkie** [comment]
We host the symbols, for all out packages, over at https://www.symbolsource.org or you could do it yourself by using [dotPeek at a Symbol Server](http://hmemcpy.com/2014/07/how-to-debug-anything-with-visual-studio-and-jetbrains-dotpeek-v1-2/)

**Comment by samizzo** [comment]
The presence of PDB files doesn't affect performance. PDB files can exist for release builds as well. @thecodejunkie thanks, I didn't realise the PDB files for nuget packages are published there.
