### ISSUE TITLE
Nested validation using Data Annotations

### ISSUE THREAD

**Issue by fagnercarvalho** [NancyFx/Nancy#1980]
Hello!

It's possible to do nested object validation using Data Annotations along with the ```Validate``` method from Nancy?

I'm basically got two scenarios:
- A complex object
```
public class Person : IValidatableObject {

 // I want to validate this object as well.
 public Address Address { get; set; }

}
```

- A list

```
public class Person : IValidatableObject {

 // I want to validate every item from this list.
 public List<Job> Jobs { get; set; }

}
```

I see it's possible to call the ```Validate``` method for every object separately but is there a better solution?

**Comment by khellang** [comment]
If your object implements `IValidatableObject` and the nested objects does the same, why don't you just call the nested object's `Validate` method as part of the top-level one?

**Comment by fagnercarvalho** [comment]
It's a very good option but this can't be done automatically, right?

And changing the subject a little, for my list property: how I'm going to know what list item trigger a validation error? I will need to do a for and return the current index?

**Comment by khellang** [comment]
Nope. This is a limitation the data annotations validation and not Nancy per se. There are ways to do [recursive validation using data annotations](http://www.technofattie.com/2011/10/05/recursive-validation-using-dataannotations.html), but I don't think that's something we'll add support for in Nancy's validation abstraction. It basically boils down to what the underlying validation framework supports. Maybe FluentValidation supports it?
