### ISSUE TITLE
Nancy.Authentication.Token.Tokenizer produces different token formats on Windows and Unix

### ISSUE THREAD

**Issue by andypea** [NancyFx/Nancy#1982]
By default the Tokenizer uses an Environment.NewLine as an item delimiter.

```
private string itemDelimiter = Environment.NewLine;
```

This will be a "\r\n" when running on Windows, but just a "\n" when running on other systems:

https://msdn.microsoft.com/en-us/library/system.environment.newline(v=vs.110).aspx

Not a big issue, but it could lead to client-side token parsing breaking.

Thanks for the software!

**Comment by thecodejunkie** [comment]
Good catch! This should be changes. Will assign this to the next milestone and ping @jeffdoolittle as well =)

**Comment by jeffdoolittle** [comment]
Fortunately, this is only a default value and can be overridden, so I think the bug should be closed.

See the code available here: https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Authentication.Token/Tokenizer.cs#L204

:beers:

**Comment by andypea** [comment]
Sure. It's easy to work-around as long as one is aware of it.

**Comment by jeffdoolittle** [comment]
I recommend someone updates the wiki to describe the configurability options: https://github.com/NancyFx/Nancy/wiki/Token-Authentication

I'm not sure what other default value would be the most "correct" and am open to suggestions, I'm just not sure this qualifies as a "bug".

**Comment by andypea** [comment]
In the long term it would be a good idea for Nancy's token implementation to follow the JWT specification: http://self-issued.info/docs/draft-ietf-oauth-json-web-token.html.

In the meantime, so as not to break existing code, I would leave the current default separators as is and mention the issue in the documentation.

**Comment by jeffdoolittle** [comment]
My understanding is that the TokenAuth method is going to be discontinued in the Nancy project since things like JWT or other Token authorization mechanisms can/should be implemented as OWIN middleware.

**Comment by thecodejunkie** [comment]
@jeffdoolittle care to update the wiki as previously mentioned? Once that's been done then we can close this

**Comment by jeffdoolittle** [comment]
@thecodejunkie done: https://github.com/NancyFx/Nancy/wiki/Token-Authentication#sensible-defaults

**Comment by thecodejunkie** [comment]
@jeffdoolittle :+1:
