### ISSUE TITLE
Nancy approach to periodic server tasks?

### ISSUE THREAD

**Issue by VictorySquareAdmin** [NancyFx/Nancy#1983]
I'd like my server to preform a task once every second. I could throw something together with Action<> and Task<>, but I was wondering if there was a Nancy-preferred approach? Or, at the very least; is there anything I should watch out for when running my own threads alongside Nancy?

Thanks!

**Comment by phillip-haydon** [comment]
Nancy is a Web Framework like MVC. There is nothing built in to run tasks. 

Windows has a built in Scheduler. Create a console app and setup a schedule to execute it.
