### ISSUE TITLE
Request never completes if the awaited task is cancelled

### ISSUE THREAD

**Issue by nvivo** [NancyFx/Nancy#1989]
I'm having an issue where a task being awaited is cancelled, and the request never finishes. 

In this example, "/a" and "/b" finish correctly, "/c" hangs forever.

```cs
Get["a", true] = async (x, ct) =>
{
    await CompleteAfter1SecWith(c => c.SetResult(1));
    return "OK";
};

Get["b", true] = async (x, ct) =>
{
    await CompleteAfter1SecWith(c => c.SetException(new Exception("This was expected")));
    return "OK";
};

Get["c", true] = async (x, ct) =>
{
    await CompleteAfter1SecWith(c => c.SetCanceled());
    return "OK";
};
...
private Task CompleteAfter1SecWith(Action<TaskCompletionSource<object>> action)
{
    var cts = new CancellationTokenSource();
    var tcs = new TaskCompletionSource<object>();

    cts.Token.Register(() => action(tcs));

    cts.CancelAfter(1000);

    return tcs.Task;
}
```

**Comment by nvivo** [comment]
It looks like Nancy is swallowing the `TaskCancelledException` for some reason. Wrapping the await in a try-catch and retrhowing seems to fix it. 

```cs
try
{
    await CompleteAfter1SecWith(c => c.SetCanceled());
}
catch (TaskCanceledException ex)
{
    throw new Exception("Cancelled", ex);
}
```

Still, sounds like this shouldn't happen.

**Comment by thecodejunkie** [comment]
@grumpydev / @damianh what do you guys think?

**Comment by nvivo** [comment]
Hi. Any updates on this?

**Comment by thecodejunkie** [comment]
@nvivo let's ping @grumpydev and @damianh again ;)

Also, I will assign this to the 2.0 milestone as we will be doing some internal re-plumbing of the async stuff for that release

**Comment by damianh** [comment]
Looks like a bug. Yes, this should be looked at in v2.

**Comment by damianh** [comment]
I have recently cleaned up all the async/await internal stuff #2105 . I have [added a test](https://github.com/damianh/Nancy/commit/b8497f83b387db5a6c66d0a77643874f498f0aff) to a branch based on that. It seems the problem no longer is present. Can you verify this code please? For now am closing issue. Please let us know if this test code is wrong.

I'm reluctant to add this test to main code base though because the failure condition is a _hang_. This isn't good for CI etc.

**Comment by damianh** [comment]
Tweaked the assertion: https://github.com/damianh/Nancy/commit/e6d4715aa2076948efd335e648e020bcc4e48ab7

**Comment by grumpydev** [comment]
I know this is a bit of a blast from the past, but I actually found the issue with this today and fixed it in 1.4.5 :)

**Comment by tomtheisen** [comment]
@grumpydev:  I can't find any commits after July of last year, or any release notes for 1.4.5.  I'm doing an audit of dependencies, and this is raising a few red flags.  Can you shed any light on this?

**Comment by grumpydev** [comment]
@tomtheisen it's on the 1.x working branch:

https://github.com/NancyFx/Nancy/tree/1.x-WorkingBranch
