### ISSUE TITLE
tokenizer.Tokenize error test enviroment (Nancy.ErrorHandling.RouteExecutionEarlyExitException)

### ISSUE THREAD

**Issue by ronydj** [NancyFx/Nancy#1992]
Guys,

I have implemented the token Auth on my aplication. In production its workin fine.  But during unit tests I am getting this error:

An exception of type 'Nancy.ErrorHandling.RouteExecutionEarlyExitException' occurred in Nancy.Authentication.Token.dll but was not handled in user code

Stacktrace:

   em Nancy.Authentication.Token.Tokenizer.Tokenize(IUserIdentity userIdentity, NancyContext context)
   em EasyMidia.Service.Rest.AuthModule.<>c__DisplayClassd.<.ctor>b__7(Object x) na EasyMidia.Service.Rest\AuthModule.cs:line 34
   em CallSite.Target(Closure , CallSite , Func`2 , Object )
   em System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   em Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

My auth class is:

        public AuthModule(ITokenizer tokenizer)
            : base("/auth")
        {
            Post["/"] = x =>
            {
                var userName = (string)this.Request.Form.UserName;
                var password = (string)this.Request.Form.Password;

                var userIdentity = new EasyUserService().Authenticate(new EasyUser(userName,userName,password));

                if (userIdentity == null)
                {
                    return HttpStatusCode.Unauthorized;
                }

                var token = tokenizer.Tokenize(new BasicUser(){UserName = userName,Claims = new List<string>(){"admin"}}, Context);

                return new
                {
                    Token = token,
                };
            };

Its happening in this line:

var token = tokenizer.Tokenize(new BasicUser(){UserName = userName,Claims = new List<string>(){"admin"}}, Context);

My test block of code that is calling the auth token is:

var bootstrapper = new Bootstrapper();
var browser = new Browser(bootstrapper, defaults: to => to.Accept("application/json"));

            var token = browser.Post("/auth", with =>
            {
                with.HttpRequest();
                with.FormValue("username", "admin");
                with.FormValue("password", "passmd5");
            });

Do you have any idea what is causing this error ? Its being thrown only when I run the unit tests.

**Comment by ronydj** [comment]
I have found the problem. And a fix for it.

On the Tokenizer.cs class we have the method Tokenize:

 public string Tokenize(IUserIdentity userIdentity, NancyContext context)
        {
            var items = new List<string>
            {
                userIdentity.UserName,
                string.Join(this.claimsDelimiter, userIdentity.Claims),
                this.tokenStamp().Ticks.ToString(CultureInfo.InvariantCulture)
            };

            if (this.additionalItems != null)
            {
                foreach (var item in this.additionalItems.Select(additionalItem => additionalItem(context)))
                {
                    if (string.IsNullOrWhiteSpace(item))
                    {
                        throw new RouteExecutionEarlyExitException(new Response { StatusCode = HttpStatusCode.Unauthorized });
                    }
                    items.Add(item);
                }
            }

            var message = string.Join(this.itemDelimiter, items);
            var token = CreateToken(message);
            return token;
        }

The additionalItems list is being filled with the userAgent header. But when we are running using the Nancy Browser implementation, the userAgent is a empty string.
So one of the items is a empty string:

if (string.IsNullOrWhiteSpace(item))
                    {
                        throw new RouteExecutionEarlyExitException(new Response { StatusCode = HttpStatusCode.Unauthorized });
                    }

then the exception is thrown becacuse of the empty item.

My solution was to include the an user agent header when calling the auth request:

 var token = browser.Post("/auth", with =>
            {
                with.HttpRequest();
                with.Header("User-Agent", "Nancy Browser");
                with.FormValue("username", "admin");
                with.FormValue("password", "21232F297A57A5A743894A0E4A801FC3");
            });

**Comment by phillip-haydon** [comment]
This seems like a @jchannon issue to look at. I think.

**Comment by thecodejunkie** [comment]
ping @jchannon

**Comment by jchannon** [comment]
Huh? No idea how the tokeniser thing works. It was a PR from a community
member to out that in

**Comment by thecodejunkie** [comment]
Ah, sorry I was being stupid. The thing we need to do is to make sure that the `Browser` has a default user-agent set. Will take a look

Thanks @ronydj for reporting this and also reporting a work-around!

**Comment by thecodejunkie** [comment]
Submitted a pull-request to add a default user-agent when using `Nancy.Testing.Browser` #2017

**Comment by thecodejunkie** [comment]
Resolved by #2017
