### ISSUE TITLE
about helper in App_Code

### ISSUE THREAD

**Issue by billypon** [NancyFx/Nancy#1997]
I want use some helpers anywhere, so I put xxx.cshtml in App_Code.
But it didn't work with Nancy.
What could I do?

**Comment by xt0rted** [comment]
Support was started in #1373 but it was never merged.

**Comment by billypon** [comment]
@xt0rted OK, thanks! It's helpful

**Comment by billypon** [comment]
But when will it(#1373) be merged, it's very helpful.

**Comment by thecodejunkie** [comment]
Closing this as there is an open issue for it already (#1373)
