### ISSUE TITLE
Small issue with Intellisense & Razor

### ISSUE THREAD

**Issue by Infernno** [NancyFx/Nancy#1998]
Hey guys.
This maybe a stupid question, but i can't solve it.
I created a new project, added Nancy & Nancy.Hosting.Self & Nancy.ViewEngines.Razor from nuget to the project, and everything works, except intellisense:
![1](https://cloud.githubusercontent.com/assets/7915327/9157000/b5e5cf58-3f16-11e5-89a2-2a9d68d066bd.png)
![2](https://cloud.githubusercontent.com/assets/7915327/9157001/b695fbe4-3f16-11e5-8a66-fe17465dcced.png)
What i need to do to make intellisense work with Nancy's razor?
P.S. Visual Studio 2015 Community

**Comment by khellang** [comment]
Have you read (and followed) the [wiki entry](https://github.com/NancyFx/Nancy/wiki/Razor-View-Engine)?

**Comment by Infernno** [comment]
I guess i found the problem, adding @inherits Nancy.ViewEngines.Razor.NancyRazorViewBase to each view helped.

**Comment by khellang** [comment]
:+1:

**Comment by Infernno** [comment]
Okay, forgot one thing, things like Html.BeginForm are not supported?

**Comment by khellang** [comment]
A lot of the HtmlHelpers are MVC specific. I think BeginForm is one of them :disappointed:

**Comment by Infernno** [comment]
Sad :tired_face:
BTW, is there any documentation on how to use ```Nancy.Validation.DataAnnotations```? In order to check if model is valid

**Comment by khellang** [comment]
The docs on validation is rather poor, unfortunately. You might be able to get something out of the [validation sample](https://github.com/NancyFx/Nancy/tree/master/src/Nancy.Demo.Validation), though. It should basically be

 - Install **Nancy.Validation.DataAnnotations**
 - Add annotations to your model
 - Call Validate or BindAndValidate in your model

Also, if you have custom attributes, you need to provide a "bridge" into Nancy's own validation system. See [`OddLengthStringAttributeAdapter`](https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Demo.Validation/Models/OddLengthStringAttributeAdapter.cs).

**Comment by xt0rted** [comment]
The closest you'll get to mvc's helper methods is [Nancy.ViewEngines.Razor.HtmlHelpers](https://github.com/davidwhitney/Nancy.ViewEngines.Razor.HtmlHelpers). `BeginForm` isn't implemented yet and can't be without a bit of hacking because of how the view engine is setup. #1709 has more info on that.

If you're using .net 4.5+ you'll also probably need to install [Nancy.Validation.DataAnnotations.Extensions](https://github.com/xt0rted/Nancy.Validation.DataAnnotations.Extensions) which also has a sample project.

**Comment by Infernno** [comment]
Okay, thanks guys. I'll close this issue if you nobody is against :wink:
