### ISSUE TITLE
Create new unified configuration API

### ISSUE THREAD

**Issue by thecodejunkie** [NancyFx/Nancy#1999]
_THIS WILL BE A NANCY v2.x FEATURE ONLY DUE TO THE BREAKING CHANGES_

Overtime we have gotten a bit of fragmentation when it comes to configuring various parts of Nancy. We need to re-evaluate this and create a unified approach. I have created a [pull-request](
https://github.com/NancyFx/Nancy/pull/2003) with a design that we've talked about in the team.

The base for the new approach is a new method, on the bootstrapper, called [Configure()](https://github.com/NancyFx/Nancy/blob/nancy-configuration-feature/src/Nancy/Bootstrapper/NancyBootstrapperBase.cs#L316)

```c#
public virtual void Configure(INancyEnvironment environment)
{
}
```

The [INancyEnvironment](https://github.com/NancyFx/Nancy/blob/nancy-configuration-feature/src/Nancy/Configuration/INancyEnvironment.cs) instance, that is passed in, is essentially an `IReadOnlyDictionary<string, object>` with a couple of more methods added. In short it's a property bag, more or less. You can take a dependency on this interface wherever you want to read configuration values.

To provide a configuration API you simply create extension methods on `INancyEnvironment` which sticks a config (your own type, tailored to your needs), in environment.

Here is what it could look (just sample code) like when configuring Nancy diagnostics, using the new approach

```c#
public virtual void Configure(INancyEnvironment environment)
{
    environment.Diagnostics("password", "the/path/to/use");
}
```

The `Diagnostics` extension method could manufacture an instance of a class that looks something like this

```c#
public class DiagnosticsConfiguration
{
    public DiagnosticsConfiguration(string password, string path)
    {
        this.Password = password;
        this.Path = path;
    }

    public string Password { get; private set; }

    public string Path { get; private set; }
}
```

A very basic, immutable, object that contains the configuration value. To get the value back out you take a dependency on `INancyEnvironment` and use one of the `GetValue` extension methods.

```c#
var config = environment.GetValue<DiagnosticsConfiguration>();

// Do something with config.Password and config.Path
```

There are a couple of more bits such as
* [INancyEnvironmentFactory](https://github.com/NancyFx/Nancy/blob/nancy-configuration-feature/src/Nancy/Configuration/INancyEnvironmentFactory.cs) - Creates an `INancyEnvironment` instance
* [INancyEnvironmentConfigurator](https://github.com/NancyFx/Nancy/blob/nancy-configuration-feature/src/Nancy/Configuration/INancyEnvironmentConfigurator.cs) - Responsible for "pulling it all together" and creating the configured `INancyEnvironment` instance.
* [INancyEnvironmentExtensions](https://github.com/NancyFx/Nancy/blob/nancy-configuration-feature/src/Nancy/Configuration/INancyEnvironmentExtensions.cs) - Set of extension methods to make adding / retrieving values from the environment

If you want to have a look at the various default implementations, of the configuration interfaces, then have a look in the [Nancy.Configuration](https://github.com/NancyFx/Nancy/tree/nancy-configuration-feature/src/Nancy/Configuration) namespace

Once this is in place, we'll start replacing the various configuration approaches that are currently available (StaticConfiguration, XmlSettings, JsonSettings, NancyConventions, RazorConfiguration, DiagnosticsConfiugration, CryptographicConfiguration and so on). See #2000 for discussions on migration work

## Update 2015-08-15 - The `INancyDefaultConfigurationProvider` interface

Added the `INancyDefaultConfigurationProvider` interface. The interface is used to let Nancy know that you can provide default configurations for something. By providing a default configuration you can ensure that there will always be an instance, of your configuration object, in the `INancyEnvironment` even though the user has not explicitly provided a configuration.

```c#
/// <summary>
/// Defines the functionality for providing default configuration values to the <see cref="INancyEnvironment"/>.
/// </summary>
public interface INancyDefaultConfigurationProvider
{
    /// <summary>
    /// Gets the default configuration instance to register in the <see cref="INancyEnvironment"/>.
    /// </summary>
    /// <returns>The configuration instance</returns>
    object GetDefaultConfiguration();

    /// <summary>
    /// Gets the key that will be used to store the configuration object in the <see cref="INancyEnvironment"/>.
    /// </summary>
    /// <returns>A <see cref="string"/> containing the key.</returns>
    string Key { get; }
}
```

Nancy will scan for all `INancyDefaultConfigurationProvider` implementations and call the `GetDefaultConfiguration()`-method to get the default configuration instance. This will happen after the [Configure()](https://github.com/NancyFx/Nancy/blob/nancy-configuration-feature/src/Nancy/Bootstrapper/NancyBootstrapperBase.cs#L316) has been executed, and only configurations that have not been supplied by user code will be inserted into the environment. This all happens inside the [DefaultNancyEnvironmentConfigurator](https://github.com/NancyFx/Nancy/blob/nancy-configuration-feature/src/Nancy/Configuration/DefaultNancyEnvironmentConfigurator.cs#L37) (the default implementation of the `INancyEnvironmentConfigurator` interface)

The `DefaultNancyEnvironmentConfigurator` performs the following steps

1. Invokes the `Action<INancyEnvironment>` that is supplied by [NancyBootstrapperBase.Configure()](https://github.com/NancyFx/Nancy/blob/nancy-configuration-feature/src/Nancy/Bootstrapper/NancyBootstrapperBase.cs#L316)
2. Iterated over all `INancyDefaultConfigurationProvider` instances and, unless the returned type is already, registered in the environment it will register the default configuration.

This means that it will _never_ override user defined configurations, but it will ensure that all configurations, that should be present in the environment will be there even if the user has not explicitly configured it.

**Update 2015-11-09**

Added `string Key` property on `INancyDefaultConfigurationProvider` interface, to enable you to explicitly specify the key that should be used when storing a configuration object in the `INancyEnvironment`. Also added the abstract `NancyDefaultConfigurationProvider` class

```c#
/// <summary>
/// Default (abstract) implementation of <see cref="INancyDefaultConfigurationProvider" /> interface.
/// </summary>
/// <typeparam name="T">The type of the configuration object.</typeparam>
public abstract class NancyDefaultConfigurationProvider<T> : INancyDefaultConfigurationProvider
{
    /// <summary>
    /// Gets the default configuration instance to register in the <see cref="INancyEnvironment"/>.
    /// </summary>
    /// <returns>The configuration instance</returns>
    public abstract T GetDefaultConfiguration();

    /// <summary>
    /// Gets the default configuration instance to register in the <see cref="INancyEnvironment"/>.
    /// </summary>
    /// <returns>The configuration instance</returns>
    object INancyDefaultConfigurationProvider.GetDefaultConfiguration()
    {
        return this.GetDefaultConfiguration();
    }

    /// <summary>
    /// Gets the full type name of <typeparamref name="T"/>.
    /// </summary>
    /// <returns>A <see cref="string"/> containing the key.</returns>
    public virtual string Key
    {
        get { return typeof(T).FullName; }
    }
}
```

This can be used to make use of the default behavior of using `Type.FullName` as the key. The `Key`-property was made `virtual` in case you ever should need to customize the key generation.

## Update 2015-08-15 - The `ConfigurableBootstrapperConfigurator.Configure`-method

Provided a way to configure the `INancyEnvironment` using the `ConfigurableBootstrapper` for tests. 

Example of what this could look like

```c#
var bootstrapper = new ConfigurableBootstrapper(with =>
{
   with.Configure(env =>
   {
       env.Diagnostics(
           password: null,
           cryptographyConfiguration: this.cryptoConfig);
   });
});
```

## Update 2015-08-15 - The `DefaultConfigurationProvider` methods on `ConfigurableBootstrapperConfigurator` for testing

Also added various overloads of the `DefaultConfigurationProvider` (and `DefaultConfigurationProviders`) methods, on `ConfigurableBootstrapperConfigurator` , to help define which `INancyDefaultConfigurationProviders` instances that should be available during test execution

## Updated 2015-11-16 - The `INancyBootstrapper.GetEnvironment()` method

We updated the `INancyBoostrapper` interface to expose a new `GetEnvironment()` method to get the current configured `INancyEnvironment` instance. This method should _only_ be called after `Initialise()` have been called.

**Comment by thecodejunkie** [comment]
Just to give people and idea on how various kinds of configuration API's could look like. Here are three approaches to the diagnostics configuration. It is all going to come down to what you are configuring (required/optional values etc)

```c#
public void Configure(INancyEnvironment environment)
{
    environment.Diagnostics("password", "path");

    environment.Diagnostics(
        password: "Password",
        path: "some/path",
        requireSecureConnection: true);

    environment.Diagnostics(
        password: "Password",
        path: "some/path",
        options: with =>
        {
            with.RequireSecureConnection();
        });
}
```

**Comment by jchannon** [comment]
:eyes: :+1:

**Comment by thecodejunkie** [comment]
Updated initial post with information about the `INancyDefaultConfigurationProvider`-interface and the `ConfigurableBootstrapperConfigurator.Configure()`-method

ping @NancyFx/most-valued-minions @NancyFx/nancy-core-contributors
