### ISSUE TITLE
How add https support in ubuntu?

### ISSUE THREAD

**Issue by Radzhab** [NancyFx/Nancy#2005]
How add https support in ubuntu?

**Comment by jchannon** [comment]
Register a certificate and start your host up with https://

**Comment by Radzhab** [comment]
I understand it. https://coderead.wordpress.com/2014/08/07/enabling-ssl-for-self-hosted-nancy/ This tutorial work on WIndows. How make this operations on Ubuntu?

**Comment by thecodejunkie** [comment]
That's a question for an Ubuntu support forum. Unfortunately we are not able to provide support for configuring your environment. Sorry

**Comment by Radzhab** [comment]
please provide good documentation.

**Comment by damianh** [comment]
lol

**Comment by richorama** [comment]
why not terminate your SSL with a reverse proxy like nginx?

**Comment by Yantrio** [comment]
`httpcfg -add -port 443 -pvk yourstuff.pvk -cert yourstuff.crt` 
check that it was added with 
`httpcfg list`
then listen on https instead of http in your application.

**Comment by Radzhab** [comment]
Richard, i read you tutorial https://coderead.wordpress.com/2014/08/07/enabling-ssl-for-self-hosted-nancy/. How make its on Ubuntu?

**Comment by jchannon** [comment]
@Radzhab Look at what @Yantrio provided
