### ISSUE TITLE
AutoRegisterIgnoredAssemblies comment has bools wrong way around

### ISSUE THREAD

**Issue by samal84** [NancyFx/Nancy#2006]
Am I understanding it wrong or does DefaultNancyBootstrapper.AutoRegisterIgnoredAssemblies have the bools in the last sentence of the comment the wrong way around?

https://github.com/NancyFx/Nancy/blob/master/src/Nancy/DefaultNancyBootstrapper.cs#L39

/// Gets the assemblies to ignore when autoregistering the application container
/// Return true from the delegate to ignore that particular assembly, returning true
/// does not mean the assembly *will* be included, a false from another delegate will
/// take precedence.

Should be
/// Gets the assemblies to ignore when autoregistering the application container
/// Return true from the delegate to ignore that particular assembly, returning false
/// does not mean the assembly *will* be included, a true from another delegate will
/// take precedence.

**Comment by thecodejunkie** [comment]
Hey @samal84 you want to join the [contributors](http://nancyfx.org/contribs.html) by sending us a pull-request for this? =)

**Comment by samal84** [comment]
Ok first Github pull Request. Did I do it right?

https://github.com/NancyFx/Nancy/pull/2030
