### ISSUE TITLE
How get json from post request (question)

### ISSUE THREAD

**Issue by Radzhab** [NancyFx/Nancy#2009]
I have route 
```
Post["/"] = _ =>
            {
                 ...
            }
```
and with curl i send post request 
```curl -XPOST -H "Content-Type: application/json" http://localhost:7777/ -d '{"ok":true,"result":[{"update_id":698487365,"message":{"message_id":45,"from":{"id":10902074,"first_name":"Radzhab"},"chat":{"id":10902074,"first_name":"Radzhab"},"date":1439460132,"text":"asd"}}]}'```

How get this json in response?

**Comment by SlavaBobik** [comment]
@Radzhab  You can do than like:
```csharp
Post["/"] = _ =>
{
    var jsonString = this.Request.Body.AsString();
    return Response.AsJson(jsonString);
}
```

**Comment by Radzhab** [comment]
Спасибо)

**Comment by SlavaBobik** [comment]
@Radzhab  include this namespace `using Nancy.Extensions;`

**Comment by jchannon** [comment]
You can also use `<Bind>` to bind the payload to a class. See the wiki on ModelBinding
