### ISSUE TITLE
Cross platform RESTful Services

### ISSUE THREAD

**Issue by goldytech** [NancyFx/Nancy#2014]
Hello,
As per documentation Nancy supports both Windows and Linux. I want to develop the RESTful services which can be hosted on IIS on windows and Apache on Linux. Do I need to write anything specific in the code to make this work ?

I do understand deployment will differ.

Thanks

**Comment by khellang** [comment]
> Do I need to write anything specific in the code to make this work ?

Nope. Just make sure the solution builds/runs on both .NET and Mono. There might be some differences in file path handling etc.
