### ISSUE TITLE
NullReferenceException when accessing Contents of Response in AfterRequest pipeline item

### ISSUE THREAD

**Issue by ProfessionalNihilist** [NancyFx/Nancy#2016]
Hey,

From following https://github.com/NancyFx/Nancy/wiki/The-Application-Before%2C-After-and-OnError-pipelines I had written an AfterRequest pipeline item for our application using Nancy 0.22 which has broken upon upgrading to 1.0.

In my handler I am trying to copy the response stream into a buffer with `context.Response.Contents.Invoke(copy)` but I am getting a NullReferenceException since the `PreExecute` method on the new `MaterialisingResponse` has not been called. 

Is this a bug or is manually calling `PreExecute` prior to accessing the proper way to do this?

Regards

**Comment by thecodejunkie** [comment]
It's a bug, only happens in Debug-mode. We will supply a fix in 1.4

**Comment by thecodejunkie** [comment]
Fix applied in 1.3 :smile:
