### ISSUE TITLE
special characters response issue.

### ISSUE THREAD

**Issue by AlexDsp** [NancyFx/Nancy#2018]
var str= "✈️ From Osaka to Okinawa 🎌";
return new TextResponse(str,"text/html");

result
?? From Osaka to Okinawa ??

**Comment by khellang** [comment]
I just tested the following:

1. New console application
2. Install `Microsoft.Owin.SelfHost`
3. Install `Nancy.Owin`
4. Run the following code:

```csharp
public static class Program
{
    public static void Main(string[] args)
    {
        using (WebApp.Start("http://localhost:8080", app => app.UseNancy()))
        {
            Console.ReadLine();
        }
    }
}

public class Module : NancyModule
{
    public Module()
    {
        Get["/"] = _ => new TextResponse("✈️ From Osaka to Okinawa 🎌", "text/html");
    }
}
````

Sending a request to `http://localhost:8080/` results in the following response:

> HTTP/1.1 200 OK
> Transfer-Encoding: chunked
> Content-Type: text/html
> Server: Microsoft-HTTPAPI/2.0
> Date: Wed, 19 Aug 2015 23:48:03 GMT
> 
> ✈️ From Osaka to Okinawa 🎌

This is not a Nancy error or bug, it's probably the way your browser handles encoding or something.

**Comment by AlexDsp** [comment]
im running on Microsoft.Owin.Host.SystemWeb

**Comment by xt0rted** [comment]
I'm seeing the same results with the systemweb host. If I change the response to include `Encoding.Unicode` then it works in IE but not in FF or Chrome. If I put the text in a razor view it shows fine in all browsers.

Trying this as middleware produces the same results. After playing with it some I was finally able to get it to work in all browsers with this.
```c#
app.Use((ctx, next) =>
{
    ctx.Response.ContentType = "text/html; charset=utf-16";
    ctx.Response.Write(Encoding.Unicode.GetBytes("✈️ From Osaka to Okinawa 🎌"));

    return Task.FromResult(0);
});
```

This lead to trying it in Nancy again like so, which does work in all browsers.
```c#
Get["/test"] = _ => new TextResponse(
    "✈️ From Osaka to Okinawa 🎌",
    "text/html; charset=utf-16",
    Encoding.Unicode);
```

The key to getting it to work was manually including `; charset=utf-16`. If you use an encoding other than `UTF8` the `TextResponse` isn't appending that to the content type like it should be.

**Comment by xt0rted** [comment]
[According to the W3C](http://www.w3.org/International/O-HTTP-charset#charset)

> It is very important to always label Web documents explicitly. HTTP 1.1 says that the default charset is ISO-8859-1. But there are too many unlabeled documents in other encodings, so browsers use the reader's preferred encoding when there is no explicit charset parameter.

It looks like IE will try to auto select a character set when one isn't set, while the other browsers don't and stick to the default.

**Comment by khellang** [comment]
So there might actually be something we can do about this, then?

**Comment by xt0rted** [comment]
@khellang when using `TextResponse` we can append the charset if it's not UTF8. The supplied [encoding](https://github.com/NancyFx/Nancy/blob/22a3eeef3b5abfb48f06855ceda8d7434a2b4321/src/Nancy/Responses/TextResponse.cs#L32) is how we get the string's bytes but if you're not using UTF8 the browser won't know. This change would be similar to the [JsonResponse](https://github.com/NancyFx/Nancy/blob/22a3eeef3b5abfb48f06855ceda8d7434a2b4321/src/Nancy/Responses/JsonResponse.cs#L28) and [XmlResponse](https://github.com/NancyFx/Nancy/blob/22a3eeef3b5abfb48f06855ceda8d7434a2b4321/src/Nancy/Responses/XmlResponse.cs#L38).

**Comment by khellang** [comment]
:cool: Submitted #2020 :grin:

**Comment by jchannon** [comment]
nice work chaps

**Comment by AlexDsp** [comment]
i tried manually including charset=utf-16 / utf-8 , Encoding.Unicode /etc...
still not working for me....
in webapi there are no issues with this...it just works.
i'll dig in later today, i suspect the problem is buried somewhere deep.

**Comment by AlexDsp** [comment]
ok so i got xt0rteds code working after saving the document in utf-8 encoding (vs2013).
still didnt find a solution for json response;

im getting facebook posts from the graph api, those posts contain special chars, im trying to pass the json to the client;

     var postsJson = await GetPosts(token); // json from facebook
     var jObject = new JObject { { "posts", postsJson } }; // newtonsoft json JObject
     // in the debugger i see that all is good up until this point

     var responseContent = Encoding.Unicode.GetBytes(jObject.ToString());
     
      return new Response()
                      {
                          ContentType = "application/json; charset=utf-16",
                          StatusCode = HttpStatusCode.OK,
                          Contents = stream => stream.Write(responseContent, 0, responseContent.Length)
                      };


      //result
       message: "✈㼏 From Osaka to Okinawa 㼼㼿"
       ........................................................................................
       suppose to be "✈️ From Osaka to Okinawa 🎌"

i tried appending charset=utf-8 and Encoding.UTF8 , doesn't work.
