### ISSUE TITLE
UrlReservations.CreateAutomatically fails if port is 80

### ISSUE THREAD

**Issue by i255** [NancyFx/Nancy#2038]
If uri port is 80 Nancy tries to execute the following command:
`netsh http add urlacl url=http://+/ user=Everyone`
which produces:
Url reservation add failed, Error: 87
The parameter is incorrect.
netsh requires the port number. instead of just using `uri.ToString()` which omits the port number if port is 80 one should do something like this: `uri.Scheme + Uri.SchemeDelimiter + uri.Host + ":" + uri.Port + uri.PathAndQuery`

**Comment by khellang** [comment]
Thanks for reporting! :+1: I have a fix pending at #2039 :smile:
