### ISSUE TITLE
NullReferenceException when testing with context factory.

### ISSUE THREAD

**Issue by bsommardahl** [NancyFx/Nancy#2040]
My test code:

 ```
var browser = new Browser(
    with =>
        {
            with.Module<PatientSearchModule>();
            with.Dependencies(patientSearchService, mappingEngine);
            with.ContextFactory(new TestingContextFactory());
        });
browser.Get("/test", with => with.HttpRequest());
```

My test context factory is this:
```
public class TestingContextFactory : INancyContextFactory
    {
        public NancyContext Create(Request request)
        {
            return new NancyContext();
        }
    }
```

I am getting the following exception: 

```
Object reference not set to an instance of an object.
   at Nancy.Conventions.StaticContentConventionBuilder.<>c__DisplayClass2.<AddDirectory>b__0(NancyContext ctx, String root)
   at Nancy.DefaultStaticContentProvider.GetContent(NancyContext context)
   at Nancy.NancyEngine.HandleRequest(Request request, Func`2 preRequest, CancellationToken cancellationToken)
   at Nancy.NancyEngineExtensions.HandleRequest(INancyEngine nancyEngine, Request request, Func`2 preRequest)
   at Nancy.Testing.Browser.HandleRequest(String method, Url url, Action`1 browserContext)
   at Nancy.Testing.Browser.HandleRequest(String method, String path, Action`1 browserContext)
```

Now, I understand that I might be doing something wrong. But a null ref isn't be the error that will help me know what to do to fix my code.

**Comment by khellang** [comment]
The implementation is clearly breaking the "contract" of the `INancyContextFactory` which requires the implementation to fully populate the returned `NancyContext`, which includes at least passing it the given `request`. I agree that the API should've enforced it better though. Preferably through the `NancyContext` ctor.

Not passing the request yields a null reference at https://github.com/NancyFx/Nancy/blob/7bdfb4f22d8a717a461237342e9d39044c2fb5c4/src/Nancy/Conventions/StaticContentConventionBuilder.cs#L41

**Comment by khellang** [comment]
I'm really not sure what we can do to protect against this though. Yes, in this case we can force the request being set by adding it as a parameter to the `NancyContext` ctor (which would be a major breaking change at this point), but what this boils down to is simply *always* checking *everything*, for a null reference, *everywhere*. At the end of the day, it's impossible to "protect" the users from themselves :wink:

**Comment by bsommardahl** [comment]
@khellang What do you think of that patch?
