### ISSUE TITLE
Response.FromStream with Bson serializer

### ISSUE THREAD

**Issue by Furgas** [NancyFx/Nancy#2048]
I'm using Newtonsoft.Json to return some data in BSON format. Following code returns 0 bytes in response:
```C#
SomeClass someObject = new SomeClass();

MemoryStream ms = new MemoryStream();
BsonWriter writer = new BsonWriter(ms);
JsonSerializer serializer = new JsonSerializer();
serializer.Serialize(writer, someObject);

return Response.FromStream(ms, "application/bson");
```

I have to modify this code as below to return the serialized data:
```C#
SomeClass someObject = new SomeClass();

MemoryStream ms = new MemoryStream();
BsonWriter writer = new BsonWriter(ms);
JsonSerializer serializer = new JsonSerializer();
serializer.Serialize(writer, someObject);

ms.ToArray();
ms.Seek(0, SeekOrigin.Begin);

return Response.FromStream(ms, "application/bson");
```

Is this normal?

**Comment by khellang** [comment]
Just to be clear; is is the `ToArray` call, the `Seek` call or both that makes this work?

I bet it's the `Seek` call. `FromStream` probably expects a rewinded stream and starts reading from current position, while the `BsonWriter` leaves the stream position at the end.

**Comment by Furgas** [comment]
Yes, indeed `Seek` is enough for this to work. I guess, you're right, that `FromStream` is not rewinding a stream. Thanks.
