### ISSUE TITLE
Seeing performance issues with Forms Auth.

### ISSUE THREAD

**Issue by donnyv** [NancyFx/Nancy#2049]
I'm using Forms Auth. with my Nancyfx project and used JetBrain dotTrace tool to see where the hot spots are. These are the top spots.
![capture](https://cloud.githubusercontent.com/assets/2224189/9702227/8b91e734-5422-11e5-95e3-d4c9ebebe15c.JPG)

The Bcrypt library is mine but the others are used by Forms Auth.
Has anyone else seen issues with these? What am I doing wrong?

**Comment by grumpydev** [comment]
Enable forms auth on app startup, not request startup.

**Comment by donnyv** [comment]
Spot on! I set this up when I first put the project together a while ago. I wonder why I put it in request startup? Thank You!
