### ISSUE TITLE
Discrepancy between Nancy host and Nancy Testing

### ISSUE THREAD

**Issue by adamdriscoll** [NancyFx/Nancy#2060]
I have an issue where a particular URL works fine in my Nancy host during integration but not during unit testing. The problem is I have a URL that checks for the existence of a query parameter and returns a little more data depending on that URL. 

Something like this: 
"/api/application?icons=true"

This works fine when querying it from our REST client. While executing the same URL in our Nancy Testing project, the Browser returns a 404 when the query parameter is specified. If I hit the same URL without the query parameter at all, it returns fine. 

For example: 
"/api/application/"

Is there something that I'm missing that would be causing this? I can provide code samples if necessary, I'm just not really sure what is relevant to this issue. 

Currently, using the 1.1 version of Nancy and Nancy.Testing.

**Comment by thecodejunkie** [comment]
If you want to pass in a query-string value, during test, please use the `.Query` method on the Browser. 

Here's an example

```c#
    var response = browser.Get("/api/application", (with) => {
        with.HttpRequest();
        with.Query("icons", "true");
    });
```

**Comment by adamdriscoll** [comment]
Works great. Thanks!
