### ISSUE TITLE
ErrorPipeline + operator signature changed

### ISSUE THREAD

**Issue by TrueWill** [NancyFx/Nancy#2071]
Not an issue, but an undocumented breaking change in 1.3.0.

The ErrorPipeline + operator signature changed from 1.2.0. This made the versions not binary-compatible; NuGet packages referencing the old version must be upgraded in order to use them in a project that references 1.3.0.

See http://stackoverflow.com/questions/32980300/method-not-found-nancy-errorpipeline-nancy-errorpipeline-op-addition

**Comment by khellang** [comment]
Yeeah. That was kinda lazy. We kinda knew that was a breaking change, but it wasn't marked as such. I've added it to the [breaking changes overview](https://github.com/NancyFx/Nancy/wiki/Breaking-Changes).

**Comment by TrueWill** [comment]
Thank you very much! :+1:
