### ISSUE TITLE
Nancy does not respect probing path for the primary appdomain

### ISSUE THREAD

**Issue by bitbonk** [NancyFx/Nancy#2087]
It seems that Nancy's `AppDomainAssemblyTypeScanner` does not respect the probing path, if the current appdomain is the primary/default appdomain. I have put each of my modules into separate subfolders and added all these directories to the App.config:

```
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
  <publisherPolicy apply="yes" />
  <probing privatePath="Dir1;Dir2;Dir3" />
</assemblyBinding>
```

But the AppDomainAssemblyTypeScanner fails to find them, because `AppDomain.CurrentDomain.SetupInformation.PrivateBinPath` is always null for the primary/default appdomain.

**Comment by khellang** [comment]
Do you have any idea how to fix this?

**Comment by thecodejunkie** [comment]
That's strange, we have this code in the `AppdomainAssemblyTypeScanner` https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Bootstrapper/AppDomainAssemblyTypeScanner.cs#L332 

Can you run using symbols and debug that price of code and see what it does for your setup?

**Comment by bitbonk** [comment]
@thecodejunkie `AppDomain.CurrentDomain.SetupInformation.PrivateBinPath` is always null for the *primary/default* Appdomain. This seems to be [by design](http://stackoverflow.com/questions/33353420/appdomain-currentdomain-setupinformation-privatebinpath-is-null).

@khellang I have no idea how to fix this, hence [my question on stackoverflow](http://stackoverflow.com/questions/33353420/appdomain-currentdomain-setupinformation-privatebinpath-is-null). The only thing I can think of is what I describe in my question as a workaround.
