### ISSUE TITLE
Three-Pass Rendering Not Working, Nancy.ViewEngines.Spark, Shade

### ISSUE THREAD

**Issue by Yoshi325** [NancyFx/Nancy#2090]
When using the SparkViewEngine and the left offset syntax (shade) three pass rendering is not working.

Simplest recreation can be achieved by creating a New Project using the "Nancy with self host" template. Then adding the NuGet package: "Nancy.Viewengines.Spark". Then creating a three-pass rendering setup with shade files (eg: html, application, index). Two pass works as expected (eg: application, index). But three pass only renders the index template.

**Comment by RobertTheGrey** [comment]
Any chance you can supply your 3 shade files as an example in a gist with your expected outcome? I'm assuming the same happens when you use plain spark language as well instead of the shade parser?

**Comment by Yoshi325** [comment]
Yup. Here it is: https://gist.github.com/Yoshi325/be7e7c5960b879e72a45
Kept it as simple as possible.
The output with this example is:

```html
<img src="/Content/nancy-logo.png" alt="Nancy Logo"/><br/>This view was rendered using the SparkViewEngine
```

**Comment by RobertTheGrey** [comment]
Awesome - this should be enough for me to investigate, and although I had 3 pass rendering working in the past, I recall the view engine bits got a major overhaul and I'm not sure any work has gone into the Spark integration since then or if it's even still possible - but I'l take a look

**Comment by Yoshi325** [comment]
Thank You! I'm happy to contribute, but I'll need some pointers in the right direction. Nancy + Spark ends up being quite a large codebase to trek through.

Here is the spark gist: https://gist.github.com/Yoshi325/3d00c6362081bab4dddb

**Comment by Yoshi325** [comment]
Looks like even Two-Pass is broken in Nancy.Viewengines.Spark 1.3.0 at the moment.

**Comment by Yoshi325** [comment]
@RobertTheGrey Did you ever get a chance to investigate this?

**Comment by RobertTheGrey** [comment]
Hi @Yoshi325 - thanks for the reminder! I did get some way through looking at this, but then I got busy and then Christmas happened :), and then I forgot :-\

I'm away this weekend, but will hopefully get some time to look at it next week.

**Comment by RobertTheGrey** [comment]
FYI - been look at this the last few days - not forgotten again :) and hopefully making some progress. Will keep you posted if I fix it on the Spark side, otherwise it'll be a PR for the Nancy repo

**Comment by Yoshi325** [comment]
Glad to hear it! Thanks for taking the time.

**Comment by RobertTheGrey** [comment]
Sorry @Yoshi325 - Fortunately for me, but unfortunately for you my wife and I had a baby (came two weeks early) so I had to drop everything. I didn't forget about it, but I've not been able to pick up any code. I'm hoping (with enough sleep) to have time to take this on soon though

**Comment by RobertTheGrey** [comment]
Hi @Yoshi325 - using [your gist](https://gist.github.com/Yoshi325/3d00c6362081bab4dddb), I wrote the following unit test in the [SparkViewEngineFixture](https://github.com/NancyFx/Nancy/blob/master/test/Nancy.ViewEngines.Spark.Tests/SparkViewEngineFixture.cs):
```
        [Fact]
        public void Should_be_able_to_perform_three_pass_rendering()
        {
            //Given
            const string viewName = "ViewThatRendersThreePass";
            var viewLocationResult = this.GetThreePassViewLocation(viewName);

            //When
            this.FindViewAndRender(viewName);

            //Then
            System.Diagnostics.Debug.WriteLine(this.output);
            this.output.ShouldContainInOrder(
                "<html lang=\"en\">",
                "<head>",
                "<meta charset=\"utf-8\"/>",
                "<title>NancySelfHost2</title>",
                "<style>",
                "body { text-align: center; }",
                "</style>",
                "</head>",
                "<body>",
                "This goes before the view.",
                "<img src=\"http://cdn.example.com/mysite/nancy-logo.png\" alt=\"Nancy Logo\"/>",
                "<br/>",
                "This view was rendered using the SparkViewEngine",
                "</body>",
                "</html>");
        }
```

And the test passes. So from the tests it seems that 3-pass rendering works fine. Before I dig too much deeper, are you still experiencing this with `.spark` files?
