### ISSUE TITLE
Release 1.4 (and 1.4.1)

### ISSUE THREAD

**Issue by khellang** [NancyFx/Nancy#2091]
- [x] Update breaking changes - @khellang 
- [x] Update documentation (see [issues](https://github.com/NancyFx/Nancy/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Update+Documentation%22+milestone%3A1.4+)) - @khellang 
- [x] Fix Windsor CI build - @damianh 
- [x] Run Build Script of Doom™ - @grumpydev 
- [x] Close milestone  - @khellang
- [ ] Update CI version number - @khellang
- [x] Tweet - @thecodejunkie 
- [x] Blog about 1.X freeze and 2.0 plans - @thecodejunkie
- [x] Release 1.4.1 ;) 

:shipit:

Anything I forgot? @NancyFx/most-valued-minions

**Comment by grumpydev** [comment]
I started typing " Waiting on @damianh " and Chrome crashed.. hacker!

**Comment by damianh** [comment]
lol
