### ISSUE TITLE
Nancy frame work uri is not working when . (dot) at start /end of the url

### ISSUE THREAD

**Issue by Samba-Konduri** [NancyFx/Nancy#2095]
I'm using Nancy frame work,

my post route : 
data/customers/DemoCompany/entities/abc
data/customers/DemoCompany/entities/xyz
data/customers/DemoCompany/entities/yup
data/customers/DemoCompany/entities/.
in db its going to save 4 values  (abc,xyz,yup, . )

now im trying to perform  retrieve  (get operation )  
get data/customers/DemoCompany/entities/.

its return all list off records ?

i googled some thing about this issues, i came to know that file system rules will apply in url also 
they suggests some  code snip add into web config , but  that not working .

code i added in web.config ; 

```xml
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true" />    
    <httpErrors existingResponse="PassThrough"/>
    <handlers>
      <add name="Nancy" verb="*" type="Nancy.Hosting.Aspnet.NancyHttpRequestHandler, Nancy.Hosting.Aspnet" path="*" preCondition="integratedMode,runtimeVersionv4.0"/>
    </handlers>
   </system.webServer>
```

but this is not worked for me . 
 finally i came to know that nancy itself deleting the last .(dot) on url
could some one guide me how to resolve this ? 

@thecodejunkie  could please review this ?

**Comment by Samba-Konduri** [comment]
Does any once had a chance to review this ?

**Comment by jongleur1983** [comment]
I didn't get exactly what you mean when i first saw this issue.
Can you clarify e.g. by a small example? like:
+ a module with the routes you think are mixed up
+ a set of post request urls (and if required, content) to trigger
+ where you expect a different route than what is used

**Comment by thecodejunkie** [comment]
Please provide a sample that reproduces the problem, including a

- Bare bones module that declare the route(s) needed to reproduce it (all excess should be excluded)
- A URL that you call your route(s) with that displays the bug

Thanks

**Comment by thecodejunkie** [comment]
Looking close at this, this is not something we support out of the box with the existing routing implementation - sorry

The solution would be to redesign your resource URIs to be more ReSTful
