### ISSUE TITLE
static content under the /Content dir isn't served

### ISSUE THREAD

**Issue by gideondsouza** [NancyFx/Nancy#2100]
As stated in the title straight forward problem. 

Googling came up with this:
http://stackoverflow.com/questions/21123089/nancy-fails-to-find-static-content-in-custom-convention

Fortunately I can see a deleted post with my mod status and it said to ensure the individual files are set to "Copy To Output Directory" => "Copy always" and that seems to work. And yes, I'm not deploying but merely debugging. Without doing the step above files aren't served.

Could someone shed more light on this.

**Comment by damianh** [comment]
Yeah, you need to copy the content to the output directory (the path is relative to the binaries...). Is this an issue?

**Comment by thecodejunkie** [comment]
That's not us, that's how console applications work. The content folder wont be copied to the output directory if you don't set it, hence it won't be in the application path.
