### ISSUE TITLE
Add .DotSettings file

### ISSUE THREAD

**Issue by thecodejunkie** [NancyFx/Nancy#2106]
List of things (needs work)

- [x] `this.` qualifer
- [x] Using-statements in the deepest scope
- [x] No single-line `if`/`using` etc.
- [ ] One class/interface/stuff per file
- [x] No silly prefixes on variable names

More?

**Comment by khellang** [comment]
All of these are in place. Just in this repo only.

**Comment by xt0rted** [comment]
Since you're using TeamCity you can add a build step using the `Inspections (.NET)` runner which will check these rules during each build. I'm sure this would require some cleanup to have it fail the build though.

**Comment by khellang** [comment]
I think this was mostly covered by #2120?

**Comment by khellang** [comment]
> One class/interface/stuff per file

I'm not sure you can specify this using R#?

**Comment by xt0rted** [comment]
StyleCop has a rule for this which is [SA1402](http://www.stylecop.com/docs/SA1402.html) `FileMayOnlyContainASingleClass`, and there's also [SA1403](http://www.stylecop.com/docs/SA1403.html) `FileMayOnlyContainASingleNamespace` that goes with it. I doubt there's an easy way to add this to the local build process though.

**Comment by khellang** [comment]
There's always [StyleCop.MSBuild](https://www.nuget.org/packages/StyleCop.MSBuild/), but I doubt how much longer that holds up when it comes to the project system. Besides, we have @thecodejunkie :cop: :oncoming_police_car:  :wink:
