### ISSUE TITLE
Stateless Authentication - Swallows User Validator Exceptions

### ISSUE THREAD

**Issue by JoaoRXFernandes** [NancyFx/Nancy#2112]
Hi,

I'm having intermittent exceptions from the user validator and would have expected those to have bubbled through the pipeline to the internal server error handler but instead the exceptions are swallowed and the request ends up on the unauthorised handler as if everything is fine but authorisation failed.

I could be missing something so, is that the intended behaviour? 

Thanks,

Joao

**Comment by khellang** [comment]
Yeah, I have no idea why it's this way. It's all wrapped in a try catch [here](https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Authentication.Stateless/StatelessAuthentication.cs#L77-L85).

It looks like this landed as part of #674. @bsommardahl, time to drag out the time machine and ask 2012 yourself about this?

@JoaoRXFernandes If you want to send a pull request, we'd :heart: to take a look at it!

**Comment by bsommardahl** [comment]
@khellang I'll happily take a look when I get to the office.

**Comment by khellang** [comment]
:+1:

**Comment by JoaoRXFernandes** [comment]
Hey @bsommardahl, 

You had a chance to look into this issue? I'm happy to try and figure it out if you're overrun with other stuff.

Let me know.

**Comment by khellang** [comment]
Just sent a PR: #2173 :smile:

**Comment by bsommardahl** [comment]
Thanks guys. Yes, I got covered up with other things. It's still on my todo
list. Hopefully Kristian's PR solves it.
On Wed, Dec 23, 2015 at 3:50 AM Kristian Hellang <notifications@github.com>
wrote:

> Just sent a PR: #2173 <https://github.com/NancyFx/Nancy/pull/2173> [image:
> :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NancyFx/Nancy/issues/2112#issuecomment-166849696>.
>
-- 
*Byron Sommardahl*
CTO, Co-Owner
Acklen Avenue | www.acklenavenue.com | 615-669-8239
632 Fogg Street Suite 8, Nashville, TN 37212

Acklen Avenue is a custom software development company committed
to creating quality software that people love to use.

**Comment by JoaoRXFernandes** [comment]
Thanks for this, good stuff!

**Comment by nntarasov** [comment]
Hello there, it seems that ver. 1.4.1 - latest 1.x in nuget doesn't contain this fix
