### ISSUE TITLE
Nancy 1.4.1 memory leak

### ISSUE THREAD

**Issue by cusnirati** [NancyFx/Nancy#2113]
While testing for high-load, I discovered a memory leak issue directly linked to either Nancy or Nancy.Hosting.Self .
Downgrading to the 1.2.0 version solves this.
I uploaded a small demo for this : https://github.com/cusnirati/Nancy1.4.1MemoryLeakDemo

I tested this using JMeter, the project for repeating my steps is inside the solution linked above.

![screenshot 2015-11-15 22 28 26](https://cloud.githubusercontent.com/assets/10377229/11171623/ab90f5a0-8bec-11e5-9856-9bdeb8ddd7f3.png)
![screenshot 2015-11-15 22 29 04](https://cloud.githubusercontent.com/assets/10377229/11171622/ab901bd0-8bec-11e5-87ee-fe9d513c53dd.png)
![screenshot 2015-11-15 22 29 41](https://cloud.githubusercontent.com/assets/10377229/11171621/ab9007f8-8bec-11e5-9e2a-e94e9589d364.png)
![screenshot 2015-11-15 22 30 13](https://cloud.githubusercontent.com/assets/10377229/11171620/ab8eaffc-8bec-11e5-82c4-6d8bd6eefe47.png)
![screenshot 2015-11-15 22 30 52](https://cloud.githubusercontent.com/assets/10377229/11171624/ab9151e4-8bec-11e5-9b1c-2f050c5ea581.png)

**Comment by khellang** [comment]
It would be nice to narrow down the version even more. Are you seeing the same on 1.3?

**Comment by cusnirati** [comment]
For 1.3.0 everything looks good, no leaks.
Let me check for the 1.4.1.
I just mentioned the 1.2.0 because that was my previous working version.

**Comment by khellang** [comment]
OK, I've identified the regressing commit; https://github.com/NancyFx/Nancy/commit/4aeaf318e9710f9a0c3ac00befb35ee109ec82a2.

It introduced the `CancellationTokenSource.CreateLinkedTokenSource` call which allocates per request, without disposing it afterwards.

![image](https://cloud.githubusercontent.com/assets/582487/11171758/8abc1b64-8bf8-11e5-8218-ed7e379d0f88.png)

![image](https://cloud.githubusercontent.com/assets/582487/11171766/a9337f1a-8bf8-11e5-845d-64bf69e91e63.png)

I'll send a PR for it. Thanks for filing this! :+1:

**Comment by cusnirati** [comment]
No problem :)

**Comment by khellang** [comment]
@cusnirati We've now shipped 1.4.2. Would you mind updating and letting us know if things look better?

**Comment by cusnirati** [comment]
I confirm, the issue is fixed.

**Comment by khellang** [comment]
Thanks for following up! :+1:

**Comment by fastatech** [comment]
Hi, 
I am not sure that the issue is fixed. I have installed version 1.4.3 from Nuget (but somehow the actual version referenced in project is 1.4.2 so maybe here is the problem) but the leak is still there. My process with Nancy grew up over the day up to 1GB of memory. Only thing I do is calling one GET(passing some parameters) route which returns string "success"  from around 80 hosts. That is my real and only traffic on my server (I am just gathering data from the hosts).
Downgrading to 1.3.0 fixed the problem and the memory is around 115MB now. Please can you verify that you pushed correct package version to Nuget and the leak is really fixed. It seems strange to me. I can profile it for you if you want but I am bit new into this. I am running it on Ubuntu server with Mono, only in console. So if you tell me how to profile it I can do it.
Thanks,
Jan

**Comment by khellang** [comment]
@fastatech We've had several people confirm that the issue is fixed, including @cusnirati, in this thread. It could be something else, though. I'd like you to make sure you're actually running with 1.4.3 first...

**Comment by fastatech** [comment]
@khellang I have upgraded to the latest version (1.4.3) using Nuget manager but the version of the referenced Nancy.dll still says 1.4.2. Is this expected?
Please see this screenshot: http://snag.gy/CyLHL.jpg

**Comment by khellang** [comment]
@fastatech Hmm. Yes, looks like we forgot to bump the `AssemblyVersion` for the 1.4.3 release. Sorry about that :disappointed: 

If you check the properties for the assembly, you should see the "product version" is correct:

![image](https://cloud.githubusercontent.com/assets/582487/12263342/897f98e4-b92e-11e5-9097-afe45f4dea85.png)

**Comment by fastatech** [comment]
No worries. So you are saying if I reference product version 1.4.3 (file version 1.4.2.0) the leak is no longer there and I should look for something else? I will try it again and investigate it. I just dont know how to profile Nancyfx on mono in console mode :/

**Comment by khellang** [comment]
Yep. The leak (in this issue) should be fixed in that version. If you still see a memory leak, it must be something else... :disappointed:

**Comment by yzhou88** [comment]
I afraid the leak is still serious!
I am using Nancy 1.4.3.

**Comment by thecodejunkie** [comment]
@yzhou88 the leak, that was discussed in here, has been fixed, profiles and verified to have been fixed. If you think you have a memory leak, please file a _new_ issue and provide _as much detail as you possibly can_ and preferably a sample app that reproduces the bug. Make sure you are not causing the leak yourself by allocating unmanaged resources etc. but failing to properly release them. You can use the [5 day trial of DotMemory](https://www.jetbrains.com/dotmemory/) to profile your application and provide some better insight in your bug report. 

Thanks
