### ISSUE TITLE
How response image?

### ISSUE THREAD

**Issue by Radzhab** [NancyFx/Nancy#2118]
Subj. I found this gist, but i dont understand how use it.
https://gist.github.com/grumpydev/4605541

**Comment by khellang** [comment]
@Radzhab That *is* a working project. Just put those files into your project and it should work.

**Comment by phillip-haydon** [comment]
I think he needs to explain what hes trying to do. Streaming files out is already supported out of the box and requires no additional files.

**Comment by Radzhab** [comment]
I want simply return url to one image in my server.

**Comment by phillip-haydon** [comment]
To a static file, in a folder...

i.e you have a image in:

/site/images/bananas/yellow-banana.jpg

and you want to navigate to that and return it?

Or do you want to return an image from the database via a url?

Can you please explain what you are trying to achieve.

**Comment by Radzhab** [comment]
Phillip. I have two image. online and offline.png
![image](https://cloud.githubusercontent.com/assets/2556411/11245753/5a4afdc2-8e25-11e5-8b61-ec4932f0950b.png)

![image](https://cloud.githubusercontent.com/assets/2556411/11245876/1176f618-8e26-11e5-8504-138d04d2a52d.png)

**Comment by Radzhab** [comment]
I return empty data. in html source i see ```localhost:8888/online.png` but link is dead

**Comment by Radzhab** [comment]
Ну же мужики. Помогите

**Comment by thecodejunkie** [comment]
This should provide you with all the information you need https://github.com/NancyFx/Nancy/wiki/Managing-static-content
