### ISSUE TITLE
_method in form request is case sensative

### ISSUE THREAD

**Issue by alnya** [NancyFx/Nancy#2119]
Version 1.1
It appears that the ParseFormData() in the Request which reads the _method value from submitted form data is case sensitive. Lower case methods cause a 405 error to be thrown in our application.

The following call throws a 405
Example:
POST http://localhost:8080/route
Body:
_method=post

The following is handled by the route
Example:
POST http://localhost:8080/route
Body:
_method=POST

**Comment by zonal-andrewp** [comment]
This isn't the http method, this is to do with the _method body attribute, which is not covered by RFC7231. Handling lowercase _method values would allow for improved compatibility with other frameworks which do not follow http convention (see rails for a good example).

**Comment by khellang** [comment]
@zonal-andrewp We :heart: pull requests :wink:
