### ISSUE TITLE
Nancy Engine Memory Leaks 

### ISSUE THREAD

**Issue by woodywu** [NancyFx/Nancy#2135]
Hi All,

After running Nancy for few days, I got a memory leak issue. Here is what I get from CLR Profile. 

![clrprofile](https://cloud.githubusercontent.com/assets/3216210/11385977/ad3c8284-9358-11e5-830a-f60ef57bcaca.png)

These objects all lived to Gen2.

 I think the issue have some relationship with this one. http://stackoverflow.com/questions/9717592/async-and-cancellationtokens-cancellationtokensource-memory-issue. But I am not very sure. 

Please give me a help. 

Thanks!

-- .Net Framework 4.0, Nancy 1.4.1, Nancy.Hosting.Self 1.4.1

**Comment by xt0rted** [comment]
This should be resolved in v1.4.2 as per #2113

**Comment by woodywu** [comment]
That's great. Thank you very much!
