### ISSUE TITLE
Display a list of a model in a razor view using NancyFx

### ISSUE THREAD

**Issue by prakschoudhary** [NancyFx/Nancy#2137]
I'm having trouble just displaying a List<some_type> with NancyFx. The issue seems to be something pretty basic I'm missing or perhaps the framework has changed from the examples?

My Module looks like this:

	public IndexModule()
	{
		Get["/"] = parameters =>
		{
			dynamic d = new BlogPost();
			return View["index", d];
		};
		Post["/"] = paramters =>
		{
			IEnumerable<BlogPost> result = new List<BlogPost>()
			{
			   new BlogPost { Id = 3 },
			   new BlogPost { Id = 5 }
			};
			return View["index", result];
		};
	}

My cshtml:

	{
			 @foreach (var item in Model) 
			 {
					  <tbody>
							<tr>
								<td>
									@item.Id
								</td>
							</tr>
					  </tbody>
			 }
	}

Inside the .cshtml I tried each separately, they didn't work:
	@inherits Nancy.ViewEngines.Razor.NancyRazorViewBase<NancyApplication.Objects.BlogPost>
	@model System.Collections.Generic.IEnumerable<NancyApplication.Objects.BlogPost>

Oddly I don't get errors! I Just get a blank page with no html generated at all!

**Comment by khellang** [comment]
```csharp
Get["/"] = parameters =>
{
    dynamic d = new BlogPost();
    return View["index", d];
};
```

If your view is expecting an `IEnumerable<BlogPost>`, why are you passing a single `BlogPost`? Also, it that your entire .cshtml? It looks really weird and definitely isn't valid HTML.

> Inside the .cshtml I tried each separately, they didn't work:
> `@inherits Nancy.ViewEngines.Razor.NancyRazorViewBase`
> `@model System.Collections.Generic.IEnumerable`

I think both of those should have generic parameters, like `IEnumerable<BlogPost>` or `NancyRazorViewBase<IEnumerable<BlogPost>>`.

I'm not very familiar with Razor and all its quirks, but I suggest you read the documentation; https://github.com/NancyFx/Nancy/wiki/Razor-View-Engine

There's also quite a bit of good information on StackOverflow; http://stackoverflow.com/questions/tagged/nancy+razor

**Comment by khellang** [comment]
Update; I see you've already posted on StackOverflow (http://stackoverflow.com/questions/33993692/display-a-list-of-a-model-in-a-razor-view-using-nancyfx). I'm closing this issue and we'll see if someone can answer there. It's a much better place for support cases like this :smile:
