### ISSUE TITLE
CancellationToken Disposed before async request is complete

### ISSUE THREAD

**Issue by jeffthiele-iq** [NancyFx/Nancy#2141]
After updating to 1.4.2, I started getting `ObjectDisposedException: The CancellationTokenSource has been disposed.` when calling async methods using the `CancellationToken` provided by Nancy.  In my case it was EntityFramework methods, but I believe it would happen with any async methods.

The error does not exist in 1.4.1, and I think I tracked it down to the changes in pull request #2114.  It might be because the `lifeCycleTask` task isn't allowed to complete before the the token is disposed.

**Comment by khellang** [comment]
> The error does not exist in 1.4.1

That's because the CTS wasn't disposed *at all*, so we had a nice 40 byte memory leak per request :stuck_out_tongue:

I'll take a look at it. @damianh, feel free to beat me to it :wink:

**Comment by khellang** [comment]
@jeffthiele-iq Thanks for filing and digging into this, BTW! :+1:

**Comment by jeffthiele-iq** [comment]
Here's a test module which recreates the issue with only file access.  The test file is just the text for War and Peace to slow down the file read enough that the token gets disposed part-way through.
```
using System;
using System.IO;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using Nancy;

namespace NancyAsyncTesting
{
	public class TestModule : NancyModule
	{
		public TestModule()
		{
			Get["/test", true] = TokenTest;
		}

		private async Task<dynamic> TokenTest(dynamic o, CancellationToken cancellationToken)
		{
			using (var memoryStream = new MemoryStream())
			using (var dataFile = new FileStream(Path.Combine("C:/code", "TestFile.txt"), FileMode.Open, FileAccess.Read, FileShare.Read, 4096, true))
			{
				await dataFile.CopyToAsync(memoryStream, 4096, cancellationToken);
			}

			return "test";
		}
	}
}
```

**Comment by damianh** [comment]
Fixed via #2150

**Comment by damianh** [comment]
Personal note: will need to reimplement on the async branch

**Comment by khellang** [comment]
Version 1.4.3 was just pushed to [NuGet](https://www.nuget.org/packages/Nancy/1.4.3).
