### ISSUE TITLE
NancyBootstrapperBase.cs Register Modules twice in one Method

### ISSUE THREAD

**Issue by Hell0wor1d** [NancyFx/Nancy#2142]
Hi There,
I just found in this code file https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Bootstrapper/NancyBootstrapperBase.cs

In line 265 and 277.
There are two lines of the same code to register Module.
```
this.RegisterModules(this.ApplicationContainer, this.Modules);
this.RegisterInstances(this.ApplicationContainer, instanceRegistrations);
this.RegisterRegistrationTasks(this.GetRegistrationTasks());

var environment = this.GetEnvironmentConfigurator().ConfigureEnvironment(this.Configure);
this.RegisterNancyEnvironment(this.ApplicationContainer, environment);

foreach (var applicationStartupTask in this.GetApplicationStartupTasks().ToList())
{
      applicationStartupTask.Initialize(this.ApplicationPipelines);
 }

this.RegisterModules(this.ApplicationContainer, this.Modules);
```
I confused and want to know if this is an input error or not?

Thanks a lot.

**Comment by khellang** [comment]
Good catch! It seems @thecodejunkie added the second registration in https://github.com/NancyFx/Nancy/commit/75704d6377c6c90ac9981bc9b32d10341207976a. I wonder why... It also seems the indentions is off! :scream: :cop: :oncoming_police_car:

**Comment by thecodejunkie** [comment]
@Hell0wor1d why was this closed?

**Comment by Hell0wor1d** [comment]
@thecodejunkie Sorry, I think that has been fixed. Just reopened.

**Comment by thecodejunkie** [comment]
Nope it's still in there and it looks like it's the artefact from a bad merge resolution. I will take a closer look, submit a pull-request and then proceed to close this issue once it's been resolved

**Comment by dorvan** [comment]
This and other initializion parts seems are the root of problem of a nancyfx applications hangs and tcp allocation deadlock using owin + https 

the the doubled trhead it's initialized,seems, the application answer, hangs up after firsts successfull answers. 

there is a couious thread multiplexy by nancy related code after the deadlock of the certificate handshake stream, this can be cused by a initialization problem of nancyfx stack or due memory leaks on thread allocation or forking..

**Comment by khellang** [comment]
@dorvan Wat? I'm not sure I understood much of that, but could #2113 or #2141 be related? This initialization has nothing to do with threading (or the request pipeline at all), it's just registering modules in the container. I suggest you file a separate issue with a bit more (clearer) information :smile:
