### ISSUE TITLE
Is there a way to dynamically register module with Nancy?

### ISSUE THREAD

**Issue by Hell0wor1d** [NancyFx/Nancy#2143]
Hello,

I am going to dynamically register a module via manually loading assembly( *.dll ).  Any ideas? 

Big Thanks.

**Comment by Hell0wor1d** [comment]
@khellang Hello, Any ideas? Thanks.

**Comment by khellang** [comment]
You can override the `Modules` property in the bootstrapper and return a list of `ModuleRegistration`. The default implementation looks like this; https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Bootstrapper/NancyBootstrapperBase.cs#L107-L121.

**Comment by Hell0wor1d** [comment]
@khellang Thanks for your information. Unfortunately, this is not what I really want.  By your way, We can customize Modules List; Howerver,  It need to reboot NancyHost everytime when you want to register a new module at runtime. What I want to do is to reflect a dll dynamically and register the module to NancyHost at runtime. In fact, is to achieve NancyModule hot-plugging. Any Ideas? Thanks!

**Comment by khellang** [comment]
Nope. This is not possible. Nancy scans for modules and registers them in the container once, at startup. This is because of caching of route handlers etc.

**Comment by Hell0wor1d** [comment]
@khellang  How about if we create multiple NancyHost instance or Mutitiple Process to handle NancyModule hot-plugging. Eh, This is not a good way.  Anyway, thank you for your prompt reply. Otherwise, maybe I'll have to debug & research your source code all night. :D

**Comment by grumpydev** [comment]
The only way I can think of is to run self hosted and whenever you have a new DLL to load you kill the host, load the DLL, then spin it back up again - you will also need to dispose the bootstrapper and create a new instance of it each time.

**Comment by Hell0wor1d** [comment]
@grumpydev If user want to upload dll via web page...

I am going to implement a system container(platform)  based on Nancy ( It is a little similar to docker design). Such as cms/media/blog/ums/ecommerce etc. as plugin package, and backend portal/System Core as bundle.

Thank you for your updates.

**Comment by Hell0wor1d** [comment]
@khellang @grumpydev   Hi Guys,  Nancy support module hot-plugging is possilbe, I just make a small-changes of Nancy. It works well. :D  If you are interested, we can discuss together. I have to go to bed, now it is half past three in the morning. :D

**Comment by brgrz** [comment]
@Hell0wor1d How did you do it? Why not sharing it with the community? PR or a gist maybe?

**Comment by Hell0wor1d** [comment]
@brgrz Just wrote a post for you. Thx. [Make the Nancy Support Hot-plugging]( https://kev7n.com/2016/05/03/make-the-nancy-framework-support-hot-plugging/)

**Comment by brgrz** [comment]
Thanks, great job.

**Comment by JHorvath-MaxetaTech** [comment]
I understand this issue is closed, but what are the chances it will find it's way into the official build?

**Comment by Franki1986** [comment]
Sorry, but I think this is not up to date anymore.. Is there currently a way for registrating only specific modules by code??
