### ISSUE TITLE
How to reference EmbeddedStaticContentConventionBuilder?

### ISSUE THREAD

**Issue by nicholas-brooks** [NancyFx/Nancy#2147]
Just wondering if there was ever a decision made re `Nancy.Embedded.Conventions.EmbeddedStaticContentConventionBuilder` ?  I've read through #1608 but it appeared to be closed without a resolution.

Was it supposed to be included in core or a nuget package?

We're busy using it but couldn't find any reference to it in nancy 1.4.2 or find any nancy.embedded nuget package so we resorted to simply copying the source into our project.

Happy to help out with it if needed.

**Comment by khellang** [comment]
@nicholas-brooks I think we ended up with @jugglingnutcase pulling out the code to https://github.com/jugglingnutcase/Nancy.EmbeddedContent and pushing a separate NuGet package. We never got as far as pushing an "official" package, and I'm not sure we will. We'd rather see the community own it :smile:

**Comment by khellang** [comment]
That said, we do still have the code sitting in the repository, and when porting to project.json (#2155), we'll automatically create a NuGet package for it. Maybe we should discuss if we want to continue this here, or just kill it in favor of @jugglingnutcase's version?

**Comment by jugglingnutcase** [comment]
I never ended up pushing this to NuGet, but I'd be happy to if you think anyone else would use this.

**Comment by nicholas-brooks** [comment]
Thanks for taking the time to reply gents.

Just reading through @jugglingnutcase repo; I'm not stuck on 4.0 so might just look at `Microsoft.Owin.StaticFiles` (which I wasn't aware of).

Would it be worthwhile removing `Nancy.EmbeddedContent` from core and pointing any future devs to @jugglingnutcase repo?  I'm happy to write a wiki page about embedding non-view resources using Microsoft.Owin.StaticFiles for 4.5+ users or @jugglingnutcase repo for 4.0 users.

**Comment by khellang** [comment]
> Would it be worthwhile removing `Nancy.EmbeddedContent` from core and pointing any future devs to @jugglingnutcase repo?

Yes, that's what I was thinking. We're keeping it for now (while porting to project.json). Will revisit this when the dust settles...
