### ISSUE TITLE
ReasonPhrase is discarded on application/json processsor

### ISSUE THREAD

**Issue by mbp** [NancyFx/Nancy#2148]
If you have a route such as:

    Get["/notfound"] = parameters =>
    {
        return new NotFoundResponse
        {
            ReasonPhrase = "foobar",
        };
    };

And you call the API with accept header `application/json`, then "ReasonPhrase" will be `Not Found` instead of `foobar`.

If accept header is `text/html`, then "ReasonPhrase" will be `foobar` (as expected).

This behavior has changed in some version between Nancy 0.22.2 and 1.4.2.

I have tried looking into the code, but could not find a solution in my available time frame.

**Comment by khellang** [comment]
If you return a response, it shouldn't even hit negotiation. It's a way to short-circuit the whole negotiation process :confused:

**Comment by khellang** [comment]
What happens if you `return Negotiate.WithStatusCode(404).WithReasonPhrase("foobar")`?

**Comment by mbp** [comment]
@khellang same result

**Comment by khellang** [comment]
I think we'd need a small repro of this. I can't reproduce this using tests :disappointed:

**Comment by khellang** [comment]
OK, I found a way to reproduce this. I've submitted #2149.

**Comment by mbp** [comment]
Awesome. Thanks!

**Comment by khellang** [comment]
Version 1.4.3 was just pushed to [NuGet](https://www.nuget.org/packages/Nancy/1.4.3).
