### ISSUE TITLE
RequestStream's AsString() extension modifies stream position

### ISSUE THREAD

**Issue by aryelfnd** [NancyFx/Nancy#2157]
If you use the AsString() extension to get the textual representation of a request's body...

```
Console.WriteLine(this.Request.Body.AsString());
```

...the RequestStream position gets left at the end of the stream because the StreamReader being used by the extension reads the stream until the end...

```
public static string AsString(this RequestStream stream, Encoding encoding = null)
{
    using (var reader = new StreamReader(stream, encoding ?? Encoding.UTF8))
    {
        return reader.ReadToEnd();
    }
}
```

...but doesn't update the position back to the initial one.

It can get confusing if you try to read again from Request.Body afterwards. A solution might be resetting the stream's position before returning.

**Comment by jchannon** [comment]
LGTM, do you want to add a PR for it? Only thing I would say is double check we dont already have a test fixture already in this area. Thanks :+1:
