### ISSUE TITLE
The httpcontext.curren will be null when using nancy in a existed asp.net application

### ISSUE THREAD

**Issue by MingYueGuWo** [NancyFx/Nancy#2161]
When using nancy in an existed asp.net application(.net 4.0).
If the build mode is "Debug", it seems everything is OK. 

but when switching build mode to "Release". the HttpContext.Current is always be null.

I'm not sure if I need some other configurations.

Thanks. this is the first time I speak here.

**Comment by khellang** [comment]
`HttpContext.Current` has *nothing* to do with Nancy. Nancy doesn't even use it. There's an equivalent `NancyContext` that's used throughout a Nancy application.

**Comment by MingYueGuWo** [comment]
Hi khellang,
you are absolutely right. i just wonder,
why Debug and release mode can affect nancy. from my knowledge it should be keep same behavior, if i cannot access httpcontext.curent, it should be the nancy handler is in another thread. i just want to know how nancy works here. 

as i said currently my project is running under asp.net. and i want to rewrite it by nancy for some part of it. if it's a mixed project with nancy and asp.net. for a given method how do i know current pipe is asp.net or nancy? or the question is, for a given method how do i know it works under asp.net or nancy?  and what context i should use, httpcontext or nancycontext?

thanks very much for your reply
