### ISSUE TITLE
routing '+' character bug

### ISSUE THREAD

**Issue by tbdbj** [NancyFx/Nancy#2162]
# Normal
```C#
Get["/products/{Product}/{Version}/resolve"] = ...
```
**Request:**
http://localhost:20000/products/**Notepad++**/1.0.0.0/resolve

**Result:**
Get["/products/{Product}/{Version}/resolve"] = _parameters =>...
> _parameters.Product: "Product "

# Greedy
```C#
Get["/products/{Product*}/{Version}/resolve"] = ...
```

**Request:**
http://localhost:20000/products/**Notepad++**/1.0.0.0/resolve

**Result:**
No response.
> Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
> Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in System.Core.dll
> Exception thrown: 'Nancy.ViewEngines.ViewNotFoundException' in Nancy.dll

**Comment by khellang** [comment]
Related to #1154, #1280, #1676 and #1678.

**Comment by khellang** [comment]
@tbdbj what host are you using?

**Comment by tbdbj** [comment]
MS.OWIN.Host.HttpListener
SelfHosting Kotana

**Comment by damianh** [comment]
This is probably [unresolveable](https://github.com/NancyFx/Nancy/issues/1280#issuecomment-143021279)

How other people do it: https://chocolatey.org/packages/notepadplusplus

**Comment by tbdbj** [comment]
Kotana successfuly decoded it.
IOwinContext _context;
 _context.Request.Path.Value: '/products/Notepad++/1.0.0.0/resolve'
google chrome send correct request: 
_context.Request.Path.ToString():
 /products/Notepad%2B%2B/1.0.0.0/resolve

Why probably? 
In my case I can manually split incoming Request.Path, but it will looks like dirty hack...

**Comment by tbdbj** [comment]
In general case yes. But there are many cases with constraints when it solvable.
If in the segments (char sequency between '/') diassalow "%2F" every will works fine.
So routing {a}/{b}%2F{c} ~ {a}/{b}/{c} with constaint a && b && c doesn't contains '/' or "%2F".

**Comment by thecodejunkie** [comment]
Going to close this as it's been iterated over a couple of time, last time in #1280 

We've taken a couple of serious stabs at making this possible, cross hosting, and there are always edge cases and trade offs.

Sorry
