### ISSUE TITLE
Memory Leak on Nancy (Owin + HttpListener hosted).

### ISSUE THREAD

**Issue by monster1025** [NancyFx/Nancy#2164]
Here is sample project,info how to reproduce the leak and my configuration:
https://github.com/monster1025/NancyMemoryLeakTest

**Comment by khellang** [comment]
This is a dupe of #2113 and was fixed with 1.4.2 :smile:

**Comment by monster1025** [comment]
Oh, sorry: saw this issue, but didn't check my version :) Thx!

**Comment by monster1025** [comment]
Oh, thx a lot for a fast answer! :) Will update!)

**Comment by khellang** [comment]
:+1: It would be awesome if you reported back, just to make sure :grin:

**Comment by monster1025** [comment]
Updated and re-checked: now all great, no leaks!
