### ISSUE TITLE
NullReferenceException when Razor Partial View was not found

### ISSUE THREAD

**Issue by dwonisch** [NancyFx/Nancy#2165]
When I use HtmlHelpers<T>.Partial method to locate a view that is not available, I would get a NullReferenceException.
But when I use a non existing view in Module by calling `return View["ViewName"]` I would get a ViewNotFoundException.

Furthermore by throwing the NullReferenceException, an error message is shown, that possibly the Model or one of it's properties could be null, leading to a wrong error research.

**Comment by khellang** [comment]
Closed by #2166

**Comment by khellang** [comment]
Version 1.4.3 was just pushed to [NuGet](https://www.nuget.org/packages/Nancy/1.4.3).
