### ISSUE TITLE
Cache Expiry

### ISSUE THREAD

**Issue by tigerclawn82** [NancyFx/Nancy#2174]
Hi, I am using System.Runtime.Caching to cache OracleConnection object. The problem is, after request is processed item is removed from Cache immediately. I have used RequestStartup to implement this. 
Here is the snippet which details about the implementation.

```
base.RequestStartup(container, pipelines, context);
            DBRequest request = DBRequest.From(context.Request.Form);
            if (!string.IsNullOrEmpty(request.Query))
            {
                _cache["Key"] = DateTime.Now;
                OracleConnection _connection = _cache[request.TNS] as OracleConnection;
                if (_connection != null && SequelMed.Utils.Database.NeedToConnect(_connection))
                {
                    _connection = null;
                }
                if (_connection == null)
                {
                    _connection = SequelMed.Utils.Database.Connection(request.TNS, request.UserName, request.Password);
                    CacheItemPolicy policy = new CacheItemPolicy();
                    policy.SlidingExpiration = new TimeSpan(0, 10, 0);
                    policy.RemovedCallback = itemRemovedCallback;
                    _cache.Add(request.TNS, _connection, policy);
                    Logger.Instance("DatabaseAsREST").Info("Bootstrapper::RequestStartup", "Connection has been cached for 10 Min", client: request.TNS, data: Logger.DB(request.TNS, request.UserName, request.Password));
                }
                container.Register(_connection);
```

_cache is added in the Bootstrap class as private

```
private MemoryCache _cache = new MemoryCache("ConnectionCache");
```

I have added _cache["Key"] = DateTime.Now; to test whether it removed OracleConnection or all objects, its also removing Key from Cache. Is there any configuration issue or i am not bootstraping correctly. Any help would be appreciated.

**Comment by tigerclawn82** [comment]
Hi, i also tried creating static Dictionary and its strange that its also not persisting its value in multiple requests and it got clear.

**Comment by khellang** [comment]
What is the question here? I'm failing to see how this relates to Nancy. It sounds like you're having trouble with the caching APIs :confused:

**Comment by jvandertil** [comment]
I wouldn't recommend putting something like a database connection into a Cache like this. I think it's better to either use Connection pooling implemented by the Oracle driver itself (http://docs.oracle.com/html/E10927_01/featConnecting.htm#i1006393) or implement pooling through the Bootstrapper / DI container.

**Comment by jchannon** [comment]
What @jvandertil said

**Comment by tigerclawn82** [comment]
Thank you so much for the feedback. Yeah, @khellang  you are right, i am newbie and i encountered this issue and posted.

@jvandertil Thanks for your detailed answer :-)
