### ISSUE TITLE
nancy route cannot exactly matches the route patten 

### ISSUE THREAD

**Issue by MingYueGuWo** [NancyFx/Nancy#2175]
hello everyone,
I met an weird issue. i integrated nancy with my exist asp.net webform application. and i want nancy work in some specified path. i defined the config in web.config file like the following
<add name="Nancy2" verb="*" type="Nancy.Hosting.Aspnet.NancyHttpRequestHandler" path="Device/*" />
I wish every routes under ~/Device/* can be handled by nancy. It works fine, but one issue, in other folder there is a folder under the root path like like ~/root/somesubfolder/Device/. all aspx files under the folder will be handled by nancy too. it's not i want. i just want the route handled like ~/Device/* not like ~/path/path/Device/*

my module class like:
public Module(): base("/Device")

anyone can helps me out? thanks very much!

**Comment by khellang** [comment]
Why don't you just map the NancyHandler to a different path in your web.config? :smile:

**Comment by MingYueGuWo** [comment]
Hi Khellang,
You are right. I did try to map NancyHandler to different path. but as i said it's an exist application and it's a complicated application. i just found that there some  physical sub folders use the same name. I'll have to change the structure in future but i I just wonder if i can avoid this issue now? 

btw, in another environment that uses lower iis version(windows server 2003) there is no this issue, just happened in my development machine(iis 7.5).

**Comment by MingYueGuWo** [comment]
Hi Khellang,
I resolve this issue by following configuration,
add a location node and put the nancy config in the location node.
but from my knowledge it has the same meaning. maybe i am wrong. the config has different meanings for different iis version. 

Thanks, again!
