### ISSUE TITLE
Nancy module get initiated each time

### ISSUE THREAD

**Issue by DaveChintan** [NancyFx/Nancy#2176]
Hi,

I am new to Nancy. I am evaluating it and find out that very useful and interesting. I have downloaded the source code of Nancy and use debug DLL in my project to debug Nancy to understand inner workings. I noticed that, for each request, Nancy module get initiated. Isn't this wrong? I think during building route cache all modules should be cached
 and later on when request arrives, just invoke a method on it. I am new to Nancy, so I may be wrong.

Thanks,
Chintan

**Comment by DaveChintan** [comment]
Might be I am wrong. Module creation is not very expensive and also if module expects dependencies then, it is necessary to initiate module each time.

**Comment by khellang** [comment]
This is certainly by design. If the modules are singletons, there'd be no way to inject request-scoped services into your modules, which would really suck :smile: Did you _really_ think this was an oversight?

**Comment by DaveChintan** [comment]
Hi Khellang,

Thanks for your reply.
