### ISSUE TITLE
Owin HttpListener + Client Certificates seems to hang

### ISSUE THREAD

**Issue by dealproc** [NancyFx/Nancy#2179]
When self-hosting Nancy using the Owin Stack, if you `EnableClientCertificates` on your `UseNancy()` call in your app configuration, the request does not complete and eventually fails.

If I implement the same module within a web host (e.g. that runs on IIS), this issue is not present.

Below is the proof for this issue.  In order to run this, you'll need a trusted certificate, and an ability to `PUT` a file to the endpoint (we are trying to emulate what the server-side of nuget does when you push a package, so you could use that as the demo.  Make sure the file is >= 500k in size.  A smaller file will not cause this issue.

``` C#
using Nancy;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Owin;
using Microsoft.Owin.Hosting;

namespace TheConsole
{
    class Program
    {
        static void Main(string[] args)
        {
            var url = "https://{your-computer-name}:{your-ssl-port}";

            using (var webApp = WebApp.Start(url, (app) =>
            {
                app.UseNancy((opts) =>
                {
                    opts.EnableClientCertificates = true;
                });
            }))
            {
                Console.ReadLine();
            };

        }
    }

    public class HomeModule : NancyModule
    {
        public HomeModule()
        {
            Put["/api/v2/package/"] = _ =>
            {
                var hasFiles = Request.Files.Any();
                return "We said hello";
            };
        }
    }
}
```

As a workaround until we can find out why this is happening, although not tasteful, we are doing the following early on within the pipeline:

``` C#
    public class BufferContentIntoAMemoryStreamMiddleware : OwinMiddleware
    {
        public BufferContentIntoAMemoryStreamMiddleware(OwinMiddleware next):base(next){}
        public override System.Threading.Tasks.Task Invoke(IOwinContext context)
        {
            // DIRTY HACK TO GET FILES TO UPLOAD!  This is only needed if you need to use client certificates.
            // need to find out why client certificates seem to bork the pipeline.
            var bytes = ReadFully(context.Request.Body);

            context.Request.Body = new MemoryStream(bytes);
            context.Request.Body.Seek(0, 0);

            return Next.Invoke(context);
        }

        static byte[] ReadFully(Stream input)
        {
            byte[] buffer = new byte[16 * 1024];
            using (MemoryStream ms = new MemoryStream())
            {
                int read;
                while ((read = input.Read(buffer, 0, buffer.Length)) > 0)
                {
                    ms.Write(buffer, 0, read);
                }
                return ms.ToArray();
            }
        }
    }
```

**Comment by xt0rted** [comment]
Possibly related? https://github.com/Bobris/Nowin/issues/55

I know the hosts aren't the same, but if they use the same or similar code then it could explain the issue and/or help resolve it.

**Comment by dorvan** [comment]
NO. It's not related, because we have tested all conbinations.
it's related on System.threading.tasks and System.Net calls. on Nowin.

**Comment by khellang** [comment]
This seems unrelated to Nancy, no? The only factor you've changed is the OWIN host?

**Comment by dorvan** [comment]
Yes, 

and on OWIN we tested some different nancy initialization methods, also looking to:
and 3 versions of mono. 1 stable and 2 from master from github, combining all variables following scientific process.

on windows is less frequent, on linux extremely frequent and variable.

 Owin and Nowin have the same instability IF:
- this https://bugzilla.xamarin.com/show_bug.cgi?id=33254 and this https://katanaproject.codeplex.com/workitem/438 is not applied.
- and System.Threading.Tasks is used in program initialization (System.Threading it's ok)
- and System.Net it's used for network binding with NOWIN proposed syntax, or old/compatible way syntax  (syntax "+:port" works.)

The working and really stable example for our test is this our simple project:
https://github.com/Anthilla/RepoGui

I hope this can help to solve.

**Comment by dealproc** [comment]
so is this flag being set a better option then?

**Comment by dorvan** [comment]
it's not only an option, @dealproc debends on middleware dependencies, with owin you can be free to set the project like https://github.com/Anthilla/RepoGui and no Threading.task it's called, with Nowin it's not possible also for system.net syntax for url/port binding

**Comment by jchannon** [comment]
@dealproc is this on mono? We had this fairly recently #2053

**Comment by dorvan** [comment]
@jchannon yes in mono... but there are some async/thread forking problems with mono (also on git versions)
