### ISSUE TITLE
Exploring the nancy module  bug in Nancy.hosting.self

### ISSUE THREAD

**Issue by lmoonx** [NancyFx/Nancy#2180]
using System;
using Nancy;
using Nancy.Hosting.Self;
namespace Hosting_Nancy.Hosting.Self
{
    class Program
    {
        static void Main(string[] args)
        {
            string Url = "http://localhost:1234/abc/bb/";
            using (var host = new NancyHost(new Uri(Url)))
            {
                host.Start();
                Console.WriteLine("start");
                System.Diagnostics.Process.Start(Url);
                Console.Read();
                host.Stop();
            }
        }
    }

    public class Module : NancyModule
    {
        public Module()
        {
            Get["/"] = _ => { return "root"; };
        }
    }

    public class abcModule : NancyModule
    {
        public abcModule() : base("/abc")
        {
            Get["/"] = _ => { return "abc-root"; };
            Get["/bb"] = _ => { return "abc-bb"; };
        }
    }
}

result：
http://localhost:1234/       404 (why not is root)
http://localhost:1234/abc    404 (why not is abc-root)
http://localhost:1234/abc/bb    root (why not is abc-bb)

**Comment by lmoonx** [comment]
but the same code hosting in asp.net , it runs good;
http://localhost:1234/                root
http://localhost:1234/abc           abc-root
http://localhost:1234/abc/bb      abc-bb

maybe the nancy.hosting.self has some  problem

**Comment by khellang** [comment]
Eeh... You're hosting the app on `http://localhost:1234/abc/bb/`. Everything is relative to that, so the following is expected:

| URL | Result |
| ---- | ---- |
| http://localhost:1234/ | 404 |
| http://localhost:1234/abc | 404 |
| http://localhost:1234/abc/bb | root |
| http://localhost:1234/abc/bb/abc | abc-root |
| http://localhost:1234/abc/bb/abc/bb | abc-bb |

This is as designed. If you want the same behaviour as the ASP.NET host; use `http://localhost:1234/` as your host URL.

**Comment by lmoonx** [comment]
This is my negligence. I'm sorry.  
Thank you very much.
