### ISSUE TITLE
Trouble returning views and application root path using DNX

### ISSUE THREAD

**Issue by thiagomajesk** [NancyFx/Nancy#2182]
Hi guys...

I'm receiving this error when trying to return views with my Nancy application

```bash
Nancy.RequestExecutionException: Oh noes! ---> Nancy.ViewEngines.ViewNotFoundException: Unable to locate view 'Index'
Currently available view engine extensions: sshtml,html,htm
Locations inspected: views/Login/Index-pt-BR,views/Login/Index,Login/Index-pt-BR,Login/Index,views/Index-pt-BR,views/Index,Index-pt-BR,Index
Root path: C:\Users\thiag\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\
```

Interesting is that the root path of the application is defined to: 
*C:\Users\thiag\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\* (is this right?)

I've posted an issue on the dnx github too based on the premise that the view files should be configured to be copied as content: https://github.com/aspnet/dnx/issues/3291

**Comment by thecodejunkie** [comment]
I'm unsure how DNX resolved the base-directory, like we do in our [DefaultRootPathProvider](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/DefaultRootPathProvider.cs#L16) implementation. A possible work around could be to implement your own `IRootPathProvider` and have your bootstrapper register it as described here https://github.com/NancyFx/Nancy/wiki/The-root-path

Perhaps @khellang or @horsdal can add more context

**Comment by khellang** [comment]
I'd definitely go with a custom path provider, based on IApplicationEnvironment or AppContext for this. I doubt the old way will work correctly on DNX.

**Comment by thiagomajesk** [comment]
@thecodejunkie @khellang Ok guys, I can access the application path using the code bellow:

```c#
public class Startup
{
        public Startup(IHostingEnvironment env, IApplicationEnvironment appEnv)
        {
            var path = appEnv.ApplicationBasePath;
        }

        public static void Main(string[] args) => WebApplication.Run<Startup>(args);

        public void Configure(IApplicationBuilder app) =>  app.UseOwin(x => x.UseNancy());
}
```

The question now is: How can I pass that path to the nancy bootstrapper initializing my custom IRootPathProvider. Any thought on how to implement it?

**Comment by khellang** [comment]
There are many ways, but I'd probably go with the following:
 1. Populate the container in the `Startup` class (register the `IApplicationEnvironment`)
 2. Pass the container in the bootstrapper constructor.
 3. Pass the bootstrapper to the `UseNancy` method
 4. Override the `GetApplicationContainer` method and pass the pre-populated container

You can see an example of this [here](https://github.com/khellang/Nancy.Autofac.Dnx/blob/master/src/WebApplication1/Startup.cs). The example uses Autofac and its `Populate` extension method for MS.Extensions.DependencyInjection. That will copy all registrations in the `IServiceCollection` in to the Autofac container builder. I know there's a similar "adapter" for StructureMap (since I wrote it :stuck_out_tongue_winking_eye:) [here](https://github.com/structuremap/structuremap.dnx).

After that, you'll be able to just implement `IRootPathProvider`, inject `IApplicationEnvironment` (and all other DNX services you'd like), and return the base path, like this:

```csharp
public class ApplicationEnvironmentRootPathProvider : IRootPathProvider
{
    public ApplicationEnvironmentRootPathProvider(IApplicationEnvironment environment)
    {
        Environment = environment;
    }

    private IApplicationEnvironment Environment { get; }

    public string GetRootPath()
    {
        return Environment. ApplicationBasePath;
    }
}
```

Nancy should automatically pick up the new `IRootPathProvider` :grin:

**Comment by khellang** [comment]
Ugh. Wait. Apparently Nancy doesn't pick up `IRootPathProvider` implementations automatically, and it's not hooked up to the container by default :disappointed: 

I guess you could stick with the same approach, but instead of relying on Nancy magic:
 1. Register `ApplicationEnvironmentRootPathProvider` in the container as `IRootPathProvider`.
 2. Override the `RootPathProvider` property in your bootstrapper:
  
  ```csharp
      protected override IRootPathProvider RootPathProvider =>
          ApplicationContainer.Resolve<IRootPathProvider>();
  ```

**Comment by thiagomajesk** [comment]
Thanks @khellang for the help... I managed to implement it using your guidelines. 
I'm using StructureMap as a container and the code looks like this:

**Startup.cs**

```c#
public class Startup
{
    private IContainer Container { get; set; }
    
    public Startup(IHostingEnvironment env, IApplicationEnvironment appEnv)
    {
        Container = new Container(config => { config.For<IApplicationEnvironment>().Use(appEnv); });            
    }

    public static void Main(string[] args) => WebApplication.Run<Startup>(args);

    public void Configure(IApplicationBuilder app) => app.UseOwin(owin => owin.UseNancy(config => config.Bootstrapper = new Bootstrapper(Container)));
}
```

**Bootstrapper.cs**
```c#
public class Bootstrapper : DefaultNancyBootstrapper
{
    private readonly IContainer container;

    public Bootstrapper(IContainer container)
    {
         this.container = container;
    }

    protected override IRootPathProvider RootPathProvider => container.GetInstance<RootPathProvider>();
}
```

**RootPathProvider.cs**
```c#
public class RootPathProvider : IRootPathProvider
{
    public RootPathProvider(IApplicationEnvironment environment)
    {
         Environment = environment;
    }

   private IApplicationEnvironment Environment { get; }

   public string GetRootPath()
   {
        return Environment.ApplicationBasePath;
   }
}
```

**Comment by VanKrock** [comment]
Hi @thiagomajesk Can you write your usings for Startup.cs and project.json? You use Microsoft.AspNet.Hosting? What about Nancy.Hosting.Self?

**Comment by VanKrock** [comment]
I Resolve it
`public class ApplicationBootstrapper : DefaultNancyBootstrapper
	{
		protected override void ConfigureApplicationContainer(TinyIoCContainer container)
		{
			container.Register<IRootPathProvider, ApplicationEnvironmentRootPathProvider>();
			base.ConfigureApplicationContainer(container);
		}

		protected override IRootPathProvider RootPathProvider => ApplicationContainer.Resolve<IRootPathProvider>();
	}

	public class ApplicationEnvironmentRootPathProvider : IRootPathProvider
	{
		public string GetRootPath()
		{
			return PlatformServices.Default.Application.ApplicationBasePath;
		}
	}`

**Comment by thiagomajesk** [comment]
@VanKrock Yes, I use `Microsoft.AspNet.Hosting` exclusively because of the `IHostingEnvironment` interface and the startup method `WebApplication.Run<T>`. I've never tried implementing using  `Nancy.Hosting.Self`.

The project.json file (Remember to ajust it to your own needs):

```json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true,
    "languageVersion": "csharp6"
  },
  "tooling": {
    "defaultNamespace": "YourProjectNamespaceHere"
  },
  "dependencies": {
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.Owin": "1.0.0-rc1-final",
    "Nancy": "1.4.3",
    "StructureMap": "4.0.1.318",
    "EntityFramework": "6.1.3"
  },
  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },
  "frameworks": {
    "dnx451": { }
  },
  "content": [ "Views/**/*.html", "*.html" ],
  "contentFiles": ["Views/Index.html", "page.html"]
}
```

Besides my own domain usings, I have:

```c#
using Microsoft.AspNet.Builder;
using Microsoft.AspNet.Hosting;
using Microsoft.Extensions.PlatformAbstractions;
using Nancy.Owin;
using StructureMap;
```

**Comment by VanKrock** [comment]
@thiagomajesk thanks
