### ISSUE TITLE
DotLiquid ViewEngine doesn't provide a Render method

### ISSUE THREAD

**Issue by sstraus** [NancyFx/Nancy#2185]
Hello guys, I need to implement al logic like this: 

```c#
if (page==null || page.ContentType == MongoLandingPageItem.ContentTypes.Ssve)
                {
                    var viewEngineSsve = new SuperSimpleViewEngine();
                    return viewEngineSsve.Render(template, Model, null);
                }
                else
                {
                    var viewEngineLiquid = new DotLiquidViewEngine(new CSharpNamingConvention());
                    return viewEngineLiquid.Render(template, Model, null);
                }
```

But in DotLiquidViewEngine the Render method is missing, how can I get rid of this without changing the source code?

**Comment by thecodejunkie** [comment]
All Nancy view engines implements the `IViewEngine` interface, which provides a `RenderView` method. `SuperSimpleViewEngine` is created as a stand alone view engine and then we wrap that in an `IViewEngine` class called [SuperSimpleViewEngineWrapper](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/ViewEngines/SuperSimpleViewEngine/SuperSimpleViewEngineWrapper.cs). This class has a constructor dependency on `IEnumerable<ISuperSimpleViewEngineMatcher> matchers` so you have two options.

1. You take your own ctor dependency on `IEnumerable<IViewEngine>` and get the correct view engine instances out of that using either their type names or by checking the supported [Extensions](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/ViewEngines/IViewEngine.cs#L15)

2. You could take hard dependencies on both `DotLiquidViewEngine` and `SuperSimpleViewEngineWrapper`
