### ISSUE TITLE
When the release and Optimize Code project with razor, will get an error: "Unable to locate layout"

### ISSUE THREAD

**Issue by thinkif** [NancyFx/Nancy#2191]
In release , "Optimize Code" option is default.

Run or deploy the project get the error message as :

> System.InvalidOperationException: Unable to locate layout: /Shared/_Layout.cshtml at Nancy.ViewEngines.Razor.RazorViewEngine.<>c__DisplayClass2b.b__2a(Stream stream) at Nancy.Responses.MaterialisingResponse.PreExecute(NancyContext context)

But in debug is ok. And uncheck  "Optimize Code" option is ok, too.

The file "/Shared/_Layout.cshtml" is exist.

I've followed the instructions ( https://github.com/NancyFx/Nancy/wiki/Razor-View-Engine  ), but to no avail.

This error only in release and "Optimize Code" option checked.

Environment : 
> Visual Studio 2015
> .Net 4.5

Thank you read this issue.

And I'm sorry my English is poor.

Jeffrey

**Comment by zwcloud** [comment]
I got exactly the same error on Ubuntu 14.01, when hosting my website by Jexus.
The project runs normally on windows7 when debug with VS2013.

> Application Exception
> System.InvalidOperationException
> Unable to locate layout: /Shared/_Layout.cshtml
> 
> Description: HTTP 500.Error processing request.
> Details: Non-web exception. Exception origin (name of application or object): Nancy.ViewEngines.Razor.
> Exception stack trace:
>   at Nancy.ViewEngines.Razor.RazorViewEngine+<>c__DisplayClass2b.<RenderView>b__2a (System.IO.Stream stream) [0x00000] in <filename unknown>:0 
>   at Nancy.Responses.MaterialisingResponse.WriteContents (System.IO.Stream stream) [0x00000] in <filename unknown>:0 
>   at Nancy.Hosting.Aspnet.NancyHandler.SetNancyResponseToHttpResponse (System.Web.HttpContextBase context, Nancy.Response response) [0x00000] in <filename unknown>:0 
>   at Nancy.Hosting.Aspnet.NancyHandler.EndProcessRequest (System.Threading.Tasks.Task`1 task) [0x00000] in <filename unknown>:0 
>   at Nancy.Hosting.Aspnet.NancyHttpRequestHandler.EndProcessRequest (IAsyncResult result) [0x00000] in <filename unknown>:0 
>   at System.Web.HttpApplication.async_handler_complete_cb (IAsyncResult ar) [0x00000] in <filename unknown>:0 
> Version Information: 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1); ASP.NET Version: 4.0.30319.17020

**Comment by zwcloud** [comment]
OK... I fixed it using `Layout = "Views/Shared/_Layout.cshtml"` instead of 'Layout = "/Shared/_Layout.cshtml"'.
But why it's different on windows or linux...

**Comment by thinkif** [comment]
To @zwcloud 

Wow, it's work.

I run at windows 10 with release mode.

Thank you

**Comment by xt0rted** [comment]
If this is the same issue as #1281 then don't prefix the view paths with a `/`. The view engine handles paths differently in debug mode and allows for leading slashes while release mode doesn't.
