### ISSUE TITLE
async problem related to System.Threading.Tasks, unpredictable error 500, (nancy + mono + linux)

### ISSUE THREAD

**Issue by dorvan** [NancyFx/Nancy#2193]
On a 3 layer application, where frontend call backend's api with  http client, internally, 
using latest 2 versions of neancy with lastest version on mono and the git master version
we obtain randomly this error 500.

We initially worked on mono and nancy projects to reduce as possible the usage of System.Threading.Tasks, but is impossible to remove totally, using async methods.

Then we have upgraded all the system, because wi had instability problems with 4.2.6 linux kernel
now we have a 4.4  kernel, with mono from git, and latest nancy. System stability issues are solved, but the application present the same problem about async with an error 500

anyone can help us?

Nancy.RequestExecutionException: Oh noes! ---> System.Net.Http.HttpRequestException: 500 (Internal Server Error)
  at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode () <0x407b51a0 + 0x000b7> in :0 
  at System.Net.Http.HttpClient+c__async5.MoveNext () <0x40787b50 + 0x00253> in :0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x4083a980 + 0x0002b> in :0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x4083a5f0 + 0x000d3> in :0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x4083a540 + 0x00097> in :0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x4073f1b0 + 0x0003b> in :0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x4073f130 + 0x00017> in :0 
  at AnthillaCore.Authentication.DatabaseHelper+d__1.MoveNext () <0x40837000 + 0x0017b> in :0 
  --- End of inner exception stack trace ---
  at Nancy.NancyEngine.InvokeOnErrorHook (Nancy.NancyContext context, Nancy.ErrorPipeline pipeline, System.Exception ex) <0x4083e4e0 + 0x002af> in :0

**Comment by phillip-haydon** [comment]
Do you get the error on an async method that returns a string.

i.e

```
Get["/test", true] = async (_, ctx) => {
    return "hello world";
};
```

**Comment by Grul-** [comment]
Hi, I'm going to answer for @dorvan about this issue, as we are working on the same project.
We don't have any error on that method. Actually the Nancy method isn't explicitly declared as async as the "true" async Task is nested inside it and that's where we have the above error.

We are using a Method that create the connection and returns the HttpClient response:
```
public static async Task<T> GetClientResponse<T>(string uri) {
    var client = new HttpClient();
    return await client.GetStringAsync(uri);
}

public static T GetResult<T>(string uri) {
    return GetClientResponse<T>(uri).Result;
}
```
And we call this in our Nancy method (and as well in other pieces of code) like this:
```
Get["/getremote"] = _ => {
    return GetResult<string>("http://www.google.com");
};
```
We noticed that we have that error only in Nancy methods that use HttpClient to get a string from the our other application.
The thing that confuses us more is that the same application has two different behaviors, while on mono we have this kind of error on Windows works fine. For this we also wonder if mono manage the `HttpClient` class in another way...

Thanks! :)

**Comment by dorvan** [comment]
@phillip-haydon looking to semplify methods, now error it's less frequent but software it's very slow, and after 2 minutes of loading an error 500 with 2 lines appear with "System.Threading.Tasks.Task  Task canceled"   ....going crazy...

**Comment by dorvan** [comment]
on Windows works great...

**Comment by grumpydev** [comment]
Ok, this isn't actually the problem you're seeing, but your code is.. odd :)

Using .Result in an asp.net app has the potential to cause deadlocks under load, so you really shouldn't be doing that. I also don't really understand why you would do it anyway, why not just make your route async, and use the async method you already have?

```
Get["/getremote", true] = async (_, __) => {
    return await GetClientResponse<string>("http://www.google.com");
};
```

Down to the actual issue you're seeing, this isn't a 500 from the calling code, it's a 500 status code being returned from the service it is calling into (www.google.com in your sample code) - the EnsureSuccessStatusCode method you see in your stack trace throws the HttpRequestException if the status code returned isn't a success code (specifically anything that's not in the 200 range). That's where you need to be focussing your logging/debugging efforts.

**Comment by Grul-** [comment]
Actually using .Result was an old workaround, I realized it wasn't needed anymore and I've already changed that piece of code :)
We are investigating what should cause any problem in our service at the moment :)

**Comment by dorvan** [comment]
here an extended error on server (BE) with debug.

https://gist.github.com/dorvan/7c91f7012c8c823772ff
