### ISSUE TITLE
Demo for TokenAuthentication is broken

### ISSUE THREAD

**Issue by Ralf1108** [NancyFx/Nancy#2198]
The link "https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Authentication.Token/Tokenizer.cs" on WikiPage "https://github.com/NancyFx/Nancy/wiki/Token-Authentication" points to 404

**Comment by Ralf1108** [comment]
It seems that is was removed in commit: https://github.com/NancyFx/Nancy/commit/050eca2bf95efd32b4d4858900f9f729f520b152

Was this by accident?

**Comment by khellang** [comment]
Read the commit message:

> Removing Nancy.Authentication.Token and all related projects. Token (Bearer) auth should be implemented by suitable middleware.

Do you still think it was by accident? :wink:

I've removed the link in the wiki and added a deprecation notice. Thanks for filing this :+1:

**Comment by Ralf1108** [comment]
Ok... the remark said it.

But I didn't found a proper example how to integrate TokenAuthentification...so I took the deleted code..thx SourceControl :D

Or did I miss a demo project which shows this?
Maybe a link to such a demo could be inserted for other first time implementors?

**Comment by khellang** [comment]
@Ralf1108 There is a demo in the `1.x-WorkingBranch`: https://github.com/NancyFx/Nancy/tree/1.x-WorkingBranch/src/Nancy.Demo.Authentication.Token

**Comment by Ralf1108** [comment]
Ok thx!
