### ISSUE TITLE
Json.NET generated dynamic ViewModel not working

### ISSUE THREAD

**Issue by ralfw** [NancyFx/Nancy#2205]
Consider this code:

```
public class CustomerModule : NancyModule
{
	public CustomerModule()
	{

		Get["/test"] = p => {
			dynamic vm = Newtonsoft.Json.JsonConvert.DeserializeObject("{\"Name\":\"Mary\"}");
			return View["index.html", vm];
		};
	}
}
```

and this view:

```
<html>
  <head>
    <title>Json Test</title>
  </head>
  <body>
	Hello, @Model.Name
  </body>
</html>
```

It looks simple - but does not work. No page will be rendered, no exception will be thrown.

Why is that?

If instead I generate the view model like this:

```
vm = new ExpandoObject();
vm.Name = "Mary";
```

all is well.

Interestingly the Json.NET deserialization works in this project: https://dotnetfiddle.net/9CMzYi where the view is returned like this: `return View[vm]`

Since Json.NET is such a popular Json lib I'd like to see Nancy work with it well.

Any suggestions how to work around this? Or maybe someone wants to fix this?

-Ralf

**Comment by psibernetic** [comment]
Try using @Model.Name.Value (@Model.Name is a node in the JSON element so you need to access its value)

My experience with JSON.NET's dynamic objects has been less than ideal as they have their own IDynamicObject implementation for representing JSON, it isn't really intended to be a drop in replacement for classes or exandos but rather a simple way to access JSON indirectly.

**Comment by ralfw** [comment]
Thanks for the tip - but it does not work.

Can you recommend another JSON lib to use with Nancy which supports dynamic objects?

**Comment by psibernetic** [comment]
My tests show that this functions, but calling `@Model.name.Value` in the view for the dynamic object doesn't. I believe SSVE (Super-Simple-View-Engine) only supports top-level properties. 

```csharp
            Get["/"] = parameters =>
            {
                dynamic vm = Newtonsoft.Json.JsonConvert.DeserializeObject("{\"name\":\"Mary\"}");

                var model2 = new { name = vm.name.Value };
                return View["index", model2];
            };
```

My recommendation is to use the generic version of the DeserializeObject<T> method to map to a strongly-typed model.

```csharp
    public class HomeModule
        : NancyModule
    {
        public HomeModule()
        {
            Get["/"] = parameters =>
            {
                Person vm = Newtonsoft.Json.JsonConvert.DeserializeObject<Person>("{\"name\":\"Mary\"}");

                return View["index", vm];
            };
        }
    }


    public class Person
    {
        public string Name { get; set; }
    }
```

**Comment by thecodejunkie** [comment]
The Super Simple View Engine supports the following model types

- Plain POCO objects
- `IDictionary<string, object>`
- `IDynamicMetaObjectProvider`
- `DynamicDictionaryValue`
- `DynamicObject`

The Newtonsoft.Json [JObject](http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Linq_JObject.htm) does not satisfy either of these, hence it is unable to retrieve model member values from it.
