### ISSUE TITLE
Delete returns 405

### ISSUE THREAD

**Issue by senj** [NancyFx/Nancy#2209]
Hello,
I'm hosting nancy in IIS8. I have a JS application calling against an API.
I'm using

```xml
<handlers>
  <remove name="ExtensionlessUrl-Integrated-4.0" />
  <add name="ExtensionlessUrl-Integrated-4.0" path="*." verb="GET,POST,DELETE,PUT" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
</handlers>
```

but i still get 405 method not allowed. it works on my local machine so something must be wrong with the configuration. If I use

```xml
<system.webServer>
  <modules runAllManagedModulesForAllRequests="true">
    <remove name="WebDAVModule" />
  </modules>  
</system.webServer>
````
I works 1 time but then all scripts won't load anymore. (404)

**Comment by thecodejunkie** [comment]
Have you enabled DELETE requests in your IIS for the site?

**Comment by thecodejunkie** [comment]
Oh sorry, you hadn't added code formatting to your post so the XML did now show. I'm sure this is not a Nancy thing, can you do something like overriding `RequestStartup` in your bootstrapper, set a breakpoint and see if it hits it?

**Comment by senj** [comment]
I'm sorry.. 
Ok I will try that
