### ISSUE TITLE
No cshtml file precompiling when deploy

### ISSUE THREAD

**Issue by billypon** [NancyFx/Nancy#2210]
I created a web project, added references: Nancy, Nancy.Hosting.Aspnet and Nancy.Viewengines.Razor. added buildProviders config to web.config.

When I deployed, I found the cshtml files were still the same, and they couldn't be precomfiled.

**Comment by phillip-haydon** [comment]
Why do you need them to be precompiled?

**Comment by dealproc** [comment]
perf. optimization i would presume.

**Comment by billypon** [comment]
@phillip-haydon perf. optimization, and don't allow to modify template files

**Comment by thecodejunkie** [comment]
@billypon we currently do not support pre-compiling of Razor views, I am afraid
