### ISSUE TITLE
Not sure how it works.

### ISSUE THREAD

**Issue by sometowngeek** [NancyFx/Nancy#2216]
I'm trying to download this and test it out for work.

I downloaded NancyFx/Nancy and tried to build/run it, but I keep running into errors after errors because I'm missing a laundry list of dependencies.

I'm feeling stumped because it does not give clear instructions on how to use it or which libraries I am required.

I think in your wiki, you should include transparent instructions on what is required in order to use NancyFx, or the developers will be really frustrated with trying to comprehend it. Even I am struggling to infer between lines of why things are missing and when I try to look up the errors, I am directed to download and install a variety of things, which I think could be mentioned in the wiki. The wiki could also mention the workarounds if the users would like to avoid installing the components, or indicate that there are no workarounds to installing the required components.

**Comment by thecodejunkie** [comment]
Our Wiki does have quite extensive documentation

![image](https://cloud.githubusercontent.com/assets/50543/12764332/71a0dc52-c9f9-11e5-87ec-4293ff33a3b0.png)

Including an entire section called [Introduction](https://github.com/NancyFx/Nancy/wiki/Introduction) which has a section called [Creating your first Nancy application](https://github.com/NancyFx/Nancy/wiki/Introduction#creating-your-first-nancy-application) the documentation then goes on to describe the majority of the concepts of the framework.

Things aren't missing at all. The repository builds perfectly fine - we build it every day, multiple times. 

There is also a pretty extensive file titled [How_to_build.txt](https://github.com/NancyFx/Nancy/blob/master/how_to_build.txt) which explains how you can build Nancy using the RAKE script that is included. Not that it is required, all you need to do it pull down the solution, load it up and compile - not a single build error 

I also welcome you to investigate any of the [20 demo projects](https://github.com/NancyFx/Nancy/tree/master/samples) in our repository or read any of the [Blog posts, Video & Audio](https://github.com/NancyFx/Nancy/wiki/Blog-Posts%2C-Video-%26-Audio) links that we provide on our Wiki

While you are at it, grab the [free e-book](https://www.syncfusion.com/resources/techportal/details/ebooks/nancyfx) 

Have fun :smile:
