### ISSUE TITLE
Response throwing An operation was attempted on a nonexistent network connection error

### ISSUE THREAD

**Issue by jinwah** [NancyFx/Nancy#2266]
Hi,

I have the following code:

``` csharp
Get["/classlist/pdf"] = parameters => {
    var response = new Response();
    string filename = DateTime.Now.ToString("yyyyMMddhhmm") + " Participants Report.pdf";
    response.Headers.Add("Content-Disposition", "attachment; filename=" + filename);
    response.ContentType = "application/pdf";

    response.Contents = stream =>
    {
        var writer = new StreamWriter(stream) { AutoFlush = true };
        ViewModel.CreatePDFReport(writer, ViewModel.CourseIdAsInt());
    };

    return response;
};
```

But when I try to write to the stream it throws HttpListenerException An operation was attempted on a nonexistent network connection error 

I think this is because I am trying to write to the response stream when the request stream is still open. (Thats an educated guess based upon a lot of searching)

Any ideas? I just want to pass a pdf generated dynamically back to the user, not from a file). PS This has worked and I have seen the PDF arrive at the client end, but the above error throws most of the time.

Thanks

Jin

**Comment by jinwah** [comment]
When deployed to the server I get: Nancy.RequestExecutionException: Oh noes! ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship 

The certificate is signed with SHA-1

**Comment by phillip-haydon** [comment]
Why sha-1

**Comment by jinwah** [comment]
Infrastructure set the servers up. Is it that preventing it? I am guessing so. I am just the Dev. My original question stands though Locally when I try to write to the stream it throws HttpListenerException An operation was attempted on a nonexistent network connection error. Thanks for responding

**Comment by phillip-haydon** [comment]
They aren't supported anymore.

https://blog.qualys.com/ssllabs/2014/09/09/sha1-deprecation-what-you-need-to-know

(first google link I found, but there's lots) 

You should issue a new SHA-2 cert. Your error is very similar to 1 I was getting on AWS API Gateway and my phone. Fixed up issuing an SHA-2 cert.

**Comment by phillip-haydon** [comment]
@jinwah are you able to update the cert?
