### ISSUE TITLE
JsonDeserializer does not have Deserialise<T> on it

### ISSUE THREAD

**Issue by jchannon** [NancyFx/Nancy#2273]
Due to a change required for CoreCLR and BinaryFormatter not working I created #2264 however this causes numerous tests to fail as it has no type information to deserialize to whereas BinaryFormatter "probably" serialised the type info so was able to deserialize.

We could change JsonDeserializer to have a `Type` arg in its Deserialise method but this means changing everywhere that calls it, 5 in source and 7 in tests.

There has been talk of replacing it with SimpleJSON but we're unsure if this is suitable at present but should we do this work if we plan to replace JsonDeserializer?

This issue is an opener for a discussion on what we want to do.

**Comment by jchannon** [comment]
Pinging @NancyFx/nancy-core-contributors

**Comment by grumpydev** [comment]
I'm guessing this isn't an easy port to coreclr:

https://github.com/mosa/Mono-Class-Libraries/tree/master/mcs/class/corlib/System.Runtime.Serialization.Formatters.Binary

The whole serialisation/deserialisation "flow" needs updating at some point, but I don't really see this as connected to the binaryformatter replacement as it's very much just an implementation detail - the code that uses binaryformatter (followed by base64 encoding) just needs something to turn an object into something that can be stored as a string (and turn it back again).

To me the easiest solution is to drop in simplejson and use it directly, then if we also decide to bring that in to replace our "normal" json serialiser then it's just a case of wiring that up.

**Comment by jchannon** [comment]
I've tried dropping in SimpleJson but we have tests that assume the `Type` that comes back from Deserialise but because we now use Json we have to pass the Type we want back

**Comment by thecodejunkie** [comment]
@grumpydev I think the problem that JC ran into was that the [IObjectSerializer.Deserialize](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/IObjectSerializer.cs) does not take a `Type` parameter so he can't really swap out the internals for a JSON one as they generally give you a dictionary back unless you specify a type. The reason we "get away" with it, in the `DefaultObjectSerializer`, is that the binaryformatter stores type information in the serialized data and can recreate the correct type when you deserialize.

What would mean we'd need to change the signature of the  [IObjectSerializer.Deserialize](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/IObjectSerializer.cs) method but I think JC said that had some ripple effects through Nancy?

**Comment by jchannon** [comment]
Yu,p one example, in ISession you can use square brackets to get your object because its `IEnumerable<KeyValuePair<string, object>>` and as the binary formatter is used it knows the type to deserilaize to however with JSON it doesnt.  This means ISession would need to change to `IEnumerable<KeyValuePair<string,<Tuple<object,Type>>>` or `IEnumerable<KeyValuePair<string,NewSessionClassWithTypeProperty>>`

**Comment by jchannon** [comment]
I think we can close this. This was fixed in #2264
