### ISSUE TITLE
Nuget v1.4.3 is Nancy v1.4.2?

### ISSUE THREAD

**Issue by corelgott** [NancyFx/Nancy#2275]
Hi there!

I'm trying to use Nancy with Ninject on Mono. Therefor I target Nancy 1.4.3 which I've installed via nuget. But when I take a look at the installed "packages/nancy.1.4.3/lib/net4.0/Nancy.dll" it is actually version 1.4.2. (I've found this due to the missing Nancy.Configuration namespace)
VS2013 & Nuget on Windows does the same (obviously & tried it)

Is this version mismatch intended? Is is expected that **Nuget Package 1.4.3** contains **Nancy.dll v1.4.2**?

Any clarification on this would be greatly appreciated!

Cheers,

Corelgott

**Comment by khellang** [comment]
Yes, this is expected. It was a mistake on our part. See https://github.com/NancyFx/Nancy/issues/2113#issuecomment-170894212

**Comment by corelgott** [comment]
Ahh ok I see... . 

@khellang
> "Yes, looks like we forgot to bump the AssemblyVersion for the 1.4.3 release" 

But I'd expect to see the **Nancy.Configuration** namespace if only the version labeling is wrong... So the delivered DLL is still v1.4.2 on purpose due to the memory leak issues...?

**Comment by thecodejunkie** [comment]
@corelgott `Nancy.Configuration` is not part of the `1.x` branch of builds, that is going to be a `2.x` feature and only exists on our master branch so far
