### ISSUE TITLE
FluentValidation dependency version not specified

### ISSUE THREAD

**Issue by stuart-bennett** [NancyFx/Nancy#2302]
Hi

When installing the Nancy.Validation.FluentValidation package, there is no minimum version of the FluentValidation dependency. If you're nuget "dependency behaviour" is set to "lowest" you get an exception when initializing Nancy (see screen grabs at bottom) due to a incompatible version of FluentValidation.

The solution is easy (upgrade FluentValidation to at least 3.4.0.0) but this may catch more inexperienced people out.

I'm happy to submit a pull request for this if you think it's worth sorting :)

Exception:

![web exception](https://cloud.githubusercontent.com/assets/493995/13253240/0a378dfa-da33-11e5-851a-32f4cf03dfb4.PNG)

From nuget package manager:

![image](https://cloud.githubusercontent.com/assets/493995/13253138/69842526-da32-11e5-9b3e-4b64bbef94bb.png)

**Comment by jchannon** [comment]
Yes please, seems our project.json for it is set just not the nuspec 

https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Validation.FluentValidation/project.json#L13

https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Validation.FluentValidation/nancy.validation.fluentvalidation.nuspec

**Comment by thecodejunkie** [comment]
Closed by #2303
