### ISSUE TITLE
NumericConverter should exclude enums

### ISSUE THREAD

**Issue by xmedeko** [NancyFx/Nancy#2305]
When I copy & paste `NumericConverter` into my project, then Binding if enums stops working. The problem is that `IsNumeric(Type)` extension returns `true` for an enum, too. Either fix the `IsNumeric(Type)`  extension or `NumericConverter.CanConvertTo`:

```c#
public bool CanConvertTo(Type destinationType, BindingContext context)
{
    return !destinationType.IsEnum && destinationType.IsNumeric();
}
```

**Comment by thecodejunkie** [comment]
Closed by #2306
