### ISSUE TITLE
Should we rename Nancy.Owin project?

### ISSUE THREAD

**Issue by jchannon** [NancyFx/Nancy#2322]
As the title suggests. Currently this project won't compile on `dotnet54` due to the `Owin` lib not being `dotnet54` compatible.  For using `Nancy` in `dnxcore50` apps the usage will be `app.UseOwin(x => x.UseNancy());` which uses the `MidFunc` extension in `Nancy` not the `IAppBuilder` extension in `Nancy.Owin`, `IAppBuilder` being something inside the `Owin` lib.

Should we rename it and/or make it clear that using the Nancy.Owin IAppBuilder extensions won't work for `dnxcore50` apps?

Thoughts? @damianh 

> **Glossary** 
> 
> dnxcore50 - An application that runs on CoreCLR
> dotnet54 - A library that is targeting the CoreCLR

**Comment by damianh** [comment]
I'd wouldn't be angry if it was called Nancy.MSOwin. @grumpydev may have a
problem with breaking package name though...

**Comment by jchannon** [comment]
Its not MS though is it? IAppBuilder is in Owin.dll not anything MS related?

**Comment by khellang** [comment]
OWIN.dll *is* MS (Katana) related :smile:

**Comment by psibernetic** [comment]
I'd prefer leaving the name as is currently. The owin dll is Katana related, but not owned or maintained by MS.

**Comment by grumpydev** [comment]
If we're going to do this we should put out a new version of the current one with an obsolete attribute pointing to the new library - despite it being uploaded by "owincontrib", owin.dll is very much Microsoft, they just don't maintain it.. they just steamrollered all over the rest of the owin group then rode out of town ;)

We'd have to make it obvious though, not sure MSOwin does that, maybe something like:

Nancy.Owin.IAppBuilder
Nancy.Owin.AppBuilderExtensions
Nancy.Owin.Katana

**Comment by phillip-haydon** [comment]
Nancy.Microsoft.SteamRollered.Owin

**Comment by jchannon** [comment]
I think the Katana suffix

**Comment by psibernetic** [comment]
Nancy.Owin.Katana seems the best of the options.

**Comment by MeirionHughes** [comment]
The `Owin` and `Owin.Builder` seem rather basic and not linked to anything Apart from the Owin spec itself. Its the `Microsoft.Owin` lib that is ms flavoured, no? Is there another library that is closer to the Owin spec? I doubt it.

**Comment by khellang** [comment]
@MeirionHughes Where can you find `IAppBuilder` in the spec? :wink:
