### ISSUE TITLE
AutoRegister doesn't work with OWIN self host?

### ISSUE THREAD

**Issue by tpluscode** [NancyFx/Nancy#2324]
Hi. I'm not sure what I'm doing wrong. I'm self-hosting Nancy using OWIN and my dependencies aren't getting automatically registered with TinyIoC unless I explicitly refer any type from the assembly. On the other hand, when IIS hosted the application works fine. I haven't found any mention about such behavior. 

For a repro you can have a look at https://github.com/tpluscode/nancy-selfhost-autoregister. NancyRegistration project is the self-hosted application. Uncomment the `typeof` and it works. Otherwise it doesn't. NancyIIS project always works super-duper-happy

**Comment by jchannon** [comment]
Try adding `[assembly: IncludeInNancyAssemblyScanning]` to your AssemblyInfo in you dependency project

**Comment by tpluscode** [comment]
Thanks. I'm aware of this attribute but what if I can't or don't want to add a reference to Nancy? Such as in a shared or 3rd party library

**Comment by jchannon** [comment]
Only other option I can think of is to reference the project from the host project, in your sample the NancyRegistration project.

@thecodejunkie might know of a better way

**Comment by grumpydev** [comment]
Use the AppDomainAssemblyTypeScanner to load the assembly is the only way unless you have a hard reference between the two (which is what the attribute does, and what referring to a type explicitly also does) - the wonders of .net's "clever" assembly loading.

**Comment by tpluscode** [comment]
So the difference between self-host and IIS is buried in the framework itself?

**Comment by grumpydev** [comment]
Yep, asp.net loads everything in the bin folder by default:

http://stackoverflow.com/questions/508034/how-to-stop-asp-net-from-loading-all-assemblies-from-bin-on-first-load

**Comment by tpluscode** [comment]
I see. Thanks. 
Closing then. Nothing to see here

**Comment by wtilton** [comment]
Is there any documentation on this anywhere? How would it work with the 2.0 alpha? I've bounced around between versions to see if I can get this working, added the attribute to my dependent projects, tried calling AppDomainAssemblyTypeScanner.LoadAssemblies (but this is now gone in 2.0) in my bootstrapper's ConfigureApplicationContainer method and nothing is working. Any ideas on what I'm doing wrong?

Nancy.TinyIoc.TinyIoCResolutionException
Unable to resolve type: Services.Contracts.IDataService
at Nancy.TinyIoc.TinyIoCContainer.ResolveInternal(TinyIoCContainer.TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) 
at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
