### ISSUE TITLE
Cannot hook pipeline for static files

### ISSUE THREAD

**Issue by MeirionHughes** [NancyFx/Nancy#2328]
I've added this to the pipeline: 
```cs
ApplicationPipelines.BeforeRequest += ((ctx) => {
    LogTo.Info($"{ctx.Request.UserHostAddress} - {ctx.Request.Method} {ctx.Request.Path}");
    return null;
});
```
Which works great for everything apart from static files. Nothing I've tried allows to me see the static files in the before or after request pipelines.  I'm hosting Nancy in Nowin and its the only middleware. Am I missing something? Version: 1.4.3

**Comment by thecodejunkie** [comment]
Hi,

This is not possible because the static content handler is executed before the request pipeline. There would be a substantial performance overhead if each request, for a static file, would have to be put through the pipelines. The only way you could get this behaviour was if you didn't use the `IStaticContentProvider` and used a module to handle static content

**Comment by MeirionHughes** [comment]
then this contradicts with the documentation that states it is part of the pipeline? 

> Nancy supports multiple static content conventions at once and is shipped with a default convention that will look for files in the /Content path of your application. The static content handler in Nancy is executed as a BeforeRequest filter in the application pipeline.

https://github.com/NancyFx/Nancy/wiki/Managing-static-content

**Comment by thecodejunkie** [comment]
Yes, that used to be true but was changed quite a while ago. Thanks for
pointing it out, I will update the documentation ASAP

**Comment by MeirionHughes** [comment]
Okay cool, no problem. I suppose I can add owin middleware to do the logging before Nancy.

**Comment by jchannon** [comment]
This may help https://github.com/VQComms/TracingMiddleware

**Comment by MeirionHughes** [comment]
If useful, I solved for the AfterReques case with a hook into `OnSendingHeaders` owin event. 

```
app.Use(new Func<AppFunc, AppFunc>(next => (async context =>
{
    var sendingHeaders = (Action<Action<object>, object>) context["server.OnSendingHeaders"];

    sendingHeaders(state =>
    {
        var ip = context["server.RemoteIpAddress"];
        var port = context["server.RemotePort"];
        var method = context["owin.RequestMethod"];
        var path = context["owin.RequestPath"];
        var status = context["owin.ResponseStatusCode"];

        LogTo.Info($"{ip}:{port} - {method} {path} - {status}");

    }, context);

    await next.Invoke(context);
})));
```
