### ISSUE TITLE
Internal Error with static-files direct from root

### ISSUE THREAD

**Issue by MeirionHughes** [NancyFx/Nancy#2332]
I have a `IRootPathProvider` that links directly to the root path of the static content. 
Without a static-file convention I get 404s. 
With a static-file convention: 
```cs
StaticContentConventionBuilder.AddDirectory("/", "/"));
```
Any requests for static files results in 500 server error; (no errors on the application pipeline either)

if I move everything into sub-folder static
```cs
StaticContentConventionBuilder.AddDirectory("/", "/static"));
```
... it all works.

**Comment by phillip-haydon** [comment]
This is by design. It's too hard to manage security around allowing statics from the root directory and trying to figure out if a path is a route or static. 

You should always load your static data from a sub directory so people don't navigate to your bin or config files.

**Comment by MeirionHughes** [comment]
Is there a way to have routes respond with a files direct from the static-handler then? 

I *want* to do this: `Response.AsFileFromStatic("login.html", "text/html");`, but 
I have to do this:  `Response.AsFile("static/login.html", "text/html");`

That means all my modules will be coupled to the directory name.

If I want to configure it, now I have to inject that information and do something like: 
`Response.AsFile($"{settings.StaticFolder}/login.html", "text/html");`

which doesn't seem happy-path like. :P

I can go with convention for now.
