### ISSUE TITLE
Nancy.Tests.Functional skipped by build.ps1/AppVeyor

### ISSUE THREAD

**Issue by akoeplinger** [NancyFx/Nancy#2334]
https://github.com/NancyFx/Nancy/commit/3b271649e64882907cb5ea78ecba9e0c9cc67f7d added a filter to only run tests ending in *Tests.xproj, but Nancy.Tests.Functional.xproj doesn't follow this convention so it is skipped on build.ps1 and AppVeyor. Is that intentional?

**Comment by thecodejunkie** [comment]
:heart:
