### ISSUE TITLE
Make Nancy work under UWA/UWP

### ISSUE THREAD

**Issue by HakanL** [NancyFx/Nancy#2347]
UWA for Windows 10 (IoT for example) uses the dotnet moniker, would it be possible to use Nancy on this platform?

**Comment by thecodejunkie** [comment]
Currently for rc1 we are targeting `dotnet54` and once rc2 lands we are likely to end up on `netstandard1.2` (or higher, it's not been decided yet)

**Comment by vsmike** [comment]
Any word on Nancy supporting UWP at this point last message what in Mar

**Comment by thecodejunkie** [comment]
@vsmike as far as I know - nobody in the core team uses UWP so I have no idea what it would require to make it work

**Comment by HakanL** [comment]
If Nancy supports one of the netstandards then it should automatically work with UWP.

**Comment by thecodejunkie** [comment]
The 2.0 pre-release supports netstandard 1.6

**Comment by stefaanv** [comment]
Unfortunately,
When I try to NuGet Nancy in a Core IoT UWP application, I get a lot of error message like the ones below.  My target platform is a Raspberry Pi 3 running Windows 10 IoT core (version 10.0.14393.0).  Am I overlooking something ?  I'd love to get Nancy working on this platform.
Any Ideas on how I can solve this ?

```
Installing Nancy 2.0.0-barneyrubble.
Nancy 2.0.0-barneyrubble is not compatible with UAP,Version=v10.0.
Some packages are not compatible with UAP,Version=v10.0.
Nancy 2.0.0-barneyrubble is not compatible with UAP,Version=v10.0 (win10-arm).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
Nancy 2.0.0-barneyrubble is not compatible with UAP,Version=v10.0 (win10-arm-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).

```

**Comment by thecodejunkie** [comment]
We target `net452` and `netstandard1.6` so unless UAP is covered in any of those, then no then it will not be possible to use Nancy with it as it stands now
