### ISSUE TITLE
Diagnostics on OWIN+IIS

### ISSUE THREAD

**Issue by tpluscode** [NancyFx/Nancy#2348]
I've just noticed that Nancy diagnostics doesn't work when hosted on IIS with OWIN. The diagnostics page throws a number od 404s for all the static content:

![missing assets](http://i.imgur.com/PWcuqxP.png)

Apparently it is only a problem with `Microsoft.Owin.Host.SystemWeb`. Works fine on selfhost (both OWIN and Nancy) as well as `Nancy.Hosting.Aspnet`. Am I missing some package maybe?

**Comment by khellang** [comment]
What versions are you using? Can you show your web.config? This sounds like an IIS misconfiguration. It's probably trying to serve static files before Nancy gets the chance.

**Comment by khellang** [comment]
I think you might need to go through this step: https://github.com/NancyFx/Nancy/wiki/Managing-static-content#extra-steps-required-when-using-microsoftowinhostsystemweb

**Comment by tpluscode** [comment]
Ah yes that was it. Thank you. I missed the link on OWIN wiki page
