### ISSUE TITLE
PUT method has Daylight savings DateTime deserialization issue on Bind

### ISSUE THREAD

**Issue by brkx** [NancyFx/Nancy#2349]
I've encountered strange behaviour on Bind() method when deserializing DateTime objects which fall into Daylight savings time calculations. The problem appears only on parsing RequestPayload of PUT method while on POST it works as expected.
Please find the project showing the explained problem attached: [date-serialization.zip](https://github.com/NancyFx/Nancy/files/169375/date-serialization.zip)
The versions of packages are the ones on my production. The latest currently available package versions don't fix the issue

**Comment by brkx** [comment]
It seems that the Json serializer used for RequestPayload on PUT was ignoring the local server time.
I need to test it the full extent yet but by the looks of it adding 
`DateTimeZoneHandling = DateTimeZoneHandling.Local;`
in the CustomJsonSerializer looks like it have solved the problem.

**Comment by jchannon** [comment]
Please pull latest master branch and check again. Work as been done on DateTime processing.

Re-open if issue not fixed
