### ISSUE TITLE
__NCTRACE behaviour difference between v1 & v2

### ISSUE THREAD

**Issue by jchannon** [NancyFx/Nancy#2350]
In v1 this cookie doesn't seem created when there is general usage of an app with Diagnostics turned on.

In v2 this cookie is created in general usage of an app.

By general usage I just mean hitting API endpoints.

I think its because I'm running in debug mode, the below link returns true and in the engine it checks if tracing enabled and if so a cookie is created.  This seems like a flaw to me. 

Code workflow goes from these links:

https://github.com/NancyFx/Nancy/blob/master/src/Nancy/NancyEngine.cs#L156

https://github.com/NancyFx/Nancy/blob/master/src/Nancy/DefaultTraceConfigurationProvider.cs#L26

https://github.com/NancyFx/Nancy/blob/master/src/Nancy/DefaultRuntimeEnvironmentInformation.cs#L32

**Comment by thecodejunkie** [comment]
This has nothing to do with diagnostics. It looks like we changed how the default value, for determining if tracing should be enabled or not, has changed

- Old - do nothing, default to `false` https://github.com/NancyFx/Nancy/blob/1.x-WorkingBranch/src/Nancy/StaticConfiguration.cs#L102
- New - default to `IRuntimeEnvironmentInformation,IsDebug`

In the old code only [DisableErrorTraces](https://github.com/NancyFx/Nancy/blob/1.x-WorkingBranch/src/Nancy/StaticConfiguration.cs#L28) where set based on the debug state. I think we should change https://github.com/NancyFx/Nancy/blob/master/src/Nancy/DefaultTraceConfigurationProvider.cs#L30 to be `false` by default

**Comment by jchannon** [comment]
Agreed

**Comment by jchannon** [comment]
Also why doesn't TraceConfiguration have a static default instance like the
other configuration classes ?

**Comment by thecodejunkie** [comment]
@jchannon probably because one of the default values isn't a static
