### ISSUE TITLE
Diagnostics information not displayed when custom bootstrapper lacks a parameterless constructor

### ISSUE THREAD

**Issue by xt0rted** [NancyFx/Nancy#2352]
My bootstrapper's constructor takes in a TinyIoC instance since I'm creating that in my Startup class for use elsewhere. As a result the diagnostics information page doesn't display anything because it's crashing on the call to [NancyBootstrapperLocator.Bootstrapper](https://github.com/NancyFx/Nancy/blob/d680275aa192c76fa061ab1f293197beaad1a9b5/src/Nancy/Diagnostics/Modules/InfoModule.cs#L40).

When using nancy as middleware should we be setting `NancyBootstrapperLocator.Bootstrapper` to whatever custom instance we're using? I know a lot of the static config removal was done to allow running multiple instances of nancy so we should probably be storing this somewhere else instead. Maybe add it to the owin environment and then remove it before going to the next piece of middleware?

For now I'm working around this with a parameterless constructor.

**Comment by jchannon** [comment]
You can pass your tinyioc instance to your bootstrapper in the UseNancy
middleware then in your bootstrapper override ApplicationContainer and set
it to your passed in instance

**Comment by xt0rted** [comment]
That's how my bootstrapper & middleware is setup and the reason the diagnostics page crashes. The nancy middleware doesn't assign the custom bootstrapper to `NancyBootstrapperLocator.Bootstrapper` which is used to get the type name. So since that was never assigned it's trying to create a new instance but can't since there's no parameterless constructor.

**Comment by jchannon** [comment]
Can you show the code you have including the bstrapper?

**Comment by xt0rted** [comment]
```c#
public partial class Startup
{
    public void Configuration(IAppBuilder app)
    {
        var container = SetupTinyIoC();

        app.UseNancy(options =>
        {
            options.Bootstrapper = new Bootstrapper(container);
            options.PassThroughWhenStatusCodesAre(HttpStatusCode.NotFound);
        });
        app.UseStageMarker(PipelineStage.MapHandler);
    }
}
```

```c#
public class Bootstrapper : DefaultNancyBootstrapper
{
    private readonly TinyIoCContainer _container;

    public Bootstrapper(TinyIoCContainer container)
    {
        _container = container;
    }

    protected override DiagnosticsConfiguration DiagnosticsConfiguration => new DiagnosticsConfiguration { Password = "abc123" };

    protected override TinyIoCContainer GetApplicationContainer()
    {
        return _container;
    }
}
```

Setting the bootstrapper that way bypasses the call to [NancyBootstrapperLocator.Bootstrapper](https://github.com/NancyFx/Nancy/blob/d680275aa192c76fa061ab1f293197beaad1a9b5/src/Nancy/Bootstrapper/NancyBootstrapperLocator.cs#L25) as seen in [NancyOptions.cs#L20](https://github.com/NancyFx/Nancy/blob/d680275aa192c76fa061ab1f293197beaad1a9b5/src/Nancy/Owin/NancyOptions.cs#L20). So when a call to that is made in [InfoModule.cs#L40](https://github.com/NancyFx/Nancy/blob/d680275aa192c76fa061ab1f293197beaad1a9b5/src/Nancy/Diagnostics/Modules/InfoModule.cs#L40) it tries to create a new bootstrapper instance and then crashes.

**Comment by khellang** [comment]
There is a quick solution to this; add a default ctor :wink:
