### ISSUE TITLE
Optional datetime with default values

### ISSUE THREAD

**Issue by StefanRKarlsson** [NancyFx/Nancy#2353]
As the heading says, is this possible?

**Tried this without luck:**
```
Get["/{fromDate?" + new DateTime(DateTime.Now.Year, 1, 1) + ":datetime}/{toDate?" + new DateTime(DateTime.Now.Year, 12, 31) + ":datetime}"] = parameters =>
             {
//....
};
```

**Comment by jchannon** [comment]
I don't believe so but when you get the value of parameters into a variable
you can set a default in the Default method or in the TryParse method here
https://github.com/NancyFx/Nancy/blob/df8722d11e983029446d48d5b08740d9dad24218/src/Nancy/DynamicDictionaryValue.cs#L49

**Comment by thecodejunkie** [comment]
@jchannon provided the correct resolution to this. If you have any further questions, please let us know. In the meantime I will close this
