### ISSUE TITLE
Self-hosting on mono (OS X) fails for multiple URIs

### ISSUE THREAD

**Issue by mteper** [NancyFx/Nancy#2359]
Given this code:

```cs
				var uris = new []
					{
						new Uri("http://localhost:1234"),
						new Uri("http://127.0.0.1:1234")
					};
				using (var host = new NancyHost(uris))
				{
					host.Start();

					Console.ReadLine();
				}
```

The host will start without error, however navigating to http://localhost:1234 will yield a 400 (Bad Request) response, while http://127.0.0.1:1234 will work correctly.

**Comment by jchannon** [comment]
Register localhost only. The should be able to browse to both localhost and
127.0.0.1

**Comment by khellang** [comment]
By default, Nancy will rewrite `http://localhost:1234` to `http://+:1234` (see `RewriteLocalhost` [on the wiki](https://github.com/NancyFx/Nancy/wiki/Self-Hosting-Nancy)). This means that I'll bind to any adapter, so you should get by with `localhost` only.

**Comment by mteper** [comment]
@jchannon, @khellang 

Here's a little more context.

You are right that if I *only* specify `localhost`, when things work, they seem to work as you describe: I can access the server via both locahost and loopback URIs. There's a question of why it works (browsing mono source, I don't see them supporting the "+" as host, but maybe I am just misreading code here https://github.com/mono/mono/tree/master/mcs/class/System/System.Net), but that's beside the point.

The problem I am trying to solve is that for a small percentage of my users, out in the wild, `localhost` doesn't seem to work. I have not been able to reproduce this in-house, so largely taking stabs in the dark here, and was attempting to experiment with explicit loopback / localhost registrations.

**Comment by khellang** [comment]
If you'd rather specify everything yourself, you just set the setting I linked (`RewriteLocalhost`) to `false`. It's really hard for us (and you) to be able to work anything out without more info, like what the environment looks like, i.e. Nancy version, Mono version, OS (version) etc. etc. There are many things that could get you a 400 response in return :smile:

**Comment by khellang** [comment]
Also, `*` and `+` prefixes in Mono are handled at https://github.com/mono/mono/blob/048ed1a6b2ee769a3aa488e9ab615012b270ba83/mcs/class/System/System.Net/EndPointListener.cs#L287

**Comment by mteper** [comment]
@khellang 

> If you'd rather specify everything yourself, you just set the setting I linked (RewriteLocalhost) to false. 

Ah, I see, OK I'll try that.

> Also, * and + prefixes in Mono are handled at ...

Yup, that's the code file I was looking at, but GitHub search must have handed me a copy from some ancient branch since it didn't have the "+" logic. Thanks, at least I don't have to wonder about this any more!

> ... what the environment looks like, i.e. Nancy version, Mono version, OS

NancyFx: 1.4.3
Mono: 4.2.2
OS: OS X El Capitan

**Comment by khellang** [comment]
> GitHub search must have handed me a copy from some ancient branch since it didn't have the "+" logic

Heh, that must be a really ancient branch, cause that logic has been there since the class [was introduced in 2005](https://github.com/mono/mono/commit/3e700ee55199ebd016856f9b438dab0d4fac0b03#diff-6eebad59ccd3da49d7491a369d9a8053R212) :wink: 

> NancyFx: 1.4.3
> Mono: 4.2.2
> OS: OS X El Capitan

Is this the environment you're able to reproduce this on?

**Comment by mteper** [comment]
@khellang 

> Heh, that must be a really ancient branch ...

I was looking here: https://github.com/mono/mono/blob/3fda636ef7cf3c31625e260b595aed436e16e2ae/mcs/class/System/System.Net/EndPointManager.cs#L85  :sob: 

> Is this the environment you're able to reproduce this on?

Depends on which "this" you are referring to. It's my environment and I am able to reproduce the issue I described here (which is not a real issue, as you suggested). It's also a match for my user's environment (to which I don't have access) for whom my app crashes w/o giving up any useful info when initializing NancyFx and that's the problem I am ultimately trying to get to the bottom of.

We can close this case, as the following code works and enables me to access the endpoint both via `localhost` and loopback IP address:

```cs
var x = new HostConfiguration() { RewriteLocalhost = false };
using (var host = new NancyHost(x, new[] { new Uri("http://localhost:1234"), new Uri("http://127.0.0.1:1234") }))
{
	host.Start();
	// ...
}
```

Thanks!!

**Comment by pinkli** [comment]
I've encontered a similar issue here running Mono on OSX El Capitan.
```
var host = new NancyHost(new Uri("http://127.0.0.1:8888"));
host.Start();
```
this works fine. But,
```
var host = new NancyHost(new Uri("http://localhost:8888"));
host.Start();
```
gives me runtime SocketException "invalid address in this context" in host.Start(); line.
But when deployed to a Ubuntu server, it works great.

And it works when add a HostConfiguration with RewriteLocalhost = false.
```
var conf = new HostConfiguration() { RewriteLocalhost = false };
var host = new NancyHost(conf, new Uri("http://localhost:8888"));
host.Start();
```
The strange thing is that, i can only access  on local machine with exactly the same uri in code. 
Accessing `http://localhost:8888` gives me "Bad Request (Invalid host)" when coding `new Uri("http://127.0.0.1:8888")`.
Another strange thing, I can not access from local LAN by IP address, that said from machine 192.168.1.120 to this dev Mac 192.168.1.130.
Using node.js package `http-server`, I have none of these issues: on local machine, http://127.0.0.1 and http://localhost works equally, and acess by LAN IP with no problem.
I don't know if there are some quirks in my Mac machine, or is something not right in NancyHost or Mono?

My environment:
Mac OSX El Capitan
Nancy 1.4.1
Mono 4.2.3

My hosts file:
```
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
fe80::1%lo0	localhost
```

Need your help.

**Comment by khellang** [comment]
What if you use `http://*:8888`?

This isn't something we can do much about. Nancy simply takes the URL, replaces `localhost` with `+` (wildcard) if `RewriteLocalhost` is `true` and passes it to the `HttpListener`. `HttpListener` is Mono.

**Comment by pinkli** [comment]
@khellang 
using `http://*:8888` gives System.UriFormatException "invalid URI: the hostname could not be parsed".

**Comment by khellang** [comment]
And `http://+:888`?

**Comment by pinkli** [comment]
Same exception as `http://*:8888`

**Comment by pinkli** [comment]
Update:
when deployed to Ubuntu server, the `localhost` version works, '127.0.0.1' gives "bad request(invalid host)".
code is just simple hello world.
running as `mono nancytest.exe -d`

Env:
Ubuntu 14.04 server freshly setup 
Mono 4.2.3

**Comment by khellang** [comment]
Hmm. I wonder if this can be an IPv4 vs IPv6 issue? 127.0.0.1 is certainly a valid host.

**Comment by pinkli** [comment]
update:
sorry for the Ubuntu server thing, I miss-configured the Nginx proxy.
