### ISSUE TITLE
Nancy tries to create new bootstrapper when I have supplied one.

### ISSUE THREAD

**Issue by hvidgaard** [NancyFx/Nancy#2366]
I'm trying to inject a Ninject kernel from my OWIN startup method into Nancy by creating a bootstrapper with the kernel:

`app.UseNancy(options => { options.Bootstrapper = new Bootstrapper(kernel); });`

However, when a request comes in, I get exception because there is no parameterless constructor.

```
[BootstrapperException: Could not initialize bootstrapper of type 'WebApi.Bootstrapper'.]
   Nancy.Bootstrapper.NancyBootstrapperLocator.LocateBootstrapper() +129
   Nancy.Bootstrapper.NancyBootstrapperLocator.get_Bootstrapper() +32
   Nancy.Hosting.Aspnet.NancyHttpRequestHandler.GetBootstrapper() +47
   Nancy.Hosting.Aspnet.NancyHttpRequestHandler..cctor() +25
```

Am I mistaken in expecting only one instance of the bootstrapper to be created, or is it a bug?

**Comment by khellang** [comment]
Can you post your `Startup.cs`? I've personally done this many times, and I know it works. What versions are you using?

**Comment by khellang** [comment]
Ah, now I see what happens! You've installed the Nancy.Hosting.Aspnet package. See `Nancy.Hosting.Aspnet.NancyHttpRequestHandler` in the stack trace. You don't need that host when you're hosting on OWIN.

**Comment by hvidgaard** [comment]
That was the issue. Not sure why it was there in the first place. Thanks for the very quick response.
