### ISSUE TITLE
Alternatives to Token Authentication

### ISSUE THREAD

**Issue by SaberZA** [NancyFx/Nancy#2374]
Hi,

I've been using Token Authenticaiton from Nancy for 6 six months and is now coming under deprecation.

What middleware can you recommend that we switch over to, instead of Nancy Token Auth?

Thanks

**Comment by SlavaBobik** [comment]
Perhaps you should use Stateless Authentication, if I correctly understand you.
Also you can implement yours middleware for e.g based on [JWT](http://mikehadlow.blogspot.ru/2014/04/json-web-tokens-owin-and-angularjs.html).

**Comment by xt0rted** [comment]
If you're using Nancy as owin middleware then you could use [Microsoft.Owin.Security.Jwt](https://www.nuget.org/packages/Microsoft.Owin.Security.Jwt/). I just used this to secure an API I've been working and it was pretty easy to setup and use.

**Comment by jchannon** [comment]
There is Owin.StatelessAuth also
