### ISSUE TITLE
Internal server error (500)

### ISSUE THREAD

**Issue by tidusjar** [NancyFx/Nancy#2376]
Any one know what's going on this this issue: https://github.com/tidusjar/PlexRequests.Net/issues/50

It doesn't seem to be anything related directly to my application. It seems to work for everyone but not Ubuntu. There has been a few reports of this error.

**Comment by tidusjar** [comment]
Anyone have an idea?

**Comment by khellang** [comment]
I left a comment on https://github.com/tidusjar/PlexRequests.Net/issues/50. TBH, I think this smells like a Mono bug, but without knowing more about what's passed down the stack, it's hard to know for sure.

**Comment by tidusjar** [comment]
@khellang Thanks, I have raised a bug on mono's bug tracker. Is there any information I could provide you with further?

**Comment by khellang** [comment]
I think we can close this as a Mono bug?

**Comment by tidusjar** [comment]
@khellang Agreed
