### ISSUE TITLE
raml generation tool for api

### ISSUE THREAD

**Issue by GomesNayagam** [NancyFx/Nancy#2377]
How do i generate raml documentation for my api( nancy module)

**Comment by jchannon** [comment]
You would have to do that yourself however we do a couple of ways to read information about routes in your API. One being a metadata module. Here's a couple of examples:

https://github.com/khellang/Nancy.Swagger/blob/master/samples/Nancy.Swagger.Demo/Modules/HomeMetadataModule.cs

https://github.com/khellang/Nancy.Swagger/blob/master/samples/Nancy.Swagger.Demo/Modules/HomeMetadataModule.cs

You'll see the latter is from a Swagger library in which it uses the metadata modules to build up the json files that swagger needs to read the information about the API.

That library is looking for someone to maintain it if interested in helping out, if not I imagine you'll have to start your own raml library.

You can also use this example:

https://github.com/NancyFx/Nancy/blob/4a6f848b3830714264212c8917708e1e47fe01fb/samples/Nancy.Demo.Hosting.Aspnet/DefaultRouteMetadataProvider.cs

used here:

https://github.com/NancyFx/Nancy/blob/4a6f848b3830714264212c8917708e1e47fe01fb/samples/Nancy.Demo.Hosting.Aspnet/MainModule.cs#L28
