### ISSUE TITLE
Add GitVersion?

### ISSUE THREAD

**Issue by asbjornu** [NancyFx/Nancy#2379]
Seeing commits such as a1035ca1db35c2cec69719db65f1a0a708dec776 makes me think that this project could use a little [GitHubFlow](https://guides.github.com/introduction/flow/) and [GitVersion](/GitTools/GitVersion) to make versioning the assemblies and having a [continuous delivery](http://gitversion.readthedocs.org/en/latest/reference/continuous-delivery/) strategy (with unique, auto-generated version numbers) easier.

Right now, GitVersion is Windows-only, but in v4.0 it's going to be x-plat, so I'm just wondering if adding this is something that's interesting to receive a PR for or not.

What I would do is add a development reference to [GitVersionTask](https://www.nuget.org/packages/GitVersionTask), which is an MSBuild task that auto-generates `Assembly*Version` attributes at compile time. The generated version number is dependent on which branch is built and how many commits it is ahead of the last tag on the `master` branch.

Having GitVersionTask in place makes separate version number bump commits unnecessary, since the version number is auto-generated at compile time.

Thoughts?

**Comment by thecodejunkie** [comment]
Short answer; no.

Longer: No, we have quite a complicated release process (look at the Nancy.Build repo) that involves building, testing, updating 25 nuges, spread over 9 repositories, linked by git submodules. For the time we're going to leave that as-is and might take a bigger stab at changing that process in the future

**Comment by thecodejunkie** [comment]
Oh and that commit is required, but other repos uses Nancy's SharedAssemblyInfo.cs though a sub-module to get the current version

**Comment by asbjornu** [comment]
@thecodejunkie Thanks for the explanation. :smiley:

**Comment by thecodejunkie** [comment]
Sorry for the brevity, I was in the middle of releasing `2.0-alpha` :stuck_out_tongue:
