### ISSUE TITLE
OnError +=

### ISSUE THREAD

**Issue by sjblom** [NancyFx/Nancy#2380]
Hi there,

I'm very new to Nancy, so, excuse me if this have been answered before.

I have the following snippet:

 **_pipeLines.OnError += (context, exception) => HandleException(context, exception);_**

I keep on getting: error **CS0019: Operator '+=' cannot be applied to operands of type 'ErrorPipeline' and 'lambda expression'**

My project is in fact targeting .NET 4.5, I even had it targeting .NET 4.6.

Any suggestions?

Thx

**Comment by grumpydev** [comment]
This (unhelpful) compiler error is normally because you have the signature of something wrong, probably the "HandleException" method?

**Comment by sjblom** [comment]
Thank you very much, I will check it out... :)

**Comment by patridge** [comment]
@sjblom Does your `HandleException` method happen to return anything?

I ran into the same issue. In looking at the code, I tried to swap for  what the `+` operator calls anyway, `pipelines.OnError.AddItemsToEndOfPipeline((ctx, ex) => …);`, which gave me a much better error message. Apparently, this lambda needs to return a `dynamic` to be valid.

> Error CS1643: Not all code paths return a value in anonymous method of type `System.Func<Nancy.NancyContext,System.Exception,dynamic>'

I haven't found any best practices on what to return from these methods and when to do so, and the docs currently just show a sample that does a `return null`. Heading back to the source again, though, and it seems all the items in the pipeline get called [until something does return a response](https://github.com/NancyFx/Nancy/blob/4d21032addaf32fc6d860e2151b6a8a5ca718238/src/Nancy/ErrorPipeline.cs#L56), so maybe that is what I need for my particular situation: I don't slow any default behavior down, just log the issue externally. If that is true of your situation, you could do the same.

```C#
pipeLines.OnError += (context, exception) => {
    HandleException(context, exception);
    return null;
};
```

**Comment by psibernetic** [comment]
Thanks @patridge the `.AddItemsToEndOfPipeline(` call will be useful.
