### ISSUE TITLE
Nancy Owin self host with reverse proxies

### ISSUE THREAD

**Issue by tidusjar** [NancyFx/Nancy#2383]
Hello again! 

I have a few people attempting to use my application with some sort of reverse proxy (Ngnix). 

I have read all of the documentation but I'm finding it difficult to get it to work correctly.

Can anyone lead me in the right direction?

(Plex Requests.Net issue: https://github.com/tidusjar/PlexRequests.Net/issues/72)

Thanks again

**Comment by jchannon** [comment]
Left a comment on the linked issue
