### ISSUE TITLE
filename changed by nancy when downloading

### ISSUE THREAD

**Issue by xcalibre0** [NancyFx/Nancy#2391]
My code is below.  I go to that route/url in my browser and i'm served a file called blah. Nancy is renaming the file to the name of the route.  What am i doing wrong?  Either way this doesnt seem happy path to me.

```
            Get["/tools/blah"] = _ =>
            {
                return Response.AsFile("content/tools/blah.msi", "application/x-msi");
            };
```

**Comment by khellang** [comment]
This isn't something Nancy is doing. This is the default behavior for browsers, where the server doesn't provide a `Content-Disposition` header. If you add that header with the corresponding parameters, like `filename`, the browser should download the file with the correct name.

**Comment by xcalibre0** [comment]
Then I might suggest that the happy path would be, at least, to provide your use the ability to set that disposition thingy.

I might characterize teh issue as "this is something that nancy is NOT doing"

**Comment by thecodejunkie** [comment]
@xcalibre0 you are going to want to use the [AsAttachment](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/ResponseExtensions.cs#L22) extension to do this

**Comment by xcalibre0** [comment]
BAM! perfecto!

Does exactly what i wanted, thank you :D

**Comment by phillip-haydon** [comment]
![](https://s-media-cache-ak0.pinimg.com/236x/af/fa/05/affa05228aba3241a51e5e5564e95729.jpg)

**Comment by xcalibre0** [comment]
now can we make so it works wether i put /content or content/ :-D
