### ISSUE TITLE
Nancy 2.0-alpha upgrade feedback

### ISSUE THREAD

**Issue by thecodejunkie** [NancyFx/Nancy#2396]
We are trying to collect feedback on the `2.0-alpha` pre-release of Nancy. We are looking for both people with existing applications, whom are willing to update to `2.0-alpha` (evaluation purpose only, we are not asking you to put it into production) and share their experience as well as people whom would just like to try out the new bits and share their though and experiences.

Currently we are mostly looking for:
- Pain points while upgrading from `1.x` to `2.0-alpha`
- Any stability issues (hanging requests, exceptions, performance and so on)?

But, of course, if you come across anything else then we will happily accept that feedback as well.

If you find any problems, please [open an issue](https://github.com/NancyFx/Nancy/issues/new) and provide as much information, as possible, to help us identify your problem. Alternatively, feel free to submit a [pull-request](https://github.com/NancyFx/Nancy/pulls) if you think you can help resolve the problem. If you need a guiding hand, on how to get started with pull-requests, please have a look at our [contributing](https://github.com/NancyFx/Nancy/blob/ab80c22b3aa5226a860b84cc65a90660c10fb88f/.github/CONTRIBUTING.md) guidelines. Make sure you don't miss the [style guidelines](https://github.com/NancyFx/Nancy/blob/ab80c22b3aa5226a860b84cc65a90660c10fb88f/.github/CONTRIBUTING.md#style-guidelines), I won't :D

> **NOTE:** Because Nancy 2.0-alpha is a pre-release, you are going to have to install packages using the `-pre` toggle, i.e `install-package Nancy -pre`

Please use this issue for posting comments that are not directly related to any specific reported bug or pull-request.
## Resources
- We have put together a brief (living documentation, will be updated as we move forward) [Nancy v2 Upgrade Notes](https://github.com/NancyFx/Nancy/wiki/Nancy-v2-Upgrade-Notes) post that highlights some of the things that have changes, along with proposed workarounds
- You can find a draft of the new Configuration API documentation [here](https://github.com/NancyFx/Nancy/wiki/Configuration-API-%28Draft%29)

THANK YOU for helping us with testing `2.0-alpha`! Your feedback is going to help us move forward with a stable release

**Comment by xt0rted** [comment]
Next week I should have the time to send a PR for #1577 so we can get that in to v2

I've also got a site for my own use that I could try updating to the v2 betas. I've been running it on preview builds all along so if v2 is far enough along now I'll give that a try.

**Comment by thecodejunkie** [comment]
Replaced by #2659
