### ISSUE TITLE
calling custom class inside NancyModule

### ISSUE THREAD

**Issue by anishpsla** [NancyFx/Nancy#2400]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of Nancy
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### System Configuration

- Nancy version:
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

--------

I am trying to write add a web ui for my application. For that, I want to display a list that get from a class. I add an instance of my class and use that to call a method and pass to result into view. But I am getting series of errors. My code is like this

```CS
using System;
using System.Windows;
using Nancy.Hosting.Self;
using Nancy;
using Nancy.ViewEngines.Razor;
using System.Collections.Generic;
using Nancy.ModelBinding;

namespace Nancy_test
{
    public class MainModule : NancyModule
    {
        MkAdmin MikroAdmin = new MkAdmin();
        public MainModule()
        {
            Get["/"] = x =>
            {
                this.ViewBag.test = "test";
                this.ViewBag.userlist = MikroAdmin.GetUsers();
                return View["index/index"];
            };
        }
    }
}
```

**Comment by thecodejunkie** [comment]
@anishpsla in order for us to help you are are going to have to tell you what errors you are seeing. Just viewing the code alone makes it impossible know what runtime exceptions you are seeing. We have been working on issue templates and I would like for you to fill it out for us. I have updated your post with the template that we will be using. Please fill it out so we can help you. Thanks

**Comment by thecodejunkie** [comment]
@anishpsla any updates on this?
