### ISSUE TITLE
Accessing a public IP hosted through Nancy

### ISSUE THREAD

**Issue by kshkrao3** [NancyFx/Nancy#2411]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I was trying to access a system with public IP which I started with local IP. Say for ex: My system has local IP 192.168.100.85 and it has been assigned with public IP say 203.91.140.65. I started a host with below IP https://192.168.100.85:9000 and this I tried to access with https://203.91.140.65:9000. This does not allow me to access the public IP. Not sure what is blocking the way, but I can telnet and RDP the public IP. Does Nancy has any special blocking for these type of request?

- Nancy host
  - [x] ASP.NET
  - [x] Self-Hosted
  
- Environment (Operating system, version and so on): Windows 7
- .NET Framework version:4.0

A post related to this issue in SO.. The **Update** part in the below post specifies what I actually want to do.

**http://stackoverflow.com/questions/36644838/is-it-possible-to-start-host-0-0-0-0port-with-nancy**

**Comment by khellang** [comment]
There's no info here...

**Comment by kshkrao3** [comment]
@khellang Sorry.. Posting for the first time.. Please bare with me.. I've updated the issue.

**Comment by khellang** [comment]
@kshkrao3 What IP did you bind to? When you start Nancy, you specify which addresses you want to bind to. Have you allowed the port through your firewall? See http://stackoverflow.com/questions/9791008/httplistener-not-listening-outside-of-host-computer

**Comment by kshkrao3** [comment]
@khellang I've binded public IP to local IP say IPv4 address something like 192.168.100.54 to 203.91.103.26 and with port 9000 I've started the host.. I can confirm that host has been started with `netstat -a` command. The firewall has been disabled for testing purpose. I can also confirm that telnet to the started IP address and port is successfull.

**Comment by kshkrao3** [comment]
The problem was with URL reservation. I had reserved the URL, but for testing purpose I had rolled it back and forgot again to reserve the URL. After reserving the URL, I was able to access. Thanks for the help @khellang
