### ISSUE TITLE
Unable to access Nancy created host through external IP

### ISSUE THREAD

**Issue by kshkrao3** [NancyFx/Nancy#2416]
### Description
I am creating a Nancy Module that will eventually be hosted inside of a Windows Service. To start the Nancy hosting, I am using Nancy.Hosting.Self. Below is the code to start Nancy host.

```
string strHostProtocol = Convert.ToString(ConfigurationManager.AppSettings["HostProtocol"]);
string strHostIP = Convert.ToString(ConfigurationManager.AppSettings["HostIP"]);
string strHostPort = Convert.ToString(ConfigurationManager.AppSettings["HostPort"]);

//Here strHostProtocol="https", strHostIP = "192.168.100.88" i.e. System IPv4, strHostPort = "9003"

var url = strHostProtocol + "://" + strHostIP + ":" + strHostPort;

//url ="https://192.168.100.88:9003"
this.host = new NancyHost(new Uri(url));
this.host.Start();
```
Now once the windows service starts, it will start the above host and I could see this in `netstat -a` command. When I browse this in browser using **`https://192.168.100.88:9003`** I will get proper response. 

The problem arises when the same is browsed using its external IP. Say this system has been assigned with external IP of `208.91.158.66` and when I try browsing this as **`https://208.91.158.66:9003`** I will just get a browser default loading progress continuosly which does not stop and without any error thrown. I have also added the below command and reserved URL successfully.

`netsh http add urlacl url=https://192.168.100.88:9003/ user=everyone`

But even after this the host cannot be browsed using external IP assigned to that system. Is there any restricting Nancy is putting up? Firewalls are turned off, defenders are turned off. Anyone has any idea on this?

- Nancy host
  - [x] ASP.NET
  - [ ] OWIN
  - [x] Self-Hosted
  - [ ] Other:
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: 4.0

**Comment by khellang** [comment]
When you bind to `https://192.168.100.88:9003`, the TcpListener/HttpListener won't listen on other interfaces. You either have to bind to `https://208.91.158.66:9003` or `https://localhost:9003` and set `RewriteLocalhost = true` (default).

**Comment by khellang** [comment]
You should read more about URL prefixes on https://msdn.microsoft.com/en-us/library/aa364698(v=vs.85).aspx

**Comment by kshkrao3** [comment]
@khellang So, while starting the host I should start using `https://192.168.100.88:9003` and with `netsh http add urlacl url=https://192.168.100.88:9003/ user=everyone` I should bind with `public IP`?

**Comment by khellang** [comment]
If you also want to listen to requests coming to the external IP, yes. Or you could use a wildcard, like `https://+:9003/`, `https://*:9003/` or `https://localhost:9003/` (with `RewriteLocalhost = true`, this will result in `https://+:9003/`). You can read more about them in the link I posted.

**Comment by kshkrao3** [comment]
Bro.. You are god.. :+1: Seriously.. I started host with `localhost` and registered `localhost` with `urlacl` and guess what, it works now. So one last question. It works with any of `https://+:9003/`, `https://*:9003/` or `https://localhost:9003/` right?

**Comment by khellang** [comment]
The first and last will be the same, given that `RewriteLocalhost == true`. They're both a *Strong wildcard*. The one with the asterisk is a bit different. It's a *Weak wildcard*. Again, I urge you to read the documentation I linked above. It explains the difference between the different types of prefixes.

**Comment by kshkrao3** [comment]
@khellang .. Sure I will read it.. By default `RewriteLocalhost` will be `true` right? Thanks much once again,.

**Comment by khellang** [comment]
Yes, it's `true` by default. This is simply to make sure most people don't face these issues when using `https://localhost/`-type prefixes.
