### ISSUE TITLE
Black diagnostics page

### ISSUE THREAD

**Issue by tofutim** [NancyFx/Nancy#2423]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
### Description

I discovered the _Nancy diagnostics page today and tried it on my app. However, when I go to /_Nancy the page is black. I do see what looks like a broken icon. Also the login with the Go which works.

If I look at the html code I see text, and background:black - 
### Steps to Reproduce

```
    protected override DiagnosticsConfiguration DiagnosticsConfiguration
    {
        get
        {
            return new DiagnosticsConfiguration { Password = @"xxx" };
        }
    }
```

then go to localhost:###/_Nancy
### System Configuration
- Nancy version: latest
- Nancy host
  - [x] ASP.NET
  - [x] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version: 4.5
- Additional information:

**Comment by tofutim** [comment]
This is also in VS2015 Debug, and I am overriding in NinjectNancyBootstrapper, I do not see /_Nancy/Resources

**Comment by Sphiecoh** [comment]
As of v2.0.0-alpha the api has changed, this override is no longer applicable. Can you confirm your version ?
The diagnostics are registered as part of INancyEnvironment

**Comment by tofutim** [comment]
I am using 1.4.3 via nuget, but also using the ninject version

**Comment by tofutim** [comment]
I must have missed something because I don't actually have a
_Nancy/Resources/... directory - and that is probably the issue. I can get
to the _Nancy login page, and after logging in, I can go to _Nancy/trace -
but there is no visible text, because I presume the background is black and
the text is black.

**Comment by Sphiecoh** [comment]
That directory is built-in, its included in the nancy.dll.

**Comment by khellang** [comment]
Have you read through the wiki on [hosting with ASP.NET and OWIN](https://github.com/NancyFx/Nancy/wiki/Hosting-nancy-with-owin#katana---aspnet-host)? Specifically the part that mentions

> **NOTE!** You might have to perform an extra step to get custom static content conventions and diagnostics to work

I think that should fix it for you. See https://github.com/NancyFx/Nancy/wiki/Managing-static-content#extra-steps-required-when-using-microsoftowinhostsystemweb

**Comment by xt0rted** [comment]
Does your bootstrapper's constructor take in any parameters? Because if so you'll need to add a parameterless constructor in order for the diagnostics page to load correctly. ref: #2352

**Comment by tofutim** [comment]
Indeed, my bootstrapper takes IKernel as a parameter

**Comment by tofutim** [comment]
Kristian, I was able to get things to work by following the OWIN
directions. Thank you so much for the link, I don't think I would ever have
been able to figure that one out!

**Comment by tofutim** [comment]
Hi, I encountered something odd with this fix. I added to things to be able
to see the _Nancy static files

app.UseStageMarker(PipelineStage.MapHandler);

in the bootstrapper, and

<modules runAllManagedModulesForAllRequests="true"/>

in the Web.Config. This got _Nancy working and everything looked fine.
However, in publishing to Azure, suddenly the .js files in my "Scripts"
folder, e.g., site/Scripts/utils.js were no longer accessible. Reversing
these two changes got them up again. Why would this be?

**Comment by xt0rted** [comment]
Your static content was probably being handled by IIS but with those settings enabled Nancy is trying to handle it. If that's the case then you'll need to add the scripts folder to the static content conventions in your bootstrapper.

```cs
protected override void ConfigureConventions(NancyConventions conventions)
{
    base.ConfigureConventions(conventions);

    conventions.StaticContentsConventions.AddDirectory("scripts");
}
```
