### ISSUE TITLE
HTTP_X_FORWARDED_FOR

### ISSUE THREAD

**Issue by tofutim** [NancyFx/Nancy#2424]
Hi, does anyone know how I can get HTTP_X_FORWARDED_FOR inside of Nancy?

**Comment by thecodejunkie** [comment]
First, there is an issue template for a reason, please make use of it.

Do you mean the header, If so then you can just read it from the headers `this.Request.Headers["HTTP_X_FORWARDED_FOR"]`

**Comment by tofutim** [comment]
Sorry I did not use the template for this one. Turns out I needed


var ipAddress = this.Request.Headers["X_FORWARDED_FOR"];

instead of HTTP_X_FORWARDED_FOR

On Fri, Apr 22, 2016 at 1:57 PM, Andreas Håkansson <notifications@github.com

**Comment by thecodejunkie** [comment]
:

**Comment by thecodejunkie** [comment]
:+1:

**Comment by sx212** [comment]
I also seem to have encountered the same problem, unable to get the IP address of the client through "HTTP_X_FORWARDED_FOR or X_FORWARDED_FOR"

**Comment by Zaid-Ajaj** [comment]
@sx212 Try this:
```cs
string ipAddress = this.Request.UserHostAddress;
```

**Comment by sx212** [comment]
@Zaid-Ajaj  Yes, this method can be obtained, but not the real IP address. I want to get the IP address of the browser. In the case of agent, the IP address obtained is not what I want.
