### ISSUE TITLE
Integrate with Swagger 

### ISSUE THREAD

**Issue by hoangtrongphuc** [NancyFx/Nancy#2425]
Document in Web API is impotant. How can I integrate NancyFx with swagger ?

**Comment by jchannon** [comment]
Take a look here https://github.com/khellang/Nancy.Swagger

However I'm looking to use Nancy's metadata modules to produce something
like Swagger but not so restricted to a specification and allow more
documentation if you want to help out

https://github.com/jchannon/Nancy.Docs
