### ISSUE TITLE
Improving route return value handling for primitive values

### ISSUE THREAD

**Issue by thecodejunkie** [NancyFx/Nancy#2437]
With the change to async for all routes, we have lost the ability to return primitives (string, int, HttpStatusCode etc.) without wrapping them in a task. 

This means

```c#
Get["/"] = (parameters, ct) =>
{
    return "Hello World";
};
```

Has turned into this

```c#
Get["/"] = async (parameters, ct) =>
{
    return await Task.FromResult("Hello World");
};
```

which, obviously, isn't as pretty as what we used to have. One way, that I can think of, if to make `Response` awaitable, which would help us make it a bit clear

```c#
Get["/"] = async (parameters, ct) =>
{
    return await (Response)"Hello World";
};
```

The problem we're facing is that we, ultimately, need to return `Task<dynamic>` because we cannot implicitly infer the return type and that dynamic will later on be either cast to `Response` or be treated as a model that should be negotiated.

The signature for a route is `Func<dynamic, CancellationToken, Task<dynamic>>`

Perhaps there are alternative approaches? Very open for suggestions here. Even if they might mean breaking changes

ping @NancyFx/most-valued-minions

**Comment by btrepp** [comment]
You don't need to use async if you are only using Task.FromResult

```
Get["/"] =  (parameters, ct) =>
{
    return Task.FromResult("Hello World");
};
```

**Comment by JoeStead** [comment]
@btrepp You'd need `Task.FromResult<dynamic>...` for that to work IIRC. Even so, it still isn't particularly elegant. I'm sure it can be done better.

**Comment by thecodejunkie** [comment]
@btrepp the point is to simply / clean up the `return Task.FromResult("Hello World");` part

**Comment by thecodejunkie** [comment]
Also #2422 is related, where we changed how you can use `Negotiate` and `View` from inside async routes

**Comment by nblumhardt** [comment]
I missed the earlier discussions, but would it be less surprising/more in line with the widespread `*Async` naming convention to do:

```csharp
GetAsync["/"] =  (parameters, ct) =>
{
    return Task.FromResult("Hello World");
};
```

I'm working in an app that doesn't use async much, so the thought of adding all the redundant `Task.FromResult()` boilerplate is unpleasant. I'd rather tack on a few chars when I actually want async. Not sure this is typical of .NET apps in general though - just one angle :-)

**Comment by thecodejunkie** [comment]
@nblumhardt in `2.0` all routes will be async, but you can definitely make them synchronous yourself either with

```c#
Get["/"] = async (parameters, ct) =>
{
    return Task.FromResult("Hello World");
};
```

Or by doing something like what we do in [LegacyNancyModule](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/LegacyNancyModule.cs) which gives you the same route syntax as you get in `1.x`

**Comment by nblumhardt** [comment]
:+1: .. I was rather thinking, the "real" 2.0 routes could be named `GetAsync` etc., while the classic `Get` would do pretty much what `LegacyNancyModule` does. (Or, the other way around, `GetSync` could provide a wrapper for `Get` with non-Task-based signatures.

Not a blocker of course! Will post if I can come up with any more creative suggestions :-)

**Comment by btrepp** [comment]
Heh, I'm new to nancy so I'm getting the vibe that super clean syntax is important.

From other situations I have little problem using Task.FromResult.

1. Its standard and pretty clear what it is doing. 
2. I find most of the time I end up using async things anyway. Plus I find it nicer to encourage people to use the async stuff, nothing worse than having a low level library have async, and then having to refactor all the way back up to get it to work properly.

If that syntax is really important perhaps you could define a class "Route Response" and write implicit converters that wrap up objects into tasks as needed?. I'm not 100% sure if this is possible, and won't be near a compiler for awhile to test it out.

**Comment by JoeStead** [comment]
Is there a way of wrapping up an awaiter in the Response object? Similar to:
```csharp
public TaskAwaiter<dynamic> GetAwaiter()
{
    return Task.FromResult<dynamic>(Contents).GetAwaiter();
}
```
I'm not sure how to handle *actual* async code, but this would make it possible to return a Response straight up (and all of the implicit casts should still work)

**Comment by thecodejunkie** [comment]
@JoeStead that's what I meant by 

> One way, that I can think of, if to make Response awaitable, which would help us make it a bit clear

Which means adding

```c#
public TaskAwaiter<Response> GetAwaiter()
{
    return Task.FromResult(this).GetAwaiter();
}
```

to the `Response` object, which let us do

```c#
public class TestModule : NancyModule
{
    public TestModule() : base("/testmodule")
    {
        Get["/"] = async (parameters, ct) =>
        {
            return await (Response)("Hello From " + typeof(TestModule).Name);
        };

        Get["/statuscode"] = async (parameters, ct) =>
        {
            return await (Response)403;
        };

        Get["/httpstatuscode"] = async (parameters, ct) =>
        {
            return await (Response)HttpStatusCode.InternalServerError;
        };
    }
}

There is no way (at least using this approach), to get away with having the `(Response)` cast there

**Comment by JoeStead** [comment]
Ahh I must've missed that 😄 

I'm not sure how you'd get around the `(Response)` cast tbh, to my knowledge you won't be able to implicitly chain together the casts from `int`/`status code`/`string`/etc. -> `Response` -> `Task<dynamic>`, so you'll either have to have `(Response)`, use a different solution, or someone much smarter than me can prove me wrong 😛 

It's also worth pointing out that with your synchronous code, the async/await operators seem odd. Of course, a cast *from* Response to fix that, but that can be quite misleading to a lot of people I guess.

**Comment by thecodejunkie** [comment]
I'm hacking around on this and testing some alternative solutions

![image](https://cloud.githubusercontent.com/assets/50543/15040710/0517c6c0-12b7-11e6-94d5-7ecc903fe875.png)

![image](https://cloud.githubusercontent.com/assets/50543/15040716/08f4d012-12b7-11e6-863a-768f60aade8d.png)

![image](https://cloud.githubusercontent.com/assets/50543/15040718/0d2f7c72-12b7-11e6-8090-b46df87d2461.png)

Here is a spike where awaiting on `string`, `int` or `HttpStatusCode` ends up resulting in a Nancy `Response` object

I love doing weird API stuff :dancer: 

Back to the laboratory....

**Comment by chriscamplejohn** [comment]
What about

`public class TestModule : NancyModule
    {
        public TestModule()
        {
            Get["/string"] = async (parameters, cancellationToken) =>
            {
                return await "Hello world!";
            };

            Get["/int"] = async (parameters, cancellationToken) =>
            {
                return await 100;
            };

            Get["/statuscode"] = async (parameters, cancellationToken) =>
            {
                return await HttpStatusCode.OK;
            };
        }
    }

    public static class Awaiters
    {
        public static TaskAwaiter<object> GetAwaiter(this object result)
        {
            return Task.FromResult(result).GetAwaiter();
        }
    }`

To make it less general you could just create awaiters for the few simple types you want to support instead of taking object...

**Comment by martdi** [comment]
Why not providing a simple converter / Sync method in NancyModule, such as:

~~~~~~~~~~~~~~~~~~c#
public class SomeModule : NancyModule {
    public SomeModule() 
    {
            Get["/"] = Sync(parameters => "Some string");
            Get["/otherPath"] = Sync(OtherMethod);
    }

    public object OtherMethod(dynamic parameters) {
        return new List<string> {
             "Some string",
             "Some other string"
        }
    }
}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

And the converter method could look like:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~c#
private Func<dynamic, CancellationToken, Task<dynamic>> Sync(Func<dynamic, object> sync)
{
    return async (p, ct) => await Task.FromResult(sync(p));
}
~~~~~~~~~~~~~~~~~~~~~~~

**Comment by jchannon** [comment]
FYI : @thecodejunkie is working on a PR that will answer this issue. Should be incoming very soon

**Comment by thecodejunkie** [comment]
@chriscamplejohn that's exactly what I did in my comment right above yours :P

**Comment by thecodejunkie** [comment]
Closing this issue.. I've posted a proposed change on route declaration for `2.0` so all further discussions should happen on https://github.com/NancyFx/Nancy/pull/2441
