### ISSUE TITLE
Forms authentication per module can not work

### ISSUE THREAD

**Issue by liupengf12** [NancyFx/Nancy#2439]
### Forms authentication per module can not work

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of Nancy
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I need the forms authentication only works for one of my special module, but it did not redirect to the login page and only return a HTTP code with 401.
Is there any mistake in my codes?

### Steps to Reproduce
 I wrote the codes like this:
```C#
protected override void RequestStartup(TinyIoCContainer requestContainer, IPipelines pipelines, NancyContext context)
{
    base.RequestStartup(requestContainer, pipelines, context);

    var waiterModule = GetModule(typeof(WaitersModule), context);
    FormsAuthentication.Enable(waiterModule, new FormsAuthenticationConfiguration {
        RedirectUrl = "~/waiters/login",
        UserMapper = requestContainer.Resolve<IUserMapper>()
    });
}
```

And the module like this:
```C#
public WaitersModule() : base("/waiters")
{
    Get["/profile"] = parameters =>
    {
        this.RequiresAuthentication();

        return View["profile", model];
    };
}
```

### System Configuration

- Nancy version: 1.4.3
- Nancy host
  - [ ] ASP.NET
  - [x] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions: Nancy.Authentication.Forms v1.4.1
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: 4.5.1
- Additional information:

**Comment by GusBeare** [comment]
It may be a daft question but do you have a module handling your login page route?

Get["/login"] = parameters =>
    {

**Comment by khellang** [comment]
The problem is that you haven't enabled forms auth for the specific module instance. Nancy modules are intiantiated on each request, so you have to enable the forms auth in the constructor:

```csharp
public WaitersModule(IUserMapper userMapper) : base("/waiters")
{
    FormsAuthentication.Enable(this, new FormsAuthenticationConfiguration {
        RedirectUrl = "~/waiters/login",
        UserMapper = userMapper
    });

    Get["/profile"] = parameters =>
    {
        this.RequiresAuthentication();

        return View["profile", model];
    };
}
```

**Comment by liupengf12** [comment]
@khellang Thanks for your help, but I got a error after changed the codes as you suggest:
![image](https://cloud.githubusercontent.com/assets/117811/15676100/903ef79e-2777-11e6-9b0a-4ca65eb8213c.png)

**Comment by khellang** [comment]
Yeah, now you're going in a redirect loop. You're basically redirecting to the login page, which it looks like you've secured (?), so it redirects to itself, which again redirects to itself on and on and on, until you get an error because the `returnUrl` query parameter is too long.

**Comment by liupengf12** [comment]
I know why redirect loop happened: all the actions of the module are require authentication after  enable the forms auth in its constructor, so I have to change the RedirectUrl with a different module.

Finally I found another solution: [Multiple forms authentication sections](http://www.philliphaydon.com/2012/12/20/configuring-multiple-forms-authentication-sections-with-nancyfx/)

Thanks for your help again.
