### ISSUE TITLE
GetOwinEnvironment returns a dictionary that behaves differently in 2.0.0-alpha

### ISSUE THREAD

**Issue by psibernetic** [NancyFx/Nancy#2444]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In Nancy 2.0.0 Alpha, NancyContextExtensions.GetOwinEnvironment(this NancyContext context), the IDictionary returned will now throw an exception if you attempt to access a key that is not present in the dictionary.

### Steps to Reproduce
In 1.4.3 the dictionary would not throw an exception, but would return null instead. I believe the new behavior is correct, but something to note for migration purposes.

### System Configuration

- Nancy version: 2.0.0-alpha
- Nancy host
  - [x] OWIN
  - [x] Self-Hosted
- Other Nancy packages and versions:
  Nancy.Owin 2.0.0-alpha
- Environment (Operating system, version and so on):
 Windows 10
- .NET Framework version:
NET461
- Additional information:

**Comment by psibernetic** [comment]
Hold on this one, may be adjusting it.

**Comment by psibernetic** [comment]
Verified this is not due to mismatched versions, behavior has changed.

**Comment by khellang** [comment]
This is weird. AFAIK, Nancy doesn't touch the OWIN environment dictionary passed from the underlying OWIN host. It simply stores it in the `NancyContext` and gives it to the user, verbatim, when calling `GetOwinEnvironment`. Have you changed OWIN versions?

**Comment by psibernetic** [comment]
I didn't, lets close for now, but keep an eye on it.
