### ISSUE TITLE
Task Cancellation exception in Async routes hides real exception

### ISSUE THREAD

**Issue by psibernetic** [NancyFx/Nancy#2449]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When an unhandled exception is thrown inside a route in the new route syntax a Task Cancelled exception is raised that suppresses the original exception. The OnError pipeline receives only the Task Cancelled exception.

### Steps to Reproduce
Using the new route syntax create any route with the async signature making sure your route itself is async/await. Throw an unhandled exception.

### System Configuration
My issue was a TypeLoadException with mismatched versions of assemblies, but was completely hidden until I switched the route to the sync signature.

- Nancy version: 2.0-Pre1728
- Nancy host
  - [x] OWIN
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
  Windows 10, VS 2015 Update 2
- .NET Framework version: NET461

**Comment by psibernetic** [comment]
@thecodejunkie Raising this to your attention.

**Comment by jchannon** [comment]
Sounds like we need to do something with AggregateException

**Comment by psibernetic** [comment]
Info about the task:
![image](https://cloud.githubusercontent.com/assets/621605/15441686/e3715a62-1ea1-11e6-9918-b060524e5789.png)


and here is the mostly useless stack trace:

```
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Routing.DefaultRouteInvoker.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Nancy.Routing.DefaultRequestDispatcher.<Dispatch>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.NancyEngine.<InvokeRequestLifeCycle>d__9.MoveNext()
```

**Comment by thecodejunkie** [comment]
Not sure what we can do here since you are ending up with a `TaskCancelledException` and it won't have the `InnerException` set.

I assume the following route illustrates what you are experiencing

```c#
Get("/exception", (args, ct) =>
{
    return Task<int>.Factory.StartNew(() =>
    {
        throw new Exception("This is my exception");
    });
});
```
![image](https://cloud.githubusercontent.com/assets/50543/15442532/14347478-1ee2-11e6-9290-c5c953985608.png)

The only thing I can think of right now is that somewhere in our code we need to stick a

```c#
Exception actualException = null;

task.ContinueWith(t =>  actualException  = t.Exception.InnerExceptions[0];, TaskContinuationOptions.OnlyOnFaulted);

if (exception != null)
{
   throw actualException;
}
```

sort of construct.. perhaps in https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Routing/DefaultRouteInvoker.cs#L40

ping @damianh @khellang @grumpydev

**Comment by psibernetic** [comment]
Actually it is much simpler.

```csharp
Get("/exception", async (args, ct) =>
{
    throw new Exception("this causes it");
    return await Task.FromCompleted<int>(200);
});
```

**Comment by khellang** [comment]
This seems to work, though:

```csharp
Get("/exception", (args, ct) =>
{
    throw new Exception("this causes it");
    return Task.FromResult(200);
});
```

**Comment by psibernetic** [comment]
Great work, tested on CI build and works as expected.
