### ISSUE TITLE
How to limit num of concurrent requests in nancy selfhost? 

### ISSUE THREAD

**Issue by wangke1020** [NancyFx/Nancy#2455]
Hi, I have build a web server with nancy selfhost,  I want to limit num of concurrent requests. 
Does nancy support it?

**Comment by khellang** [comment]
This seems like a really odd requirement. Can you explain some of the reaaoning behind this?

Nancy doesn't handle anything related to connections or request handling concurrency. It simply sits on top of a host and handles requests as the host passes them. I suggest you look into the host you'really running on top of. You failed to fill out the issue template, so I have no idea what that host is, and won't be able to help you, sorry...
