### ISSUE TITLE
html textarea not binding to model

### ISSUE THREAD

**Issue by GusBeare** [NancyFx/Nancy#2460]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of Nancy
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I am doing a form post and finding that the textarea control is not binding to my model. 
The text area contents are always null.

### Steps to Reproduce

The following HTML in my view.

```
<form action="/sign-visitors-log/" method="post" id="VisitorsLogForm">
<label for="Comment">Comment</label> <textarea class="form-control" cols="30" rows="8" id="Comment" form="VisitorsLogForm" tabindex="4">@Model.Comment</textarea>
```

The following module post handler:

```
Post["/sign-visitors-log"] = parameters => 
{ 
	try 
	{ 
	var model = new Models.FlickaVisitorsLog(); this.BindTo(model);
```

My model:

```
public class FlickaVisitorsLog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public string Comment { get; set; }
        public DateTime CreatedDate { get; set; }
    }
```
### System Configuration

- Nancy version: 1.4.3
- Nancy host
  - [X] ASP.NET
  - [ ] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions: 
Nancy.Authentication.Forms 1.4.1
Nancy.ViewEngines.Razor 1.4.3
- Environment (Operating system, version and so on):
Win 10, Visual Studio Community 2015
- .NET Framework version: 4.5.2
- Additional information:

**Comment by phillip-haydon** [comment]
Your text area does not have a name attribute. Forms are posted as key/value where the key is made from the name attribute of a form element.

**Comment by GusBeare** [comment]
great, thanks, glad it was something I missed.
