### ISSUE TITLE
%2B in url is translated to space, should be + (plus sign)?

### ISSUE THREAD

**Issue by AnderssonPeter** [NancyFx/Nancy#2461]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of Nancy
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I make a request to my nancy server with a url that contains `%2B`, if I put a breakpoint in `BeforeRequest` and look at `NancyContext.Request.Path` the `%2B` is translated into a space.

The `%2B` is part of a Base64 string that I passed into javascripts `encodeURIComponent` function, the webbrowser was Edge if that helps.

My guess is that `%2B` is translated to `+` and the `+` is translated into a space is this correct behavior? and if it is how would I correctly encode a `+` so that it stays a `+` in the url?

### Steps to Reproduce

- Make a http request with `%2B` in the url example: `http://127.0.0.1:3597/Print/Test%2BTest`
- Put a breakpoint in `BeforeRequest`
- Check the value of `NancyContext.Request.Path`.

### System Configuration

- Nancy version: 1.4.2.0
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [X] Self-Hosted: 1.4.1.0
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version: 4.5.2

**Comment by khellang** [comment]
Can you try with `%252B` (`+` double encoded). I think Nancy self-host double decodes the URL :disappointed:

**Comment by AnderssonPeter** [comment]
@khellang that seems to work, does this happen for all encoded chars? (should I call `encodeURIComponent(encodeURIComponent(content));`?

Seems like a bug if it decodes 2 times?

**Comment by khellang** [comment]
Yes. It is a bug. It's been that way for a really long time. 2.0 is probably the time to break it though.

**Comment by khellang** [comment]
Want to send a PR? It's just a matter of removing `HttpUtility.UrlDecode` [here](https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Hosting.Self/NancyHost.cs#L263)

**Comment by AnderssonPeter** [comment]
I just made my base64 string url safe by replacing + with - and \ with _ and then the reverse before decoding. But if i get some time over ill do a PR.

**Comment by Tommixoft** [comment]
So is there a fix or not?

**Comment by khellang** [comment]
@Tommixoft "It doesn't work" isn't really a good description of the problem. Are you running the same setup as @AnderssonPeter?

**Comment by Tommixoft** [comment]
@khellang  for me it's good description :) i put in url double encoded + and in debugger i only get space. SO i say-it doesn't work :)

**Comment by khellang** [comment]
@Tommixoft You have to give us more than that. Sorry :disappointed:

**Comment by Tommixoft** [comment]
So you saying this bug is fixed? If no, why ask me details on topic which is not fixed? 
SelfHosted app.

`Get[@"/card/{id}"] = req =>`

req.id is without +. 
Url was /card/12863623788273%252B

**Comment by khellang** [comment]
> So you saying this bug is fixed?

If you'd bothered reading the issue, you'd see that @AnderssonPeter's issue was resolved when using `%252B`.
You'd also see that we've fixed the double-decoding issue for Nancy self-host (using HttpListener).

> If no, why ask me details on topic which is not fixed and try to make it loook like it is?

I'm not sure what you're saying here. We always want to know as many details as we possible can.
Just because it's fixed for some people, doesn't mean it's fixed for all. There could be many differences in environment and setup, version etc. Or it could be a totally unrelated issue.

You've still failed to say which packages and versions you're running.

**Comment by Tommixoft** [comment]
How it's fixed if it still exists? You remind me russians when they want to get rid of support job they starting to ask questions non related to problem.
Why i need to spend gazillion hours writing all info if this problem is well known for you? You admited several times it exists, and i came here to ask maybe it's fixed. That's it, i now know it's not.

**Comment by khellang** [comment]
> How it's fixed if it still exists?

It's fixed, but you probably don't have the version it's fixed in. And you don't want to provide us with the info we need to tell you if it's fixed or not.

> Why i need to spend gazillion hours writing all info if this problem is well known for you?

Because how can we tell you if it's fixed or not if you don't want to tell us which versions you're running? :stuck_out_tongue_closed_eyes:

**Comment by danbarua** [comment]
Same problem in Asp.Net hosting btw.

**Comment by khellang** [comment]
Read this? http://programmaticallyspeaking.com/the-mysteriously-escaped-request-path-in-aspnet.html

**Comment by AnderssonPeter** [comment]
@khellang @Tommixoft im not 100% sure but i think its only fixed in the source code and not in the released version (that me most likely is using)?

**Comment by khellang** [comment]
It should be in [this version](https://www.nuget.org/packages/Nancy/2.0.0-barneyrubble). It's the one this issue is assigned to (see the milestone).
