### ISSUE TITLE
generator-aspnet for Nancy application does not run

### ISSUE THREAD

**Issue by cemremengu** [NancyFx/Nancy#2463]
The newly updated [aspnet generator](https://www.npmjs.com/package/generator-aspnet) fails to produce a running nancy application template.

Here is what happens when I try running it after I restore and build:

```
C:\Users\CMENGU\Desktop\MySh>dotnet run
Project MySh (DNX,Version=v4.5.1) was previously compiled. Skipping compilation.
Unhandled Exception: System.InvalidOperationException: No service for type 'Microsoft.Extensions.PlatformAbstractions.IApplicationEnvironment' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNet.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNet.Hosting.WebApplication.Run(Type startupType, String[] args)
   at MySh.Startup.Main(String[] args) in C:\Users\CMENGU\Desktop\MySh\Startup.cs:line 14
```

The project.json file is as follows:

```
{
    "version": "1.0.0-*",
    "buildOptions": {
        "emitEntryPoint": true
    },
    "tooling": {
        "defaultNamespace": "MySh"
    },
    "dependencies": {
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
        "Microsoft.AspNet.Owin": "1.0.0-rc1-final",
        "Nancy": "1.4.3"
    },
    "commands": {
        "web": "Microsoft.AspNet.Server.Kestrel"
    },
    "frameworks": {
        "dnx451": {}
    }
}
```

I tried to get it running by playing with the dependencies but was not successful. Anyone has an idea what might be the issue ?

**Comment by peterblazejewicz** [comment]
@cemremengu 
The Nancy was not yet update when RC2 was shipped, hence RC1 is still used in generator:
https://github.com/OmniSharp/generator-aspnet/issues/640

I can build and run (on OS X) this sample from cloned Nancy repo:
https://github.com/NancyFx/Nancy/tree/master/samples/Nancy.Demo.Hosting.Kestrel
but to be standalone with generator as template it requires some input from someone that uses Nancy on daily basis.
Thanks!

**Comment by thecodejunkie** [comment]
I'll just close this issue because we do not have anything to do with the aspnet generator, at least not on a project level (I have no idea if any team member submitted anything). Feel free to continue discussion in here though.

**Comment by cemremengu** [comment]
@thecodejunkie Yes, kind of off-topic but I will see what I can do to at least suggest a fix for it or let them know about it. It gives Nancy a bad name :(

**Comment by cemremengu** [comment]
Thanks to input from @peterblazejewicz I have fixed it. Soon will submit a request to them to at least provide something working. 

Btw, The docs says they have deprecated dnx platform monikers but they are still using it. I can't keep track of anymore what the heck is going on :dancers:
