### ISSUE TITLE
How to identify a Action/Module

### ISSUE THREAD

**Issue by uliian** [NancyFx/Nancy#2482]
In the design mode of Action the definition of Nancy, we can get Action too few information in the Pipleline, resulting in some operation more difficult.
For example: I have a permission management system, I wanted to give each of my Action or Module an identifier, and according to the permission management system in the Pipleline in the unified control over the information, now I find it hard to for Action identified If in ASP.NET of mode, I can through Attribute to they do identifies, and I currently seems Nancy do not to. Nancy's document in the by to of permission control way are is in method implementation do control, I think this way is not flexible, if I has a page, someday ago need control, and now hope public, I hope in permission system in the for configuration on can entered into force, and in Nancy in the achieved up is difficult. What do you think about this issue?

**Comment by khellang** [comment]
I'm sorry, but I'm not really sure what you're asking... Do you want to identify which module/action is being/have been invoked?

When you define a route, you can give it a name. That can later be picked up from the NancyContext when/after the route is invoked. Take a look at the `ResolvedRoute` property. It has the information about the selected route. In partictular, you might be interested in `Description.Name`.

**Comment by uliian** [comment]
thx!
