### ISSUE TITLE
Move from Rake to Cake

### ISSUE THREAD

**Issue by jchannon** [NancyFx/Nancy#2484]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Nancy and all its repositories(Serialization and Bootstrappers) have Rake files to handle compilation, packaging etc.

As part of v2 and CoreCLR work has been carried out to move the Nancy repo to use Cake as the build system https://github.com/NancyFx/Nancy/pull/2450

Once that is done all the Serialization and Bootstrapper repos will need to be update to Cake too.

The Build Script of Doom repo (https://github.com/NancyFx/Nancy.Build) will also need doing.  This is the script that orchestrates the build of Nancy and all the other repos.

I believe this should be reasonably trivial once one repo is done because the script can mostly be copy/pasted into the other repos.

Therefore we need to tick off the following:

- [x]  Nancy.Bootstrappers.Autofac (PR https://github.com/NancyFx/Nancy.Bootstrappers.Autofac/pull/41/)
- [x]  Nancy.Bootstrappers.Ninject (PR https://github.com/NancyFx/Nancy.Bootstrappers.Ninject/pull/30)
- [x]  Nancy.Bootstrappers.StructureMap (PR https://github.com/NancyFx/Nancy.Bootstrappers.StructureMap/pull/51)
- [x]  Nancy.Bootstrappers.Unity (PR https://github.com/NancyFx/Nancy.Bootstrappers.Unity/pull/25)
- [x]  Nancy.Bootstrappers.Windsor (PR https://github.com/NancyFx/Nancy.Bootstrappers.Windsor/pull/35)
- [x]  Nancy.Serialization.ProtBuf (PR https://github.com/NancyFx/Nancy.Serialization.ProtBuf/pull/18)
- [x]  Nancy.Serialization.ServiceStack (PR https://github.com/NancyFx/Nancy.Serialization.ServiceStack/pull/19)
- [x]  Nancy.Serialization.JsonNet (PR https://github.com/NancyFx/Nancy.Serialization.JsonNet/pull/41)

The BSOD PR is here https://github.com/NancyFx/Nancy.Build/pull/2

**Comment by adamralph** [comment]
why is this a breaking change?

**Comment by Sphiecoh** [comment]
https://github.com/NancyFx/Nancy.Bootstrappers.StructureMap/pull/51 For StructureMap

**Comment by Sphiecoh** [comment]
Am taking on https://github.com/NancyFx/Nancy.Bootstrappers.Ninject next

**Comment by cemremengu** [comment]
Submitted PR for AutoFac: https://github.com/NancyFx/Nancy.Bootstrappers.Autofac/pull/40

Taking on https://github.com/NancyFx/Nancy.Bootstrappers.Windsor

**Comment by Sphiecoh** [comment]
https://github.com/NancyFx/Nancy.Serialization.ServiceStack next !!!

**Comment by cemremengu** [comment]
https://github.com/NancyFx/Nancy.Bootstrappers.Unity coming up!

**Comment by Sphiecoh** [comment]
#addin nuget:?package=Newtonsoft.Json&version=8.0.3 the addin needs to change to this for non windows builds

**Comment by Sphiecoh** [comment]
Submitted PR for ServiceStack : [Nancy.Serialization.ServiceStack#19](https://github.com/NancyFx/Nancy.Serialization.ServiceStack/pull/19)
