### ISSUE TITLE
Can't build a fresh clone

### ISSUE THREAD

**Issue by adamralph** [NancyFx/Nancy#2489]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
A fresh clone does not build from the command line.

#### Scenaro 1
1. `git clone git@github.com:NancyFx/Nancy.git`
1. `cd Nancy`
1. `bundle install`
1. `bundle exec rake`
1. Observe errors: [output-1.txt](https://github.com/NancyFx/Nancy/files/312841/output-1.txt)

#### Scenaro 2
1. `git clone git@github.com:NancyFx/Nancy.git`
1. `cd Nancy`
1. `build.ps1`
1. Observe errors: [output-2.txt](https://github.com/NancyFx/Nancy/files/312843/output-2.txt)
1. Incidentally, the current directory is changed to `test\Nancy.Authentication.Basic.Tests` after the build script fails

### System Configuration
- Environment (Operating system, version and so on): **Windows 10, with Visual Studio 2015 Enterprise**
- .NET Framework version: **4.6.1**

**Comment by adamralph** [comment]
I missed

> If you don't have Visual Studio 2010 installed you'll need to download and install Visual Studio 2010 Shell from http://www.microsoft.com/en-us/download/details.aspx?id=1366

from https://github.com/NancyFx/Nancy/blob/master/how_to_build.txt and I presume that will fix scenario 1.

I'm not convinced it will fix scenario 2 though.

**Comment by squidge** [comment]
On OSX (El Capitan)
Using clone as of today

`$ sh build.sh`
`Unhandled Exception: System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.`

**Comment by cemremengu** [comment]
Is this issue resolved now, given the recent changes ?

**Comment by adamralph** [comment]
In Windows, scenario 2 seems to be fixed. I can't confirm Scenario 1 because I'm not willing to install the VS 2010 shell just for this, but I guess there's no problem there.
