### ISSUE TITLE
RethinkDB Session Provider

### ISSUE THREAD

**Issue by danieljsummers** [NancyFx/Nancy#2493]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy

### Description
I am currently working on a project, and have come to the "hey, sessions need to be implemented" phase.  My data store for this project is RethinkDB (a document store, similar to MongoDB or RavenDB).  I'm going to end up writing a session provider that uses RethinkDB as its backing store.

My question is this: if I wanted to contribute this to the community, would this be something that would be welcomed in this project, or would it need to be something I host and package up myself?  If it's the former, is there a pattern to follow to create a self-contained package that doesn't levy dependencies on any other projects?  Also, if there's a desire, I could probably do a few others as well.

I'm also open to responses along the lines of "Hey, why not just (x) instead?" if I'm missing something; I'm a Nancy n00b.

Thanks!

**Comment by danieljsummers** [comment]
I put a notional project together.  I know it's not in the right place in the directory tree, but it gives you an idea of what I'm talking about.

[Nancy.Session.RethinkDb](https://github.com/danieljsummers/Nancy/tree/master/Nancy.Session.RethinkDb)

Comments are welcome.

**Comment by jchannon** [comment]
Hi, whilst this is a great idea and sample, things like this we tend to keep for community members to maintain themselves as its not a direct core aspect of Nancy. @NancyFx/most-valued-minions

**Comment by danieljsummers** [comment]
Got it - thanks!  I'll work it up under my profile, and drop you all a note when it's ready.  (And I'll probably do it in F#... LOL)  Should I use the Nancy.Session.RethinkDb namespace (to aid in discoverability), or should I choose something different, to distinguish that it's not part of the Nancy project?

I also didn't find very much on the wiki in the way of sessions; would you like me to contribute some documentation on configuring sessions in general, and the cookie session specifically?

p.s.  Thank you for your work with Nancy; I can't believe I didn't check this framework out sooner.  Using SSVE, the app I'm working on uses about 50 MB of RAM to display the home page (under Mono); the tiny footprint of interpreted code, but I get to code with the expressiveness of .NET!  :)
