### ISSUE TITLE
Provide an ability to use SuperSimpleViewEngine not in Nancy context.

### ISSUE THREAD

**Issue by olsh** [NancyFx/Nancy#2504]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Could you please add an ability to use SuperSimpleViewEngine not in Nancy context. I have a case when I need to render Views in background threads and It would be gread if I can use `SuperSimpleViewEngine` this way:
```
var engine = new SuperSimpleViewEngine();
var body = engine.Render(template, model);
```
Where `template` is content of a template.

Thanks.

### Steps to Reproduce
-

### System Configuration
The latest Nancy version

- Nancy version:
- Nancy host
  - [ ] ASP.NET
  - [x] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on): Windows 10 x64
- .NET Framework version: 4.6.1
- Additional information: -

**Comment by grumpydev** [comment]
You already can, SSVE is a standalone thing and not tied to Nancy at all, all you have to do is implement the "IViewEngineHost" interface, which is an SSVE interface, so it knows how to to things like encode output etc.

https://github.com/NancyFx/Nancy/blob/master/src/Nancy/ViewEngines/SuperSimpleViewEngine/IViewEngineHost.cs

If you know exactly which features you are/aren't going to use in your views (such as masters/partials) you can leave parts of the implementation just throwing NotSupportedException.

**Comment by olsh** [comment]
@grumpydev thanks
