### ISSUE TITLE
Exceptions from async routes produces irrelevant information

### ISSUE THREAD

**Issue by jchannon** [NancyFx/Nancy#2514]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When an exception is thrown from a v2 async route the exception details returned are pretty much useless.  When its from a synchronous route, the expected exception information is present.

### Steps to Reproduce
```
       public class HomeModule : NancyModule
       {
            public HomeModule()
            {
                Get("/logout", async _ => await this.Logout(_), name: "Logout");

                Get("/logoutsync", args => LogoutSync(args), name: "Logoutsync");
            }
        

          private async Task Logout(dynamic parameters)
          {
            throw new Exception("oops");
          }

          private dynamic LogoutSync(dynamic parameters)
          {
            throw new Exception("oops");
          }
      }

     namespace netcorenancyapp
{
    using Nancy;
    using Nancy.ErrorHandling;
    using Nancy.Responses.Negotiation;
    using System;

    using System.Reflection;

    public class ErrorStatusCodeHandler : IStatusCodeHandler
    {
        private readonly IResponseNegotiator responseNegotiator;

        public ErrorStatusCodeHandler(IResponseNegotiator responseNegotiator)
        {
            this.responseNegotiator = responseNegotiator;
        }

        public bool HandlesStatusCode(HttpStatusCode statusCode, NancyContext context)
        {
            return statusCode == HttpStatusCode.InternalServerError;
        }

        public void Handle(HttpStatusCode statusCode, NancyContext context)
        {
            var response = new Negotiator(context);
            string errorName = string.Empty;

            Exception exception = null;
            if (context.Items.ContainsKey("OnErrorException"))
            {
                exception = context.Items["OnErrorException"] as Exception;
            }

            response.WithModel(new ErrorPageViewModel
            {
                Title = "Sorry, something went wrong",
                Summary = exception.Message,
                Name = errorName,
                Details = exception.ToString()
            }).WithStatusCode(statusCode);

            var errorresponse = responseNegotiator.NegotiateResponse(response, context);
            context.Response = errorresponse;
        }
    }
}
```

Enter this to get a response `curl -H "Accept:application/json" http://localhost:5000/logout` which shows

```
{"title":"Sorry, something went wrong","summary":"Cannot implicitly convert type 'void' to 'object'","name":"","details":"Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert
 type 'void' to 'object'\n   at CallSite.Target(Closure , CallSite , Object )\n   at netcorenancyapp.HomeModule.<<-ctor>b__0_3>d.MoveNext() in /Users/jonathan/Projects/netcorenancyapp/HomeModule.cs:line 34\n--- 
End of stack trace from previous location where exception was thrown ---\n   at 
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at 
Nancy.Routing.DefaultRouteInvoker.<Invoke>d__2.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at 
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at 
Nancy.Routing.DefaultRequestDispatcher.<Dispatch>d__5.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at 
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at 
Nancy.NancyEngine.<InvokeRequestLifeCycle>d__22.MoveNext()"}
```

### System Configuration

- Nancy version: 2.0.0-barneyrubble
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [ ] Self-Hosted
  - [x] Other: Kestrel
- Other Nancy packages and versions:
- Environment (Operating system, version and so on): OSX & Windows
- .NET Framework version: netcore RTM
- Additional information:

**Comment by khellang** [comment]
That's what async'll do to your stack traces. Not sure what we can do about it?

**Comment by jchannon** [comment]
Well async sucks then. How are people supposed to know what the root exception is and where?

**Comment by khellang** [comment]
Look at the stack trace? If you distill it a bit, you can see what's wrong:

> **Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'void' to 'object'**
> at **netcorenancyapp.HomeModule**.<<-**ctor**>b__0_3>d.MoveNext() in **/Users/jonathan/Projects/netcorenancyapp/HomeModule.cs:line 34**

A **`Microsoft.CSharp.RuntimeBinder.RuntimeBinderException`** is thrown with the message **"Cannot implicitly convert type 'void' to 'object'"** in **the constructor** of **`HomeModule`** at **line 34** :smile:

**Comment by GraemeBradbury** [comment]
Would it not be a good idea to do a "pretify" of the stack trace first?

Project that already does it: [AsyncFriendyStackTrace](https://github.com/aelij/AsyncFriendlyStackTrace)

**Comment by jchannon** [comment]
That's not the exception though. That's a knock on async effect from having an exception. 

Only way to do it is to wrap methods in a try/catch and return a 500 in the catch. Problem with that is you no longer have a central error handler like OnError where you can get the exception and rely on IStatusCodeHandlers to return a pretty response. 

This will add a lot more noise to people's apps.

**Comment by jchannon** [comment]
Looking at a aspnetcore mvc app with the below you get a direct pointer to where the exception occured:

```
 public class HomeController : Controller
    {
        public async Task<IActionResult> Yo()
        {
            var data = await DoThis();
            return Json(data);
        }

        public async Task<IEnumerable<string>> DoThis()
        {
            throw new Exception("poo");
        }
```

**Comment by jchannon** [comment]
I've expanded the Nancy demo to match the aspnetcore one:

```
Get("/logout", async _ => await this.Logout(_));

private async Task<dynamic> Logout(dynamic parameters)
{
        var data = await DoThis();
        return Response.AsJson(data);
}

public async Task<IEnumerable<string>> DoThis()
{
        throw new Exception("poo");
}
```

Stack trace is comparable I guess

```
"System.Exception: poo\n   at netcorenancyapp.HomeModule.<DoThis>d__3.MoveNext() in /Users/jonathan/Projects/netcorenancyapp/HomeModule.cs:line 54\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\n   at netcorenancyapp.HomeModule.<Logout>d__2.MoveNext() in /Users/jonathan/Projects/netcorenancyapp/HomeModule.cs:line 48\n
```

**Comment by khellang** [comment]
What are you talking about? Not the same exception?

**Comment by khellang** [comment]
Also, is this part of the next release?

**Comment by jchannon** [comment]
latest myget

**Comment by jchannon** [comment]
Its because the original method returned Task not Task<dynamic> which
probably explains the error

**Comment by khellang** [comment]
I mean why is it assigned to the next milestone, but closed?
