### ISSUE TITLE
Response.AsXXX results in a invalid Response cast

### ISSUE THREAD

**Issue by jchannon** [NancyFx/Nancy#2515]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Response.Redirect results in a context.Response.StatusCode of OK not SeeOther in AfterPipeline

### Steps to Reproduce
In a module do a `return Response.AsRedirect("~/")`, use a `AfterRequest` pipeline like so

```
 public class NancyGzipCompression : IApplicationStartup
    {
        public void Initialize(IPipelines pipelines)
        {
            pipelines.AfterRequest += CheckForCompression;
        }

        private static void CheckForCompression(NancyContext context)
        {
            if (!RequestIsGzipCompatible(context.Request)
                || context.Response.StatusCode != HttpStatusCode.OK
                || !ResponseIsCompatibleMimeType(context.Response)
                || ContentLengthIsTooSmall(context.Response))
            {
                return;
            }

            CompressResponse(context.Response);
        }

        private static void CompressResponse(Response response)
        {
            response.Headers["Content-Encoding"] = "gzip";

            var contents = response.Contents;
            response.Contents = responseStream =>
            {
                using (var compression = new GZipStream(responseStream, CompressionMode.Compress))
                {
                    contents(compression);
                }
            };
        }

        private static bool ContentLengthIsTooSmall(Response response)
        {
            string contentLength;
            if (response.Headers.TryGetValue("Content-Length", out contentLength))
            {
                var length = long.Parse(contentLength);
                if (length < 4096)
                {
                    return true;
                }
            }
            return false;
        }

        private static readonly List<string> ValidMimes = new List<string>
        {
            "application/json",
            "application/json; charset=utf-8",
            "text/css",
            "text/html",
            "text/plain"
        };

        private static bool ResponseIsCompatibleMimeType(Response response)
        {
            return ValidMimes.Any(x => x == response.ContentType);
        }

        private static bool RequestIsGzipCompatible(Request request)
        {
            return request.Headers.AcceptEncoding.Any(x => x.Contains("gzip"));
        }
    }
```

If you inspect the context.Response.StatusCode its OK not SeeOther as defined in the Redirect.

This returns an OK https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Routing/DefaultRouteInvoker.cs#L59 but 1.xWorkingbranch returns SeeOther

The issue is here https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Responses/Negotiation/DefaultResponseNegotiator.cs#L85 It gets the methods in `Response.cs` and inspects whether it can implicitly cast the `routeResult` to `Response`.  It's saying, can I cast `RedirectResponse` against the method args in the implicit methods in `Response` https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Response.cs#L98-L151 As `RedirectResponse` is not a `HttpStatusCode, int, string, streamFactory` or `DynamicDictionaryValue` it returns out of the method with a null response whereas in fact you could just do `response = (Response)routeResult;` and all would be well.  The commit where it all went wrong in the name of "performance" is here https://github.com/NancyFx/Nancy/commit/9ac2b35dc20eaaf740acf338d2c6c52f2cfb4954 @thecodejunkie 😜 

Pinging @NancyFx/most-valued-minions on what the path forward is?

### System Configuration

- Nancy version: 2.0.0-barneyrubble
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [ ] Self-Hosted
  - [x] Other: Kestrel
- Other Nancy packages and versions:
- Environment (Operating system, version and so on): Windows
- .NET Framework version: netcore RTM
- Additional information:

**Comment by jchannon** [comment]
Here's some benchmarks over 10,000 requests with the below code.
```
 class Program
    {
        static void Main(string[] args)
        {
            for (int i = 0; i < 10000; i++)
            {
                var browser = new Browser(with =>
                {
                    with.Module<MyTestModule>();
                });

                var resp = browser.Get("/").Result;

                if (resp.StatusCode != HttpStatusCode.OK)
                {
                    Console.WriteLine("FAIL");
                }
                Console.WriteLine(i);
            }
            Console.WriteLine("DONE - Press a key to exit");
            
        }
    }

    public class MyTestModule : NancyModule
    {
        public MyTestModule()
        {
            Get("/", _ => "Hi");
        }
    }
```

Without my change:
![before](https://cloud.githubusercontent.com/assets/105126/17170680/2e147194-53e5-11e6-9eba-d7fad3a03d24.PNG)

With my change:
![after](https://cloud.githubusercontent.com/assets/105126/17170687/330811ba-53e5-11e6-8784-4f1b67a0e4f2.PNG)

**Comment by jchannon** [comment]
Re-running the code above but with the `browser` created outside the `for` loop the results are below

Without my change:
![before](https://cloud.githubusercontent.com/assets/105126/17175450/7cea88c0-53ff-11e6-90cd-c8e4dbf73288.PNG)

With my change:
![after](https://cloud.githubusercontent.com/assets/105126/17175452/80f477b4-53ff-11e6-8c9c-8d0860d8e835.PNG)

**Comment by jchannon** [comment]
Re-running the code above but with the browser created outside the for loop and 100,000 requests the results are below

Without my change:
![before](https://cloud.githubusercontent.com/assets/105126/17175595/4abcde88-5400-11e6-873d-75ee48c6b4ac.PNG)

With my change:
![after](https://cloud.githubusercontent.com/assets/105126/17175597/4e8e6612-5400-11e6-9d6a-51c50c8078cd.PNG)

**Comment by thecodejunkie** [comment]
This can be closed now, correct?
