### ISSUE TITLE
Limit size of http Post / File Upload - Nancy.Self-Hosted

### ISSUE THREAD

**Issue by CristianPietrobon** [NancyFx/Nancy#2517]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
How to limit the http Post / File upload without receiving all the Http form / Post data

### Steps to Reproduce
We need to limit the amount of incoming data to few MB maximum (server check).
This will prevent malicious user to post very large file/form and make damage to server bandwidth.
Right now i didn't found a way to close the connection / stop client and return error. 

example:
something like php_value post_max_size 20M

Http request should contain the "set content length" that can be checked before accepting the request so, there's a way to check that parameter before any action is taken under Nancy?

### System Configuration

- Nancy version:
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [X] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions: 1.4.3
- Environment (Operating system, version and so on): Windows / Linux(mono)
- .NET Framework version: 4.6.1
- Additional information:

**Comment by danbarua** [comment]
You could try using this OWNI middleware to achieve the same:
https://github.com/damianh/LimitsMiddleware

**Comment by CristianPietrobon** [comment]
Thank you, this will be surely help.
