### ISSUE TITLE
Why is Response awaitable?

### ISSUE THREAD

**Issue by jchannon** [NancyFx/Nancy#2518]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
### Description

Why is Response awaitable?
### Steps to Reproduce

There was some noob confusion when having a method to return a response. `Get("/logout", async _ => await this.Logout(_));`

I determined that the method should return `Task<dynamic>` not `Task` but I think this was due to some confusion with intellisense saying that Response was awaitable eg `await Response.AsRedirect("/")` where in fact I should `return Response.AsRedirect("/")`

I assume Response is awaitable for rendering Views but what would that look like `return await View["Home"]` ??

Anyway just thought I'd log the issue for other noobs like me
### System Configuration

- Nancy version:
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [ ] Self-Hosted
  - [x] Other: Kestrel
- Other Nancy packages and versions: 2.0.0-barneyrubble
- Environment (Operating system, version and so on): Windows/OSX
- .NET Framework version: netcore
- Additional information:

**Comment by thecodejunkie** [comment]
To be honest I think this is a left over from when we were exploring various implementations of the new route syntax. I think it can be removed without any implications. It has nothing to do with `View` since that does not return a `Response`. I just commented it out and ran all out tests and they all came back green. I will send a PR to remove it 👍
