### ISSUE TITLE
StaticConfiguration.DisableErrorTraces is gone in v2.0.0-alpha

### ISSUE THREAD

**Issue by nerfpops** [NancyFx/Nancy#2522]
I can't enable detailed error messages because this setting is doesn't exist anymore in https://github.com/NancyFx/Nancy/blob/master/src/Nancy/StaticConfiguration.cs

How do I enable detailed error messages in v2?

**Comment by thecodejunkie** [comment]
They've moved to the `Configure` method (which is part of the new configuration API that was introduced in `2.0-alpha`). Have a look here for an example of how to use it https://github.com/NancyFx/Nancy/blob/master/samples/Nancy.Demo.Hosting.Aspnet/DemoBootstrapper.cs#L40
