### ISSUE TITLE
Using MiniProfiler with Razor View Engine

### ISSUE THREAD

**Issue by tidusjar** [NancyFx/Nancy#2528]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
### Description

So I am trying to use [MiniProfiler](miniprofiler.com) with NancyFx, I've hooked it up in the bootstrapper all fine.

My problem is using it on the View (Using Razor View Engine).
I am getting the following error:

```
The type or namespace name 'StackExchange' could not be found (are you missing a using directive or an assembly reference?)
```

View Code:

```
@using StackExchange.Profiling
@inherits Nancy.ViewEngines.Razor.NancyRazorViewBase
<html>
@Html.Partial("Shared/Partial/_Head")

<body>

    @Html.Partial("Shared/Partial/_Navbar")

    <div class="container" style="padding-top: 5%">
        @RenderBody()
    </div>
<div class="scroll-top-wrapper ">
    <span class="scroll-top-inner">
            <i class="fa fa-2x fa-arrow-circle-up"></i>
        </span>
</div>

    @MiniProfiler.RenderIncludes()
</body>
</html>
```
### System Configuration

- Nancy version: 1.4.2
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [X] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
  - Nancy.ViewEngines.Razor: 1.4.2
- Environment (Operating system, version and so on): N/A
- .NET Framework version: 4.5

Any advice?

**Comment by felipeleusin** [comment]
Are you referencing this assembly in your configuration (web.config or IRazorConfiguration)? Check https://github.com/NancyFx/Nancy/wiki/Razor-View-Engine
