### ISSUE TITLE
SimpleJson doesn't support nullable integers

### ISSUE THREAD

**Issue by xt0rted** [NancyFx/Nancy#2529]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
### Description

If the class you're deserializing to has a nullable integer then SimpleJson throws an exception.
### Steps to Reproduce

I just ran into this issue last week in my own project and had to hack around it. Modifying the tests in [BrowserFixture.cs](https://github.com/NancyFx/Nancy/blob/d76e7ef6ee938c8ac1f3c42b50b610c158fdeccc/test/Nancy.Testing.Tests/BrowserFixture.cs) so the test model's `int` is `int?` exposes the issue here as well.

I can put together a PR for this in the next day or so. I just wanted to report this before I forgot about it.

**Comment by WinniX** [comment]
Could anyone tell me what is the status of this issue?

**Comment by khellang** [comment]
There's still a pending PR at https://github.com/NancyFx/Nancy/pull/2530

**Comment by WinniX** [comment]
Is there a chance to complete this pull request in the nearest future? Or maybe there is a natural way to get around the issue?

**Comment by thecodejunkie** [comment]
@WinniX I left a comment on that PR to see if we can get it back on the track of being pulled in 👍

**Comment by xt0rted** [comment]
The PR for this was just merged. Not sure when it'll make it to NuGet but it should be on MyGet shortly.
