### ISSUE TITLE
Able to cause host to lock up with concurrent POST requests

### ISSUE THREAD

**Issue by callanwhite** [NancyFx/Nancy#2533]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of Nancy
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Launching a high amount of concurrent POST requests with any kind of body data causes the program to lock up indefinitely and no longer return any responses. In my case, I have managed to reproduce this using both loader.io and jmeter with 100 concurrent requests/second. This only seems to occur when the POST request contains any kind of body data, the server stays responsive when no body data is sent with the POST request. I have not found this to occur using GET requests.

This behaviour is reproducible using both Nancy Self-Hosted, as well as running Nancy under Kestrel/Owin. Switching from using Nancy's routing to, for example, the built in ASP.NET routing does not have this issue. This issue is also reproducible under both Windows and Linux (Ubuntu).

### Steps to Reproduce
Example available at https://dl.dropboxusercontent.com/u/73667353/NancyReproCase.7z
Git repo: https://github.com/callanwhite/NancyReproCase

Run repro project locally and hit the server with concurrent post requests containing any kind of body data. I used Apache JMeter, the config file of which is included in the repro link.
Observe server very quickly seems to lock up and no longer return requests, easily verifiable using something like Postman.
Run the same test but with no post data, server stays responsive throughout the test.

### System Configuration

- Nancy version:
2.0.0 but also seen on 1.4.3.
- Nancy host
  - [X] ASP.NET (Kestrel)
  - [X] OWIN
  - [X] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
Windows 10 (2 different machines), Ubuntu 14.04, Ubuntu 16.04 (running on EC2)
- .NET Framework version:
4,5, Core 1.0
- Additional information:

**Comment by jchannon** [comment]
Thanks for the report. This is concerning

**Comment by jchannon** [comment]
Any chance you could put your project in a git repo?

**Comment by callanwhite** [comment]
I've updated the steps to reproduce with a link to the git repo.

**Comment by jchannon** [comment]
Thanks

Your Nancy example has no routes defined.

**Comment by callanwhite** [comment]
@jchannon The routes are in NancyRouting/Program.cs (apologies for not making that clear, I put the repro case together quite quickly last night)

**Comment by jchannon** [comment]
Thanks, missed that on the phone :)

**Comment by khellang** [comment]
Thanks for the awesome issue and repo, @callanwhite! :heart: This *should* be fixed in the next version :smile:

**Comment by jchannon** [comment]
Yup great work!

**Comment by jchannon** [comment]
It should be in Myget now if you want it asap https://www.myget.org/feed/nancyfx/package/nuget/Nancy
