### ISSUE TITLE
Process is terminated due to StackOverflowException

### ISSUE THREAD

**Issue by Yantrio** [NancyFx/Nancy#2539]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
On latest nancy, when returning Response.AsRedirect("~/") the application exits with the message in the title (`Process is terminated due to StackOverflowException`). 

I have tracked this down to this method : https://github.com/NancyFx/Nancy/blob/d1171954075e81cdad55aca44e51baf21f23611e/src/Nancy/Json/Simple/SimpleJson.cs#L996

The value it's trying to serialize is  of type RedirectResponse

### Steps to Reproduce
return Response.AsRedirect("~/");

### System Configuration

- Nancy version: d1171954075e81cdad55aca44e51baf21f23611e
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [x] Self-Hosted (kestrel)
  - [ ] Other:
- Other Nancy packages and versions:
```
"Nancy.Validation.FluentValidation": {"target": "package", "version": "2.0.0-barneyrubble"},
"Nancy.Bootstrappers.Autofac": "2.0.0-Pre458",
```
- Environment (Operating system, version and so on):
>dotnet --info
```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by khellang** [comment]
> The value it's trying to serialize is of type RedirectResponse

The million dollar question; why is it trying to serialize a `Response` object? It should never get that far in the pipeline...

**Comment by Yantrio** [comment]
upon further inspection (im mid way through solving this) @jchannon has written a `NancyGzipCompression` class which seems to be passing the response into the json serializer so it can gzip it, this may be PEBKAC error here. I'll update as soon as I get more information.

**Comment by jchannon** [comment]
This has been fixed in a fork the VQ has.  This has also been fixed
recently in Nancy not sure why you're seeing this as I saw the same
symptoms and fixed it.

**Comment by jwjosefy** [comment]
As a non native English speaker, I laughed hard when found out what's
PEBKAC 😂😂😂

Em sex, 19 de ago de 2016 09:44, James Humphries <notifications@github.com>
escreveu:

**Comment by thecodejunkie** [comment]
@Yantrio so this can be closed? =)

**Comment by Yantrio** [comment]
Yes, this can be closed, sorry :)
