### ISSUE TITLE
Nancyfx Test Webpage 404 error page

### ISSUE THREAD

**Issue by Elicomp17** [NancyFx/Nancy#2541]
### Description
404 - NotFound

The resource you have requested cannot be found.**

### Steps to Reproduce

I have added the Nancyfx, Nancy.Hosting.Asp.net, and the Nancy.BootStrappers.StructureMap. 

Below is the module I have 

 
```
using Nancy;

namespace NancyExample
{
    public class Class1 : NancyModule
    {
        public Class1()
        {
            Get["/status"] = _ => "Hello world";


        }
    }
}
```

This is just a test case I am trying to implement something larger but I can't seem to get this to work.

### System Configuration

- Nancy version: latest
- Nancy host
  - [X] ASP.NET

- Environment (Operating system, version and so on): Windows 10 and using Visual studio
- .NET Framework version: 4.5.2

@khellang

**Comment by khellang** [comment]
Is this a Nancy 404 or an IIS/ASP.NET 404? Where is this server running (URL) and how are you making the request?

**Comment by Elicomp17** [comment]
I believe this is a Nancy 404 error. I'm using "/status" to generate a page that says "hello world" after the given url in picture.

![capture1](https://cloud.githubusercontent.com/assets/17628870/17933116/7db9bd36-69d8-11e6-8923-a39e9af21ec0.PNG)

**Comment by khellang** [comment]
I don't get it. You're not hitting `http://localhost:64723/status`. You're hitting `http://localhost:64723`. No wonder you're getting a 404 :smile:

**Comment by Elicomp17** [comment]
Yes I'm also doing that 
![capture1](https://cloud.githubusercontent.com/assets/17628870/17933467/db1aafc0-69d9-11e6-9c4f-1ec84a41bb97.PNG)

**Comment by Elicomp17** [comment]
#NancyFX_test

**Comment by khellang** [comment]
If you remove the leading slash:

```diff
-Get["/status"] = _ => "Hello world";
+Get["status"] = _ => "Hello world";
```

Does that work?

**Comment by khellang** [comment]
Also, can you post your web.config?

**Comment by thecodejunkie** [comment]
The leading slash shouldn't have an impact here. I am guessing there is more to the story than what has been said. Is the module the _exact_ module you are using? Are there name space differences? And so on. Usually problems are described using _similar_ but not _identical_ code and details gets lost. The setup you describe is the absolute most common setup for a Nancy application and one that we use over and over again in our sample applications. I'd say it's the most tested execution path in the entire code base, hence why I think there is something else that is not mentioned but having an impact. 😄

**Comment by Elicomp17** [comment]
<?xml version="1.0"?>
<configuration>
  <system.web>
    <httpHandlers>
      <add verb="*" type="Nancy.Hosting.Aspnet.NancyHttpRequestHandler" path="*"/>
    </httpHandlers>
    <compilation debug="true"/>
  </system.web>
  <system.webServer>
    <validation validateIntegratedModeConfiguration="false"/>
    <httpErrors existingResponse="PassThrough"/>
    <handlers>
      <add name="Nancy" verb="*" type="Nancy.Hosting.Aspnet.NancyHttpRequestHandler" path="*"/>
    </handlers>
  </system.webServer>
</configuration>

**Comment by thecodejunkie** [comment]
@Elicomp17 any chance you could zip your project and link it here? Or upload it to a github repo (even better) ?

**Comment by thecodejunkie** [comment]
Also, wrap code in triple back-quote ` and it will be highlighted properly

**Comment by Elicomp17** [comment]
[WebApplication1.zip](https://github.com/NancyFx/Nancy/files/434932/WebApplication1.zip)

**Comment by thecodejunkie** [comment]
I downloaded and ran your application

![image](https://cloud.githubusercontent.com/assets/50543/17934959/0deab43c-6a1a-11e6-868e-16eba3509697.png)

¯\_(ツ)_/¯

**Comment by Elicomp17** [comment]
Could it be a firewall got any hunches on what it could be?

**Comment by thecodejunkie** [comment]
Should just work. There should not be any firewall issues if you are running it all on your local machine. Try manually deleting your bin folder and rebuild (don't just do a clean)

**Comment by Elicomp17** [comment]
okay as in delete everything in it?

**Comment by thecodejunkie** [comment]
Yep

**Comment by Elicomp17** [comment]
'''An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  

Stack Trace: 



[HttpException (0x80004005): Could not load type 'Nancy.Hosting.Aspnet.NancyHttpRequestHandler'.]
   System.Web.Compilation.BuildManager.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase) +9905705
   System.Web.Configuration.HandlerFactoryCache.GetTypeWithAssert(String type) +38
   System.Web.Configuration.HandlerFactoryCache.GetHandlerType(String type) +13
   System.Web.Configuration.HandlerFactoryCache..ctor(String type) +19
   System.Web.HttpApplication.GetFactory(String type) +86
   System.Web.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +224
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

 
'''

Well I deleted content in bin folder and did a rebuild this is what I got afterwards

**Comment by Elicomp17** [comment]
Does it matter which Net framework I'm supposed to use

**Comment by thecodejunkie** [comment]
Your solution (the one you linked) worked perfectly on my machine without any changes at all. It is running Nancy on your machine .. or you wouldn't have gotten the 404 page.. the problem is that the module discovery does not seem to be picking up the module on your machine, which is strange since it's in the same application. Might be a security thing on your box? Type scanning uses reflection in this case.

**Comment by Elicomp17** [comment]
"Might be a security thing on your box? Type scanning uses reflection in this case."

Can you clarify what this part means?

**Comment by thecodejunkie** [comment]
On the full-framework (not .net core) Nancy uses reflection to scan the current `AppDomain` to find all types that inherits from `NancyModule`. Sounds like this is failing for some reason.

**Comment by thecodejunkie** [comment]
Also, try removing the `Nancy.Bootstrappers.StructureMap.1.4.3` because right now you're not really using it (nancy is internally) so remove it to reduce the number of moving parts that could be the potential source of your problem

**Comment by Elicomp17** [comment]
That also Did not work thanks for the help I really appreciate it. I can't figure out whats wrong with it I tried everything you said. Strange how it works for you and not me.  @thecodejunkie

**Comment by Elicomp17** [comment]
Figured it out for some reason the .dll files for the project were missing or were not generated. I ran the solution on a different computer and it generated files that were not in by "obj" files or my "debug" files .
I still can't figure out why though
@khellang 
@thecodejunkie

**Comment by jods4** [comment]
Maybe I missed something in the docs but a big catch here is that your NancyModule needs to be public.
Got bitten by that.

**Comment by streamtree** [comment]
Thanks @jods4; that fixed the issue for me!

**Comment by tedward1** [comment]
no

**Comment by TimEulink** [comment]
Can sombody please help me with this, I cant figure out what im doining wrong.

`using Nancy;
using Nancy.Hosting.Self;
using System;

namespace TestNancyweb
{
    public class Module : NancyModule
    {
        public void SetRoutes()
        {
            Get("/greet/{name}", x => {
                return string.Concat("Hello ", x.name);
            });
        }
    }
}
 







namespace TestNancy
{
    class Program
    {
        
        static void Main(string[] args)
        {
            String url = "http://127.0.0.1:9998";
            HostConfiguration config = new HostConfiguration();
            config.UrlReservations.CreateAutomatically = true;

            var uri = new Uri(url);

            
            using (var host = new NancyHost(config, uri))
            {
                host.Start();
                Console.WriteLine("Running on " + uri);
                Console.ReadLine();

                while(true)
                {
                    //logger.Debug("API heartbeat");
                    System.Threading.Thread.Sleep(1000);

                }
            }
        }
    }
}
`
