### ISSUE TITLE
The _nc cookie is too big ,in my case more than 4M.

### ISSUE THREAD

**Issue by xiaowy** [NancyFx/Nancy#2544]
The _nc cookie is more than 4M , so response very slowly , just written the following code in my case.
  protected override void ApplicationStartup(TinyIoCContainer container, IPipelines pipelines)
        {
            base.ApplicationStartup(container, pipelines);
            CookieBasedSessions.Enable(pipelines);
        }

- Nancy version:
   1.4.2.0

- Nancy host
    Self-Hosted 

- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
win7 + sp1
- .NET Framework version: 
4.5.2

**Comment by phillip-haydon** [comment]
The max size is 4093 bytes for cookies.

Don't store so much data in your session. Store it in the database.

**Comment by xiaowy** [comment]
I don't store any data.

**Comment by phillip-haydon** [comment]
Cookie size limit is 4k, not 4M (I assume you mean 4 megabytes), per domain. 

That means you can either have 1 cookie at ~4000 bytes or 2 cookies at ~2000 bytes.

There is no way you have such a large cookie.
