### ISSUE TITLE
Nancy.Hosting.Aspnet improperly handles chunked Transfer-Encoding

### ISSUE THREAD

**Issue by yahehe** [NancyFx/Nancy#2546]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
### Description

When hosted with ASP.Net, Nancy does not properly handle incoming requests with the Transfer-Encoding header set to 'chunked'. When Transfer-Encoding is set to 'chunked', the Content-Length header is absent (see: https://en.wikipedia.org/wiki/Chunked_transfer_encoding). NancyHandler only sets the Body stream if Content-Length exists and is not zero, so the stream is never set for chunked requests. 
### Steps to Reproduce

1) Create a POST endpoint
2) Send chunked data to the endpoint with the following format (make sure Content-Length is not set): https://en.wikipedia.org/wiki/Chunked_transfer_encoding#Format
3) Verify that Request Body is null
### System Configuration
- Nancy version: 1.4.3
- Nancy host
  - [x] ASP.NET
  - [ ] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on): 64bit Windows Server 2012 R2 v1.1.0 running IIS 8.5
- .NET Framework version: 4.5.2
- Additional information:

**Comment by Franki1986** [comment]
Anything new here?

**Comment by yahehe** [comment]
New? No, I've had a PR (#2547) open for a while now.

**Comment by thecodejunkie** [comment]
Sorry lads! Just gave Kristian a ping on the PR and kicked of the broken build server again (it kicked because of a problem with Travis)

**Comment by wilhen01** [comment]
@yahehe @thecodejunkie we've just run across this in a project using Nancy 1.4.4 and could use a fix. Having looked at the code I don't think it's fixed in 2.0.0-clienteastwood either? Could upgrade to 2.0.0 for the fix if it exists there (assuming 2.0.0 runs on .Net Framework and not just .Net Core...)

**Comment by yahehe** [comment]
Sorry, forgot about this since I no longer use .Net at work :(
I'll port this fix to clinteastwood this weekend.

**Comment by wilhen01** [comment]
@yahehe thanks man, much obliged!
