### ISSUE TITLE
403 on Hello World

### ISSUE THREAD

**Issue by 7eee** [NancyFx/Nancy#2549]
Hello,

I am very new to NancyFX, though experienced with C# for desktop apps. I just created a barebones project based on helloworld instructions from the docs, but I got this error when I run my app:

HTTP Error 403.14 - Forbidden
The Web server is configured to not list the contents of this directory.

I then added

```
<system.webServer>
    <directoryBrowse enabled="true" showFlags="Date,Time,Extension,Size" />
  </system.webServer>
```

to my `Web.config`, and now I am getting a directory listing of my project directory (not `bin`)

I am not getting any kind of `Hello, World` or anything. What am I doing wrong?

My one and only source file:

```
using Nancy;

namespace NancyHelloWorld
{
    public class HelloModule : NancyModule
    {
        public HelloModule()
        {
            Get("/", args => "Hello World");
        }
    }
}
```

**Comment by phillip-haydon** [comment]
Hi,

We have an issue template which asks for specific information to help us with these sort of problems. Without that information and/or a project for us to view, it's very hard to help you.

**Comment by grumpydev** [comment]
You probably haven't installed a hosting package.

**Comment by FVMSAW** [comment]
there may be conflict in server host numberlike 8080
