### ISSUE TITLE
I want to know  how many  applications and sites run on nancy?if u know tell me!

### ISSUE THREAD

**Issue by icpka** [NancyFx/Nancy#2552]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of Nancy
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### System Configuration

- Nancy version:
- Nancy host
  - [ ] ASP.NET
  - [x] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by khellang** [comment]
Umm... I'm not sure how we're supposed to know that without including some "phone home" tracking or something in our users software, which we'd never do. You can take a look at the [number of installed packages](https://www.nuget.org/profiles/NancyFx) if you want. That's probably the best number we have...
