### ISSUE TITLE
No response @ Nancy.Demo.Hosting.Kestrel

### ISSUE THREAD

**Issue by Deilan** [NancyFx/Nancy#2556]
Repro steps:
1) Start the Nancy.Demo.Hosting.Kestrel app
2) Make a request to it from the browser
Result:
No response.

**Comment by jchannon** [comment]
Pretty sure this must be a tooling issue you have

**Comment by Deilan** [comment]
@jchannon, then please make an instruction on how to setup tooling for run your samples. Because a simple hello-world-app based on Nancy 2.0 works fine.

**Comment by jchannon** [comment]
I'm not sure what the issue is really.

The kestrel demo is pretty much a hello world example with a bit more code.

As long as you have the latest CoreCLR runtime and CLI installed it should
work fine.

**Comment by jchannon** [comment]
<img width="824" alt="screen shot 2016-09-11 at 11 31 45" src="https://cloud.githubusercontent.com/assets/105126/18416695/627a10a4-7813-11e6-8e2f-c42cc69c8b64.png">

**Comment by Deilan** [comment]
@jchannon, I do have the latest CoreCLR runtime and CLI installed and all the latest updates and fixes for Visual Studio 2015. If you explain some way to collect logs/traces/etc., which could help for the case, I will collect it and provide it to you.

**Comment by jchannon** [comment]
You could try adding a OnError delegate and a breakpoint to see if that gets hit.

https://github.com/NancyFx/Nancy/wiki/The-Application-Before,-After-and-OnError-pipelines

That might help if Nancy is throwing an exception but I'd expect a 500 response not just "no response"
