### ISSUE TITLE
Request.Body.AsString() in BeforPipeline brokes this.Bind()

### ISSUE THREAD

**Issue by mykytanikitenko** [NancyFx/Nancy#2559]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I'm using method AsString() for RequestStream in BeforeRequest pipeline, it modifes request and after this when I'm binding this request in module, it deserializes properties to default values.

### Steps to Reproduce
1. Implementent IApplicationStartup
2. Use anywhere in BeforeRequest pipeline method AsString() for RequestStream
3. Bind model for request in module using this.Bind()
### System Configuration
Windows 10, VS 2015

- Nancy version:
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [x] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions: Nancy.Bootstrappers.Autofac, Nancy.Serialization.JsonNet
- Environment (Operating system, version and so on): Windows 10 
- .NET Framework version: net46
- Additional information: I'm injecting another interface to constructor of implementation IApplicationStartup

**Comment by jchannon** [comment]
It's be caused it's pulled it out the stream. When you do it try setting
the position back to zero

**Comment by mykytanikitenko** [comment]
Yes, setting requestStream position to zero helped, but it's very strange behavior.

**Comment by jchannon** [comment]
Its standard behaviour of streams
