### ISSUE TITLE
Unit test "Add_duplicate_parameter_in_different_casing_throws_argument_exception" failed when system culture is not "en".

### ISSUE THREAD

**Issue by EAllmann** [NancyFx/Nancy#2565]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The Unit test "Add_duplicate_parameter_in_different_casing_throws_argument_exception" failed when system Culture is not en.
The test compare the exception message to a constant string: "An item with the same key has already been added."
If the default system language is not englisch the test will fail.

### Steps to Reproduce
Run the Unit Tests on a system with an other culture then "en".

### System Configuration

I run the tests configured for de-DE

- Nancy version:
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by khellang** [comment]
Thanks for reporting @EALLMANN! :heart:
