### ISSUE TITLE
Link in Remarks of IHideObjectMembers does not exist.

### ISSUE THREAD

**Issue by KlemensE** [NancyFx/Nancy#2571]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
### Description

Not a bug but the link in the remark of IHideObjectMembers does not exist. It gives a 404.
http://www.clariusconsulting.net/blogs/kzu/archive/2008/03/10/58301.aspx

https://github.com/NancyFx/Nancy/blob/master/src/Nancy/IHideObjectMembers.cs#L10
- Nancy version: 1.4.3

**Comment by khellang** [comment]
The blog post is at http://blogs.clariusconsulting.net/kzu/how-to-hide-system-object-members-from-your-interfaces/ now. Want to send a PR?
