### ISSUE TITLE
Can't get host working with RewriteLocalHost set to false and not running as admin

### ISSUE THREAD

**Issue by glenserraview** [NancyFx/Nancy#2572]
I'm trying to configure nancy as a self hosting app and want:
- RewriteLocalhost set to false - in case the customer wants the host to only be accessible from the local box
- Not require running as administrator

Here is sample code that illustrates the problem:

```
class Program
  {
    static void Main(string[] args)
    {
      var uri =
        new Uri("http://localhost:3579");
      var config = new HostConfiguration {RewriteLocalhost = false};

      using (var host = new NancyHost(config, uri))
      {
        host.Start();

        Console.WriteLine("Your application is running on " + uri);
        Console.WriteLine("Press any [Enter] to close the host.");
        Console.ReadLine();
      }
    }
  }

  public class EchoModule : NancyModule
  {
    public EchoModule()
    {
      Get["/"] = _ => Response.AsJson("Success");
    }
  }
```

I have added a urlacl entry:

```
   Reserved URL            : http://localhost:3579/
        User: \Everyone
            Listen: Yes
            Delegate: No
            SDDL: D:(A;;GX;;;WD)
```

I then get a 503 error from http://localhost:3579/. If I change RewriteLocalhost to true, it works perfectly (I'm not sure why, since the urlacl shouldn't match http://+:3579)

Can anyone shed any light on this?

**Comment by khellang** [comment]
What happens if you use `127.0.01` instead?

**Comment by grumpydev** [comment]
Yeah, could be a "localhost resolves to ::1" thing - I've had that stuff things up before in other things.

**Comment by glenserraview** [comment]
@khellang Do you mean in the code or in the client trying to hit the service, or the urlacl or all/none?

**Comment by khellang** [comment]
> What happens if you use 127.0.0.1 instead?

I mean both urlacl reservation *and* the URL in the code.

> What is the Host header that's sent to the server?

I mean the HTTP `Host` header :smile:

> Can you list out your reservations? Make sure there are no wildcards reserved for other accounts or something, That could mess things up.

I mean your urlacl reservations.

**Comment by glenserraview** [comment]
uri in code|urlacl|RewriteLocalhost|Result
------------|-----|-------------------|-------
http://127.0.0.1:3579|http://127.0.0.1:3579/|false|Server wouldn't start, with AutomaticUrlReservationCreationFailureException
Http://localhost:3579|Http://localhost:3579/|false|Server wouldn't start, with AutomaticUrlReservationCreationFailureException
http://localhost:3579|http://localhost:3579/|true|Chrome dev tools shows Host header value: Host:localhost:3579

Here's an export of all my urlacl reservations
[out.txt](https://github.com/NancyFx/Nancy/files/496981/out.txt)

**Comment by khellang** [comment]
Eh. I couldn't find the urlacl entry you said you had added. Instead, I found these:

```
    Reserved URL            : http://*:3579/ 
        User: NT AUTHORITY\NETWORK SERVICE
            Listen: Yes
            Delegate: No
            SDDL: D:(A;;GX;;;NS) 

    Reserved URL            : http://localhost:3579/ 
        User: NT AUTHORITY\NETWORK SERVICE
            Listen: Yes
            Delegate: No
            SDDL: D:(A;;GX;;;NS) 
```

Looks like you didn't follow my advice;

> Make sure there are no wildcards reserved for other accounts or something, That could mess things up.

Remove the existing reservations and add one for the correct user.

**Comment by glenserraview** [comment]
Please don't close the issue before it's been resolved!

I see the extra urlacl's, sorry, I've been adding and removing things trying to troubleshoot this. I also was cleaning up the ones I listed in my table as I was going.

I've removed them all, leaving only:

> Reserved URL            : http://localhost:3579/ 
>         User: NT AUTHORITY\NETWORK SERVICE
>             Listen: Yes
>             Delegate: No
>             SDDL: D:(A;;GX;;;NS)

Then trying to start the host on localhost3579 gets the 'Nancy.Hosting.Self.AutomaticUrlReservationCreationFailureException'..

I then removed that and added 127.0.0.1

>     Reserved URL            : http://127.0.0.1:3579/ 
>         User: NT AUTHORITY\NETWORK SERVICE
>             Listen: Yes
>             Delegate: No
>             SDDL: D:(A;;GX;;;NS) 

Then trying to start the host on 127.0.0.1:3579 gets the 'Nancy.Hosting.Self.AutomaticUrlReservationCreationFailureException'.

I've attached my urlacl entries after localhost was removed and 127.0.0.1 was added
[out.txt](https://github.com/NancyFx/Nancy/files/499471/out.txt)

**Comment by khellang** [comment]
> Please don't close the issue before it's been resolved!

I closed it because this is not really a Nancy issue. At this point, we're troubleshooting your Windows setup. There's thousands of people running self-hosted Nancy without problems.

> Then trying to start the host on 127.0.0.1:3579 gets the 'Nancy.Hosting.Self.AutomaticUrlReservationCreationFailureException'.

This is probably because you've configured the reservation for `NT AUTHORITY\NETWORK SERVICE`, but the application is running as a different user.

**Comment by glenserraview** [comment]
I understand that thousands of people are running with no problem. I can run nancy in other combinations of parameters. The specific combination of localhost and RewriteLocalHost = false is what's causing the problem. Is this a supported scenario? Can you confirm that it works for you?

I've changed the urlacl entry to be my user and visual studio is not running as admin and it still doesn't work.

**Comment by shana** [comment]
Leaving this here in case someone else runs into this problem: to use localhost without admin rights or the need for acl reservations, you need to use a high port number (> 1024) that is not taken by other apps and has no urlacl reservation. Port ranges 49152 to 65535 are dedicated to private or customized services, temporary connections and ephemeral ports, so those will not likely have existing reservations on the system.
