### ISSUE TITLE
ModelBinding - Fails to bind if was called in Before hook or more than once in the Module

### ISSUE THREAD

**Issue by leonibr** [NancyFx/Nancy#2583]
using Nancy 1.4.3 - Owin Self Host

Let's say I have a module `FakeIdModule` that inherits from an abstract module and uses its constructor to define a base route `/fake/{idUri:long}`, then I provide a `ValidateIdUri` function in the Before hook to verify the `idUri` for all routes.
It is all working great up to this point, but when the requests enters the route `'POST /fake/{idUri:long}/property-one'` the call to `Bind<...>()` fails because returns an empty object.
If the call to `ValidateIdUri` is commented everything works as expected

```
    //inside module
    internal class FromUri
    {
        public long idUri {get;set;}
    }
    internal class FakeRequest
    {
        public string Name {get;set;}
        public int Year {get;set;}
    }
    
    public FakeIdModule(IService _service): base("/fake/{idUri:long}")
    {
        service = _service;
        this.Before.AddItemToStartOfPipeline(ValidateIdUri);
        Post["/property-one"] = PostPropertyOne;
    }
    private Task<Response> ValidateIdUri(NancyContext context, CancellationToken cancel)
    {
        var id = this.Bind<FromUri>().idUri;  ///used first time - IT WORKS, if I comment this line and its dependencies it will work on next method
        if (!id)
            return Task<Response>.Factory.StartNew(() => {
                    return HttpStatusCode.NotFound;
                });
        var obj = service.GetById(id);
        if (!obj)
            return Task<Response>.Factory.StartNew(() => {
                    return HttpStatusCode.NotFound;
                });
        return Task<Response>.Factory.StartNew(() => {
                    return null;
                });
    }

    //route POST: /fake/1234/property-one
    public dynamic PostPropertyOne(dynamic arg)
    {
        var fakeObject = this.Bind<FakeRequest>();  //DOES NOT WORK! Only if the previous bind is commented
        /// ...
    }
```

**Comment by jchannon** [comment]
Binding should work like that but what are you sending in the request, how
can it bind to two separate objects unless you are sending in iduri, name
and year in your POST

**Comment by leonibr** [comment]
I didnt want to repeat the logic of verify idUri in every route, something like (using angularjs): 

`$http.post('/fake/1234/property-one', {name: 'Fake name', year: 2016 })`
`$http.post('/fake/1234/another-property', {comment: 'this is another comment' , year : 2016 })`

For every route I must verify if 1234 is valid, and then get the data sent.

**Comment by jchannon** [comment]
Long shot but thought it had been fixed. After first Bind do Body.Position
= 0

**Comment by leonibr** [comment]
That is it!!!
Thank you
