### ISSUE TITLE
Do not perform system wide installations in the build script

### ISSUE THREAD

**Issue by adamralph** [NancyFx/Nancy#2586]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I run build.ps1 or build.sh, a specific version of the .NET CLI is installed on my system. IHMO a build script should not be performing system-wide installations. It should generally only be manipulating the file system inside the repo folder, plus those parts of the file system which are designed for per-app/script persistence, e.g. the temp folder or AppData. The minimum versions of system-wide installations should be listed in the pre-requisites instead.

### Steps to Reproduce
Run build.ps1 or build.sh.

**Comment by khellang** [comment]
It's not system-wide though; https://github.com/NancyFx/Nancy/blob/master/build.sh#L32

**Comment by grumpydev** [comment]
Yeah, always installs locally when I've used it - never run as admin so not sure how it would install globally anyway?

**Comment by adamralph** [comment]
Embarrassing.  I missed `--install-dir`.

That will teach me to raise issues in the middle of the night when I can't sleep. Apologies.
