### ISSUE TITLE
RequestExtensions.IsLocal returning false on local url even though Nancy.Request.UserHostAddress is "127.0.0.1" 

### ISSUE THREAD

**Issue by dcr26** [NancyFx/Nancy#2589]
### Description
I need to check that a request I receive is coming from the local machine before I serve this request.

### Steps to Reproduce
Start a nancy server, and in a module determine if the request is from a local address as below:

`bool isLocalRequest = _nancyContext.Request.IsLocal();`

FYI - the _nancyContext.Request.UserHostAddress = "127.0.0.1"

I expect isLocalRequest to be true but that is not the case. 

### System Configuration

- Nancy version:  Nancy, Version=1.4.1.0
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [ X ] Self-Hosted
  - [ ] Other:
- Environment (Operating system, version and so on): Win 10 x64 
- .NET Framework version: 4.6
- Additional information:

Sorry to add fix but this is what I have done to rectify the issue:
`if (_nancyContext.Request.UserHostAddress == "127.0.0.1" || _nancyContext.Request.UserHostAddress== "::1") isLocalRequest = true;`

**Comment by khellang** [comment]
What's the value of `_nancyContext.Request.Url`?

**Comment by dcr26** [comment]
local.Mydomain.com which has a DNS entry to 127.0.0.1

**Comment by jchannon** [comment]
Why do you have _nancycontext in a module? You can use this.Request.Context

**Comment by dcr26** [comment]
I don't its actually in my nancy startup IApplication Initialize(IPipelines pipelines) .... on the pipelines.BeforeRequest but its easier to illustrate the problem here. Trying to keep the steps to reproduce simple... sorry if its a bit confusing.
