### ISSUE TITLE
Different instances resolved after Singleton registration

### ISSUE THREAD

**Issue by stefaanv** [NancyFx/Nancy#2592]
### Description
I am trying to add a restfull instrumentation interface using Nancy (selfhosting in Console app) into an application that I am writing.
Because the application supports pluggable types, I already have Autofac for IoC support.
My NancyContainer has a dependancy on the type `HttpGatewayInstrumentation ` in which I keep the information that needs to be reported to the REST interface.

```
namespace ProtocolHub
{
    public class HelloModule : Nancy.NancyModule
    {
        HttpGatewayInstrumentation i;

        public HelloModule(**IGatewayInstrumentation i**)
        {
            this.i = i;
            Get["/"] = parameters =>
            {
                return View["test.sshtml", new { Name = "test:" + i.List().Count().ToString() }];
            };
        }
    }
}
```

However, since the pluggable modules also have a dependency on the same HttpGatewayInstrumentation instance, I'm resolving the instance in the beginning of the application and inserting it into the AutoFac container like this 

```
            var hostConfig = new HostConfiguration();
            hostConfig.UrlReservations.CreateAutomatically = true;
            hostConfig.UrlReservations.User = "stefaan";
            using (var host = new NancyHost(hostConfig, new Uri("http://localhost:1234")))
            {
                host.Start();
                Console.WriteLine("Running on http://localhost:1234");

                **//get the instance from Nancy IoC**
                var gwi = Nancy.TinyIoc.TinyIoCContainer.Current.Resolve<HttpGatewayInstrumentation>();

                var builder = new ContainerBuilder();
                builder.RegisterInstance(log).Exported(x => x.As<ILog>());

                **// Put the instance into AutoFac container**
                builder.RegisterInstance(gwi).Exported(x => x.As<IGatewayInstrumentation>());
                builder.RegisterInstance(controller).Exported(x => x.As<IController>());
                builder.RegisterComposablePartCatalog(catalog);
                builder.RegisterType<Controller>().As<IController>().SingleInstance();
    ... etc

```

Here is how I override the Nancy bootstrapper
```
    public class CustomBootstrapper : DefaultNancyBootstrapper
    {
        protected override void ApplicationStartup(TinyIoCContainer container, IPipelines pipelines)
        {
            container.Register<IGatewayInstrumentation, HttpGatewayInstrumentation>().AsSingleton();
        }
    }

```
Why do I keep getting different instances from the Nancy IoC container and from the Autofac IoC container ?  Actually, when I add a instantiation counter to HttpGatewayInstrumentation it turns out Nancy uses the first created instance while the instance returned into the gwi variable is the 3rd one created in the application.  Why does nancy not stick to one instance, as instructed ?

When I change the instance resolve code into var `gwi = Nancy.TinyIoc.TinyIoCContainer.Current.Resolve<IGatewayInstrumentation>();`, I get a Nancy.TinyIoc.TinyIoCResolutionException which baffles me because it looks to me like it is more correct to request the interface than the concrete class because the interface is registered to Nancy, not the concrete class.

**Comment by khellang** [comment]
OK, there's quite a lot going on here. Let me go through some things;

1. Just a minor, but there's no reason to assign injected services to fields: `this.i = i;`
2. You're using `TinyIoCContainer.Current` to resolve the `HttpGatewayInstrumentation` instance. That's always wrong. Nancy does not use `TinyIoCContainer.Current` in any way, so that will always be a separate "singleton".
3. When you're registering stuff using the Autofac `ContainerBuilder`, you're using `.Exported(x => x.As<IGatewayInstrumentation>())`. Is that intended? Are you also using MEF? If not, that should probably just be `.As<IGatewayInstrumentation>()`.
4. Why are you using Autofac alongside your host, but not in Nancy? You're deriving from `DefaultNancyBootstrapper`, which means you're using the TinyIoC-based bootstrapper. Don't you want to use `Nancy.Bootstrappers.Autofac`? How is Nancy supposed to know about your Autofac container?

This leads us to some of your questions:

> Why do I keep getting different instances from the Nancy IoC container and from the Autofac IoC container ?

As mentioned above, `TinyIoCContainer.Current` is totally unrelated to Nancy. This is a separate container instance. Nancy will also create its own application container, which is the one you're getting passed in `ApplicationStartup`. This means that you will always get (at least) two different instances within your application.

> Why does nancy not stick to one instance, as instructed ?

Again, how have you instructed Nancy to use a single instance?

> When I change the instance resolve code into `var gwi = Nancy.TinyIoc.TinyIoCContainer.Current.Resolve<IGatewayInstrumentation>();`, I get a `Nancy.TinyIoc.TinyIoCResolutionException` which baffles me because it looks to me like it is more correct to request the interface than the concrete class because the interface is registered to Nancy, not the concrete class.

How have you registered the `IGatewayInstrumentation` service? If I'm not mistaken, TinyIoC lets you resolve concrete classes without registering it first. That's why it works with the concrete class, but not the interface.

**Comment by stefaanv** [comment]
Hi, thank for the very swift reply.
Looking at your answer I start to feel rather ignorant.
Let's try to answer some of your questions
1. (this.i = i) Yes, you're right
2. OK, that make sense.  Can I access the correct Nancy IoC in my Main() function ?
3. Yes, I'm using MEF for the ability to plug in new classes after deployment.  It took me a lot of effort to get MEF going, so I wouldn't be surprised if there's shortcuts here and there.  However, things work with the current code
4. I wasn't aware I could use Autofac as IoC for Nancy.  i'll have a look into that, thanks for the suggestion, I guess that will be the solution to the problem, I'll let you know.

**Comment by khellang** [comment]
> Can I access the correct Nancy IoC in my Main() function ?

Yes, but you have to create the container and pass it to the bootstrapper. You then have to override the `GetApplicationContainer` method and return the container instance you passed in. If you want to look at an example doing this with Autofac, you can take a look at https://github.com/khellang/Nancy.AutofacExample/blob/master/src/Nancy.AutofacExample/Program.cs

**Comment by stefaanv** [comment]
No luck, I'm having trouble translating the example (which I assume is for OWIN ?) to NancyHost.
So, I copied the bootstrapper class from the example
```
    public class Bootstrapper : AutofacNancyBootstrapper
    {
        private readonly ILifetimeScope _lifetimeScope;

        public Bootstrapper(ILifetimeScope lifetimeScope)
        {
            _lifetimeScope = lifetimeScope;
        }

        protected override ILifetimeScope GetApplicationContainer()
        {
            return _lifetimeScope;
        }
    }
```
Next, I adapted the part where I start the Nancy server
```
            var bootstrapper = new Bootstrapper(container);
            using (var host = new NancyHost(bootstrapper, hostConfig, new Uri("http://localhost:1234")))
            {
                host.Start();
                Console.WriteLine("Running on http://localhost:1234");
                Console.ReadLine();
            }
```

Now when I use the below Autofac registration code, then the part (`container.ResolveExports<IGatewayFactory>().ToDictionary(x=>x.Value.GetType().Name);`) where I get the MEF pluggable types cannot resolve IGatewayInstrumentation.
```
            var catalog = new AggregateCatalog();
            catalog.Catalogs.Add(new DirectoryCatalog(System.IO.Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)));
            _container = new CompositionContainer(catalog);
            _container.ComposeParts(this);

            var builder = new ContainerBuilder();
            builder.RegisterInstance(log).Exported(x => x.As<ILog>());
            var gwi = new HttpGatewayInstrumentation();
            builder.RegisterInstance(gwi).As<IGatewayInstrumentation>().SingleInstance();
            builder.RegisterInstance(controller).Exported(x => x.As<IController>());
            builder.RegisterComposablePartCatalog(catalog);
            builder.RegisterType<Controller>().As<IController>().SingleInstance();
            var container = builder.Build();

```

If, on the other hand, I use the below for the Autofac registration the I get this exception in the activation of the NancyHost
"None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'ProtocolHub.HelloModule' can be invoked with the available services and parameters:
Cannot resolve parameter 'ProtocolHub.IGatewayInstrumentation i' of constructor 'Void .ctor(ProtocolHub.IGatewayInstrumentation)'."

```
            var catalog = new AggregateCatalog();
            catalog.Catalogs.Add(new DirectoryCatalog(System.IO.Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)));
            _container = new CompositionContainer(catalog);
            _container.ComposeParts(this);

            var builder = new ContainerBuilder();
            builder.RegisterInstance(log).Exported(x => x.As<ILog>());
            var gwi = new HttpGatewayInstrumentation();
            builder.RegisterInstance(gwi).Exported(x => x.As<IGatewayInstrumentation>());
             builder.RegisterInstance(controller).Exported(x => x.As<IController>());
            builder.RegisterComposablePartCatalog(catalog);
            builder.RegisterType<Controller>().As<IController>().SingleInstance();
            var container = builder.Build();
```

**Comment by stefaanv** [comment]
OK, got it solved by using this Autofac registration code
```
            var catalog = new AggregateCatalog();
            catalog.Catalogs.Add(new DirectoryCatalog(System.IO.Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)));
            _container = new CompositionContainer(catalog);
            _container.ComposeParts(this);

            var builder = new ContainerBuilder();
            builder.RegisterInstance(log).Exported(x => x.As<ILog>());
            var gwi = new HttpGatewayInstrumentation();
            builder.RegisterInstance(gwi).Exported(x => x.As<IGatewayInstrumentation>());
            builder.RegisterInstance(gwi).As<IGatewayInstrumentation>().SingleInstance();
            builder.RegisterInstance(controller).Exported(x => x.As<IController>());
            builder.RegisterComposablePartCatalog(catalog);
            builder.RegisterType<Controller>().As<IController>().SingleInstance();
            var container = builder.Build();

```
