### ISSUE TITLE
FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0

### ISSUE THREAD

**Issue by durilka** [NancyFx/Nancy#2593]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I've migrated my NancyFX 1.4 app to 2.0-barneyrubble and after some tweaking made it run and work. When using Json binding, though, I'm getting the following error:

```

2016-10-20 15:57:57.1437|Bootstrapper|ERROR|Exception: Nancy.ModelBinding.ModelBindingException: Unable to bind to type: Max.Routes.AccountPublic+LogonModel ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

   at Nancy.Serialization.JsonNet.JsonNetBodyDeserializer.Deserialize(MediaRange mediaRange, Stream bodyStream, BindingContext context)
   at Nancy.ModelBinding.DefaultBinder.Bind(NancyContext context, Type modelType, Object instance, BindingConfig configuration, String[] blackList)
   --- End of inner exception stack trace ---
   at Nancy.ModelBinding.DefaultBinder.Bind(NancyContext context, Type modelType, Object instance, BindingConfig configuration, String[] blackList)
   at Nancy.ModelBinding.DynamicModelBinderAdapter.TryConvert(ConvertBinder binder, Object& result)
   at CallSite.Target(Closure , CallSite , Object )
   at CallSite.Target(Closure , CallSite , Object )
   at Max.Routes.AccountPublic.<Login>d__4.MoveNext() in /Users/sasha/projects/work/ABB/MaX/src/MaX/BackendNew/src/Api/Routes/AccountPublic.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Routing.DefaultRouteInvoker.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Routing.DefaultRequestDispatcher.<Dispatch>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

```

### Steps to Reproduce
In a route call this.Bind<SomeJsonModel>();

### System Configuration
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64

- Nancy version: 2.0-barneyrubble
- Nancy host
  - [ ] ASP.NET
  - [x] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
    "Nancy": "2.0.0-barneyrubble",
    "Nancy.Hosting.Aspnet": "2.0.0-barneyrubble",
    "Nancy.Authentication.Basic": "2.0.0-barneyrubble",
    "Nancy.Serialization.JsonNet": "2.0.0-barneyrubble",

- Environment (Operating system, version and so on):
MacOS 10.12

- .NET Framework version:
Core net 1.0.0-preview2-003131

- Additional information:
Any ideas? Thank you!  (NancyFX is awesome!)

**Comment by khellang** [comment]
Could you share your project.json? Do you know which version of Newtonsoft.Json you ended up with? I think it might be worth pinning it to `"Newtonsoft.Json": "9.0.1"`.

**Comment by durilka** [comment]
```
{
  "version": "1.0.0",
  "title": "Max.API",
  "buildOptions": {
    "define": [
      "DEBUG"
    ],
    "emitEntryPoint": true,
    "debugType": "portable"
  },
  "tooling": {
    "defaultNamespace": "Max"
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Shared": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.*",
    "Microsoft.AspNetCore.Owin": "1.*",
    "Microsoft.AspNetCore.Cryptography.KeyDerivation": "1.*",
    "Nancy": "2.0.0-barneyrubble",
    "Nancy.Hosting.Aspnet": "2.0.0-barneyrubble",
    "Nancy.Authentication.Basic": "2.0.0-barneyrubble",
    "Newtonsoft.Json": "9.*",
    "Nancy.Serialization.JsonNet": "2.0.0-barneyrubble",
    "Microsoft.EntityFrameworkCore.Sqlite": "1.*",
    "Microsoft.EntityFrameworkCore.Sqlite.Design": "1.*",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.*",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.*",
    "Microsoft.Extensions.Configuration.Json": "1.*",
    "Microsoft.Extensions.Configuration.Binder": "1.*",
    "Microsoft.Extensions.Logging": "1.*",
    "Microsoft.Extensions.Logging.Console": "1.*",
    "Microsoft.Extensions.Logging.Debug": "1.*",
    "AutoMapper": "5.1.1",
    "NLog": "4.4.0-betaV15",
    "NLog.Extensions.Logging": "1.0.0-rtm-alpha4",
    "jose-jwt": "2.0.1"
  },
  "tools": {},
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.1"
        }
      },
      "imports": [
        "net452",
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },
}
```

I've tried forcing 9.0.1, no result (previous was 9.0.0)

**Comment by khellang** [comment]
Hmm. There's something in that list that's not meant for running on `netcoreapp1.0`. The `"imports"` section there has me worried. What's the reason you have those in there? I think you might be better off just running on `net452` if you have older assemblies that doesn't target `netstandard1.x`.

**Comment by khellang** [comment]
Hmm. It looks like `Nancy.Serialization.JsonNet` that hasn't been updated to support `netstandard1.x`. `Nancy.Hosting.Aspnet` will also be a problem, since that's based on `System.Web` (and doesn't run on .NET Core).

**Comment by durilka** [comment]
The list of imports is basically a desperate attempt to make it work. Strangely enough if i have 
```
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.1"
        }
      },
      "imports": [
        "net452"
      ]
    }
  },

```

everything still compiles and starts but the problem persists as well.
Yup, no netstandard for `Nancy.Serialization.JsonNet`. Looks like i'm a little stuck if that's the cause then.

**Comment by khellang** [comment]
It might be. Do you have a specific need to target `netcoreapp1.0`? If you can run on full framework, you can just target `net452` for now, then switch back (or multi-target) later, when we've pushed support for `netstandard1.x` to `Nancy.Serialization.JsonNet`.

**Comment by jchannon** [comment]
Or do you have a specific need to use JsonNet?

**Comment by durilka** [comment]
seems to be not supported on mac os, which is my dev environment. i can try to go docker but that doesn't seem to work out of the box either, 99 problems :)

**Comment by durilka** [comment]
@jchannon fair point. i was using it in 1.4 because ... well, the default one was acting a little strange :)
Now i got rid of it and the binding seems to be working. Closing as "has a workaround".
