### ISSUE TITLE
Version 2.00 requires DotNet 4.5.2. Can this be changed to 4.5.0?

### ISSUE THREAD

**Issue by yzhou88** [NancyFx/Nancy#2607]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

My big project is using Dotnet 4.5.0, when upgrading Nancyfx, we will be forced to 4.5.2. Can Nancy 2.00 support Dotnet 4.5.0?

**Comment by jchannon** [comment]
Nope afraid not due to how netcore works.

Sorry

**Comment by yzhou88** [comment]
Ok. But with Version 1.4.3, there is a memory leak issue that I have found and fixed, can you release a new version? The pull request is here:
https://github.com/NancyFx/Nancy/pull/2605

**Comment by cemremengu** [comment]
Just change your big project to target net452 @yzhou88 ? You will eventually need to do that anyway.

**Comment by yzhou88** [comment]
Thank you for your good suggestion.
