### ISSUE TITLE
Nancy.Bootstrapper.BootstrapperException: Located multiple bootstrappers

### ISSUE THREAD

**Issue by cemremengu** [NancyFx/Nancy#2617]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed]  issues to ensure it has not already been reported

### Description

When you implement a bootstrapper other then the default one, nancy fails to starts unless
you explicitly specify your bootstrapper with

```
app.UseOwin(x => x.UseNancy(options => { options.Bootstrapper = new Bootstrapper(); }));
```

Let me know if you need a sample project showing this (I couldnt attach here)

### Steps to Reproduce
- Get the packages
- Create a bootstrapper by implementing the AutofacBootstrapper. (so that there is only one bootstrapper that is explicitly implemented)
- Run your app wıth `app.UseOwin(x => x.UseNancy());`
- Bon apetit!

```
namespace BootstrapperBug
{
    using Autofac;
    using Nancy;
    using Nancy.Bootstrapper;
    using Nancy.Bootstrappers.Autofac;

    public class Bootstrapper : AutofacNancyBootstrapper
    {
        protected override void ApplicationStartup(ILifetimeScope container, IPipelines pipelines)
        {
            // No registrations should be performed in here, however you may
            // resolve things that are needed during application startup.
        }

        protected override void ConfigureApplicationContainer(ILifetimeScope existingContainer)
        {
            // Perform registration that should have an application lifetime
        }

        protected override void ConfigureRequestContainer(ILifetimeScope container, NancyContext context)
        {
            // Perform registrations that should have a request lifetime
        }

        protected override void RequestStartup(ILifetimeScope container, IPipelines pipelines, NancyContext context)
        {
            // No registrations should be performed in here, however you may
            // resolve things that are needed during request startup.
        }
    }
}
```

![files](https://cloud.githubusercontent.com/assets/1297759/20341459/5beb567c-abf7-11e6-8a99-ad3a9ff72a20.PNG)

Message:

```
Located multiple bootstrappers:
 - BootstrapperBug.Bootstrapper
 - Nancy.DefaultNancyBootstrapper

Either remove unused bootstrapper types or specify which type to use.
```

Stacktrace:
```
   at Nancy.Bootstrapper.NancyBootstrapperLocator.GetBootstrapperType()
   at Nancy.Bootstrapper.NancyBootstrapperLocator.LocateBootstrapper()
   at Nancy.Bootstrapper.NancyBootstrapperLocator.get_Bootstrapper()
   at Nancy.Owin.NancyOptions.get_Bootstrapper()
   at Nancy.Owin.NancyMiddleware.UseNancy(NancyOptions options)
   at Nancy.Owin.DelegateExtensions.UseNancy(Action`1 builder, NancyOptions options)
   at BootstrapperBug.Startup.<>c.<Configure>b__1_0(Action`1 x) in C:\Users\CMENGU\Desktop\BootstrapperBug\src\BootstrapperBug\Startup.cs:line 32
   at Microsoft.AspNetCore.Builder.OwinExtensions.UseOwin(IApplicationBuilder builder, Action`1 pipeline)
   at BootstrapperBug.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\Users\CMENGU\Desktop\BootstrapperBug\src\BootstrapperBug\Startup.cs:line 32
```

### Details
- Nancy version: 2.0.0-barneyrubble
- Nancy host
  - [ ] ASP.NET
  - [x] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
"Nancy": "2.0.0-barneyrubble",
"Nancy.Bootstrappers.Autofac": "2.0.0-Pre472",
"Microsoft.AspNetCore.Owin": "1.1.0-preview1-final"
- Environment (Operating system, version and so on): Windows
- .NET Framework version: netstandard1.6 / net452

**Comment by cemremengu** [comment]
@jchannon @damianh

**Comment by khellang** [comment]
I'm not sure what the question is here? This is expected behavior, no? You have several potential bootstrappers in your domain; `DefaultNancyBootstrapper`, `AutofacNancyBootstrapper` and `Bootstrapper`. All of them can work perfectly fine by itself, which one should Nancy pick?

**Comment by khellang** [comment]
Also, I think the exception message should make it pretty clear as well:

> BootstrapperException: Located multiple bootstrappers:
> <list of bootstrappers>
> Either remove unused bootstrapper types or specify which type to use.

**Comment by thecodejunkie** [comment]
@cemremengu like I said on slack, if you have multiple derived bootstrappers (in this case the Autofac one and your own Bootstrapper) then this is the expected behaviour because Nancy is unable to guess which one you want to use

When this happens you either have to remove all other or explicitly tell Nancy which one you want to use

**Comment by cemremengu** [comment]
But it's confusing imo because it acts like `I` implemented the `DefaultBootstrapper` creating confusion especially with new comers. So you have to know the internals of nancy (leaky abstraction ?) to understand this error and go find out how to explicitly tell which one you want to use.

**Comment by cemremengu** [comment]
And on the other hand this is not really an issue but rather a discussion/suggestion so maybe we should do it on the slack

**Comment by thecodejunkie** [comment]
Hmm THAT does sound like a bug though

**Comment by thecodejunkie** [comment]
No, if you inherit from the Autofac one then it should not throw.

**Comment by thecodejunkie** [comment]
Your steps to reproduce should be updated to mention that the bootstrapper is derived from the Autofac one and not the default. That changes it considerably

**Comment by cemremengu** [comment]
@thecodejunkie added more details, hopefully I will learn to communicate soon :)

**Comment by khellang** [comment]
Yeah, there's an algorithm to pick the "most derived" bootstrapper implementation. That should not take the default bootstrapper into account. If that's the case, then it might be a bug. The whole exception text should be included, so it's easier to see which candidates it considered.

**Comment by khellang** [comment]
There are different code paths depending on the assembly used. Is this using the `netstandard1.6` version or the `net452` version?

**Comment by cemremengu** [comment]
@khellang Happens in both

Here is the code: https://we.tl/KGZaaAfdKE

**Comment by cemremengu** [comment]
Added stacktrace to the description

**Comment by thecodejunkie** [comment]
Please try and provide as much info in here as possible. At one point that link will end up dead and we've lost a lot of context down the road if we ever have to revisit

**Comment by grumpydev** [comment]
You sound like an SO mod ;)

**Comment by cemremengu** [comment]
_closed as not constructive_

**Comment by thecodejunkie** [comment]
@grumpydev that's the meanest thing you've ever said to me! :smile:
