### ISSUE TITLE
Nancy.Authentication.Forms NullReferenceException EncryptAndSignCookie

### ISSUE THREAD

**Issue by George02** [NancyFx/Nancy#2631]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
`{"StatusCode":500,"Message":"Something went horribly, horribly wrong while servicing your request.","Details":"Nancy.RequestExecutionException: Oh noes! ---> System.NullReferenceException: Object reference not set to an instance of an object\n at Nancy.Authentication.Forms.FormsAuthentication.EncryptAndSignCookie (System.String cookieValue, Nancy.Authentication.Forms.FormsAuthenticationConfiguration configuration) [0x00000] in <91c66dca293e4531909364de82529d4c>:0 
at Nancy.Authentication.Forms.FormsAuthentication.BuildCookie (System.Guid userIdentifier, System.Nullable`1[T] cookieExpiry, Nancy.Authentication.Forms.FormsAuthenticationConfiguration configuration) [0x0000d] in <91c66dca293e4531909364de82529d4c>:0 
at Nancy.Authentication.Forms.FormsAuthentication.UserLoggedInRedirectResponse (Nancy.NancyContext context, System.Guid userIdentifier, System.Nullable`1[T] cookieExpiry, System.String fallbackRedirectUrl) [0x001ea] in <91c66dca293e4531909364de82529d4c>:0
at Nancy.Authentication.Forms.ModuleExtensions.LoginAndRedirect (Nancy.INancyModule module, System.Guid userIdentifier, System.Nullable`1[T] cookieExpiry, System.String fallbackRedirectUrl) [0x00006] in <91c66dca293e4531909364de82529d4c>:0 at LoginModule.<LoginModule>m__2 (System.Object x) [0x00461] in /home/xx/xx/xx/xx/Modules/LoginModule.cs:95 
at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)\n at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 \n --- End of inner exception stack trace --- 
at Nancy.NancyEngine.InvokeOnErrorHook (Nancy.NancyContext context, Nancy.ErrorPipeline pipeline, System.Exception ex) [0x000bd] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 "}`

### Steps to Reproduce
```
public class AuthManager : IUserMapper {
public Nancy.Security.IUserIdentity GetUserFromIdentifier (Guid identifier, Nancy.NancyContext context) {
			return ds.GetUser (identifier); //get user from database returns DbUser that implements IUserIdentity
}
}

In LoginModule:

return this.LoginAndRedirect(user.Guid, expiry, redirectURL);

Error trown
```

- Nancy version:
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [x] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions: 
```
  <package id="Common.Logging" version="3.3.1" targetFramework="net45" />
  <package id="Common.Logging.Core" version="3.3.1" targetFramework="net45" />
  <package id="Common.Logging.NLog41" version="3.3.1" targetFramework="net45" />
  <package id="EntityFramework" version="6.1.3" targetFramework="net45" />
  <package id="iTextSharp-LGPL" version="4.1.6" targetFramework="net45" />
  <package id="Microsoft.Owin" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Diagnostics" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.FileSystems" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Host.HttpListener" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Hosting" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.SelfHost" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.StaticFiles" version="3.0.1" targetFramework="net45" />
  <package id="Nancy" version="1.4.3" targetFramework="net45" />
  <package id="Nancy.Authentication.Forms" version="1.4.1" targetFramework="net45" />
  <package id="Nancy.Owin" version="1.4.1" targetFramework="net45" />
  <package id="Nancy.Serialization.JsonNet" version="1.4.1" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net45" />
  <package id="NLog" version="4.3.11" targetFramework="net45" />
  <package id="NLog.Config" version="4.3.11" targetFramework="net45" />
  <package id="NLog.Schema" version="4.3.11" targetFramework="net45" />
  <package id="Owin" version="1.0" targetFramework="net40" />
  <package id="Spring.Core" version="2.0.1" targetFramework="net45" />
```

- Environment (Operating system, version and so on): Linux Mint 17, mono 4.6.2
- .NET Framework version: 4.5 Mono

**Comment by khellang** [comment]
Can you show how and where you enable the forms auth? Also what the configuration is?

**Comment by George02** [comment]
`
public class NancyBootstrapper: DefaultNancyBootstrapper {
		protected override void ApplicationStartup (TinyIoCContainer container, IPipelines pipelines) {

			//DiagnosticsHook.Disable(pipelines);

			StaticConfiguration.Caching.EnableRuntimeViewDiscovery = true;
			StaticConfiguration.Caching.EnableRuntimeViewUpdates = true;


			var formsAuthConfiguration =
				new FormsAuthenticationConfiguration () {
					RedirectUrl = "~/login",
				UserMapper = container.Resolve<AuthManager> (),
				};

			FormsAuthentication.Enable (pipelines, formsAuthConfiguration);
		}
}
`

**Comment by George02** [comment]
The problem was that my **NancyBootstraper.cs** was set as **EmbededResource** in my application and not **Compile**. I think that we should catch this issue an throw a specific exception and not a NullReferenceException one.
