### ISSUE TITLE
Nancy 2.0.0-barneyrubble JSON retain casing

### ISSUE THREAD

**Issue by zulq** [NancyFx/Nancy#2633]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of Nancy
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Am trying to get Nancy to retain property names as they are. For example `FirstName` to remain so instead of `firstName` in Response.AsJson. I have seen where it is mentioned to set `JsonSettings.RetainCasing = true`. I couldn't find it in `Nancy.Json` or an example where to set this configuration. Any hint where to find this setting and where to place it?

### System Configuration

- Nancy version: 2.0.0-barneyrubble
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by jchannon** [comment]
In a Bootstrapper there is a Configure method you can override

In that you can do `env.Json(..)` and there are arguments that will handle this and configure JSON.

Its an extension method so if not using R# you'll need to to bring in a using statement of `Nancy.Json`

**Comment by zulq** [comment]
Thanks works.

**Comment by zwcloud** [comment]
code example

```
using Nancy;
using Nancy.Configuration;
using Nancy.Conventions;
using Nancy.Json;

namespace MyApp.Config
{
    public class Bootstrapper : DefaultNancyBootstrapper
    {
        public override void Configure(INancyEnvironment environment)
        {
            base.Configure(environment);
            environment.Json(retainCasing: true);
        }
    }
}

```
