### ISSUE TITLE
NegotiationContext.DefaultModel is not null when action returns null model

### ISSUE THREAD

**Issue by tpluscode** [NancyFx/Nancy#2635]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In Nancy 1.x when the model returned from an action is null, so is `NancyContext#NegotiationContext.DefaultModel`. I took advantage of that fact to return `404` for null models.

In Nancy 2.0 in such a scenario the `DefaultModel` is a `Response` object. Debugger displays `OK text/html` nad the response is actually empty.

### Steps to Reproduce

1. Return null from an action
1. Inspect `NancyContext#NegotiationContext.DefaultModel` in an `After` pipeline hook.

[Here's a gist with minimal reproduction](https://gist.github.com/tpluscode/b94ddd859c3e929efa5a8a727cae2d6e).

### System Configuration

- Nancy version: 2.0-barneyrubble
- Nancy host
  - [ ] ASP.NET
  - [x] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- .NET Framework version: 4.5.2

**Comment by thecodejunkie** [comment]
There must be something in your code that is setting `NegotiationContext.DefaultModel`. I had a look at our code and it's only being used 3 times, directly, in our code and only 2 of those places are set operations

![image](https://cloud.githubusercontent.com/assets/50543/21450200/dc4b9cae-c8f4-11e6-84f4-18766613a251.png)

I also took you minimal reproduction and ran it on `2.0.0-clinteastwood` 

![image](https://cloud.githubusercontent.com/assets/50543/21450166/a7020470-c8f4-11e6-81ae-e207b97d0675.png)

As you can see it is `null`. As far as I know we have not made any changes to that code in quite some time

**Comment by tpluscode** [comment]
Thank's for checking this out. 

For the record, I double checked with barneyrubble and the [gist](https://gist.github.com/tpluscode/b94ddd859c3e929efa5a8a727cae2d6e) fails there. I then ran against *clinteastwood* and it works fine. 

¯\_(ツ)_/¯

**Comment by thecodejunkie** [comment]
😄

**Comment by tpluscode** [comment]
You know what, I've just been thinking about this, and maybe a PR with test is in order to ensure there is no regression. After all there was something wrong with Barney Rubble.

**Comment by thecodejunkie** [comment]
@tpluscode sure we'd be happy to take such a PR
