### ISSUE TITLE
Method 'RenderView' in type 'Nancy.ViewEngines.Razor.RazorViewEngine' from assembly 'Nancy.ViewEngines.Razor, does not have an implementation.

### ISSUE THREAD

**Issue by ChangePlaces** [NancyFx/Nancy#2638]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am using Nancy self-host with the Razor view engine in a basic service using TopShelf. I can start the host fine outside of a service from a console application.  When in a service, initialising the host causes the following error: "Method 'RenderView' in type 'Nancy.ViewEngines.Razor.RazorViewEngine' from assembly 'Nancy.ViewEngines.Razor, Version=1.4.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation."

### Steps to Reproduce
This is inside my Main method using Topshelf to create the service.

            HostFactory.Run(x =>
            {
                x.Service<MyWikiService>(s =>
                {
                    s.ConstructUsing(_ => new MyWikiService());
                    s.WhenStarted(mw => mw.OnStart());
                    s.WhenStopped(mw => mw.OnStop());
                    s.WithNancyEndpoint(x, c =>
                     {
                         c.AddHost(port: 999);
                         c.CreateUrlReservationsOnInstall();
                         c.DeleteReservationsOnUnInstall();
                     });
                });

                x.RunAsLocalService();
                x.SetDescription("My Wiki Service");
                x.SetDisplayName("My Wiki Service");
                x.SetServiceName("MyWikiService");
            });

### System Configuration

- Nancy version: 1.4.3
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [x] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions: Nancy topshelf helper
- Environment (Operating system, version and so on):
- Windows 8.1 
- .NET Framework version: 4.5.2
- Additional information:

**Comment by thecodejunkie** [comment]
Sorry, we cannot provide help with a TopShelf hosted scenario as it is not something we are well adverse in. As you said, it works fine outside of TopShelf.. leading me to thing that some assembly does not get properly loaded or the wrong version is loaded into the topshelf context.
