### ISSUE TITLE
HTTP Basic auth doesn't work with XSP

### ISSUE THREAD

**Issue by 0xFireball** [NancyFx/Nancy#2641]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

`this.RequiresAuthentication()` redirects to: `http://127.0.0.1:8080/login.aspx?ReturnUrl=%2f`instead
of using HTTP basic auth, like it does on IIS Express on Windows. This issue only happens on XSP.

### Steps to Reproduce

Even the `Nancy.Demo.Authentication.Basic` sample has this issue on XSP.

### System Configuration

Ubuntu 16.04, XSP web server using Nancy.Hosting.Aspnet
Everything else is working fine.
It works 100% OK on IIS on windows.

- Nancy version: `2.0.0-barneyrubble`
- Nancy host: ASP.NET (XSP is the actual server that causes an issue)
- Other Nancy packages and versions: `Nancy.Authentication.Basic`
- Environment (Operating system, version and so on): Ubuntu 16.04
- .NET Framework version: .NET 4.6
- Additional information:

**Comment by grumpydev** [comment]
There is no redirect code in the basic auth module for nancy, I'd suggest this is a configuration issue with your XSP setup and its taking the unauthorised response and assuming it needs to redirect you to its own forms auth.

**Comment by 0xFireball** [comment]
Any idea how I could fix this specifically? The app in question is very simple/
