### ISSUE TITLE
Secure Flag on CSRF Token

### ISSUE THREAD

**Issue by TheAngryByrd** [NancyFx/Nancy#2649]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I noticed that the CSRF Cookie was not setting the "secure" flag.  https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Security/Csrf.cs#L41 

Would it be better to deal with it like the asp.net cookie auth does?  They allow for an enum of http, https, or SameAsRequest. 

- Nancy version:
- Nancy host
  - [ ] ASP.NET
  - [x] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions: 
- Environment (Operating system, version and so on): Any
- .NET Framework version: 4.6.1
- Additional information:

**Comment by thecodejunkie** [comment]
@grumpydev thoughts on this?
