### ISSUE TITLE
Accessing Request object in async route

### ISSUE THREAD

**Issue by firesharkstudios** [NancyFx/Nancy#2651]
I have this simple route defined in a class that extends NancyModule...

```
this.Get["/test/{id}", true] = async(parameters, ct) => {
	Console.Log("id=" + parameters.id + ",authorization=" + this.Request.Headers.Authorization);
}
```
I have two clients that connect/reconnect and sometimes the id value and authorization values are mixed up between the two clients which is obviously bad.  I'm guessing I shouldn't be using "this.Request" as this was likely designed for the non-async routes.

What is the proper way to access the Request instance on an async route?

**Comment by firesharkstudios** [comment]
I guess I don't understand how Nancy FX works under the hood.  I think it might work like this...

1) There is a single instance of my module

2) The base NancyModule has a Context property

3) When a new HTTP request is received and it matches a route, the Context property on the single instance of my module is set and then my route handler is invoked and I can reference this Context simply using "this.Context"

What I don't understand is how multiple threads are handled and what keeps each thread from overwriting the shared Context property on the single module instance.  In my async example above, it almost seems like this.Request has been overwritten by another thread (I believe the Request properly is simply calling this.Context.Request).

**Comment by firesharkstudios** [comment]
Well, modifying my original example to use this code fixes my issue...

```
Before += ctx => {
	ctx.Parameters.authorization = this.Request.Headers.Authorization;
	return null;
};

this.Get["/test/{id}", true] = async(parameters, ct) => {
	Console.Log("id=" + parameters.id + ",authorization=" + parameters.authorization);
}
```
Doesn't seem ideal to have to use a Before hook to pass all your data in the parameters dynamic dictionary.  I'm probably missing something.  If I'm not, seems like it would have been better to just pass the Context itself into each route handler.

**Comment by khellang** [comment]
It looks like you pretty much ditched the issue template we are asking people to fill out. Without that information, there's really not much we can do to help you, as this could be tied to which host you're using, which versions you're running etc.

Nancy instantiates a module per request, so it should be perfectly fine to use `this.Request` regardless.

**Comment by khellang** [comment]
BTW, using the before-hook and pulling the header directly should have the exact same behavior. You're still accessing the same request object.

**Comment by firesharkstudios** [comment]
I'm using the self hosting version and Nancy 1.4.3.

For testing, I have two clients that make requests repeatedly -- one that opens /test/1 sending a "Authorization: Token 1" header and another client that opens /test/2 sending a "Authorization: Token 2" header.  There are times with the following code...

```
this.Get["/test/{id}", true] = async(parameters, ct) => {
	Console.Log("id=" + parameters.id + ",authorization=" + this.Request.Headers.Authorization);
}
```
where the console will print a mismatch like "id=1, authorization=Token 2".  However, after modifying the code to be this...

```
Before += ctx => {
	ctx.Parameters.authorization = this.Request.Headers.Authorization;
	return null;
};

this.Get["/test/{id}", true] = async(parameters, ct) => {
	Console.Log("id=" + parameters.id + ",authorization=" + parameters.authorization);
}
```
a mismatched console output never occurs.  

Is it possible that in the prior code example that the this.Request value is being overwritten by a different thread while the lambda is being executed?

**Comment by khellang** [comment]
> Is it possible that in the prior code example that the this.Request value is being overwritten by a different thread while the lambda is being executed?

That _should not_ be possible. The lambda should not be able to close over a shared reference because the request and module objects are created per request. If this is the case, it's most certainly a bug :disappointed:

**Comment by phillip-haydon** [comment]
Are you able to identify if it's the header value or the route value that is incorrect.

i.e if you send:

/test/1 | "Authorization: Token 1"
/test/2 | "Authorization: Token 2"

When you get the result:

"id=1, authorization=Token 2"

Was it the id or the token that was correct?

(trying to narrow down if it's the header's that's incorrect or the request params)

**Comment by firesharkstudios** [comment]
> That should not be possible. The lambda should not be able to close over a shared reference because the request and module objects are created per request. If this is the case, it's most certainly a bug 

I've put a static counter field in my module constructor -- it is only being called once and reused across multiple requests.  I've probably butchered how the module gets created in the custom bootstrapper perhaps.  Here is the custom bootstrapper...

```
    public class CustomNancyBootstrapper : DefaultNancyBootstrapper {

        protected override void ConfigureApplicationContainer(TinyIoCContainer container) {
            container.Register<INancyModuleCatalog>(new CustomModuleCatalog());
        }

        protected override void RequestStartup(TinyIoCContainer container, IPipelines pipelines, NancyContext context) {
            pipelines.OnError.AddItemToEndOfPipeline((ctx, ex) => {
                logger.Error(ex);
                return new TextResponse(HttpStatusCode.InternalServerError, ex.Message);
            });
        }

        public class CustomModuleCatalog : INancyModuleCatalog {

            protected readonly Database database;
            protected readonly List<INancyModule> modules = new List<INancyModule>();

            public CustomModuleCatalog() {
                this.database = new MyDatabase();
                modules.Add(new QuerySetApiModule(this.database);
            }

            public IEnumerable<INancyModule> GetAllModules(NancyContext context) {
                return this.modules;
            }

            public INancyModule GetModule(Type moduleType, NancyContext context) {
                return this.modules.Find(findModule => findModule.GetType() == moduleType);
            }
        }

    }
```
Have I done something that breaks a new module instance per request?

**Comment by khellang** [comment]
Heh. Yeah, you've created a single module that's used for the entire lifetime of the application. That's kinda important to mention :stuck_out_tongue:

It's not really designed for that. If you want to reuse an existing instance, the least you should do is set the context on the module you're returning, but I'm not sure if that would work either :confused:

**Comment by firesharkstudios** [comment]
Well, I wasn't trying to create a single module that is used for all requests -- I was just trying to pass in a database instance into my module and modified some sample code for a custom bootstrapper to do this.  I'll figure out how to do this properly -- thanks for the help.
