### ISSUE TITLE
How can I set a new response if Next.Invoke(context) fail ?

### ISSUE THREAD

**Issue by George02** [NancyFx/Nancy#2657]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I have a custom middleware that log the request and the response to the console.
How can I set a new response if Next.Invoke(context) fail ? 

```
public class LoggerMiddleware: OwinMiddleware {

		private Logger logger = LogManager.GetCurrentClassLogger();

		public LoggerMiddleware (OwinMiddleware next) : base (next) {

		}

		public async override Task Invoke (IOwinContext context) {
			var env = context.Environment;

			logger.Info("Begin Request");
			logger.Info("--------------------------------");
			logger.Info (String.Format("Request from {0} port {1}", (string)env ["server.RemoteIpAddress"], (string)env ["server.RemotePort"]));
			try {
				await Next.Invoke (context);
			} catch (Exception ex) {
                                logger.Info (ex, ex.Message);
				logger.Error (ex, "Error while invoking next route");

                               **//SHOULD RETURN A RESPONSE**
			}

			logger.Info("--------------------------------");
			logger.Info("End Request");

			var responseBody = (Stream)env ["owin.ResponseBody"];
			var responseHeaders = (IDictionary<string, string[]>)env ["owin.ResponseHeaders"];

			logger.Info(String.Format("Response: {0}", GetText (responseBody)));
			logger.Info (responseBody);
		}
	}
```

### System Configuration

- Nancy version:
- Nancy host
  - [ ] ASP.NET
  - [x] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by thecodejunkie** [comment]
@damianh @khellang @jchannon 😄

**Comment by khellang** [comment]
Hmm. As far as I can see, Nancy isn't involved here at all?
