### ISSUE TITLE
Authentication.Stateless: Documentation mismatch between instructions and code

### ISSUE THREAD

**Issue by jeblackburn** [NancyFx/Nancy#2660]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of Nancy
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The docs for Nancy.Authentication.Stateless has outdated instructions referencing IUserIdentity, while the second example on the page (the one using jose-jwt) has an updated example correctly returning a ClaimsPrincipal.

### Steps to Reproduce
The docs are here: https://github.com/NancyFx/Nancy/wiki/Stateless-Authentication

### System Configuration
N/A

**Comment by jchannon** [comment]
The wiki is editable by anyone if you're up for the challenge?!

**Comment by jeblackburn** [comment]
Sure, I'll take a crack at it. I didn't know it was open to edits from the peanut gallery.

**Comment by thecodejunkie** [comment]
👍

**Comment by oxxford** [comment]
The problem still exists: in Visual Studio nuget packet still requires IUserIdentity.
