### ISSUE TITLE
I can't get Forms Authentication + RequiresClaims to work.

### ISSUE THREAD

**Issue by jeblackburn** [NancyFx/Nancy#2668]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of Nancy
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I have modified the Sample project Nancy.Demo.Authentication.Forms to check for a claim on the authenticated user. The claim doesn't appear to be checked at all. For my changes please check the latest on my fork of Nancy at https://github.com/jeblackburn/Nancy.

As a first step I modified UserDatabase.cs, where I replaced the construction of a ClaimsPrincipal using a GenericIdentity with a ClaimsIdentity using a list of Claims. That ClaimsPrincipal doesn't appear to work.

My replacement Identity should have the same behavior as the GenericIdentity I replaced. It contains the single Claim presented by the GenericIdentity, plus one other.

### Steps to Reproduce
Clone https://github.com/jeblackburn/Nancy and run the Nancy.Demo.Authentication.Forms project. Try to navigate to the "Secure Zone". Log in as admin/password. You'll be redirected to the login form. Back out my change to UserDatabase.cs and it will work.

### System Configuration

- Nancy version: My fork of Nancy is "101 commits behind master". I couldn't figure out how to get a more recent copy of the source.
- Nancy host:
  - [ ] ASP.NET
  - [ ] OWIN
  - [X] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on): Windows 7
- .NET Framework version: 4.5
- Additional information:

**Comment by jeblackburn** [comment]
I found the problem, after three days of foundering.

A ClaimsIdentity is not "authenticated" unless it is constructed with a non-null AuthenticationType constructor parameter, A GenericIdentity has no such constraint. Which is fine, I guess, but not at all clear. And it's opaque to me where I could have checked in the Nancy code to see it as the cause of my troubles.

Sorry for the spam. I'll go ahead and close this with a plea to consider ways to make Microsoft's mess a little clearer.

**Comment by thecodejunkie** [comment]
Not really anywhere in Nancy you should have checked to see that. Nancy uses `IIdentity.IsAuthenticated` to check if the user is considered authenticated or not. It is up to each implementation to set the criterion for what is required to be considered authenticated. The MSDN page, for ClaimsIdentity, is not very clear on the importance of `AuthenticationType` when it comes to actually consider someone to be authenticated or not. However, if we look at the [source code of ClaimsIdentity](https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/security/claims/ClaimsIdentity.cs) then we see that it is very important - in fact it is the _only_ property that is checked in the [IsAuthenticted](https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/security/claims/ClaimsIdentity.cs#L461) property of said implementation.

**Comment by jeblackburn** [comment]
That's how I ultimately tracked it down. My fork of the codebase has
modified the Forms Authentication example with a Claims-based authorization
guard. I'd be happy to send a push request if you think it might be useful.

**Comment by thecodejunkie** [comment]
@jeblackburn send a PR and we'll have a look 🙉
