### ISSUE TITLE
Unable to resolve type: Nancy.Validation.FluentValidation.FluentValidationRegistrations

### ISSUE THREAD

**Issue by sebwaks** [NancyFx/Nancy#2669]
### Prerequisites

- [ x] I have written a descriptive issue title
- [ x] I have verified that I am running the latest version of Nancy
- [ x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

FileLoadException: Could not load file or assembly 'FluentValidation, Version=3.4.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]
   Nancy.Validation.FluentValidation.FluentValidationRegistrations..ctor() +0
   lambda_method(Closure , Object[] ) +42
   Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) +697

[TinyIoCResolutionException: Unable to resolve type: Nancy.Validation.FluentValidation.FluentValidationRegistrations]
   Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) +732
   Nancy.TinyIoc.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options) +124
   Nancy.TinyIoc.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) +86
   Nancy.TinyIoc.TinyIoCContainer.<ResolveAllInternal>b__43(TypeRegistration registration) +32
   System.Linq.WhereSelectEnumerableIterator`2.MoveNext() +164
   System.Linq.<CastIterator>d__94`1.MoveNext() +163
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +460
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +58
   Nancy.Bootstrapper.NancyBootstrapperWithRequestContainerBase`1.RegisterRegistrationTasks(IEnumerable`1 registrationTasks) +52
   Nancy.Bootstrapper.NancyBootstrapperBase`1.Initialise() +414
   Nancy.Owin.NancyMiddleware.UseNancy(NancyOptions options) +84
### Steps to Reproduce

Added one simple validation class 

  public class SMSRequestValidator : AbstractValidator<SmsRequest>
    {
        public SMSRequestValidator()
        {
            RuleFor(request => request.Body).NotEmpty().WithMessage("You must specify a Body.");

        }

    }

### System Configuration

- Nancy version: 1.4.1 
- Nancy host
  - [ ] ASP.NET
  - [ x ] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by jchannon** [comment]
I don't think thats going to work.

a) AbstractValidator is generic it needs a type AbstractValidator<Person>
b) You can't check the request body like that as its a stream and not sure
request is even availble in a validator. Does that even compile?

**Comment by sebwaks** [comment]
Sorted , something strange , reinstalled all Nugets and works
