### ISSUE TITLE
why remove the .json extension in requestdispather

### ISSUE THREAD

**Issue by zhaxg** [NancyFx/Nancy#2671]
url like 'http://localhost/upload/index.json'

the nancy module is like this : Get["/upload/{name*}"]  

and i receive the url http://localhost/upload/index

why remove the json extension in  DefaultRequestDispatcher line 176??

thank you !

**Comment by khellang** [comment]
> and i receive the url http://localhost/upload/index

What does this mean? Where are you seeing this URL?

> why remove the json extension in DefaultRequestDispatcher line 176??

Nancy allows you to short-circuit the content negotiation by adding an extension to a resource, like `.json` or `.xml`. This will force it to pick a specific format, without looking at `Accept` headers etc.

I'm not really sure why it modifies the request path to do this, and I think this should be configurable. @thecodejunkie @grumpydev, do you remember?

**Comment by thecodejunkie** [comment]
It's the way it was designed and for 2.x I've raised that content negotiation should move to the co for API and let the user control it

**Comment by zhaxg** [comment]
不觉明历，不过还是谢谢你们的回复。

**Comment by thecodejunkie** [comment]
That Google translates to

> Do not feel Ming calendar, but still thank you for your reply.

**Comment by zhaxg** [comment]
不觉明历：Although do not know how, but that is still very powerful look

**Comment by DavidBoike** [comment]
Don't understand quite why this issue was closed, there's no real resolution here.

That would be useful if you were implementing an API and you wanted it to be able to respond in both XML or JSON formats.

You can "fix" it using this bootstrapper code:

```
    public class Bootstrapper : DefaultNancyBootstrapper
    {
        protected override NancyInternalConfiguration InternalConfiguration
        {
            get
            {
                return NancyInternalConfiguration.WithOverrides(x =>
                {
                    // Otherwise '.xml' and '.json' will get stripped off request paths
                    x.ResponseProcessors = new List<Type>
                    {
                        typeof(ResponseProcessor),
                        typeof(ViewProcessor)
                    };
                });
            }
        }
    }
```

This removes the default of having a `JsonProcessor` and `XmlProcessor` in there too - that's the culprit that's removing `.json` and `.xml` from the request path before it even gets to a module.

**Comment by thecodejunkie** [comment]
@DavidBoike this issue was closed because "it works as intended", as per https://github.com/NancyFx/Nancy/issues/2671#issuecomment-269759782

Could/should we change it? Quite possibly, but that's no in the scope of this issue though

Hope that clarifies things

thanks!

/A
