### ISSUE TITLE
HttpMultipart GetBoundaries does not support double-quoted boundaries for multipart/form-data

### ISSUE THREAD

**Issue by starnutoditopo** [NancyFx/Nancy#2681]
### Description
I have a situation in which a multipart/form-data contentType specifies boundaries with double-quotes.
This is supported by the standard, according to: 
https://tools.ietf.org/html/rfc2046#section-5.1.1

In my case, the Content-type is:
multipart/form-data; boundary="e0c3fff8-5eef-4358-9338-251f3abff76f"
in c#: "multipart/form-data; boundary=\"e0c3fff8-5eef-4358-9338-251f3abff76f\""

I then create a

```c#
var multipart = new HttpMultipart(this.Request.Body, boundaryString);
```

using the double-quoted boundaryString: "\"e0c3fff8-5eef-4358-9338-251f3abff76f\""
In such a situation, calling multipart.GetBoundaries() yields no results.

Unquoting the `boundaryString  multipart.GetBoundaries()` has no luck.
The only way to make it work is to workaround the problem by making a some bricolage on the client so that it sends an unquoted boundary in the contentType

Here's a simple c# client that simulates the upload of a file; this reproduces the error

```c#
 private static async Task<string> Upload(byte[] image, MediaTypeHeaderValue mediaTypeHeaderValue)
        {
            using (var client = new HttpClient())
            {
                using (var content = new MultipartFormDataContent())
                {
                    var imageContent = new ByteArrayContent(image);
                    imageContent.Headers.ContentType = mediaTypeHeaderValue;

                    content.Add(imageContent, "name", "fileName");

                    Uri uri = new Uri(baseServerUri, "Images");
                    using (var message = await client.PostAsync(uri, content))
                    {
                        var input = await message.Content.ReadAsStringAsync();
                        return input;
                    }
                }
            }
        }
```

**Comment by thecodejunkie** [comment]
I haven't run your code yet but the boundary should be able to be wrapped in double quotes. We use the following regex to extract the boundary

> boundary=""?(?<token>[^\n\;\"" ]*)"

Running that on your sample (and a variation of it)

![image](https://cloud.githubusercontent.com/assets/50543/21911481/3ee1a7be-d921-11e6-8057-42fbce31cfca.png)

Yields the following captures

![image](https://cloud.githubusercontent.com/assets/50543/21911491/496290f4-d921-11e6-952c-ab1697722941.png)

As you can see, it successfully captures the boundary as `token` in both samples

You say you create a boundary string as

> ""e0c3fff8-5eef-4358-9338-251f3abff76f""

However that is not what double-quoted means? A double quote is represented by the `"` alone and in your sample you are showing a double-double-quotes string `""` ?

**Comment by thecodejunkie** [comment]
Here is an example of a boundary that's been wrapped in double-double-quotes as well

![image](https://cloud.githubusercontent.com/assets/50543/21911772/90429694-d922-11e6-9421-ecab75046726.png)

**Comment by starnutoditopo** [comment]
Hi!

My sample deals with a boundary starting with a single double-quote
character and ending with a single double-quote character.
So probably the point is that I make some mistake in extracting the
boundary.

Here's a screen-shot from a debug session in Visual Studio, showing the
contentType's value (in the Text visualizer window) and as a C# string (at
the bottom). the boundary is represented by a string starting and ending
with a single double-quote char.

[image: Inline image 1]

So... definitely it seems like the problem is not in Nancy's code, but in
the way I extract the boundary to be passed as second parameter to the
HttpMultipart constructor.

According to my tests, it should be:
case 1) quoted:
   ContentType:
      multipart/form-data; boundary="7ef0e4ab-0ab0-4911-9988-35d37ef6c896"
      -> boundary string should be: 7ef0e4ab-0ab0-4911-9988-35d37ef6c896

case 2) unquoted:
   ContentType:
      multipart/form-data; boundary=7ef0e4ab-0ab0-4911-9988-35d37ef6c896
      -> boundary string should be: 7ef0e4ab-0ab0-4911-9988-35d37ef6c896

So, here an Helper class that detects if a contentType represents a
multipart, in which case, it returns the boundary string:

using System.Text.RegularExpressions;
 namespace Server.Common.Helpers
{
    public static class MultipartHelper
    {
        private static readonly Regex contentTypeWithUnquotedBoundariesRegex;
        private static readonly Regex contentTypeWithQuotedBoundariesRegex;

        static MultipartHelper()
        {
            contentTypeWithUnquotedBoundariesRegex = new
Regex("^multipart/form-data;\\s*boundary=(.*)$",
RegexOptions.IgnoreCase);
            contentTypeWithQuotedBoundariesRegex = new
Regex("^multipart/form-data;\\s*boundary=\"(.*)\"$",
RegexOptions.IgnoreCase);
        }

        public static bool IsMultiPart(string contentType, out string
boundaryString)
        {
            if (contentTypeWithQuotedBoundariesRegex.IsMatch(contentType))
            {
                boundaryString = contentTypeWithQuotedBoundariesRegex
                    .Match(contentType)
                    .Groups[1]
                    .Value;

                return true;
            }
            if (contentTypeWithUnquotedBoundariesRegex.IsMatch(contentType))
            {
                boundaryString =
contentTypeWithUnquotedBoundariesRegex.Match(contentType).Groups[1].Value;
                return true;
            }
            boundaryString = null;
            return false;
        }
    }
}

Then, I extract the boundaries like this:

string boundaryString;if
(MultipartHelper.IsMultiPart(this.Request.Headers.ContentType, out
boundaryString))
{
    var multipart = new HttpMultipart(this.Request.Body, boundaryString);
    var boundaries = multipart.GetBoundaries();

    ...


I wonder if some better way of doing it already exists.

Thanks very much for you support.

   Xc

**Comment by thecodejunkie** [comment]
If you are trying to get the files you send, you can simply use `Request.Files` as Nancy does all of the boundary logic internally for you and you do not have to worry about it unless you have a very specific requirement. 

Let me know if this helps - if not then we'll keep digging

**Comment by starnutoditopo** [comment]
Hallo!

thanks for your reply.
Request.Files works OK for all my test cases.

Thanks very much!

Xc

**Comment by thecodejunkie** [comment]
@starnutoditopo Glad it worked out!
