### ISSUE TITLE
New routing syntax serializes Task objects after inferring wrong GET overload

### ISSUE THREAD

**Issue by bwatts** [NancyFx/Nancy#2693]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of Nancy
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The new routing syntax (awesome, btw) has one scenario I can't shake out. Some route declarations infer an `object` return instead of a `Task<object>` return, causing the whole `Task` to serialize.

### Steps to Reproduce

```csharp
Get("/test/{bar}", args => Foo(args.bar));

...

private Task<object> Foo(int bar)
{

}
```

**Expected:** lambda resolves to `GET` overload taking `Func<dynamic, Task<object>>`

**Actual:** lambda resolves to `GET` overload taking `Func<dynamic, object>`

I should not that this does not happen if there are no arguments. I suspect it has to do with the way `dynamic` affects the lambda expression:

```csharp
Get("/test/{bar}", args => Foo());

...

private Task<object> Foo()
{

}
```

The above resolves as expected to the `GET` overload taking `Func<dynamic, Task<object>>`.

### System Configuration

- Nancy version: 2.0.0-barneyrubble
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [X] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions: None
- Environment (Operating system, version and so on): Windows 7
- .NET Framework version: 4.6.1
- Additional information:

**Comment by jchannon** [comment]
We know there are some issues with the overloaded route options. This may
be one however shouldn't you be using an async and await in your scenario.
I imagine that would fix it? (It may not)

**Comment by bwatts** [comment]
Using `async` and `await` did indeed resolve correctly, thanks. I assume the compiler can only consider overloads with `Task` return types in that case.

We hadn't originally because we returned a `Task` directly from another call, after some logging. It seems safer to be explicit in the `Get` calls.
