### ISSUE TITLE
AsString extension no longer works

### ISSUE THREAD

**Issue by jchannon** [NancyFx/Nancy#2698]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
We recently moved the Request.Body to a Stream away from a RequestStream.  We have an extension that allows you to get a request body as string however its an extension method off of RequestStream. 

### Steps to Reproduce
To get this to work you have to do `((RequestStream)this.Body)>AsString()` which is nasty.

This needs fixing https://github.com/NancyFx/Nancy/blob/be4f8d42076e4e568a3742715437868e6c7d05af/src/Nancy/Extensions/RequestStreamExtensions.cs#L18

I think this test needs ammending https://github.com/NancyFx/Nancy/blob/be4f8d42076e4e568a3742715437868e6c7d05af/test/Nancy.Tests/Unit/Extensions/RequestStreamExtensionsFixture.cs

### System Configuration

- Nancy version: 2.0-clinteastwood
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [ ] Self-Hosted
  - [x] Other: Kestrel
- Other Nancy packages and versions:
- Environment (Operating system, version and so on): OSX but will apply to all
- .NET Framework version:
- Additional information:

**Comment by thecodejunkie** [comment]
So it should be an extension method on `Stream` instead, is that way you are saying?

**Comment by jchannon** [comment]
Yup

**Comment by thecodejunkie** [comment]
Wouldn't it be quicker to send a PR than to write an issue and link stuff? 🤣

**Comment by jchannon** [comment]
Probably but busy and dont want to forget :)

**Comment by JosephWoodward** [comment]
> Wouldn't it be quicker to send a PR than to write an issue and link stuff?

Not to mention it's always nice having PRs like this up for grabs for first timers :)

**Comment by jchannon** [comment]
Make it so...

**Comment by ghuntley** [comment]
> Wouldn't it be quicker to send a PR than to write an issue and link stuff? Yes, it is faster to fix it yourself, but that removes opportunities for newbies to open-source or even seasoned vets (who are looking for suggestions of value) to get involved with the project. Check out @yourfirstpr - https://yourfirstpr.github.io/ for more information.`

**Comment by pawelsawicz** [comment]
I can do that

**Comment by pawelsawicz** [comment]
Apologies there was a typo in PR title, too long on the front of PC :( it has been renamed
