### ISSUE TITLE
Forms Authentication demo has wrong links in it

### ISSUE THREAD

**Issue by dlwiii** [NancyFx/Nancy#2704]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of Nancy
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The code in `src\Nancy.Demo.Authentication.Forms` has the path to http://localhost:[port]/forms by default

But the code itself refers to `<a href="secure">` and `<a href="partlysecure">` rather than
`<a href="forms/secure">` and `<a href="forms/partlysecure">`

### Steps to Reproduce
Download the latest Nancy off the main branch.  Set Nancy.Demo.Authentication.Forms as the starting program and run it

### System Configuration
Visual Studio 2015 Community on x64 Windows 8.1 machine.

- Nancy version: commit  9d4b679
- Nancy host
  - [x] ASP.NET
  - [ ] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version: 4.5
- Additional information: It may be related to IISExpress doing its evil things. I usually  run self hosted, but just took the demo as it was.  Out of the box  the Project URL is: http://localhost:2146/forms
And Visual Studio seems to launch a number of iisexpress.exe's 

But still - does this example work out of the box on anyone else's system?  I mean get the latest, hit F5, and browse to the URL

**Comment by thecodejunkie** [comment]
Hi,

This works just fine. When the links are defined as  `<a href="secure">` and `<a href="partlysecure">` means that they'll be relative to the current URL. Have a look at the gif below, it's running the sample app unmodified from `master` using VS2015

![forms](https://cloud.githubusercontent.com/assets/50543/23727369/0e4caede-0458-11e7-8900-03d5402ca74f.gif)
