### ISSUE TITLE
Nancy v2 release ETA

### ISSUE THREAD

**Issue by zulq** [NancyFx/Nancy#2710]
Am planning to build a web application using Nancy V2 and thus would like to know if there's an ETA. I have been using the V2-pre and so far no issues other than having to look at code etc as the docs are not yet updated. Already implemented authentication and authorization using the new csproj.
However I wouldn't want to deploy to production using a pre-release version.

**Comment by pdwetz** [comment]
There's at least one more preview release planned, you can review its [issues here](https://github.com/NancyFx/Nancy/milestone/45). Based on that I'm pretty confident the full release won't be in the very near future (e.g. in the next couple months).

**Comment by thecodejunkie** [comment]
@zulq nothing decide to be honest. We have a couple of big things we want to do before we put out 2.x RTM

**Comment by zulq** [comment]
@thecodejunkie you mean I should decide or nothing decided on ETA?

**Comment by thecodejunkie** [comment]
@zulq not sure I follow you? We cannot give you an ETA for 2.0 RTM. Given that information you have to decide if you should go with a pre-release of 2.0, use 1.4.3 or simply use something else. That is the very best I can tell you right now 😄
