### ISSUE TITLE
Model binding to a route with a route segment that contains a full stop, strips out the content including-and-after the full stop

### ISSUE THREAD

**Issue by PureKrome** [NancyFx/Nancy#2711]
Given a simple route with a full stop in one of the route segments, the routing engine strips out the full stop and the text after the full stop.

Scenario & Context:
We have a database of files and their meta data. Given a unique file name, we wish to retrieve the file meta data. For whatever reason(s), we only have the filename (at this point) and not the database identifier. This call is used to retrieve all the db row data - including that identifier.

Route: `GET /file/{filename}`
Sample route: `GET /file/test.json`

eg. 

```
Get["/file/{fileName}", true] = async (_, __) => await TryAsync(GetFileAsync);
```

When we debug the `this.Request` instance, the value of `this.Request.Path == "file/test"`

Expectations:

We're expecting the route segment to remain untouched. As such, `this.Request.Path == "file/test.json"` and then we can use model binding and this value will be `model.FileName == "test.json"`

Finally -> we have only tested this in our unit tests. We haven't pushed this code up to any live server and seen if this is the still the same case. (Unit tests are failing, so no deployment).

- Nancy version:
```
  <package id="Nancy" version="1.4.3" targetFramework="net461" />
  <package id="Nancy.MSOwinSecurity" version="2.0.0" targetFramework="net461" />
  <package id="Nancy.Owin" version="1.4.1" targetFramework="net461" />
  <package id="Nancy.Serialization.JsonNet" version="1.4.1" targetFramework="net461" />

```
- .NET Framework v 4.6.1

Thank you kindly.

CC: @phillip-haydon @jchannon

**Comment by xt0rted** [comment]
Sounds like content negotiation to me https://github.com/NancyFx/Nancy/wiki/Content-Negotiation#file-extension-support

**Comment by PureKrome** [comment]
So - can u turn Conneg off then?

**Comment by xt0rted** [comment]
According to #2671 and #2659, not currently 😕

**Comment by xt0rted** [comment]
Since it's stripping it from the end of the url, and only for `xml` & `json`, you should be able to hack around it by adding another segment. Something like `/file/{filename}/details` should work. It's not very SDHP but it should help get around the issue for now.

**Comment by PureKrome** [comment]
oooh.. 

/me alt-tabs...

haha yep! confirmed! not the _best_ answer but _an_ answer :)

thanks so much @xt0rted - you're a legend!!
