### ISSUE TITLE
DependencyContextAssemblyCatalog's methods to virtual

### ISSUE THREAD

**Issue by gilbertogwa** [NancyFx/Nancy#2722]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Could change DependencyContextAssemblyCatalog's methods to virtual? This will allow merge with default implementation. 

- Nancy version: "2.0.0-barneyrubble"
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Environment (Operating system, version and so on):
- .NET Framework version: Core 1.1.0

**Comment by thecodejunkie** [comment]
@gilbertogwa Could you please clarify what methods that you'd like to see `virtual`? Just making the `GetAssemblies()` method virtual wouldn't add much value. Exactly what step do you want to be able to reuse by inheriting from `DependencyContextAssemblyCatalog`  and what would you be customizing?

**Comment by gilbertogwa** [comment]
@thecodejunkie At the time, I needed this functionality to make my Nancy modules dynamic. The DependencyContextAssemblyCatalog class loads only the types in referenced assemblies. It is used in the NancyBootstrap class through the AssemblyCatalog property, which can be overwritten, so I would create a version of DependencyContextAssemblyCatalog that, in addition to returning the referenced assemblies, would also return loaded assemblies at run time.

What I wanted:

`
class DependencyContextAssemblyCatalogEx : DependencyContextAssemblyCatalog
{
     private IEnumerable<Assembly> _asms;

    DependencyContextAssemblyCatalogEx (IEnumerable<Assembly> asms) {

       _asms = asms;


    }
    public override IReadOnlyCollection<Assembly> GetAssemblies()
   {
         return Join(base.GetAssemblies(), this._asms);
   }
}

class MyBootstrap: NancyBootstrap
{

        private DependencyContextAssemblyCatalogEx _myCatalog;

        protected override IAssemblyCatalog AssemblyCatalog {
            get
            {
                return myCatalog;
            }
        }

}`

Anyway, I solved my problem by overriding NancyBootstrap's Modules method. It got a bit more complicated, but it works fine.
