### ISSUE TITLE
How can I using WebSocket with Nancy?

### ISSUE THREAD

**Issue by LazyCuteLion** [NancyFx/Nancy#2723]
How can I using WebSocket with Nancy?

**Comment by sp3tsnaz** [comment]
@LazyCuteLion https://docs.microsoft.com/en-us/aspnet/signalr/overview/deployment/tutorial-signalr-self-host

**Comment by molekilla** [comment]
I recommend using this library, worked well for me
http://sta.github.io/websocket-sharp/
