### ISSUE TITLE
Json serializer don't ignore property

### ISSUE THREAD

**Issue by gilbertowa** [NancyFx/Nancy#2729]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Method Respose.AsJson don't ignore property. I try:

`
Post("/search", _ =>
{
    var filtro = this.Bind<TFiltroPesq>();
    var resp = dominio.Pesquisar(filtro);
    return this.Response.AsJson(resp);
});
`
But property Id is always serialized.
`
[System.Xml.Serialization.XmlIgnore]
[Nancy.Json.ScriptIgnore]
[System.Runtime.Serialization.IgnoreDataMember]
public long? Id { get; set; }
`

### System Configuration

- Nancy version: 2.0.0-cliteastwood

- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on): Windows 8.1
- .NET Framework version: .NET Standard Library 1.6.1
- Additional information:

**Comment by cemremengu** [comment]
Can you try `[JsonIgnore]` ?

**Comment by gilbertowa** [comment]
I try [JsonIgnore] from namespace Newtonsoft.Json and won't works. Has another JsonIgnore? I don't found in Nancy.

**Comment by parmjeetkumar** [comment]
@thecodejunkie  I can work on this issue , can you assign this to me?

**Comment by phillip-haydon** [comment]
@parmjeetkumar You're free to work on it, github doesn't allow us to assign non-members to issues tho :(

**Comment by parmjeetkumar** [comment]
@phillip-haydon Thanks i was worried about that may be some one have to assign this to me to start work on this. Going to make this fix :)

**Comment by m-barthelemy** [comment]
Hi, 

Is there any ETA for getting this fixed?
In the meantime, is there any workaround?

**Comment by gilbertowa** [comment]
@m-barthelemy  How workaround I created a extesions methods

	public static class NancyExtensions
	{
		public static Response JsonResponse<TModel>(this NancyModule module, TModel data)
		{
			var settings = new JsonSerializerSettings()
			{
				ContractResolver = new CamelCasePropertyNamesContractResolver()
			};

			var json = JsonConvert.SerializeObject(data, settings);
			return module.Response.AsText(json, "application/json", Encoding.UTF8);
		}

		public async static Task<TModel> JsonRequestToObjectAsync<TModel>(this NancyModule module)
		{
			var reader = new StreamReader(module.Request.Body);
			var json = await reader.ReadToEndAsync();
			var obj = JsonConvert.DeserializeObject<TModel>(json);

			return obj;
		}

	}

So, I use like this:

            PostSeguro("/salvar", async _ =>
			{
				var entidades = await this.JsonRequestToObjectAsync<TEntidade[]>();
				var resp = dominio.Salvar(entidades);
				return this.JsonResponse(resp);

			});

**Comment by thecodejunkie** [comment]
So, personally I do not see the issue being with Nancy but rather that you are using the same model to bind to as you use to represent an entity. Your data binding model should only expose the members that you actually want to bind, and reusing the same model type for two different things is a bad idea. This is the notion that we support out of the box

Moving on. If you want more control over the serialization process, then you can move away from the default serializer and use something like [Nancy.Serialization.JsonNet](https://github.com/NancyFx/Nancy.Serialization.JsonNet) which uses `Newtonsoft.Json` internally and lets to take advantage of the capabilities that it offers you.

Hope this helps! 😄 

Closing this as this is not really a defect.

**Comment by xt0rted** [comment]
In Nancy v2 the [IgnoreDataMemberAttribute](https://github.com/NancyFx/Nancy/blob/0843e37b84ec1e90a18f7b38cda048370835d007/src/Nancy/Json/Simple/SimpleJson.cs#L1679-L1689) is honored by the (new) default json serializer.

**Comment by mb-software** [comment]
Hello,

I'm using the latest Nancy V2 from Nuget with the default Json serializer.
None of the attributes work for me. Properties get always serialized, also with IgnoreDataMember.

How to exclude certain properties from serialization?
