### ISSUE TITLE
How can I get NancyFx to autoresolve classes defined in different assemblies

### ISSUE THREAD

**Issue by TheCois** [NancyFx/Nancy#2730]
Auto resolution of dependencies does not work for me.
I have an application that uses modules depending on classes defined in different assemblies than that of the modules. When trying to run the application, I get an exception at startup that shows:

```
Unhandled Exception:
System.InvalidOperationException: Something went wrong when trying to satisfy one of the dependencies during composition, make sure that you've registered all new dependencies in the container and inspect the innerexception for more details. ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: Nancy.NancyEngine ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: Nancy.Routing.DefaultRequestDispatcher ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: Nancy.Routing.DefaultRouteResolver ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: Nancy.Routing.RouteCache ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: MessageListener.HomeModule ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: Logging.ILoggerFactory
[...]
```

The code builds fine and all the assemblies are deployed together in the same folder.
The problem seems to be with Auto Resolution across assemblies.
If I bring all the implementation classes in the same assembly as my Nancy modules, then auto resolution works.
If I keep the classes in different assemblies but create a custom bootstrapper that registers my dependencies with the container, then the application launches fine.

### Steps to Reproduce
In assembly Logging (no references except the normal .NET System.dll), I have one file: class1.cs

```c#
namespace Logging
{
    public interface ILoggerFactory
    {
        string Name { get; }
    }
    public class LoggerFactory : ILoggerFactory
    {
        public string Name => "hello";
    }
}
```

In my main Assembly (references System, Logging, Nancy, Nancy.Hosting.Self) I have one file:Program.cs

```c#
using System;
using Logging;
using Nancy;
using Nancy.Hosting.Self;

namespace MessageListener
{
    public class HomeModule : NancyModule
    {
        public HomeModule(ILoggerFactory ilf)
        {
            Post["/sms"] = args => ilf.Name;
        }
    }
    internal class Program
    {
        public static void Main(string[] args)
        {
            using (var nancyHost = new NancyHost(new Uri("http://localhost:8765")))
            {
                nancyHost.Start();

                Console.WriteLine("Listener is running");
                Console.WriteLine("Press Enter to stop");
                Console.ReadKey();
            }
            Console.WriteLine("Stopped. Good bye!");
        }
    }
}
```

This is the problem that exhibits the issue. How do I sort it out? i.e. Get Nancy to auto-resolve ILoggerFactory to LoggerFactory without bringing LoggerFactory into the main Assembly?

Thanks
### System Configuration
- Nancy version: 1.4.3
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [x] Self-Hosted: 1.4.1
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on): [OS X 10.11.6 and Windows 8.1 64 bit]
- .NET Framework version: [Mono 4.8.0, and .NET 4.6]
- Additional information:

**Comment by TheCois** [comment]
I'm not sure why the code sections appear so poorly. Hopefully, it won't be too big a problem.

**Comment by xt0rted** [comment]
From the [wiki](https://github.com/NancyFx/Nancy/wiki/Bootstrapper)
> NOTE: Sometimes, if you have class libraries (even with a reference to Nancy) where none of its types are used in the application at compile time, the compiler can be a bit too smart and removes the reference. For these scenarios it can be useful to add the IncludeInNancyAssemblyScanningAttribute to the class library (typically in Properties.cs):
[assembly: IncludeInNancyAssemblyScanning]

**Comment by TheCois** [comment]
thank you!
