### ISSUE TITLE
HEAD response when using Kestrel/.Net Core does not set Content-Length

### ISSUE THREAD

**Issue by jchannon** [NancyFx/Nancy#2734]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When using .Net Core / Kestrel setup when you execute a HEAD request, the code goes through [here](https://github.com/VQComms/Nancy/blob/master/src/Nancy/Owin/NancyMiddleware.cs#L134) to transfer nancy response headers into the OWIN dictionary but the HEAD response stream is invoked [after](https://github.com/VQComms/Nancy/blob/master/src/Nancy/HeadResponse.cs#L28) this and therefore never gets set.

### Steps to Reproduce
Create a .NET Core / Kestrel app
Create a route `this.Get("/", _ => "Hi");`
Execute a HEAD request
Spot no Content-Length header is returned

### System Configuration
OSX / .Net Core

- Nancy version: 2.0.0-clinteastwood
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [ ] Self-Hosted
  - [x] Other: Kestrel
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by thecodejunkie** [comment]
@jchannon is this resolved? If so then please close it, if not then help me by debugging it .. not sure we would explicitly ignore setting that property ourselves

**Comment by jchannon** [comment]
Yeah looks like MS don't want to deal with it
