### ISSUE TITLE
How to set the request timeout for route path in Nancy api

### ISSUE THREAD

**Issue by tylerdrdn85** [NancyFx/Nancy#2736]
I have one request that takes around 5 minutes to finish. As a result I am getting a gateway timeout 504 response, although the process continues to run in the background. Is there a way to set the settings of the execution timeout for the request so that it last longer for that particular request?

Would the following work?

```
<system.web>
  <httpRuntime executionTimeout="500000" /> 
</system.web>
```

**Comment by thecodejunkie** [comment]
This would depend on the host you are running Nancy on, and not Nancy itself.
