### ISSUE TITLE
Warning of empty body with Content-Type header

### ISSUE THREAD

**Issue by Boggin** [NancyFx/Nancy#2741]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

If a **Content-Type** header matching a deserializer, i.e. "application/json", is supplied with a **GET** request but the body is empty then when you try to do Model Binding you will get a `ModelBindingException` wrapping a `TargetInvocationException` wrapping a `SerializationException` "Invalid JSON string". 

The check in `SimpleJson.TryDeserializeObject(string json, out object obj)` checks that `json != null` but it may be missing an empty string check perhaps? Or maybe this could be checked in the `DefaultBinder.DeserializeRequestBody()` before passing an empty `context.Context.Request.Body`? It is failing and that's good but the error could be more specific, _i.e._ "Missing JSON body".

### Steps to Reproduce

A GET Request that set the Content-Type to something that will find a deserializer, _i.e._ "application/json", but doesn't have an Entity Body. 

GET http://localhost:5000/AB/accounts 
HTTP/1.1
Accept: application/json, text/javascript, */*; q=0.01
Content-Type: application/json; charset=utf-8

### System Configuration

- Nancy version: clint-eastwood
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [ ] Self-Hosted
  - [x] Other: Kestrel
- Other Nancy packages and versions:
- Environment (Operating system, version and so on): W10
- .NET Framework version: dotnetcore 1.1
- Additional information:

**Comment by sloncho** [comment]
We hit the same problem. And we verified, this was working properly in 1.4.x

The following test passes in 1.4. Similar (with the new syntax) fails in clint-eastwood:

``` csharp
namespace NancyHeader
{
    using FluentAssertions;
    using Nancy;
    using Nancy.ModelBinding;
    using Nancy.Testing;
    using NUnit.Framework;
    public class Dto
    {
        public string Data { get; set; }
    }

    public class TestModule : NancyModule
    {
        public TestModule()
        {
            Get["/"] = o =>
            {
                var model = this.Bind<Dto>();
                return Response.AsJson(model);
            };
        }
    }

    public class Test
    {
        [Test]
        public void Should_bind_with_empty_body()
        {
            var br = new Browser(c => c.Module<TestModule>());
            br.Get("/", c=>c.Header("Content-Type", "application/json"))
                .StatusCode.ShouldBeEquivalentTo(HttpStatusCode.OK);
        }
    }
}

```

**Comment by sloncho** [comment]
I would give it a try, but I'm not sure where to handle this. The JsonBodyDeserializer? Or higher, i.e. do not try to bind the body at all if it's empty.

**Comment by xt0rted** [comment]
After looking through the json deserializer in v1.4 I think that should have thrown an exception as well, but didn't due to the body being passed to a `TextReader` first. So even if the body was null/empty the `TextReader` wasn't and the code continued on and returned `null` [JsonDeserializer.cs#L334-L372](https://github.com/NancyFx/Nancy/blob/d2d0240327efe8875025c4a3c68c093ac9bfb877/src/Nancy/Json/JsonDeserializer.cs#L334-L372).

[SimpleJson.cs#L531](https://github.com/NancyFx/Nancy/blob/a9168cef7cea381af7d4aaa3c785c0b27f9603e5/src/Nancy/Json/Simple/SimpleJson.cs#L531) could be updated like so to fix this:
```diff
diff --git a/src/Nancy/Json/SimpleJson.cs b/src/Nancy/Json/SimpleJson.cs
index eb1f255a..bd00636e 100644
--- a/src/Nancy/Json/SimpleJson.cs
+++ b/src/Nancy/Json/SimpleJson.cs
@@ -538,6 +538,11 @@ static SimpleJson()
         /// <returns>An IList&lt;object>, a IDictionary&lt;string,object>, a double, a string, null, true, or false</returns>
         public static object DeserializeObject(string json)
         {
+            if (string.IsNullOrWhiteSpace(json))
+            {
+                return null;
+            }
+
             object obj;
             if (TryDeserializeObject(json, out obj))
                 return obj;
```

**Comment by kolhapuri** [comment]
Any updates on a fix for this?

**Comment by thecodejunkie** [comment]
@xt0rted care to take a stab at this? There is another proposed change to `Content-Type` header on #2769 - mentioning it to make it won't have an impact on the proposed change in here
