### ISSUE TITLE
Unable to disable AutoRegister

### ISSUE THREAD

**Issue by DavidKuennen** [NancyFx/Nancy#2744]
I'm overriding both ConfigureApplicationContainer and ConfigureRequestContainer without calling base in my Bootstrapper, but AutoRegister still seems to trigger. 

Environment ASP.net

**Comment by thecodejunkie** [comment]
Please do not ignore the issue template, it provides us with relevant information. Simply overriding the `ConfigureApplicationContainer` method does not disable. if you still call `base.ConfigureApplicationContainer(..)` from the overriden method. That's the only place where `AutoRegister` is called https://github.com/NancyFx/Nancy/blob/master/src/Nancy/DefaultNancyBootstrapper.cs#L60 

Closing this for the time being. If have you are able to provide more information (preferably a running, small, reproduction) that shows that it is still happening, then we can always re-open

Hope this helps
