### ISSUE TITLE
Super Simple View Engine Performance

### ISSUE THREAD

**Issue by nkosi23** [NancyFx/Nancy#2745]
Hello !

I am wondering if there can be any meaningful performance penalty for using the Super Simple View Engine compared to for example the Razor Engine. I find the SSVE very compelling, but I am wondering how the fact that it is Regex Based make it compare with other engines from a performance perspective.

I'm mainly wondering if there can be a big hit, like for example being able to service 10,000 per second with another engine but 6,000 per second with this one.

**Comment by amoerie** [comment]
I don't have any numbers to back this, but I would guess that the Regex based system of SSVE would indeed be bad for performance, but only on large scales. 

The method I would recommend is just let Nancy return .html files and do your templating client-side using React (or whatever flavor of frontend you most prefer).
This offloads the template processing cycles to each browser, which is a huge win for your scalability.
The fastest way to render views on the server is to not render them at all! :-)

If you do persist with server side rendering, and if performance is very important to you, I would look into precompiled Razor views and see how it compares to SSVE on a large scale.

**Comment by reddyBell** [comment]
Many thanks for the replies, it was just something I wondered. 

Now that you mention it, the templating for our really big applications is done client-side, the SSVE is just used for marketing pages. 

So the traffic should never be large to the point where the performance hit becomes noticeable, even less a problem. If it ever gets to the point where we are getting so much traffic to our landing pages that performance becomes an issue, something tells me having the budget to write/adapt a view engine  won't be an issue !

**Comment by amoerie** [comment]
@xt0rted 
I was not aware of that, thanks!

@reddyBell 
There's a famous quote by Donald Knuth you should keep in mind:

> Programmers waste enormous amounts of time thinking about, or worrying about, the speed of noncritical parts of their programs, and these attempts at efficiency actually have a strong negative impact when debugging and maintenance are considered. We should forget about small efficiencies, say about 97% of the time: premature optimization is the root of all evil. Yet we should not pass up our opportunities in that critical 3%.

Knowing when to worry, and when not to worry, about performance is a skill to hone.
