### ISSUE TITLE
Exception causes self-hosted nancy to blow up

### ISSUE THREAD

**Issue by imranazad** [NancyFx/Nancy#2746]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Totally stumped on this, at random times the exception below is thrown. So it'll serve requests fine for X number of hours and then all of a sudden start to throw exceptions. Since we are deploying it via rancher, once the docker container exits due to the exception rancher attempts to restart it however it then enters a loop. The only way to resolve it is to "upgrade" which effectively recreates the container. We're unable to replicate this issue. Towards the end you will notice it fires up and starts to work fine. Any idea when `INancyEngine.HandleRequest` is called? Is it during a http request?
```
5/17/2017 1:41:36 PMUnhandled Exception:
5/17/2017 1:41:36 PMSystem.MissingMethodException: Method 'INancyEngine.HandleRequest' not found.
5/17/2017 1:41:36 PM  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) <0x7f4aafcb1010 + 0x000d0> in <filename unknown>:0
5/17/2017 1:41:36 PM  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x7f4aafcaf850 + 0x0016e> in <filename unknown>:0
5/17/2017 1:41:36 PM  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x7f4aafcaf820 + 0x00020> in <filename unknown>:0
5/17/2017 1:41:36 PM  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) <0x7f4aafcaf770 + 0x00059> in <filename unknown>:0
5/17/2017 1:41:36 PM  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) <0x7f4aafcb1120 + 0x0004c> in <filename unknown>:0
5/17/2017 1:41:36 PM[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'INancyEngine.HandleRequest' not found.
5/17/2017 1:41:36 PM  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) <0x7f4aafcb1010 + 0x000d0> in <filename unknown>:0
5/17/2017 1:41:36 PM  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x7f4aafcaf850 + 0x0016e> in <filename unknown>:0
5/17/2017 1:41:36 PM  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x7f4aafcaf820 + 0x00020> in <filename unknown>:0
5/17/2017 1:41:36 PM  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) <0x7f4aafcaf770 + 0x00059> in <filename unknown>:0
5/17/2017 1:41:36 PM  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) <0x7f4aafcb1120 + 0x0004c> in <filename unknown>:0
5/17/2017 1:41:36 PM>
5/17/2017 1:41:47 PMBNF Search is running on http://localhost:8080/
5/17/2017 1:41:47 PMPress any [Enter] to close the host.
```

### Steps to Reproduce
Unable to reproduce.

### System Configuration
The application is running a docker environment deployed via rancher

- Nancy version: 1.4.3
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [x] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions: Nancy.Hosting.Self.1.4.1
- Environment (Operating system, version and so on): docker deployed via rancher
- .NET Framework version: mono
- Additional information:

**Comment by khellang** [comment]
`INancyEngine.HandleRequest` is called for every request, so it's pretty weird that it suddenly starts throwing this exception. This usually happens when an assembly with a non-compatible method signature is loaded. Could it be that the deployment is pushing Nancy assemblies with different (non-compatible) versions?

**Comment by imranazad** [comment]
@khellang  Thank you so much.. So we were using Nancy.LighteningCache that was referencing a really old version of Nancy and so each time the cache expired and a call needed to be made to Nancy it was blowing up which explains the missing method exception. I've updated Nancy in Nancy.LighteningCache and tested it with an expired page and it works fine now.

Thanks again.

**Comment by khellang** [comment]
Glad you figured it out! ✨
