### ISSUE TITLE
Can TinyIoC resolve generic types ?

### ISSUE THREAD

**Issue by MamboJoel** [NancyFx/Nancy#2747]
### Description
I suppose I am missing a specification. I was wondering if nancy resolved generic types.

### Steps to Reproduce
Starting From a Visual Studio 2015 Nancy empty project with ASP.NET host I define those types :

```c#
    public interface IFoo<T> where T : class {}
    public class Foo<T> : IFoo<T> where T : class {}
    public class Bar {}
```

I define this module inheriting from NancyModule  :

```c#
    public class FooModule : Nancy.NancyModule {
        public FooModule(IFoo<Bar> foo) {}
    }
```

Hit F5 and get this Nancy.TinyIoc.TinyIoCResolutionException :
**Unable to resolve type: NancyEmptyAspNetHost2.IFoo`1[[NancyEmptyAspNetHost2.Bar, NancyEmptyAspNetHost2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]**

Thank you for your help and this great project.

**Comment by khellang** [comment]
And where did you register the type?

**Comment by MamboJoel** [comment]
I supposed the [the Super-Duper-Happy-Path](https://github.com/NancyFx/Nancy/wiki/Bootstrapping-nancy) could resolve it out of the box just as it resolves successfully these non generic types in this scenario :

```c#
    public interface IFoo {}
    public class Foo : IFoo {}

    public class FooModule : Nancy.NancyModule
    {
        public FooModule(IFoo foo) { }
    }
```

Your answer leaves me with the impression that generic types are not resolved through the Super-Duper-Happy-Path. So I implemented a Bootstrapper :

```c#
    public class CustomBootstrapper : Nancy.DefaultNancyBootstrapper
    {
        protected override void ApplicationStartup(TinyIoCContainer container, IPipelines pipelines)
        {
            container.Register(typeof(IFoo<>), typeof(IFoo));
        }
    }
```

And I get this exception:
**Cannot register type NancyEmptyAspNetHost2.IFoo - abstract classes or interfaces are not valid implementation types for SingletonFactory.**

So I suppose the answer to my original question is simply "no".

Thank you.

**Comment by khellang** [comment]
I don't think the auto-registration does generic type registrations, but I've never used it so I'm not sure. You need to register the actual type; `container.Register(typeof(IFoo<>), typeof(Foo<>));`. It should probably also be done in the `ConfigureApplicationContainer` method :smile:

**Comment by MamboJoel** [comment]
Indeed, sorry for the mistake. But still :
```c#
   public class CustomBootstrapper : Nancy.DefaultNancyBootstrapper
    {
        protected override void ConfigureApplicationContainer(TinyIoCContainer container)
        {
            container.Register(typeof(IFoo<>), typeof(Foo));
        }
    }
```
throws :
**Cannot register type NancyEmptyAspNetHost2.Foo - abstract classes or interfaces are not valid implementation types for SingletonFactory.**

**Comment by khellang** [comment]
Hmm. I have a feeling that what you posted is not what you're actually running...

[This TinyIoC test](https://github.com/grumpydev/TinyIoC/blob/master/src/TinyIoC.Tests/TinyIoCTests.cs#L3292-L3297) shows that it's perfectly valid to register and resolve open generics.

The error message is pretty clear:

>  abstract classes or interfaces are not valid implementation types for SingletonFactory.

Is `Foo` an abstract class? You posted

```csharp
 public interface IFoo<T> where T : class {}
public class Foo<T> : IFoo<T> where T : class {}
public class Bar {}
```

This should work if you call `container.Register(typeof(IFoo<>), typeof(Foo<>));` and resolve `IFoo<Bar>`.

**Comment by MamboJoel** [comment]
Thank you for your research. I'm glad the test clearly shows it's supposed to resolve generic types.
Here is my entire application, running from  a Visual Studio 2015 Nancy empty project with ASP.NET host:
```c#
using Nancy;
using Nancy.TinyIoc;

public interface IFoo<T> where T : class { }
public class Foo<T> : IFoo<T> where T : class { }
public class Bar { }

public class MyModule : NancyModule
{
    public MyModule(IFoo<Bar> Foo) { }
}

public class MyBootstrapper : DefaultNancyBootstrapper
{
    protected override void ConfigureApplicationContainer(TinyIoCContainer container)
    {
        container.Register(typeof(IFoo<>), typeof(Foo<>));
        var result = container.Resolve<IFoo<Bar>>();
        bool isOfType = result is Foo<Bar>; // is true...
    }
}
```

Curiously isOfType is true. But still, it throws this error :
**Unable to resolve type: IFoo`1[[Bar, NancyEmptyAspNetHost2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]**

**Comment by MamboJoel** [comment]
I tried implementing `ConfigureRequestContainer` instead of `ConfigureApplicationContainer` and it now works as expected. I wonder why...
Anyway, thank you very much for your help.

**Comment by grumpydev** [comment]
Must be something to do with pulling down the registration from the parent container, it must think there isn't one because it isn't taking into account the open generic - good that you found a workaround though :+1:
