### ISSUE TITLE
Typo in Basic Auth tutorial

### ISSUE THREAD

**Issue by SyedWasiHaider** [NancyFx/Nancy#2748]
https://github.com/NancyFx/Nancy/wiki/Basic-Authentication

Makes mention of IUserMapper but then goes on to use IUserValidator in the bootstrap call. I believe IUserValidator is the correct one.

**Comment by MamboJoel** [comment]
I'm also confused with the `IUserMapper` of this wiki page. Its intro states :

> For a full working sample, please refer to the `Nancy.Demo.Authentication.Basic`  project in the Nancy solution.

But this project doesn't implement `IUserMapper`. I searched for an hour or two but couldn't find any implementation example of Nancy basic authentication.

**Comment by thecodejunkie** [comment]
@SyedWasiHaider updated the docs 👍 

@MamboJoel the `IUsermapper` is only available in `1.x` and was replaced by `ClaimsPrincipal` in `2.x` to let you flow credentials into your Nancy application from the outside
