### ISSUE TITLE
Nancy.Hosting.Self -Pre nuget package incompatible with Core 1.1

### ISSUE THREAD

**Issue by kreeben** [NancyFx/Nancy#2750]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am unable to install nuget package Nancy.Hosting.Self -Pre.

Log:

Install-Package : Package Nancy.Hosting.Self 2.0.0-clinteastwood is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Nancy.Hosting.Self 2.0.0-clinteastwo
od supports: net452 (.NETFramework,Version=v4.5.2)
At line:1 char:1
+ Install-Package Nancy.Hosting.Self -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more packages are incompatible with .NETCoreApp,Version=v1.1.
At line:1 char:1
+ Install-Package Nancy.Hosting.Self -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'Sir.Server'.
At line:1 char:1
+ Install-Package Nancy.Hosting.Self -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

### Steps to Reproduce
Create new core 1.1 project and try to install Nancy.Hosting.Self -Pre.

### System Configuration
VIsual Studio 2017, Windows 8.1

- Nancy version:
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version: Core 1.1
- Additional information:

**Comment by thecodejunkie** [comment]
Hi Marcus 😄 

This is actually by design. Back when we first added support for netcore, Microsoft did not support (nor did they intend to) support the `HttpListener` (which the self host it build on-top of). However, now that they've added it back into the fold, we can look into bringing it back

![image](https://cloud.githubusercontent.com/assets/50543/26520894/0cf4cb62-42dc-11e7-8e12-0d42d9cfb8d4.png)

The equivalent way of doing it, right now, is to host it using Kestrel as in the [Nancy.Demo.Hosting.Kestrel](https://github.com/NancyFx/Nancy/tree/master/samples/Nancy.Demo.Hosting.Kestrel) sample.

Hope this helps

**Comment by kreeben** [comment]
Hey Mr Håkansson. :) Very helpful, thx! 👍

**Comment by ziggisto88** [comment]
Hi Andreas, 
is there any timeline on Nancy.Hosting.Self support for .NET Core console apps?

Best regards

**Comment by thecodejunkie** [comment]
@ziggisto88 no nothing set. If you want you can send us a PR and it will be available to you on our MyGet feed once it's been pulled in. What do you need self hosting for vs hosting it using Kestrel?
