### ISSUE TITLE
Documentation for launching Nancy on AWS ECS?

### ISSUE THREAD

**Issue by josephlundtz** [NancyFx/Nancy#2760]
I'm new to Nancy and am a big fan so far! I am trying to deploy a simple Nancy project to AWS, using a docker container to hold all of my Nancy code and dependencies, and deploy to AWS ECS. I was wondering if you know of any tutorials for this flow? The "Hosting Nancy with Azure" page is great, but would love any similar tips or samples for doing this via AWS. Much appreciated!

**Comment by thecodejunkie** [comment]
Nothing documented by us - maybe @damianh or @phillip-haydon has any insight. I also know @jchannon did some stuff around docker recently

**Comment by damianh** [comment]
I'm running it on Lambda and EC2, not doing ECS stuff yet so no info to share at this time.

**Comment by phillip-haydon** [comment]
I'm running on Lambda (not Nancy but @damianh's project looks awesome), and EC2 with Windows, (been looking at Ubuntu for core stuff)

I've not touched docker at all... :(

**Comment by yahehe** [comment]
I used to run a few Nancy services in AWS Elastic Beanstalk (which uses EC2 under the hood), if I did a writeup on that would it be helpful?
