### ISSUE TITLE
SimpleInjector bootstrapper

### ISSUE THREAD

**Issue by ayoung** [NancyFx/Nancy#2763]
Would you entertain a pull request for a boostrapper for `Nancy.Bootstrappers.SimpleInjector`?

Actually it would be more like a new repository.

**Comment by thecodejunkie** [comment]
@ayoung I'm not sure we would like to take on more 3rd party dependencies, to maintain, than we already have. Ideally we like it when our community grown outside of the core team and would like to see such packages to be maintained by our community instead. We just introduced a community contribution logo https://github.com/NancyFx/Nancy.Portfolio/blob/master/guidelines/guidelines.md#community-contributions to help push this effort further.

There are a couple of direct reasons for this

1. We might not be using the technology ourselves, meaning we're not really equipped to handle bug reports of even make necessary modifications if we change the contracts in Nancy

2. The more packages we assume ownership of, the thinner we'll eventually end up spreading out time across them all. 

3. We'd like to help foster a strong .net ecosystem which means we'd like to see people maintain their packages themselves and work with their users to maintain and contribute to those packages. Also, in the event that the package author looses interest, a hand over could be done to one of the contributors

Thanks!
