### ISSUE TITLE
Support for Server-sent Events/HTTP Event Stream

### ISSUE THREAD

**Issue by qntf** [NancyFx/Nancy#2773]
Version: `2.0.0-clinteastwood`

Running on ASP.NET Core with OWIN

I was developing an application that uses SSEs to push events to the client.
https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

However I've implemented it in a very hacky way because I did not see any documentation on SSE with NancyFx.

Is there a recommended/officially supported way to properly do SSE from Nancy?

**Comment by jchannon** [comment]
I might be reading this wrong but you'd normally use something like SignalR
rondo that for you.

**Comment by dajuric** [comment]
The working sample (although written a long time ago) is available here:
   [Code](https://github.com/serbrech/EventSourceSample)

and the full explanation:
 [Explanation](https://groups.google.com/forum/#!topic/nancy-web-framework/rSbzX9aZDI4)

In essence: the response-stream should not be closed if a response type is 'EventStreamWriterResponse'.
The response type is used for SSE.

It would be great if the support for this would be integrated into Nancy.
