### ISSUE TITLE
Whether nancy can support directory browsing in self-hosted mode

### ISSUE THREAD

**Issue by jello-chen** [NancyFx/Nancy#2777]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I want to enable nancy to accomplish directory browsing in self-hosted mode, but i don't know whether nancy can support it.

- Nancy version:
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [x] Self-Hosted
  - [ ] Other:

**Comment by khellang** [comment]
There's no built-in directory browsing in Nancy, but you could switch to self-hosted OWIN-based Nancy and use Microsoft's file server middleware. See https://codeopinion.com/asp-net-self-host-static-file-server/ for some hints...

**Comment by jello-chen** [comment]
Oh, that is a great help for me, thanks!!!
