### ISSUE TITLE
[Question] - nancy with asp.net core routing

### ISSUE THREAD

**Issue by dazinator** [NancyFx/Nancy#2780]
I am working on an extensible / modular system for aspnet.core.
I am hoping to allow extension developers, to develop an extension using not just MVC, but also Nancy if they want to. 
I am using asp.net core `routing` middleware in the middleware pipeline and each extension is allowed to register its routes on startup. The module router will then evaluate the incoming request and pass it on to the matching route handler:
```
                                          ---------- MVC Module
Request ---> ModuleRouter --------|
                                          ----------Nancy Module
```

My question is, does nancy provide any kind of `RouteHandler` so that it can be invoked during asp.net core routing process? If it did, I could register a modules routes with `IRouteBuilder` and I think I can achieve the above..

**Comment by grumpydev** [comment]
Can you not already do this with owin or whatever owin bridge they have for aspnet.core now they stomped all over the standard?

**Comment by dazinator** [comment]
Not sure.. but I will look into the owin bridge to see what it provides so thanks for the suggestion. At the moment, I am working outside of owin, and all I have are `IRouter`s from aspnet core's routing system. Their `routebuilder` looks an awful lot like the `Nancy Module` sample where you can just register paths that map to handlers / delegates.

**Comment by dazinator** [comment]
I am quite new to Nancy, but have been looking at it and reading the docs today, thanks for all the effort!

My idea now is

1. On the asp.net core side, I will try to get access to all `NancyModules` and their `Routes`.
2. I will create an asp.net core `IRouter` implementation that sits on top of these `NancyRoutes`.
3. My `IRouter` will sit in the asp.net core middleware pipeline, ready to route requests.
4. When an asp.net core request comes in, my `IRouter` is asked to `RouteAsync()` it will want to use the `Nancy` `DefaultRouteResolver` to evaluate the routes on the asp.net core side. From this I should be able to get:

- the matching `INancyModule`
- the matching `NancyRoute`
- a `Nancy.Routing.Trie.MatchResult`

5. My `IRouter` will also create its own `Owin` bridge.
6. When the `owin` bridge is created, I will use a custom bootstrapper, and register my own `IRouteResolver` into nancy's tinyioc request container.

The resolver will look something like this:

```

 public class AlreadyKnownRouteResolver : IRouteResolver
    {
        private readonly Nancy.Routing.Route _route;
        private readonly INancyModule _module;
        private readonly Nancy.Routing.Trie.MatchResult _matchResult;
        private readonly GlobalizationConfiguration _globalizationConfiguraton;

        public AlreadyKnownRouteResolver()
        {
        }

        public AlreadyKnownRouteResolver(INancyEnvironment environment, Nancy.Routing.Route route, INancyModule module, Nancy.Routing.Trie.MatchResult matchResult)
        {
            _globalizationConfiguraton = environment.GetValue<GlobalizationConfiguration>();
            _route = route;
            _module = module;
            _matchResult = matchResult;
        }

        public ResolveResult Resolve(NancyContext context)
        {
            return BuildResult(context, _matchResult);
        }

        private ResolveResult BuildResult(NancyContext context, Nancy.Routing.Trie.MatchResult result)
        {

            context.NegotiationContext.SetModule(_module);
            var route = _module.Routes.ElementAt(result.RouteIndex);
            var parameters = DynamicDictionary.Create(result.Parameters, _globalizationConfiguraton);

            return new ResolveResult
            {
                Route = route,
                Parameters = parameters,
                Before = _module.Before,
                After = _module.After,
                OnError = _module.OnError
            };

        }


    }
```

The resolver above takes the route, module etc that I have already resolved on the asp.net core side.

When my `IRouter` creates it's Owin pipeline, it will `UseNancy` specifying a custom bootstrapper, that can register the `IRouteResolver` in the request container something like this:

```
                       owinAppBuilder.UseNancy((options) =>
                        {
                            options.Bootstrapper = new CustomBootstrapper(() =>
                            {
                                return new AlreadyKnownRouteResolver(this.MatchedRoute, this.MatchedModule)
                            });
                        });

```

I am hoping that if I can get this all right, then nancy's routes can be resolved to on the asp.net core side, and then when the request is sent through the OWIN pipeline, nancy will just route it to the already resolved route.

**Comment by dazinator** [comment]
Is it possible to override `IRouteResolver` on per request basis? Looking at the code, to me, it looks as though `INancyEngine` is resolved from the application container, which resolves `IRouteResolver` in the process (via `IRequestDispatcher`). So I am assuming you can't?

**Comment by dazinator** [comment]
Ok new idea. Going to look at porting the nancy middleware from owin to aspnet core. I think this would be a lot easier.

**Comment by dazinator** [comment]
Conclusion of this was, I ended up writing aspnet core based middleware to host nancy, dropping the need for the owin bridge. Nancy still uses its own routing, and for the time being I have given up on bridging that with asp.net core routing. Whichever is higher in the middleware pipeline can steal the request, and I am ok with that for the time being.
