### ISSUE TITLE
RequestStream cause a deadlock

### ISSUE THREAD

**Issue by delarocka** [NancyFx/Nancy#2781]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I got an application running on OWIN self hosting. During load testing application suffers a deadlock (most threads are in waiting state), causing by [RequestStream's](https://github.com/NancyFx/Nancy/blob/1.x-WorkingBranch/src/Nancy/IO/RequestStream.cs) MoveToWritableStream method.

### Steps to Reproduce
[NancySelfHost.zip](https://github.com/NancyFx/Nancy/files/1199373/NancySelfHost.zip) contains simplified project and JMeter test (SummonDeadlock.jmx) that i use for load test. Just build and run project and run JMeter test.

### System Configuration

- Nancy version: 1.4.4
- Nancy host
  - [ ] ASP.NET
  - [x] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions: Nancy.Owin 1.4.1
- Environment (Operating system, version and so on): Windows 10 10.0.15063
- .NET Framework version: 4.5.2
- Additional information: JMeter version 3.2, i used a separate machine to run JMeter.

**Comment by xt0rted** [comment]
I think this is what #2686 fixed but was never backported to 1.4. Are you able to try the pre-release of 2.0 to confirm if you still have the issue?

**Comment by delarocka** [comment]
I tried to backport #2686 to 1.x branch and can confirm it fixes the issue.

**Comment by thecodejunkie** [comment]
Resolved by #2686
