### ISSUE TITLE
How does Nancy cast query parameters?

### ISSUE THREAD

**Issue by alexreg** [NancyFx/Nancy#2782]
If I do something like `(bool)this.Request.Query["foo"]`, what actually goes on under the hood? How does Nancy convert the value of type `dynamic` to a `bool`? Does it use `bool.Parse` or something? How does it know to use this?

Furthermore, is there any way to leverage this feature to cast to arrays? Something like `(string[])this.Request.Query["foo"]`?

**Comment by khellang** [comment]
Parameters from the dictionaries are instances of `DynamicDictionaryValue`. This is a special type that inherits from `DynamicObject` and [overrides `TryConvert`](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/DynamicDictionaryValue.cs#L260). This is the method that is called by the runtime when you try to cast the value.

The type also defines a ton of implicit casting operators to allow it to be passed as an argument as most primitive types, but these are not involved in this case.

**Comment by khellang** [comment]
As you can see from the code in the method I linked, the runtime does some work by calling the `TryConvert` method, then it's mostly just a matter of checking the type and calling the correct `Convert` method :smile:

**Comment by alexreg** [comment]
@khellang Interesting. Thanks for that info. So it looks like there's no in-built support for getting lists/arrays from query string parameters. What would you recommend in this case, as the most natural solution?

**Comment by khellang** [comment]
I guess the easiest way is to just parse the list yourself, i.e. `string.Split` etc. There's really no standard way to represent lists in query strings, AFAIK. Some do `?param=value1&param=value2` and some do `?param=value1,value2`. It's up to you :smile:

**Comment by alexreg** [comment]
Thanks, @khellang, that's what I thought. But good to confirm. :-)
