### ISSUE TITLE
How to avoid create instance of Generic Module

### ISSUE THREAD

**Issue by ndphuong** [NancyFx/Nancy#2788]
We create a generic module (BaseModule<T>) to re-use in many others modules  
The problem is Nancy are throw exception when trying create instance of BaseModule because it is generic type

How we can avoid this ?

**Comment by Zaid-Ajaj** [comment]
@ndphuong I havn't checked this but you can try overriding the module registration to specify what modules you actually want registered:
```cs
protected override IEnumerable<ModuleRegistration> Modules
{
    get
    {
        return base.Modules.Where(m => m.ModuleType == typeof(GenericBase<YourType>));
    }
}
```

**Comment by thecodejunkie** [comment]
Make your generic module `abstract`

**Comment by ndphuong** [comment]
Great tip @thecodejunkie
