### ISSUE TITLE
How enable stateless authentication for all modules isn't clear.

### ISSUE THREAD

**Issue by ricardovsilva** [NancyFx/Nancy#2790]
[How to configure stateless authentication](https://github.com/NancyFx/Nancy/wiki/Stateless-authentication) is not clear about how to configure stateless auth to all modules.

It has the snippet below, where the _Per Module_ is clear, but I can't figure out where to run line to all modules and what is pipelines.

![image](https://user-images.githubusercontent.com/2130182/29750013-1b1819fe-8b0e-11e7-84ce-aa6e5ea548bc.png)

**Comment by khellang** [comment]
Yeah, it should really include more context. This is in the `ApplicationStartup` or `RequestStartup` methods of your bootstrapper.

**Comment by ricardovsilva** [comment]
Also, is possible to deactivate for specific modules?

**Comment by khellang** [comment]
I don't think so. You either have to add it globally to all modules, or specific modules. You could of course create a base module that adds the hook for you.

**Comment by khellang** [comment]
It's important to remember that the hook only sets the `CurrentUser` property. It does not enforce authentication/authorization, so it doesn't really matter if you add it globally.

**Comment by ricardovsilva** [comment]
I was thinking that it would work's like Authorization attribute of Identity. Do you have any snippet to automatically returns HTTP 403 when token is not valid?

**Comment by thecodejunkie** [comment]
I updated the wiki (it's a community wiki, feel free to edit if you thing clarifications are needed). Thanks!
