### ISSUE TITLE
Nancy 2.0 + AspNet Core: IApplicationStartup not fire when application start

### ISSUE THREAD

**Issue by ndphuong** [NancyFx/Nancy#2791]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
We are using Nancy 2.0.0-clinteastwood and AspNet core 1.1

### Steps to Reproduce
We try enable GZIP for our rest api, so we create custom class as follow (https://codeopinion.com/gzip-compression-nancyfx/)

```
using Nancy;
using Nancy.Bootstrapper;
using System.Collections.Generic;
using System.IO.Compression;
using System.Linq;

namespace Omnicasa.UnifiedService.RestApi
{
    public class NancyGzipCompression : IApplicationStartup
    {
        public void Initialize(IPipelines pipelines)
        {
            pipelines.AfterRequest.AddItemToEndOfPipeline(CheckAndCompressResponse);
        }

        public static void CheckAndCompressResponse(NancyContext context)
        {
            if (!RequestIsGzipCompatible(context.Request))//Just compress if request contain compress in header
            {
                return;
            }

            if (context.Response.StatusCode != HttpStatusCode.OK)
            {
                return;
            }

            if (!ResponseIsCompatibleMimeType(context.Response))
            {
                return;
            }

            if (ContentLengthIsTooSmall(context.Response))
            {
                return;
            }

            CompressResponse(context.Response);
        }
        private static void CompressResponse(Response response)
        {
            response.Headers["Content-Encoding"] = "gzip";

            var contents = response.Contents;
            response.Contents = responseStream =>
            {
                using (var compression = new GZipStream(responseStream, CompressionMode.Compress))
                {
                    contents(compression);
                }
            };
        }
        private static bool ContentLengthIsTooSmall(Response response)
        {
            string contentLength;
            if (response.Headers.TryGetValue("Content-Length", out contentLength))
            {
                var length = long.Parse(contentLength);
                if (length < 4096)
                {
                    return true;
                }
            }
            return false;
        }
        private static readonly List<string> ValidMimes = new List<string>
                                            {
                                                "application/json",
                                                "application/json; charset=utf-8"
                                            };
        private static bool ResponseIsCompatibleMimeType(Response response)
        {
            return ValidMimes.Any(x => x == response.ContentType);
        }
        private static bool RequestIsGzipCompatible(Request request)
        {
            return request.Headers.AcceptEncoding.Any(x => x.Contains("gzip"));
        }
    }
}
```

Then, we start debug application but `Initialize` function not hit breakpoint

### System Configuration

- Nancy version: 2.0.0
- Nancy host
  - [x] ASP.NET
  - [x] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version: NET Core 1.1

**Comment by thecodejunkie** [comment]
Is it located in another assembly, that you reference, and not explicitly use another type from? Sometimes the linker gets smart during compilation and removes those references 😢

**Comment by ndphuong** [comment]
@thecodejunkie 
No, it in the same assembly (entry project).
I follow this article to enable GZIP: https://codeopinion.com/gzip-compression-nancyfx/
Bellow is detail
`public class NancyGzipCompression : IApplicationStartup
    {
        public void Initialize(IPipelines pipelines)
        {
            pipelines.AfterRequest.AddItemToEndOfPipeline(CheckAndCompressResponse);
        }
...
`

**Comment by thecodejunkie** [comment]
Can you please edit your initial post and please fill out the template that was there?

**Comment by ndphuong** [comment]
@thecodejunkie Updateed

**Comment by ndphuong** [comment]
@thecodejunkie 
Sorry, it is my fault
I have try debug in release mode :(
Everything work well

Thank you

**Comment by thecodejunkie** [comment]
Thank you for confirming that it was not a bug - saved me some debugging time! 😄
