### ISSUE TITLE
Returning a 404 in an ErrorPipeline does not permit specifying a model or reason phrase

### ISSUE THREAD

**Issue by alexreg** [NancyFx/Nancy#2795]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When returning an `HttpStatusCode.NotFound` status code (i.e. 404) from an `ErrorPipeline`, the body (model) and reason phrase are not returned to the client. This only occurs for this status code, and not other status codes, e.g. `HttpStatusCode.InternalServerError` (i.e. 500).

I am overriding the `DefaultNancyBootstrapper` like so.

```csharp
protected override void RequestStartup(TinyIoCContainer container, IPipelines pipelines, NancyContext context)
{
	base.RequestStartup(container, pipelines, context);

	var responseNegotiator = container.Resolve<IResponseNegotiator>();

	pipelines.OnError += (ctx, ex) => {
		var negotiator = new Negotiator(ctx).WithStatusCode(HttpStatusCode.NotFound).WithReasonPhrase("reason").WithModel("body");
		return responseNegotiator.NegotiateResponse(negotiator, ctx);
	};
}
```

### System Configuration

- Nancy version: 1.4.4
- Nancy host
  - [ ] Nancy.Hosting.Aspnet
  - [ ] Nancy.Hosting.Self
  - [x] Nancy.Owin (Katana self-hosting, i.e. HttpListener)
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on): Mac OS X 10.12.6
- .NET Framework version: Mono 5.2.0.244 (.NET 4.6.2)
- Additional information:

**Comment by thecodejunkie** [comment]
I just tried this with `2.0-clinteastwood` + the Kestrel host and it worked just fine

![image](https://user-images.githubusercontent.com/50543/32988819-5ab80d9a-cd0c-11e7-9d5c-aa13bd0aa245.png)

That part of the code base (the content negotiation stuff) is virtually untouched between `1.4.x` and `2.x` which leads me to think that this is not related to Nancy, but the Katana self-hosting (the `Nancy.Owin` host basically just proxies stuff and does not contain much in the sense of logic)

Closing this for the time being, if it is still and issue and if you think it is in fact related to Nancy then please let us know and we can potentially re-open this issue

Thanks

**Comment by alexreg** [comment]
Okay. Could you try with 1.4.4 thpugh?

**Comment by cloudhunter89** [comment]
@alexreg I threw together a quick test with Nancy 1.4.4 using Nancy self hosting.  I must be missing something because using a string for the argument to `WithModel ` makes it look for a view named String.html (or similar).  However, when I had a file for it to return, I received the status and reason phrase along with the file as an html.

**Comment by alexreg** [comment]
Weird, still happens with me... definitely an issue.

**Comment by alexreg** [comment]
I'm doing this by the way, in a handler for `pipelines.OnError`.

```csharp
return new Negotiator(context)
    .WithStatusCode(statusCode)
    .WithReasonPhrase("Server Error")
    .WithModel(errorInfo);
```

**Comment by cloudhunter89** [comment]
I believe that it is an issue; however, the issue probably isn't in Nancy,
but rather in the host application.

**Comment by cloudhunter89** [comment]
Sorry that last half of the comment was misplaced, been reading to many issues today.
