### ISSUE TITLE
Road map of nancy 2.0

### ISSUE THREAD

**Issue by ndphuong** [NancyFx/Nancy#2798]
Hi,
What is road map of nancy 2.0 ?
Will you release stable version ?

**Comment by mikeandersun** [comment]
This an express approach to routing . I like this project, please give us a road map.

**Comment by thecodejunkie** [comment]
We've recently picked up work on closing off what is remaining `2.0-dangermouse` milestone. It is very likely that that will end up as the stable `2.0` release. Past that point we are going to evaluate some option moving forward. Thanks

**Comment by thecodejunkie** [comment]
Oh and if anyone would like to help out, check out the open issues on https://github.com/NancyFx/Nancy/milestone/45 and fire up your editors. 

```
⚠️ If you want to help out with things on that list
 
1. Open a pull-request very early on.
2. Prefix the title with [WIP]
3. Discuss design and solutions in the PR with us

This will speed up the process and prevent you from writing a pull-request that does not meet ideas we had
```
