### ISSUE TITLE
Overriding `GetApplicationContainer` on subclass of `DefaultNancyBootstrapper` does not work

### ISSUE THREAD

**Issue by alexreg** [NancyFx/Nancy#2804]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I override this method to return a customer container, but it does not get used.

### Steps to Reproduce
Override the `GetApplicationContainer` method and return a custom `TinyIoCContainer`.

### System Configuration
Mac OS X 10.3, Mono 5.2.

- Nancy version:
- Nancy host
  - [ ] Nancy.Hosting.Aspnet
  - [ ] Nancy.Hosting.Self
  - [x] Nancy.Owin (Katana Self Hosting, i.e. HttpListener)
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by khellang** [comment]
This definitely works. What makes you think it doesn't?

**Comment by khellang** [comment]
The exact call site: https://github.com/NancyFx/Nancy/blob/23de06548d9e29d0039c88b7e0af87a5fe40c28a/src/Nancy/Bootstrapper/NancyBootstrapperBase.cs#L257

**Comment by alexreg** [comment]
Because of <https://github.com/NancyFx/Nancy/issues/2805>... but it could just be that issue, and nothing more, in fairness!

**Comment by khellang** [comment]
As mentioned in #2805, we have many many people doing this very thing successfully in production as we speak. I'm pretty sure we would hear about it before now if Nancy suddenly stopped using the container returned from `GetApplicationContainer` 😉

**Comment by thecodejunkie** [comment]
This most definitely works. Make sure you do not have any stale assembly files lurking in your bin folder(s) (manually delete them, no not rely on a clean operation).
