### ISSUE TITLE
Two instances of singleton created by TinyIoCContainer

### ISSUE THREAD

**Issue by alexreg** [NancyFx/Nancy#2805]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
If I register an interface & concrete type in a `TinyIoCContainer` before Nancy boots up (custom bootstrapper), then a new instance is created when resolving.

### Steps to Reproduce
See above.

### System Configuration
Mac OS X 10.3, Mono 5.2

- Nancy version: latest
- Nancy host
  - [ ] Nancy.Hosting.Aspnet
  - [ ] Nancy.Hosting.Self
  - [x] Nancy.Owin (Katana self-hosting, i.e. HttpListener)
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by khellang** [comment]
Where are you registering this? Can you show the code?

**Comment by alexreg** [comment]
The code base is quite large, and proprietary, I'm afraid... I am registering some IoC types in my `Startup` class, however. Anything else you need to know?

**Comment by davidallyoung** [comment]
If you are calling base.GetApplicationContainer after you do your registrations you are overwriting your registrations with the auto wiring on the DefaultNancyBootstrapper. This is just a guess as to what could be going on since there's no code to go off of ;) . Maybe a small sample that mimics what is going on would be appropriate?

Here are some bits about the DefaultNancyBootstrapper and some "do's don'ts" https://stackoverflow.com/a/9572032/3874503

**Comment by khellang** [comment]
> Anything else you need to know?

You're not giving us much to work with. `Startup` class? That doesn't have anything to do with the Nancy bootstrapper?

> If I register an interface & concrete type in a `TinyIoCContainer` before Nancy boots up (custom bootstrapper), then a new instance is created when resolving.

This is basically zero information. Where are you registering these services? Singleton per application? Singleton per request? Where are you resolving these services?

We have tons of tests and thousands of people using Nancy in production as we speak. I'm pretty sure we would hear about it if Nancy were resolving different instances for services registered as singletons. Unless you can share some code, or come up with a minimal repro, I don't think we have enough information to help you 😞

**Comment by alexreg** [comment]
@khellang I can send you portions of the code privately, perhaps. Not really at a liberty to share it publicly though.

Anyway, it's singleton-per-container I believe, since I call the `.AsSingleton()` method when registering. I'm registering on the start-up of the self-hosted Katana server, which is what the `Startup` class is for.

**Comment by thecodejunkie** [comment]
Any updates on this? If not then this issue will be closed. Thanks

**Comment by alexreg** [comment]
Ah, I missed one of the replies! Let me try something and get back to you shortly. Ta.
