### ISSUE TITLE
Slow Session? Session locked? Parallel access to Session State?

### ISSUE THREAD

**Issue by jetic83** [NancyFx/Nancy#2808]
I have a windows webserver running Nancy and Razor. The client loads hundreds of small images simultaneously which are processed on the server before sending them to the client. Each image is requested with an ajax call (basically it is an openSeadragon viewer). 

I read that ASP.net windows servers have Session locks, meaning that if a request comes, the session is locked during processing this request. Thus results in unwanted behavior that the requests are handled sequentially (slow), not in parallel (fast). See https://stackoverflow.com/questions/3629709/i-just-discovered-why-all-asp-net-websites-are-slow-and-i-am-trying-to-work-out 

I wonder if this also affects Nancy Sessions which I use to save image related data for the user. If so, is there a similar option like `<% @Page EnableSessionState="False" %>` which can prevent the session lock when there is only read access?

**Comment by khellang** [comment]
What kind of sessions are you using? Nancy ships with `CookieBaseSessions`, which stores the user session in a cookie. There's no locking involved here. The cookie is simply read from the request and deserialized into a session object.

**Comment by jetic83** [comment]
Thank you, @khellang . 

I am using `MemoryCacheBasedSession` from https://github.com/bernos/Nancy.MemoryCacheBasedSessions/tree/master/Nancy.MemoryCacheBasedSessions, since I have several non-serializable objects and I feel that it is faster to get everything from cache than from the client's cookie.

I have a few routes which should be as fast as possible and which actually rely on two Session variables which I could also put into the App's cache. I wonder if this would be faster.

**Comment by thecodejunkie** [comment]
@jetic83 for support on the `MemoryCacheBasedSession` implementation, you need to reach out to that author

thanks
