### ISSUE TITLE
CSRF Token Validation Fails with Load Balanced servers and StatelessAuthentication

### ISSUE THREAD

**Issue by bytemaestro** [NancyFx/Nancy#2811]
I have an OWIN self hosted Nancy site that I need to put scale out, so I tried load balancing the URL with 2 servers, and as soon as I put up the second server, I got the CSRF validation/forgery error.

I was reading in the docs, on how to add the CrytpoConfiguration to the Forms Auth, however I am using StatelessAuthentication. Half the site is an JSON rest API, and the other half serves up views.

I also tried adding the CrytpoConfiguration to the CSRF.Enable method. I see in the Nancy code that this has been added, but is this supposed to be for load balancing?
```

protected override void ApplicationStartup(IKernel container, IPipelines pipelines)
        {
            base.ApplicationStartup(container, pipelines);
            Csrf.Enable(pipelines); //tried Csrf.Enable(pipelines, crytoConfig); didn't work
             StatelessAuthentication.Enable(pipelines, GetStatelessAuthenticationConfiguration(container));
```

Is this a bug with CSRF.Enable, or I am just doing something wrong?

**Comment by thecodejunkie** [comment]
Please refer to https://github.com/NancyFx/Nancy/issues/1405#issuecomment-340922538
