### ISSUE TITLE
Injecting one instance per request.

### ISSUE THREAD

**Issue by MamboJoel** [NancyFx/Nancy#2813]
Hello,

We use TinyIoC and we would like to know what is the best practice to register a single implementation for multiple types per request. For instance :
```c#
    public interface A { }
    public interface B { }
    public class C : A, B { }

    public class SomeModule {
        public SomeModule(A A) {}
    }

    public class SomeService
    {
        public SomeService(B B) { }
    }
```
During the lifetime of the request we'd like to be sure `C` is instantiated only once and passed to `SomeModule` and to `SomeService`.

Thanks !

**Comment by thecodejunkie** [comment]
@MamboJoel have a look at the TinyIoC documentation for `Registration and Lifetimes` https://github.com/grumpydev/TinyIoC/wiki/Registration---lifetimes#lifetimes by default, dependencies concrete classes will be resolved as multi-instance

**Comment by MamboJoel** [comment]
@thecodejunkie you're gold.
