### ISSUE TITLE
DefaultStatusCodeHandlerResult has no default constructor, and the default XML serialiser can't serialise it

### ISSUE THREAD

**Issue by JoeStead** [NancyFx/Nancy#2817]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Because `DefaultStatusCodeHandlerResult` has no default constructor, the XML serialiser cannot serialise it. This results in responses looking like:

```
> HTTP/1.1 404 Not Found
> Date: Thu, 02 Nov 2017 10:08:44 GMT
> Content-Type: application/xml
> Server: Kestrel
> Transfer-Encoding: chunked
> Vary: Accept

Nancy.ErrorHandling.DefaultStatusCodeHandler.DefaultStatusCodeHandlerResult cannot be serialized because it does not have a parameterless constructor.%
```

The content type is set to `application/xml`, and the body is the serialisation error, breaking clients.

I can think of two fixes:

1. Add a default constructor to `DefaultStatusCodeHandlerResult` and make the setters public and find any other classes which will face the same problem
2. Change the default XML Deserialiser to something that will handle this. Even with that change, it can still break if someone overrides the serialiser themselves

### Steps to Reproduce
A full repro is in this gist: https://gist.github.com/JoeStead/520795a879cd60132a76daf2e854c607

### System Configuration

- Nancy version:
- Nancy host
  - [ ] Nancy.Hosting.Aspnet
  - [ ] Nancy.Hosting.Self
  - [x] Nancy.Owin (Kestrel)
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by youngbob** [comment]
This looks like it was broken by https://github.com/NancyFx/Nancy/pull/2081/commits/7a050c01590a2d33e980a9326348886551c8c1c1
A simple revert of that commit should fix it
