### ISSUE TITLE
Ambiguous 'Get' overloads when used from F# to return Task<T>

### ISSUE THREAD

**Issue by Zaid-Ajaj** [NancyFx/Nancy#2818]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am unable to return a task result (`Task<T>`) from a Nancy module Get handler as the compiler cannot determine which overload to use: 
```
A unique overload for method 'Get' could not be determined based on type information prior to this program point. A type annotation may be needed. Candidates: NancyModule.Get<'T>(path: string, action: Func<obj,'T>,?condition: Func<NancyContext,bool>,?name: string) : unit, NancyModule.Get<'T>(path: string, action: Func<obj,Task<'T>>,?condition: Func<NancyContext,bool>,?name: string) : unit
```

So ambiguity is happening between:
 - `Func<object, T>`
 - `Func<object, Task<T>>`
 
Which is a common problem F# encounters with C# API's
```fs
type Home() as self = 
    inherit NancyModule()
    do 
        self.Get("/home", fun _ -> "This works as expected")
        self.Get("/", fun _ -> Task.FromResult("Doesn't work :("))
```
### Possible solution
Add an explicit `Get` handler (and others) named `GetAsync` that expects the `action` parameter to be `Func<object, Task<T>>`

### Steps to Reproduce
 - Create a self-hosted nancy project in F# using dotnet `dotnet new console --language F#"
 - Add nuget packages:
   - `Nancy: 2.0.0-clinteastwood` 
   - `Nancy.Hosting.Self: 2.0.0-clinteastwood`

```fs
// App.fs
module App

open Nancy
open Nancy.Hosting.Self

open System
open System.Threading.Tasks

type Home() as self = 
    inherit NancyModule()
    do 
        self.Get("/home", fun _ -> "This works as expected")
        self.Get("/", fun _ -> Task.FromResult("Doesn't work :("))

[<EntryPoint>]
let main argv =
    let hostConfig = HostConfiguration()
    hostConfig.RewriteLocalhost <- false
    use host = new NancyHost(hostConfig, Uri("http://localhost:8080"))
    host.Start()
    printfn "Server running at http://localhost:8080"
    Console.ReadKey() |> ignore
    0
```

### System Configuration
- Nancy version: 2.0.0-clinteastwood
- Nancy host
  - [ ] Nancy.Hosting.Aspnet
  - [x] Nancy.Hosting.Self
  - [ ] Nancy.Owin ()
  - [ ] Other:
- Other Nancy packages and versions: Nancy.Hosting.Self 2.0.0-clinteastwood
- Environment (Operating system, version and so on): Lubuntu (Ubuntu variant) 17.10 latest
- .NET Framework version: dotnet 2.0.2

**Comment by thecodejunkie** [comment]
Hi

We have no immediate plans on supporting `xxxAsync` method overloads. If you need this then you can always create you own module base class and provide the necessary methods

Thanks
