### ISSUE TITLE
PUT and DELETE do not work when route has more than 3 "/"'s

### ISSUE THREAD

**Issue by generik0** [NancyFx/Nancy#2820]
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
If i have a route in my application called e.g.
https://localhost/api/Foo/Bar/ then GET, POST, DELETE and PUT work.
But if i have
https://localhost/api/Foo/Bar/Something then GET, POST work**, DELETE and PUT does not work.**
If i look at teh "ROUTES" property, all the routes are correct...

Is this expected behaviour = ?

### Steps to Reproduce
*Make an Nancy module with the route:
Put["/Foo/Bar/Put1"] = _ => DoSomething();
DELETE["/Foo/Bar/Delete1] = _ => DoSomething();

and they will not be called. Buut get and post will.

### System Configuration
ASP.NET MVC5, with OWIN and Cookies auth.

- Nancy version: 1.4.4
- Nancy host
  - [ ] Nancy.Hosting.Aspnet
  - [ ] Nancy.Hosting.Self
  - [x] Nancy.Owin (System.Web)
  - [ ] Other:
- Other Nancy packages and versions: Nancy.Bootstrappers.Autofac(1.4.1), Nancy.MSOwinSecurity(2.0.0) 
- Environment (Operating system, version and so on): Win 10
- .NET Framework version: 4.7

**Comment by generik0** [comment]
Great xt0rted... i was missing builder.UseStageMarker(PipelineStage.MapHandler); !!!

**Comment by xt0rted** [comment]
In my project this works with the same packages and .NET 4.6.2.

Nancy is set up like so
```csharp
app.Map("/api", builder =>
{
    builder.UseNancy(options =>
    {
        // ...
    });
    builder.UseStageMarker(PipelineStage.MapHandler);
});
```

One of my async `DELETE` routes is
```
/api/transaction/123/horseprofile/videolink/456
```

`/api` is from the owin mapping
`/transaction/{id:int}/horseprofile` is the module path
`/videolink/{videoId:int}` is the route itself

**Comment by generik0** [comment]
Dammit. The "builder.UseStageMarker(PipelineStage.MapHandler);" did help the routing. But then it messes up the session for the http context.
I am using redis session based cache, and adding:
`
app.Use((context, next) =>
            {
                var httpContext = context.Get<HttpContextBase>(typeof(HttpContextBase).FullName);
                httpContext.SetSessionStateBehavior(SessionStateBehavior.Required);
                return next();
            });
`
Allowed the session to be available in Nancy HttpContextBase from the GetOwinEnviroement.

But this no longer works after adding the UseStageMarker to the Map.
Before i had the UseStageMarker on the App and this works fine., but the PUT and DELETE do not work with paths that have more than 3 "/"'s.

Any ideas?

**Comment by khellang** [comment]
Have you tried adding a second stage marker after Nancy to make sure it runs after the session state has been aquired?

See https://docs.microsoft.com/en-us/aspnet/aspnet/overview/owin-and-katana/owin-middleware-in-the-iis-integrated-pipeline

Something like this:

```csharp
app.Use((context, next) =>
{
    var httpContext = context.Get<HttpContextBase>(typeof(HttpContextBase).FullName);
    httpContext.SetSessionStateBehavior(SessionStateBehavior.Required);
    return next();
});

app.UseStageMarker(PipelineStage.MapHandler);

app.UseNancy();

app.UseStageMarker(PipelineStage.PostAcquireState);
```

**Comment by generik0** [comment]
Hi k
Thats really great, thanks!
I will try first thing tomorrow. The interesting thing is the “UseNancy()” and stage is in the Map. It needs to be otherwise the mvc site doesn’t work.

Still I will see if it helps :-)

**Comment by generik0** [comment]
Hi Again
I have now tried all the combinations i could think off.
I have had the SetSessionStateBehavior inside of the branch and out side of it. 

The rule is always this. If i do **not** have:
`branch.UseStageMarker(PipelineStage.MapHandler);` then the PUT and DELETE do **not** work when there is .e.g api/foo/bar/something. But do work when the address is api/foo/bar., The GET and POST always work. However the Session does resolve. 

If i do have `branch.UseStageMarker(PipelineStage.MapHandler);`  then the PUT and DELETE alone with GET and POST work for all paths,  However the Session does **not** resolve. 


I have even tried to specify this mush (inluding combinations with and without the UseStageMarker.
The Barnch MUST have a `branch.UseStageMarker(PipelineStage.MapHandler);` otherwise it does note resolve for the 3 "/"'s in PUT and DELETE:

It is very weird that the GET and POST work, but not the PUT and DELETE!...

`
app.Use((context, next) =>
            {
                var httpContext = context.Get<HttpContextBase>(typeof(HttpContextBase).FullName);
                httpContext.SetSessionStateBehavior(SessionStateBehavior.Required);
                return next();
            });
            app.UseStageMarker(PipelineStage.MapHandler);
            app.Map("/api", branch =>
            {
                branch.UseStageMarker(PipelineStage.MapHandler);
                branch.UseNancy(options =>
                {
                    options.Bootstrapper  = new ApiBootstrapper(container);
                    options.PerformPassThrough = context => context.Response.StatusCode == HttpStatusCode.NotFound;
                });
                branch.UseStageMarker(PipelineStage.PostAcquireState);
            });
            app.UseStageMarker(PipelineStage.PostAcquireState );
`

**Comment by generik0** [comment]
Funny. I have even tried with and all paths work, but not httpcontextbase session:

`app.Use((context, next) =>
            {
                var httpContext = context.Get<HttpContextBase>(typeof(HttpContextBase).FullName);
                httpContext.SetSessionStateBehavior(SessionStateBehavior.Required);
                return next();
            });
            app.Map("/api", branch =>
            {
                branch.UseNancy(options =>
                {
                    options.Bootstrapper  = new ApiBootstrapper(container);
                    options.PerformPassThrough = context => context.Response.StatusCode == HttpStatusCode.NotFound;
                });
                app.UseStageMarker(PipelineStage.MapHandler);
                
            });`

However the sessions work here, but not the PUT and DELETE paths api/foo/bar/something

`app.Use((context, next) =>
            {
                var httpContext = context.Get<HttpContextBase>(typeof(HttpContextBase).FullName);
                httpContext.SetSessionStateBehavior(SessionStateBehavior.Required);
                return next();
            });
            app.Map("/api", branch =>
            {
                branch.UseNancy(options =>
                {
                    options.Bootstrapper  = new ApiBootstrapper(container);
                    options.PerformPassThrough = context => context.Response.StatusCode == HttpStatusCode.NotFound;
                });
            });
            app.UseStageMarker(PipelineStage.MapHandler);`

**Comment by khellang** [comment]
Hmm. This sounds like an IIS issue. PUT and DELETE not working is a classic WebDAV issue. See https://stackoverflow.com/a/29885790/682105:

```xml
<modules>
  <remove name="WebDAVModule"/>
</modules>
<handlers>
  <remove name="WebDAV" />
</handlers>
```

**Comment by generik0** [comment]
I can try it, but WebDAV is not enabled.
And the DELETE and PUT do work. Only not with to many ´ssgments in the route. GET and POST do not have the Segment issue...

**Comment by generik0** [comment]
Sorry.
No cigar. No luck.

This is still the only way the session works but the POST and DELETE with "many" segments do not work.
![image](https://user-images.githubusercontent.com/2411563/32496251-e73c9134-c3c8-11e7-89ab-cf60bc43f974.png)


The question is would then be. Why does GET and POST work, but not PUT and DELETE.
It there a bug in this.
Or is there a issue in the httpcontext session resolving with the branch owin context.

I think the next step is for me to make a bare minimum project that replicates.

**Comment by khellang** [comment]
> I think the next step is for me to make a bare minimum project that replicates.

Yes, that would be awesome.

> The question is would then be. Why does GET and POST work, but not PUT and DELETE.
> It there a bug in this.

There should be absolutely no limit to how many "segments" you can have, or any connection between the route's segments and the HTTP method. At least not in Nancy.

You mentioned

> and they will not be called. Buut get and post will.

Does that mean you've set breakpoints and verified that they're not called? What's the response you get back?
It sounds an awful lot like IIS is snatching the requests before they reach Nancy, because there's no special handling of PUT or DELETE in Nancy.

**Comment by generik0** [comment]
Hi

I have put breakpoints in the Module with the route. The get, post, put and delete are in the same module. This is where i can see that the get and post gets called, but not the put/delete.

I can also see in the browser console that a 404 is returned..

I can’t see that the IIS is snatching the app has a map for /api/ goes to Nancy and I think the Nancy passthrough on the app mapping is returning the 404.

I will make sure when I make the test solution.
Please give me to the weekend... I have to finish some other stuff first....

**Comment by generik0** [comment]
Hej Kristian. Håber alt er vel :-)

I have made a very simple autofac, nancy mvc5 project with OWIN. I began adding a inproc session, but when i span the application up the get and post work, but not the delete and put.

Maybe this should be the focus, and then the session stuff as part 2.? Tehh nancy module is in the class Module1.
I have used the chrome arc app for rest testing. 
As stated all the GET and POSTs work, buit none of the DELETE and PUT work.
Have i done something completely silly/wrong?

Thanks for your time

[AutofacOwinNancy.zip](https://github.com/NancyFx/Nancy/files/1464485/AutofacOwinNancy.zip)

**Comment by thecodejunkie** [comment]
Nancy does not handle `DELETE` or `PUT` any differently than `GET` or `POST`. There's especially no artificial limitations imposed by Nancy on the number of route segments you can use with those two verbs.

Like @khellang mentioned https://github.com/NancyFx/Nancy/issues/2820#issuecomment-342415875 this is a web server thing (evident by the fact that you are getting an IIS error page and not a Nancy error page)

I took your sample, added this solution https://forums.asp.net/t/1961593.aspx?DELETE+PUT+verbs+result+in+404+Not+Found+in+WebAPI+only+when+running+locally and I can run the `DELETE` and `PUT` routes without any problems

![image](https://user-images.githubusercontent.com/50543/32700854-56dc7332-c7cb-11e7-90d4-02ef9f3ff329.png)

I'll close this now. I consider this to be done and not related to Nancy

Thanks

**Comment by generik0** [comment]
Thanks. It did the trick!

  <system.webServer>
    <validation validateIntegratedModeConfiguration="false" />
    <handlers>
      <remove name="ExtensionlessUrlHandler-ISAPI-4.0_32bit" />
      <remove name="ExtensionlessUrlHandler-ISAPI-4.0_64bit" />
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <add name="ExtensionlessUrlHandler-ISAPI-4.0_32bit" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" modules="IsapiModule" scriptProcessor="%windir%\Microsoft.NET\Framework\v4.0.30319\aspnet_isapi.dll" preCondition="classicMode,runtimeVersionv4.0,bitness32" responseBufferLimit="0" />
      <add name="ExtensionlessUrlHandler-ISAPI-4.0_64bit" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" modules="IsapiModule" scriptProcessor="%windir%\Microsoft.NET\Framework64\v4.0.30319\aspnet_isapi.dll" preCondition="classicMode,runtimeVersionv4.0,bitness64" responseBufferLimit="0" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
    </handlers>
  </system.webServer>
