### ISSUE TITLE
Why does Nancy.Authentication.Forms Enable per module trigger RequiresAuthentication for the whole module?

### ISSUE THREAD

**Issue by jetic83** [NancyFx/Nancy#2825]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported. 

### Description

When you enable Nancy.Authentication.Forms for individual modules, the whole module is automatically set module.RequiresAuthentication(). 

Is there a reason for that? 

I want to switch on Authentication only for specific modules, but require authentication only for specific routes. 

Other modules should be free of authentication at all. 

The line 

    module.RequiresAuthentication()

forces all routes to be authenticated, which is especially questionable if the login module should use (but not require) Authentication. 

### System Configuration

- Nancy version:
- Nancy host
  - [ ] Nancy.Hosting.Aspnet
  - [ ] Nancy.Hosting.Self
  - [ ] Nancy.Owin ()
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by thecodejunkie** [comment]
You are scoping your authentication for the entire module. If you need per-route scoping then you can put the `RequiresAuthentication()` in your routes or split your routes across multiple modules
