### ISSUE TITLE
Static content in virtual directory does not work (404 Error)

### ISSUE THREAD

**Issue by jetic83** [NancyFx/Nancy#2827]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I have a Nancy Webservice on a IIS 8 webserver. On the server, the website lies in `c:\inetpub\wwwroot\`. Also, there is a subfolder `\Content` with static content (js, css, img, ...).

Due to space constraints, I want to put parts of my static content to the d drive: `d:\inetpubd\wwwroot\`. 

Therefore, I added a virtual directory to the website in IIS mapping `d` to `d:\inetpubd\wwwroot\` (I haven't added the virtual directory in my Visual Studio project since I don't know how to do that).

This works partly fine, e.g. when I use `HttpContext.Current.Server.MapPath("~/d/file.html")`, I get correctly the string `d:\inetpubd\wwwroot\file.html`. Also, I can read this file with File.ReadAllText().

What does not work is to include this virtual folder as a static content folder. For that, I would do in the bootstrapper:

    protected override void ConfigureConventions(NancyConventions conv)
    {
        base.ConfigureConventions(conv);
        // static folders
        conv.StaticContentsConventions.Add(StaticContentConventionBuilder.AddDirectory("/d"));
    }

I would now expect to access e.g. the file `http://webpage.net/d/file.html` and get it returned as a static file. But I get a 404 Error File Not Found.

How can I include virtual directories outside of the webpage source folder in Nancy? What did I overlook?

Note that the file `file.html` is not available during compile time, but during runtime. I think this should not make a difference.

**Comment by grumpydev** [comment]
Nancy's static content stuff works with physical files and folders, so it won't support IIS's "virtual paths" as they are purely an IIS request->file mapping thing. There's two ways I can think of for you to get around this, either disable Nancy for the static content path you're using, and allow IIS to manage it (you can see examples of adding modules/removing modules and specifying paths in the docs here: https://github.com/NancyFx/Nancy/wiki/Hosting-Nancy-with-asp.net, you basically want to remove nancy from that specific path), or create a symbolic link/junction point using MKLINK to create a "physical file system" connection between c:\inetpub\wwwroot\content to d:\inetpub\wwwroot\content.
