### ISSUE TITLE
Disable TinyIoC AutoRegister

### ISSUE THREAD

**Issue by MamboJoel** [NancyFx/Nancy#2835]
In a small project we noticed a hit in performance using Nancy. Visual Studio's analyse suggests TinyIoC `AutoRegister` as a possible reason for that :

![image](https://user-images.githubusercontent.com/3832009/33908341-62b32866-df88-11e7-9810-088a090a3909.png)

In our custom Bootstrapper we registered our types one by one so we're suprised `AutoRegister` is ever called.

Is there a way to disable TinyIoC's auto registration? And presumably expect a resolving exception ?

Thanks !

**Comment by khellang** [comment]
See [the wiki](https://github.com/NancyFx/Nancy/wiki/Bootstrapping-nancy):

> If you don't want to take advantage of the "AutoRegister" feature you can take control of adding dependencies into the container by overriding one or both of the following methods:
> - ConfigureApplicationContainer - This is called once, when the Bootstrapper is executed, and is used to register dependencies that you either wish to have application scope lifetimes (application singletons), or be registered as multi-instance:
> - ConfigureRequestContainer - This is called once per request, before the module matching the route is resolved, and is used to register singletons that will have request lifetime.

And further down:
> - The default Nancy bootstrapper will "autoregister" everything it can in its default implementation of ConfigureApplicationContainer.
> - By calling "base" after you've made a manual registration you are effectively copying over your original registration by autoregister. Either don't call base, or call it before you do your manual registrations.

Basically, remove calls to `base.ConfigureApplicationContainer(container)` :smile:
