### ISSUE TITLE
How can I get a real client IP address? 

### ISSUE THREAD

**Issue by sx212** [NancyFx/Nancy#2837]
use this. Request.UserHostAddress get the IP is not correct, in the case of agent. 
use this.Request.Headers["HTTP_X_FORWARDED_FOR"] get the IP is empty. 
use this.Request.Headers["X_FORWARDED_FOR"] get the IP is empty.

**Comment by khellang** [comment]
Why did you remove everything from the issue template? Which host are you running? What versions are you using? Are run behind a reverse proxy? What does "in the case of agent" mean?

**Comment by sx212** [comment]
@khellang 
sorry for remove the template.
I use "Nancy.Hosting.Aspnet" as the host in version 1.41.   I want to get client IP of browser. 
this client is inner network, use internet call my Nancy REST API service. 
I want to get the client IP. but get result is empty.

**Comment by khellang** [comment]
> this client is inner network, use internet call my Nancy REST API service.

What does this mean? Are you saying that the client is calling your API through a reverse proxy?

Nancy only pulls the "client IP" from the undelying host, i.e. [`HttpContext.Request.UserHostAddress`](https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Hosting.Aspnet/NancyHandler.cs#L88). If the connection IP is not from the "real client", you need to handle this yourself.

This is usually solved by having the proxy add an `X-Real-IP` or [`X-Forwarded-For` header](https://en.wikipedia.org/wiki/X-Forwarded-For).
