### ISSUE TITLE
Question - Nancy Module multiple constructors

### ISSUE THREAD

**Issue by klym1** [NancyFx/Nancy#2838]
Hi. I haven't found solution in the documentation, so here I write my question. Basically, in my code I want to do something like this:

```
public class ProductsModule : NancyModule
{
    public ProductsModule(Service1 dep1)
    {
        Get["/products"] = _ =>
        {
            return dep1.Result;
        };
    }

    public ProductsModule(Service2 dep2)
    {
        Get["/tasks"] = _ =>
        {
            return dep2.Result;
        };
    }
}
```
Generally I would like to have ability to declare multiple constructor overloads in a Nancy Module with different dependencies injected and have different paths configured for each constructor.

But it has turned out that Nancy registers paths, defined only in one particular constructor overload (skipping the others). It would be very convenient for me to pass different dependencies through different constructor overloads and register handlers for them, instead of having single constructor with multiple dependencies specified. Is that possible somehow? If not - why such limitation exists? Sorry If similar question has been asked before.

**Comment by khellang** [comment]
Sounds like you need multiple modules, not multiple constructors :wink:

**Comment by klym1** [comment]
Yeah, that's possible solution too, but all my services are logically related to the same domain, e.g. Service1 returns Entity details, Service2 returns some statistics etc. So I would like to have them in the same module.

**Comment by thecodejunkie** [comment]
How on earth would Nancy know which ctor to use for which route? There is no way to get any kind of "constructor context" when you declare a route. 

You have two options here

1. Split it into multiple modules
2. Keep a single module, but take in a `ServiceFactory` kind of dependency that will give you a `Service1` or `Service2` dependency. This assumes `Service1` and `Service2` share a common base (like a class or interface) or the factory concept fails

hope this helps
