### ISSUE TITLE
AmbiguousViewException between x.cshtml & x.layout.cshtml

### ISSUE THREAD

**Issue by desertrats** [NancyFx/Nancy#2840]
### Prerequisites
- [* ] I have written a descriptive issue title
- [* ] I have verified that I am running the latest version of Nancy
- [* ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [* ] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I'm not sure if it is a bug. I didn't write anything in English for almost 5 years, I hope I won't offend anyone for my poor English.... also I`m not really a pro, just a molecule biologist who is trying to write his own website, so maybe this is not a real bug...

### Steps to Reproduce

Here is what I have done:

Create a class called `SubViewRenderer`:
```
using Nancy.ViewEngines.Razor;
namespace XW.Component
{
    public static class SubViewRenderer
    {
        public static IHtmlString DisplaySearchResult(HtmlHelpers htmlHelper, dynamic data)
        {            
            return htmlHelper.Partial(@"/Gadget/ProductSearchListInfo", data);
        }
   }
}
```
Create two file:  `ProductSearchListInfo.cshtml` and `ProductSearchListInfo.layout.cshtml`

Create a Module inherit from `NancyModule`
Code1:
```
return View["Gadget/ProductSearchListInfo", Model];
```

result:
every thing is fine

Change Code1 to
```
return View["test", Model];
```
In `test.cshtml` write:

```
@using XW.Component;

@SubViewRenderer.DisplaySearchResult(Html,Model)
```

get the AmbiguousViewException

![bug](https://user-images.githubusercontent.com/6656054/34291909-86e321f6-e739-11e7-89c3-4f5f0b651f3e.png)

change `ProductSearchListInfo.layout.cshtml` to `ProductSearchListInfo_layout.cshtml` everything is fine again...

### System Configuration

- Nancy version: v1.4.4 from nuget
- Nancy host
  - [ ] Nancy.Hosting.Aspnet
  - [* ] Nancy.Hosting.Self
  - [ ] Nancy.Owin ()
  - [ ] Other:
- Other Nancy packages and versions:
 nancy.Hosting.Self v1.4.1 
nancy.owin v1.4.1
nancy.serialization.jsonnet v1.4.1
nancy.viewengines.razor v1.4.3
- Environment (Operating system, version and so on): win10
- .NET Framework version: v4.5
- Additional information:

**Comment by thecodejunkie** [comment]
This is because Nancy will think `.layout` is a file extension and will strip it out when it builds a list of views. I would recommend you use another naming convention, like using an underscore (like you have) or a hyphen.

Thanks
