### ISSUE TITLE
Unable to generate routes dynamically at runtime

### ISSUE THREAD

**Issue by Zaid-Ajaj** [NancyFx/Nancy#2842]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Using latest Nancy (2.0-clinteastwood), I am unable to dynamically create routes as I was able to do using Nancy 1.4.*  

### Steps to Reproduce
Given the following module: 
```cs
public class Home : NancyModule 
{
    public Home()
    {

         if (Config.GlobalStaticFlag) 
         {
             for(int i = 1; i <= 5; i++) 
             {
                  var route = $"/number{i}";
                  var result = i.ToString();
                  Get(route, args => result);
             }
             
             Config.GlobalStaticFlag = false;

         }
    }
}
```
When navigating to `/number1` I get the `500 - Internal Server Error`:
```
Nancy.RequestExecutionException: Oh noes! ---< System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Nancy.Routing.DefaultRouteResolver.BuildResult(NancyContext context, MatchResult result)
   at Nancy.Routing.DefaultRequestDispatcher.>Dispatch<d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.NancyEngine.>InvokeRequestLifeCycle<d__22.MoveNext()
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)
```
### Why
I am upgrading my RPC library [Cable](https://github.com/Zaid-Ajaj/Cable) where I generate routes automatically for a service that can be called from a [Bridge.NET](https://github.com/bridgedotnet/Bridge) client directly for type-safe communication. 

### System Configuration

- Nancy version: 2.0-clinteastwood
- Nancy host
  - [ ] Nancy.Hosting.Aspnet
  - [x] Nancy.Hosting.Self
  - [ ] Nancy.Owin ()
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on): Ubuntu 16.04
- .NET Framework version: `dotnet --version` // 2.0.2
- Additional information:

**Comment by thecodejunkie** [comment]
I just ran your example (without the `GlobalStaticFlag`) and it "works". 

You cannot wrap the registration in an `if`-statement. If you do then the route declaration will not live on the module instance during execution, only during route discovery at startup

Hope this helps!
