### ISSUE TITLE
Is it possible to run Nancy inside a windows service application?

### ISSUE THREAD

**Issue by acrolink** [NancyFx/Nancy#2843]
I mean to define a module and run a web server inside a windows service solution. Is that possible?

**Comment by klym1** [comment]
We did that in our project by using Nancy+Topshelf. Works pretty much well.

**Comment by thecodejunkie** [comment]
Yep. Nancy doesn't care where it is hosted. It's just a simple class that you pass in an `NancyRequest` into and get a `NancyResponse` back. How you listen to requests are really up to you. You could use the Self-Host, Kestrel or perhaps a raw socket, it's up to you.
