### ISSUE TITLE
NancyModules not found/loaded if Nancy 2.0 started from ClassLibrary

### ISSUE THREAD

**Issue by Flying--Dutchman** [NancyFx/Nancy#2844]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I have multiple NanyModules in a ClassLibrary which are not loaded (getting 404 when calling the defined routes).
The Nancy and Nancy.Hosting.Self are referenced in that assembly and hosting is started there.

This assembly is called from another ClassLibrary which is called from an ASP.NetCore WebApplication.
The usage of [assembly: IncludeInNancyAssemblyScanning] does not help.

### Steps to Reproduce

ASP.NetCore WebApplication --> ClassLibrary A NetCore --> ClassLibrary B NetCore containing Nancy and Nancy.Hosting.Self references.

WebApplication loads ClassLibrary A which then, with the use of an interface, starts Nancy.Hosting.Self  in ClassLibrary B.

The defined routes are not beeing called and i'm getting 404 errors in my browser.

### System Configuration

- Nancy version: 2.0.0
- Nancy host
  - [ ] Nancy.Hosting.Aspnet
  - [x] Nancy.Hosting.Self
  - [ ] Nancy.Owin ()
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on): Windows 10 1709 64-Bit
- .NET Framework version: 2.1.2
- Additional information:

**Comment by thecodejunkie** [comment]
Unfortunately this is the linker trying to be smart and hides removes the reference, to your class library, since it thinks you are not using any types in it. What you could try and do it, from your main app, try and just use one of the types in your class library with something like `var foo = typeof(YourModule);` and it should keep the reference around, even though you don't really use `foo`. Bit of a hack, but it's the best you can do atm 😢 

hope this helps

**Comment by Flying--Dutchman** [comment]
Thank you for your help. It seems to work now. 👍 

But still, this is not a desired solution. My ClassLibraries should be optional. So I would like to not have any reference to it. Any assembly is found during startup, in a specific folder. 

Is there any posibility to provide NancyFX with assemblies to scan for Modules, or to pass these modules manually?

Thx in advance

**Comment by steve2** [comment]
Would also like to know more regarding @Flying--Dutchman's question. I was under the impression that I could supply classes explicitly with a custom Bootstrapper; I have a custom Bootstrapper being used that registers my `NancyModule` types explicitly but the registered type's constructor is never called.

**Comment by Flying--Dutchman** [comment]
As a workaround you can call a function in CustomModule which reads all the API-Calls which needs to be registered, and register them in CustomModule.
