### ISSUE TITLE
Nancy.Hosting.Self - friendly assembly public key error

### ISSUE THREAD

**Issue by oykutozlu** [NancyFx/Nancy#2857]
### Prerequisites

- I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of Nancy
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I use NancyHost in my .Net application and .Net framework version is 4.0. We do not get this error if .Net Framework 4.5 is installed. When this line is executed;
      NancyHost.Start();
 we get this exception;
    **Message: 
C:\...\Nancy.dll] Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations.
CallStack:
   at Nemesis.Agent.Core.Bootstrapper.ApplicationStartup(TinyIoCContainer container, IPipelines pipelines)
   at Nancy.Bootstrapper.NancyBootstrapperBase`1.Initialise()
   at Nancy.Hosting.Self.NancyHost..ctor(INancyBootstrapper bootstrapper, HostConfiguration configuration, Uri[] baseUris)
   at Nancy.Hosting.Self.NancyHost..ctor(HostConfiguration configuration, Uri[] baseUris)**

### System Configuration

.Net framework 4.0
Windows 10, Windows Embedded Standard 7

- Nancy version: 1.4.2.0
- Nancy host
  - [ ] Nancy.Hosting.Aspnet
  - Nancy.Hosting.Self
  - Nancy.Owin ()
  - [ ] Other: 
- Other Nancy packages and versions: Nancy.ViewEngines.Razor - 1.4.2.0
- Environment (Operating system, version and so on): Windows 10, Windows Embedded Standard 7
- .NET Framework version: 4.0
- Additional information:

**Comment by thecodejunkie** [comment]
I'm sorry, we're targeting .NET Framework 4.5.2 and higher. Microsoft stopped supporting .NET 4, 4.5 and 4.5.1 two years ago https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/ we have no plan on taking any steps to ensure Nancy functions correctly on anything older than 4.5.2. Sorry
