### ISSUE TITLE
How to run Nancy on .NET Core 2?

### ISSUE THREAD

**Issue by gbraad** [NancyFx/Nancy#2863]
### Description

What is needed to run Nancy on .NET Core 2.0?

I have issues with moving Kestrel and OWIN to later version, as they are dotnetstandard only ? Help would be appreciated.

**Comment by khellang** [comment]
Look at the Kestrel sample https://github.com/NancyFx/Nancy/tree/master/samples/Nancy.Demo.Hosting.Kestrel

**Comment by gbraad** [comment]
https://github.com/NancyFx/Nancy/blob/11a8609f66d851acea7acf5a6831e5046dae3db4/samples/Nancy.Demo.Hosting.Kestrel/Nancy.Demo.Hosting.Kestrel.csproj#L4

this app runs as .NET Core 1. this is the same scenario I had myself originally. however, updating the kestrel and owin libraries cause issues.

**Comment by khellang** [comment]
> this app runs as .NET Core 1

that shouldn't matter. what runs on .NET Core 1, should run on .NET Core 2.

> updating the kestrel and owin libraries cause issues

what issues? you said

> as they are dotnetstandard only

but that makes little sense. .NET Standard lets you target .NET Core 2.0 just as fine.

**Comment by gbraad** [comment]
Reinstalling the SDK from https://www.microsoft.com/net/download/visual-studio-sdks as it seems there is a conflict with some of the libraries. Closing for now...

**Comment by gbraad** [comment]
After reinstalling some dependencies and some issues with https://blogs.technet.microsoft.com/jagbal/2017/09/04/where-can-i-download-the-old-visual-c-redistributables/ I can finally build again.

**Comment by gbraad** [comment]
The project file I am using is:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web" ToolsVersion="15.0">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <DebugType>portable</DebugType>
    <AssemblyName>nancydemo</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>nancydemo</PackageId>
    <RuntimeFrameworkVersion>2.0.5</RuntimeFrameworkVersion>
    <StartupObject>NancyApplication.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Owin" Version="2.0.1" />
    <PackageReference Include="Nancy" Version="2.0.0-barneyrubble" />
  </ItemGroup>
</Project>
```

**Comment by khellang** [comment]
Awesome 😁
