### ISSUE TITLE
Nancy.Serilog- nuget - Read Request.Files - Stream it cause: Cannot access a closed file.

### ISSUE THREAD

**Issue by totpero** [NancyFx/Nancy#2865]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
https://github.com/Zaid-Ajaj/Nancy.Serilog/issues/2

### Steps to Reproduce
After i install this nuget into my project and activate serilog, i spent few hours to find what cause
Cannot access a closed file. when i try to access Request.Files and read archive Stream.

### System Configuration
ASP.MVC -framework 4.5

- Nancy version:
- Nancy host
  - [ ] Nancy.Hosting.Aspnet
  - [ ] Nancy.Hosting.Self
  - [x] Nancy.Owin (IIS)
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by khellang** [comment]
Can you post the code? I'm pretty certain something is being closed/disposed too early. Are you reading it on another thread? Or did you forget to await something inside a using block?

**Comment by totpero** [comment]
I will post sample app

**Comment by totpero** [comment]
This is demo app: [DemoNancySerilog.zip](https://www.mediafire.com/file/48j3qx6pwahs3k1/DemoNancySerilog.zip)
You can start in debug mode and put breakpoint  in HomeModule.cs on line 26 `file.Value.CopyTo(output);`
And using powershell you can run build.ps1 from project directory using cake build or you can try to post some files to http://localhost:60628/sync.

**Comment by khellang** [comment]
Can you push it to a GitHub repo. I can't/won't downlad a random zip-file from mediafire.com 😝

**Comment by totpero** [comment]
I publish this demo project to this repo: https://github.com/totpero/DemoNancySerilog

**Comment by khellang** [comment]
Hmm. There doesn't appear to be anything wrong with your code, but there's several posts out there suggesting that this is [related to ASP.NET request size limits and big files](https://forums.asp.net/t/1397944.aspx). Are you getting this error no matter how big the files are? What if you try to write to a different file every time? I could imagine there being concurrency issues when you have multiple requests coming in trying to write to the same file.

**Comment by totpero** [comment]
No matter the file size or the save location path of the file. In my real problem I try to get this file stream and unzip it into the memory an process it and if you try you get the same error. You can test this scenario if you run bulid.ps1 from PowerShell. If you uninstall serilog nancy nuget you will see that the problem will be fixed. I have also opened one issue on nancy serilog repo.

**Comment by totpero** [comment]
Hi,
I update the repo, get last version and try the next steps:

1. Build the last project version;
2. Now you have two project (nancy web server with this nuget and console app that make `WebClient UploadFile`);
3. Run nancy web project (DemoNancySerilog) in debug mode;
4. In the same time go to `DemoNancySerilog.Console\bin\Debug` and run `DemoNancySerilog.Console.exe`
5. In the same folder with DemoNancySerilog.Console.exe app you will have "test.zip" file;
6. You will get `Cannot access a closed file` error:

![errr](https://user-images.githubusercontent.com/1710257/36564889-8049fe36-1827-11e8-8914-16edfdbaafc7.png)

My investigation result:

1. If you try to upload file using curl or powershell you don't get this error;
2. If you try to upload small file you don't get this error;
3. If you uninstall `Nancy.Serilog` nuget you don't get this error even if you have large file or upload using curl;

I hope this help you.

**Comment by Zaid-Ajaj** [comment]
See my comment [here](https://github.com/Zaid-Ajaj/Nancy.Serilog/issues/2#issuecomment-367848289) 

@khellang Does reading the request stream like the following, make the stream unreadable again?
```cs
var inputStream = nancyContext.Request.Body;
using (var streamReader = new StreamReader(inputStream))
{
        var content = streamReader.ReadToEnd();
        // rewind stream to make it readable again from a Nancy module
        inputStream.Position = 0;
        return content;
}
```

**Comment by khellang** [comment]
I don't think it should. The stream is buffered, so as long as you rewind it, it should be fine. Not sure if the multipart handling for files does anything funky here.

**Comment by Zaid-Ajaj** [comment]
I am not sure either but for the issue I actually was able to reproduce the error, it is very strange, seems only to occur when using `WebClient` to upload the file (uploading with curl works fine) *and* the request body stream has been read by a stream reader from the function above. As a "fix" I disabled automatic logging of request body data if a file exists in the request because it doesn't make sense to read the files textually by default.

**Comment by khellang** [comment]
> As a "fix" I disabled automatic logging of request body data if a file exists in the request because it doesn't make sense to read the files textually by default.

Yeah, that's probably a good default anyway. I'm not sure if there's anything to do in Nancy on this issue?

**Comment by Zaid-Ajaj** [comment]
Original issue is fixed, this can be closed :smile:

**Comment by khellang** [comment]
Thanks @Zaid-Ajaj! ❤️
