### ISSUE TITLE
"Head" route not called in v2.0.0-clinteastwood

### ISSUE THREAD

**Issue by secana** [NancyFx/Nancy#2873]
### Description
If a custom route for a "Head" request is added to a Nancy module, the route is not called on a "Head" request.

> By default, HEAD requests are automatically handled for all routes that are declared for GET requests. If you want to manually handle HEAD requests, you can set StaticConfiguration.EnableHeadRouting to true and define the routes in your modules.

But I cannot find this option in the "StaticConfiguration".

### Steps to Reproduce
Route:
```
...
Head("{file*}", param => DoSomething(param.file));
...
```

Call route:
```
...
var result = await browser.Head($"{file}", with =>
            {
                with.HttpRequest();
            });
...
```

"DoSomething" is never called by the head request. The documentation states: 

### System Configuration

- Nancy version:  v2.0.0-clinteastwood
- Nancy host: Kestrel
- Environment (Operating system, version and so on): Windows 10 Enterprise 16299
- .NET Framework version: .Net Core 2.1.4

**Comment by khellang** [comment]
You should be able to enable explicit `HEAD` routing by overriding the `Configure` method in your bootstrapper:

```csharp
public override void Configure(INancyEnvironment environment)
{
    environment.Routing(explicitHeadRouting: true);
}
```

**Comment by secana** [comment]
Thx. That solved my problem.
