### ISSUE TITLE
How can I intercept all request and modify response data

### ISSUE THREAD

**Issue by 564064202** [NancyFx/Nancy#2876]
How can I intercept all request and modify response data

**Comment by Zaid-Ajaj** [comment]
See [https://github.com/NancyFx/Nancy/wiki/The-before-and-after-module-hooks](https://github.com/NancyFx/Nancy/wiki/The-before-and-after-module-hooks)

**Comment by khellang** [comment]
Yes, although those are per-module. There's also [The Application Before, After and OnError pipelines](https://github.com/NancyFx/Nancy/wiki/The-Application-Before%2C-After-and-OnError-pipelines) 😄

**Comment by 564064202** [comment]
how to modify reponse data(reponse text,binary(file)....)
