### ISSUE TITLE
I can't use resolve a class with constraint

### ISSUE THREAD

**Issue by danielmontalvoh** [NancyFx/Nancy#2877]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
**Hi, everybody!**
I try to resolve a class using container in the **AfterRequest**; that class has a method with a constraint...
Example:
~~~~
TinyIoCContainer.Current.Resolve<DummyProvider>().MyDummyMethod("My event dummy", new DummyClass(context));
~~~~
~~~~
public abstract class Dummy: IDummy
{
     public string Name { get; set; }    
}

public class DummyClass: Dummy
{
     public DummyClass(NancyContext context)
     {
          this.Name = "example"
     }

     public datetime Date { get; set; }    
}

public class DummyProvider
{
     public DummyProvider()
     {
     }

     public void MyDummyMethod<T>(string @event, T properties) where T : class, IDummy, new() => Task.Run(() => Console.Write("any action"));
}
~~~~

**But...** I get the following compilation error:
_**CS0019**	Operator '+=' cannot be applied to operands of type 'AfterPipeline' and 'lambda expression'_

Don't identify if it is a human error, but it works when I remove the constraint to method.
Example: 
~~~~
public class DummyProvider
{
     public void MyDummyMethod(string @event, object properties) => Task.Run(() => Console.Write("any action"));
}
~~~~
Any clue what I'm doing wrong?

**Thanks!!**
### System Configuration

- Nancy version: **1.4.4**
- Nancy host
  - [ ] Nancy.Hosting.Aspnet
  - [x] Nancy.Hosting.Self
  - [ ] Nancy.Owin ()
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on): Windows 7
- .NET Framework version: **4.6.1**
- Additional information:

**Comment by cloudhunter89** [comment]
Is it the constraint, or the generic parameter?

**Comment by danielmontalvoh** [comment]
Hi!
It was a human error. I was using the **new()** constraint but the concrete class hasn't a default constructor.

Tnk!
