### ISSUE TITLE
NU1701 Warning when building a project with nancy 2.0-clinteastwood

### ISSUE THREAD

**Issue by Nefarion** [NancyFx/Nancy#2882]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Using nancy in a .net core 2.1 (kestrel) project gives me a NU1701 warning. Since nancy is also available for netstandard1.6, i cannot really understand why i would get this message. Why is it restored with 4.6.1 instead of netstandard?

`warning NU1701: Package 'Nancy.Hosting.Self 2.0.0-clinteastwood' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.`

### Steps to Reproduce
- Pull nancy 2.0.0-clinteastwood into a project
- compile it
- get the warning

### System Configuration

- Nancy version: 2.0.0-clinteastwood
- Nancy host
  - [ ] Nancy.Hosting.Aspnet
  - [ ] Nancy.Hosting.Self
  - [x] Nancy.Owin (Kestrel)
  - [ ] Other:
- Other Nancy packages and versions: Nancy.Serialization.JsonNet
- Environment (Operating system, version and so on): VS2017 15.7.0
- .NET Framework version: .net core 2.1
- Additional information: also happened on netcore2.0 and previous VS2017 installations

**Comment by khellang** [comment]
Nancy.Hosting.Self will never be able to run on .NET Core. It's based on `HttpListener`, which uses Windows-specific kernel-level APIs (HTTP.SYS). If you want self-hosting on .NET Core, you shoud use ASP.NET Core (with the OWIN adapter) and Kestrel. See the Kestrel example in this repo.
