### ISSUE TITLE
Custom Diagnostics URL

### ISSUE THREAD

**Issue by turbo** [NancyFx/Nancy#2884]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Is it possible to change the path for the diagnostics dashboard? My server hosts a few different dashboard endpoints (e.g. Hangfire jobs) and I'd like to access them on custom paths (e.g. `debug/jobs`, `debug/nancy` etc).

**Comment by m-barthelemy** [comment]
Yes, it is possible.

In your NancyBootstrapper:
```
    public override void Configure(INancyEnvironment environment){
            var debug = true
            environment.Diagnostics(debug, "mypassword", "/api/v1/_MyCustomDashboardRoute");
            base.Configure(environment);
    }
```

**Comment by turbo** [comment]
Awesome, thanks.
