### ISSUE TITLE
Can't run with dotnet core 2.1

### ISSUE THREAD

**Issue by QuAzI** [NancyFx/Nancy#2894]
I install latest dotnet core on Kubuntu 18.04 but can't use Nancy because too old package required.

> error NU1605: Detected package downgrade: Microsoft.AspNetCore.Owin from 2.1.0-preview2-final to 2.0.3. Reference the package directly from the project to select a different version.

**Comment by khellang** [comment]
This is what happens if you try to use a newer package version than the one it's built against. Just do what the message says:

> Reference the package directly from the project to select a different version.
