### ISSUE TITLE
Nancy.RequestExecutionException: Oh noes! ---> Nancy.ViewEngines.ViewNotFoundException: Unable to locate view 'index'

### ISSUE THREAD

**Issue by isharehappycode** [NancyFx/Nancy#2905]
I am trying render views using Razor engine.  I am getting below error. 

Note: I am using TopShelf to self host. Does nancy has any issue with it?

> Nancy.RequestExecutionException: Oh noes! ---> Nancy.ViewEngines.ViewNotFoundException: Unable to locate view 'index'
Currently available view engine extensions: sshtml,html,htm
Locations inspected: views/Index/index-en-US,views/Index/index,Index/index-en-US,Index/index,views/index-en-US,views/index,index-en-US,index
Root path: C:\Users\deeku\Downloads\ConsoleApp1\bin\Debug

Code here: [https://www.dropbox.com/s/hifsawou2sto4zw/Simple.CRUD-master.zip?dl=0](url)

**Comment by khellang** [comment]
Do you have a file called index with one of the specified extensions in one of the specified folders?

**Comment by isharehappycode** [comment]
Yes I have all the file necessary. You can trust the files I have uploaded. I can give my contact details so that you can catch me if those files hurt you :) 

Second option is:  Can you send me a sample of Nancy code which is self hosted using TopShelf and supported Razor. That helps!

**Comment by khellang** [comment]
> Question is: Does Nancy self host support Razor view?

Yes, rendering Razor views should work no matter which host you use.

> Can you send me a sample of Nancy code which is self hosted using TopShelf and supported Razor.

That's not how this works. You can take a look at the samples in this repo, or Google Nancy and TopShelf to find countless examples of running self-hosted Nancy with TopShelf.

> Yes I have all the file necessary.

Can you post your code (on GitHub) to prove that?

Also, are you 100% sure you've read the exception message? I'm not seeing cshtml mentioned in there. What extension is your view? Can you post the absolute path to the view file?

**Comment by isharehappycode** [comment]
Thanks a lot for response and appreciated. 

I have uploaded simple clean code here: [https://github.com/isharehappycode/NancyHelp.git](url)

Basically I am trying to self host site using TopShelf and Nancy. I am very much comfortable with cshtml so added Nancy Razor view dll. But unfortunately views are not getting located.

Help appreciated, Kindly review the uploaded code.

**Comment by isharehappycode** [comment]
Can someone help?

**Comment by svenbit** [comment]
I know it's kinda late but I tried downloading the solution file that you have provided, and if you are still having issue with this problem I think you need to set the **Copy to Output Directory** property to either **Copy Always** / **Copy if Newer** and I think it also applies to any asset files such as CSS / images / JS in the Content directory otherwise the files will not be copied to the service bin directory when you debug.

![File Property](https://i.imgur.com/9eOrWrr.png)

If you want the view to be embedded you may need to customize the ViewLocationProvider from the bootstrapper.
