### ISSUE TITLE
.net core generic host and nancy

### ISSUE THREAD

**Issue by generik0** [NancyFx/Nancy#2907]
### Description
Hi. nancy is @netstandard2.0 on master. Great work. Well done!!!

Does this mean we can self host with the new "Generic Host" from ms/.net core
[Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1)
I know MS write that it is to be used for non http related code. But this reminds me of why i started with Nancy. I.e. a Topshelf console with Nancy providing rest service, self hosted. Nice and lite!

Will nancy work for the new Generic Host?

**Comment by generik0** [comment]
@khellang Any thoughts here?

**Comment by khellang** [comment]
I don't think they've bridged the gap between the generic host and the web host yet. I think it will be part of 2.2.

**Comment by generik0** [comment]
Ok. So you don’t think Nancy will be able to self host in generic host for now :-(.

**Comment by khellang** [comment]
I don't think any web framework will. Bu can't you just use the web host? We use it with Topshelf just fine.

**Comment by generik0** [comment]
Yes. Yes. I can :-)
Just looking back at the good “old” days with a console, topshelf and self-hosted Nancy. Nice and thin.

Honestly the web host is good enough with the inbuilt api to dona lot on its own...

Br Rik
