### ISSUE TITLE
Nancy can't create module when the inheriting class is generic

### ISSUE THREAD

**Issue by RensOliemans** [NancyFx/Nancy#2911]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE`
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I try to make a HomeModule that inherits from NancyModule, I get the following error `TinyIoCResolutionException: Unable to resolve type: NancyTest.HomeModule'1`, if HomeModule is generic (so `public class HomeModule<T> :  NancyModule` doesn't work).

### Steps to Reproduce
1. Create new Project.  
2. Create public class that inherits from NancyModule  
3. Make your class generic.
4. Attempt to run
5. Receive the error `TinyIoCResolutionException: Unable to resolve type: NancyTest.HomeModule'1`

### System Configuration
Windows 10 (10.0.17134), x64.

- Nancy version: `1.4.4`
- Nancy host
  - [ ] Nancy.Hosting.Aspnet
  - [x] Nancy.Hosting.Self `version 1.4.1`
  - [ ] Nancy.Owin ()
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on): `Windows 10`
- .NET Framework version: `4.5.2`
- Additional information: 
This is how the code looks:
````
public class HomeModule<T> : NancyModule
{
    private Predicate<T> predicate;
    public HomeModule(Predicate<T> predicate)
    {
        this.predicate = predicate;
    }
 
    // Nancy also doesn't like constructors with parameters, so we need to create an empty constructor
    // (even with : base() after the constructor)
    public HomeModule()
    {
        Post [""] = _ =>
        {
            T item = this.Bind<T>();
            bool succes = this.predicate(item);
            return succes ? 200 : 400;
        };
    }
}



public class Parser
{
    private HomeModule<Item> homeModule;
    
    public Parser()
    {
        this.homeModule<Item> = new HomeModule<Item>(HandleItem);
    }

    private bool HandleItem(Item item)
    {
        // do something
        return succes;
    }

    public struct Item
    {
        public int itemNumber;
    }
}
````

**Comment by khellang** [comment]
This is how .NET works; there's no way to construct a generic type without "filling in" the generic type arguments. How is Nancy supposed to know what `T` is supposed to be here?

I suggest you create a non-generic sub-type that has the generic type arguments filled in.

**Comment by khellang** [comment]
> // Nancy also doesn't like constructors with parameters, so we need to create an empty constructor

What kind of parameters are you talking about? Nancy should definitely support parameters, as long as they're services registered in your container.
