### ISSUE TITLE
AJAX JSON String Post to Nancy Function Vb.net

### ISSUE THREAD

**Issue by sourceship** [NancyFx/Nancy#2923]
Hello All, 

I have inherited a Project from another developer. Its a Web App written in VB.net and has Nancy (Not Sure what version). I have a c# background and little VB experience and never have touched Nancy.

I have a web page that allows me to paste images from a clipboard to attach them into an email. I take the images convert it to a base64 string, and put that into an js array. I was attempting to post the data into a function in my VB code but I keep on getting an empty DynamicDictionary. 

![image](https://user-images.githubusercontent.com/15806106/43974118-24169d16-9c9f-11e8-9e7d-52567729fe0d.png)

                            
![image](https://user-images.githubusercontent.com/15806106/43974146-39a71e4e-9c9f-11e8-9634-8829c3cff0d8.png)

![image](https://user-images.githubusercontent.com/15806106/43974463-4462143c-9ca0-11e8-9140-4f903902be1a.png)
I am passing it in as an Object but when I mouse over it, it shows up as a Nancy.DynamicDictionary with nothing inside. 

**How can I have this come in as the raw JSON String instead of a Nancy.DynamicDictionary?** I've tried this to no avail (Get Error 500 in chrome debugger): 
![image](https://user-images.githubusercontent.com/15806106/43974289-b3784ffe-9c9f-11e8-9947-907be5ce81cc.png)
 

Also, I apologize if this is the wrong place to ask questions, I work alone and have been staring at this for too many hours now. The room has no windows.

**Comment by khellang** [comment]
Have you looked at https://github.com/NancyFx/Nancy/wiki/Taking-a-look-at-the-DynamicDictionary and  https://github.com/NancyFx/Nancy/wiki/Model-binding?

Sorry I can't be more helpful, on the phone.

**Comment by khellang** [comment]
Just read that last part

> The room has no windows.

😂🤣

**Comment by Zaid-Ajaj** [comment]
@sourceship I am not sure what the syntax is in VB but you should not be looking into the `p` parameter because it is just the *route path* data, not the request body. In your function `CaptureFullImage` you can access `Me.Request.Body` which a `Stream` that you can read:
```vb
Dim reader as StreamReader = new StreamReader(Me.Request.Body)
Dim bodyContentAsJson as String = reader.ReadToEnd()
```
again, I am not sure the syntax is correct but I hope you get the idea

**Comment by sourceship** [comment]
@khellang  and @Zaid-Ajaj  Thank You So Much for your help!

Zaid The code you left was spot on in VB, was able to get the data from within my array. I really appreciate both of you, this was the small thing holding me up yesterday. 

Thanks again guys! Wish you all the best!
