### ISSUE TITLE
Can I host windows service using Nancy without .net framework? 

### ISSUE THREAD

**Issue by isharehappycode** [NancyFx/Nancy#2924]
Can I host windows service using Nancy without .net framework? I want to use .net core.

### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of Nancy
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### System Configuration

- Nancy version:
- Nancy host
  - [ ] Nancy.Hosting.Aspnet
  - [ ] Nancy.Hosting.Self
  - [ ] Nancy.Owin ()
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by khellang** [comment]
Sure, why not 😄

**Comment by isharehappycode** [comment]
How? I am not finding enough resources. Basically I am using .net core 2.1 and .net standard for all the libraries in my project. I want to install it as windows service and host pages at localhost for browsing. Basically trying to achieve below result using Nancy

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1

**Comment by khellang** [comment]
Have you tried going through the guide? Try after you've set it up as a Windows service, it's just a matter of hooking Nancy up in your Startup class. Look at the Kestrel sample in this repo to see how it's done.

**Comment by isharehappycode** [comment]
I have already seen Kestrel sample but it can not be hosted as windows service. I do not see "Start" and "Stop" methods or service manager class to override my functionalities

**Comment by khellang** [comment]
The one you linked; https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1

**Comment by isharehappycode** [comment]
Thank you. so if I understand currently, once I create windows service using .net core then we need to hook up Nancy. I have added Nancy.Hosting.Self nuget package , but I am getting below warning

Package 'Nancy.Hosting.Self 1.4.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.	


I am new bee to development. Is there any sample which shows hooking up Nancy to .net core 2.1 windows service?

**Comment by khellang** [comment]
> Is there any sample which shows hooking up Nancy to .net core 2.1 windows service?

No, but as I mentioned, you need to combine two resources:

1. The tutorial you mentioned above to set up a Windows service
2. The [Kestrel sample](https://github.com/NancyFx/Nancy/tree/dbdbe9428caea06c17d34a507c9216fe35abadc4/samples/Nancy.Demo.Hosting.Kestrel) in this repo.

The first will show you how to host ASP.NET Core in a Windows service, the second will show you how to hook up Nancy in your Startup class.

`Nancy.Hosting.Self` is .NET Framework only (not .NET Core). In addition to the core `Nancy` package, you need to install the following packages:

https://github.com/NancyFx/Nancy/blob/dbdbe9428caea06c17d34a507c9216fe35abadc4/samples/Nancy.Demo.Hosting.Kestrel/Nancy.Demo.Hosting.Kestrel.csproj#L16-L18

Adding Nancy to your pipeline is done like this:

https://github.com/NancyFx/Nancy/blob/dbdbe9428caea06c17d34a507c9216fe35abadc4/samples/Nancy.Demo.Hosting.Kestrel/Startup.cs#L26

**Comment by isharehappycode** [comment]
Thank you. we can close this ticket. Appreciated. I have updated my previous question. Great. Thanks

**Comment by khellang** [comment]
Awesome! Feel free to keep asking if you encounter problems 😄

**Comment by khellang** [comment]
You should be able to use https://github.com/NancyFx/Nancy.Bootstrappers.Autofac

**Comment by isharehappycode** [comment]
I have added prerelease version 

    Install-Package Nancy.Bootstrappers.Autofac -Version 2.0.0-clinteastwood

I have managed to build the application without build errors from below code but unable to get the instances. Basically how do I inject?

           protected override void ConfigureApplicationContainer(ILifetimeScope container)
           {
         
            _services.Configure<Settings>(_configuration.GetSection("MySettings"));
            var deviceId = _configuration["Settings:DeviceId"];

            var containerFactory = new ContainerFactory();
            var containerBuilder = new ContainerBuilder();

            container.Update(builder =>
            {
                builder.RegisterInstance(containerFactory).As<IContainerFactory>();
                containerBuilder.Register(c => new Engine(containerFactory));
                containerBuilder.Register(i => new HubClient(deviceId, containerFactory)).As<HubClient> ().SingleInstance();
            });
            base.ConfigureApplicationContainer(container);
        }`


But now how to I inject it in my modules?

         internal class CustomWebHostService : WebHostService
          {
             public CustomWebHostService(IWebHost host) : base(host)
            {
              _engine = host.Services              
                            .GetRequiredService<IContainerFactory>();  ? How do I get engine instance!        
            }
          }



This fails!

**Comment by isharehappycode** [comment]
I am completely blocked, as even Kestrel sample is showing just "Loading..." in page. something seems to be blocking it.
