### ISSUE TITLE
Increase Keylimit of Request Form

### ISSUE THREAD

**Issue by Sago92** [NancyFx/Nancy#2927]
Hello together,

I have a large view, with a lot of bindings. When I serialize the data and send them to the server with an AJAX request, not all keys are represent in the Request.Form. There is a limit of 1000 keys. Is there a way to increase the limitation?

Regards

- Nancy version: **1.4.4**
- Nancy host
  - [x] **Nancy.Hosting.Self 1.4.1**
  - [x] **Nancy.Viewengines.Razor 1.4.3**

- Environment (Operating system, version and so on): **Windows 10**
- .NET Framework version: **4.6.1**

**Comment by khellang** [comment]
I'm not aware of a limit of 1000 keys. What makes you think there's a limit?

**Comment by khellang** [comment]
You can set the `StaticConfiguration.RequestQueryFormMultipartLimit` property, which defaults to 1000:

https://github.com/NancyFx/Nancy/blob/dbdbe9428caea06c17d34a507c9216fe35abadc4/src/Nancy/StaticConfiguration.cs#L17
