### ISSUE TITLE
Where is the v1.4.5 tag?

### ISSUE THREAD

**Issue by RhinoDevel** [NancyFx/Nancy#2935]
Where can I find the v1.4.5 tag?

Are there release notes and/or a list of changes, somewhere?

Thanks in advance!

**Comment by stieler-it** [comment]
Also the source code seems to be missing yet, 1.x working branch still has 1.4.4

**Comment by phillip-haydon** [comment]
https://github.com/NancyFx/Nancy/commit/cbb94a811cd4b74139dc99f0a79d45814c7a4b42

It was just a direct commit to fix a bug.

**Comment by stieler-it** [comment]
I see but shouldn't `SharedAssemblyInfo` also be updated then?

**Comment by grumpydev** [comment]
Yeah, this was a manual build to fix a bug only in the nancy core dll, I probably didn't push the shared assembly info, or the tag, file after I'd manually created the nuget package.
