### ISSUE TITLE
Gracefully Restarting A Self-Hosted Nancy Application

### ISSUE THREAD

**Issue by nkosi23** [NancyFx/Nancy#2942]
I am wondering if there is a way to send a system signal (Unix) to a self-hosted Nancy application and have it terminate the processing of all requests before exiting similar to this [Apache's feature](https://httpd.apache.org/docs/2.2/stopping.html#graceful).

I am concerned about requests being terminated midway when the application is updated which could leave the database in an inconsistent state. Any hint would be appreciated.

Many thanks

**Comment by phillip-haydon** [comment]
Do you have your application load balanced??? If so then just remove the machine from the load balancer. Wait for requests to finish. Then deploy. Then add it back in.

**Comment by nkosi23** [comment]
No it's not, however you just made me realize that I could pause the front-end reverse proxy to achieve the same result. The update will result in downtime anyway no matter where graceful restart is handled since this is a single node setup. If there is ever a need to make this system HA and therefore load balanced, then what you suggest would cover this scenario too.

Thank you
