### ISSUE TITLE
Nancy .dlls are not signed?

### ISSUE THREAD

**Issue by Nuluvius** [NancyFx/Nancy#2943]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Nancy.dll and Nancy.Hosting.Self.dll are not signed i.e. there's no public key.

### Steps to Reproduce
Build and verify that the dlls do not have a public key.

### System Configuration
Visual Studio with .Net version 4.7.2 and Nancy Hosting Self package.

- Nancy version:
- Nancy host
  - [ ] Nancy.Hosting.Aspnet
  - [ ] Nancy.Hosting.Self
  - [ ] Nancy.Owin ()
  - [x] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on): Windows 10, Visual Studio 2017.
- .NET Framework version: 4.7.2

**Comment by khellang** [comment]
https://github.com/NancyFx/Nancy/wiki/Statement-on-strong-naming
