### ISSUE TITLE
Does Nancy server support high concurrency ？

### ISSUE THREAD

**Issue by jackletter** [NancyFx/Nancy#2965]
1. The difference between Nancy and nginx？
2. when nancy does't use socketasynceventargs, how can it support high concurrency?

i'm study the knowledge of high concurrency

**Comment by cocowalla** [comment]
For the first point, Nancy is a _framework_, whereas nginx is a _web server_ - you use Nancy to build web apps, which need a web server to run them.

**Comment by jackletter** [comment]
thanks
