### ISSUE TITLE
Evicting Nancy from the Console?

### ISSUE THREAD

**Issue by montehansen** [NancyFx/Nancy#2976]
### Description
I am using nlog and Nancy console output does not conform to the desired output. How do I prevent Nancy from writing to the console messages such as:

Request started: "GET" ...

### Steps to Reproduce
Run the app in the debugger.
I set StaticConfiguration.EnableRequestTracing = false but it has no effect that I can tell.

### System Configuration
n/a

Thanks!

**Comment by jonorossi** [comment]
@montehansen I've never seen Nancy log this and Nancy's code has no results for "Request started". My guess is that this is from IIS Express (it writes that exact message).

**Comment by montehansen** [comment]
I think you are right, _thanks so much_ for the quick reply.
