### ISSUE TITLE
RequiresRoles for Modules in Nancy 2.x not present

### ISSUE THREAD

**Issue by jetic83** [NancyFx/Nancy#2981]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Former RequiresClaims(...) could be used for a list of roles of a user.
In Nancy 2.x,, this function checks the claims of the Security.ClaimsPrincipal.

However, this ClaimsPrincipal also offers a check for roles directly (user.IsInRole). This property of a user should be leveraged for Nancy Modules: this.requiresRole(string role), or similar.

### System Configuration

- Nancy version: 2.0
- Nancy host
  - [x] Nancy.Hosting.Aspnet
  - [ ] Nancy.Hosting.Self
  - [ ] Nancy.Owin ()
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version: 4.7.2
- Additional information:

**Comment by khellang** [comment]
Closed by #2982
