### ISSUE TITLE
Nancy with SSL

### ISSUE THREAD

**Issue by WattsC-90** [NancyFx/Nancy#3004]
### Description
Lets Encrypt offer free certs via the ACME protocol, with the options for running nancy with ssl being the use of netsh from command line this meand a cert would have to be installed or updated manually during runtime. Is it possible to support assigning/updating the certificate that nancy uses at runtime? That way it could be automatically retrieved from letsencrypt and updated periodically as letsencrypt issues short term certs. While its not automatic/periodic, an example of the desired process can be found here https://medium.com/@MaartenSikkema/automatically-request-and-use-lets-encrypt-certificates-in-dotnet-core-9d0d152a59b5 it would allow much slicker ssl deployments versus running netsh commands.

**Comment by khellang** [comment]
This isn't really a Nancy issue as it depends on the host you're running on. If you're able to get the host to renew certs while running, Nancy shouldn't care 😊

**Comment by WattsC-90** [comment]
@khellang Thank you for the input, much appreciated, just trying to piece it all together in my head!
