### ISSUE TITLE
More RequestTracing enable options

### ISSUE THREAD

**Issue by grumpydev** [NancyFx/Nancy#481]
Rather than an on/off request tracing should be able to be switched on for the current user, or for a remote user by creating a "session" and sending that user to _Nancy/Tracing/<SessionName> which the admin user can then monitor and deactivate.

**Comment by thecodejunkie** [comment]
We've left this hanging for 3 years, there's not been any requests to have it happen. If we decide to do it in the future, we can create a new issue. :heart:
