### ISSUE TITLE
Support route descriptions

### ISSUE THREAD

**Issue by thecodejunkie** [NancyFx/Nancy#762]
Add a `Description` property to the `RouteDescription` class. When then `RouteCache` builds up the route descriptions it should query a `IRouteDescriptionProvider` for the description of the route. The default implementation should query a resource file, using the (full) path of the route and support localization. 

Should be able to swap out the `IRouteDescriptionProvider` in the configuration so you could pick up descriptions from anywhere

**Comment by ddiangelo** [comment]
With IRouteDescriptionProvider.GetProvider only taking path as a parameter means there isn't a way to specify a different description when GET and POST methods use the same path (or another method). It would be a lot more useful to be able to specify the method description in the route constructor -- where the path, name, and other properties of the route are defined. Being forced to define the route description out-of-band is a little cumbersome - whether through resource files or some other custom implementation. Any plans to adjust the behavior in V2?
