### ISSUE TITLE
Json serializer insists on enums being integers

### ISSUE THREAD

**Issue by grahamrhay** [NancyFx/Nancy#775]
The only workaround I've found is this monstrosity:

https://github.com/grahamrhay/Restbucks-on-Nancy/commit/dc3acda3846cb7564d273a84caf2f8cf36bc19f4

(inspired by this blog post - http://blog.calyptus.eu/seb/2011/12/custom-datetime-json-serialization/)

I don't really have any great suggestions to fix it though :(

I'm not a huge fan of the attribute soup approach, although a case could be made for re-using XmlEnum.

Maybe a global option on JsonSettings?

**Comment by lijunle** [comment]
With the `JavaScriptPrimitiveConverter` class, it is easier to do the same thing.

```cs
public class JavaScriptEnumConverter : JavaScriptPrimitiveConverter
{
    public override IEnumerable<Type> SupportedTypes
    {
        get
        {
            return new[] { typeof(Enum) };
        }
    }

    public override object Deserialize(object primitiveValue, Type type, JavaScriptSerializer serializer)
    {
        // cannot determine the concrete enumeration type from parameters
        return null;
    }

    public override object Serialize(object obj, JavaScriptSerializer serializer)
    {
        return obj.ToString();
    }
}
```

Then, in `ApplicationStartup` hook, add:

```cs
JsonSettings.PrimitiveConverters.Add(new JavaScriptEnumConverter());
```
