### ISSUE TITLE
Nancy Routing Chokes on dots and percent encoded slashes

### ISSUE THREAD

**Issue by MichaelAz** [NancyFx/Nancy#789]
As the name suggests, Nancy routing has two large bugs:
1 .  It chokes on dots. This route:

``` C#
Get["/this/{is}/a/test"] 
```

Doesn't match `www.mysite.com/this/./a/test` or `www.mysite.com/this/i.s/a/test` even though the dot is a valid character in URLs.

2 . Nancy also chokes on percent encoding. This Route:

``` C#
Get["/this/{is}/{test}"]
```

When given the URL `www.mysite.com/this/is%2Fsome/stuff` captures `is` and `some` instead of `is/some` and `stuff` as would be expected.
It seems that Nancy first decodes the URL and only then parses it. 

I'll look into the code myself and try to fix it, but in the meanwhile, here's a bug report.

**Comment by dlwiii** [comment]
Still an issue: https://github.com/NancyFx/Nancy/issues/2883
