### ISSUE TITLE
helper methods to convert raw Stream to Nancy Request

### ISSUE THREAD

**Issue by prabirshrestha** [NancyFx/Nancy#796]
I'm trying to implement a batch request support in Nancy based on http://bradwilson.typepad.com/blog/2012/06/batching-handler-for-web-api.html

I got partial parsing for multipart/batch working. https://gist.github.com/3929230

```c#
var multipart = new HttpMultipart(Request.Body, multipartBoundry);

foreach (var boundry in multipart.GetBoundaries())
{
    Stream stream = boundary.Value;
    Request req = stream.ReadAsRequest(); // ReadAsRequest needs to be implemented.
}
```

It would be good if Nancy had some extension methods that could convert Stream to Nancy Request something like in System.Net.Http which has `ReadAsHttpRequestMessageAsync` http://msdn.microsoft.com/en-us/library/hh944543(v=vs.108).aspx

Need to create a method that would convert this raw stream in to Nancy Request.
```
GET /api/values HTTP/1.1
Host: localhost
 
 ```

Since nancy is awesome at creating api, this would really be a good feature to have for those who want to optimize the api.

http://tools.ietf.org/html/draft-snell-http-batch-01
https://developers.google.com/storage/docs/json_api/v1/how-tos/batch
http://www.odata.org/documentation/batch

**Comment by thecodejunkie** [comment]
Closed. See #798 for more details
