### ISSUE TITLE
BindTo can't be used to update a model that has existing data

### ISSUE THREAD

**Issue by HeyJoel** [NancyFx/Nancy#822]
Hiya,

When using model binding, the behavior of the ModuleExtensions.BindTo method only updates properties if they are null (or default for value types). My expectation was that I could update an existing model with the request data.

My scenario is that I'm constructing a rest service where it would be really useful to update an existing model with whatever json data has been sent to it. I would have thought this would be a very common scenario, much more common than only needing to update null/empty fields?

I'm not sure on the best approach for changing the code to support this scenario so I'll probably have a go at implementing a custom IBinder to get it working for now.

**Comment by adamdriscoll** [comment]
@bennidhamma I just ran into this. Seems like how it should work.
