### ISSUE TITLE
Add Save method to HttpFile

### ISSUE THREAD

**Issue by thecodejunkie** [NancyFx/Nancy#868]
Should we add a `Save` method to `HttpFile`? It could be done in three ways.

1. Add a `Save` method that let you pass in an arbitrary path of where the file should be saved
1. Add a `Save` method that took an application-relative path where the file should be saved. We would inject the `IRootPathProvider` into each instance so it expended the relative path internally
1. Add two methods for saving, one that took the arbitrary path and the one that took the relative one. We would have to give them separate names that pointed out the differences

I personally think approach 2 would be the way to go. If you have any application-specific requirements then you can always save the file yourself, by taking the value of the file and stick it where ever you want to

**Comment by thecodejunkie** [comment]
Investigated this further and it is going to have a huge impact on how our hosts consume Nancy. This is probably not going to happen in the 1.x time frame nor the 2.x time frame

**Comment by phillip-haydon** [comment]
This could easily be done as an extension method anyway. I wrote one for my project that does: `file.Value.UploadToAzure();`

**Comment by thecodejunkie** [comment]
The problem is getting access to the `IRootPathProvider` but I can be done and it can be done without it as well
