### ISSUE TITLE
More meaningful binding exception for json content

### ISSUE THREAD

**Issue by sloncho** [NancyFx/Nancy#879]
The default model binder for json content throws TargetInvocationException if the deserialization fails.

For now as a workaround I can intercept this and get the inner exception for more descriptive information.

But I'd better see it throwing ModelBindingException instead. It'll be a little bit unclean with the current implementation to add this, as the deserializer method is created with reflection.

I see the reason, as it have to use the DestinationType of the binding context to find out which generic method to call.

So, I see 3 options:

1. Intercept the TargetInvocationException in Deserialize(string contentType, Stream bodyStream, BindingContext context) and rethrow the inner exception, and deal with it in the ModelBinder

2. Add Deserialize(Type outputType, string content) to avoid the reflection all together

3. making BindingContext generic. Then we still can use context.Model = deserializer.Deserialize(content), and it will infer the type from there, again w/o a need for reflection

I like (3) the best, so I'll start working in that direction to see what can be done there. But if you guys think about any other option, pls let me know, so I change the direction.

**Comment by thecodejunkie** [comment]
Happy to see a pull-request for this by someone in the community. I don't see us doing this atm without revisiting the model binding as a whole
