### ISSUE TITLE
ADATS / NancyInternalConfiguration Improvements

### ISSUE THREAD

**Issue by grumpydev** [NancyFx/Nancy#916]
ADATS will, by default, only include assemblies that have a reference to a nancy assembly.

ADATS will allow user to specify assemblies to *include* in the type scanning.

(note: the above two changes will not affect dependency scanning, which uses TinyIoC's autoregister, although this may link into #733)

NancyInternalConfiguration will lose the properties/methods to do with excluding assemblies - they don't make a whole lot of sense anyway as they're instance based and the scanner is static.

NancyInternalConfiguration structure will change so to defer any scanning until the types are needed - currently when the class is constructed it scans for several types of collections, which is a waste of time if they're overridden.

**Comment by khellang** [comment]
Can't this be closed?
