### ISSUE TITLE
Exception when running NUnit tests in MonoDevelop

### ISSUE THREAD

**Issue by jar349** [NancyFx/Nancy#921]
About an hour ago, I cloned, checked out master, and built everything on Mono 2.10.x (on Mac).  I moved the Nancy DLLs I needed into my project and wrote my first unit test.  When I run the unit test, there is an exception being thrown from Nancy.

System.TypeInitializationException: An exception was thrown by the type initializer for Nancy.Bootstrapper.AppDomainAssemblyTypeScanner ----> System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.

You can download my code here: http://dl.dropbox.com/u/16585486/webdav.zip

**Comment by janbaer** [comment]
We just tried to migrate a .NET4 project to Mono to use it within Docker but we have no the same problem when executing our Nancy-Tests with using the ConfigurableBootstrapper. Within docker we're using Mono 4.6 together with Nancy 1.4.3. Any ideas how to solve the problem?

```
System.Reflection.ReflectionTypeLoadException : The classes in the module cannot be loaded.
```
