### ISSUE TITLE
Accept headers processed multiple times

### ISSUE THREAD

**Issue by grumpydev** [NancyFx/Nancy#979]
Currently we parse accept headers multiple times per request when using conneg, we should store the parsed values and server them if we have them, and also when updating we should update the stored values, rather than converting to string then converting back again.

**Comment by thecodejunkie** [comment]
@grumpydev do you know if we ever resolve this?

**Comment by grumpydev** [comment]
Not that I recall.. Easy to check with a breakpoint though 😊

**Comment by thecodejunkie** [comment]
Closing this. We need to do #2054 instead as this is not specific for content negotiation.
